### ISSUE TITLE
Why written with type annotation?

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/RxJS#10]
I feel type annotation will be good helper to write the amount of code scale like RxJS. In such purpose, many project accepts TypeScript or Closure Compiler.

But the current codebase do not use any type annotation system.

Why? And do you have any plan to introduce such system?

**Comment by BerkeleyTrue** [comment]
I :-1: TypeScript. Not that there is anything wrong with it. I feel sticking with es6 is the best option.

**Comment by blesh** [comment]
This was discussed quite a bit. The goal, long term, is to produce files for ES6 modules, AMD, CJS, as well as ES5 globals... Since ES6 is a subset of TypeScript, it should "just work" to import ES6 modules.

As a matter of personal taste, I'm not a huge fan of having to maintain interfaces, but I'm not the only one working on this project (even though I have the lion's share of commits right now). It's a team effort, especially in terms of design. If the folks responsible for helping me design this implementation decide it would be best to convert to TypeScript, I'm 100% on board.

For now, though, I'm going to close this issue because I know what the result of the last discussion was.

(Closing obviously doesn't end the discussion)

**Comment by saneyuki** [comment]
I see. Thank you!
