### ISSUE TITLE
change script to add comments to all auto-patching operators to indicate generated file

### ISSUE THREAD

**Issue by jeffbcross** [ReactiveX/RxJS#1030]
Since there is a script to generate all of the auto-patching operator modules inside the `add` folder whenever operators change, comments should be added to those files indicating that they should not be manually edited without updating the script.
i.e.
```typescript
/**
 * Everything in this file is generated by the whatever-script.js
 * Any manual edits to this file will be lost next time the script is run.
 **/
```

The script is located at `tools/generate-operator-patches.js` and the affected files are in `src/add*`.

**Comment by jeffbcross** [comment]
Unassigning for now since I'll be offline for a few weeks.

**Comment by luisgabriel** [comment]
I can work on this one.

**Comment by jeffbcross** [comment]
@luisgabriel awesome! And to be clear, it's the script that should be updated to include comments in those files. I'll update the issue title to make it less ambiguous.

**Comment by luisgabriel** [comment]
@jeffbcross ok. ;)

**Comment by kevinvandervlist** [comment]
Three small things I happened to come across while doing [something unrelated](https://github.com/ReactiveX/RxJS/pull/1105):

a) On a fresh clone the generator fails because the following folder does not exist: ./src/operator/extended

b) The following files seem to be generated incorrectly (related to the kitchensink stuff?)
* src/add/operator/distinctUntilKeyChanged.ts
* src/add/operator/elementAt.ts 
* src/add/operator/exhaust.ts 
* src/add/operator/exhaustMap.ts 
* src/add/operator/find.ts 
* src/add/operator/findIndex.ts 
* src/add/operator/isEmpty.ts 
* src/add/operator/max.ts 
* src/add/operator/mergeScan.ts 
* src/add/operator/min.ts 
* src/add/operator/timeInterval.ts

c) Since the files will be autogenerated anyway, shouldn't they be removed from the source tree, and generated on build?

**Comment by kwonoj** [comment]
a / b can be discussed in PR #1097 directly - @luisgabriel , does current PR reflects this?

c - Think it depends on how we'll treat auto generated files. These files are not change frequently (mostly won't, unless adding / removing new operator) doesn't necessarily to be generated per build everytime.

**Comment by luisgabriel** [comment]
I think `a` and `b` are being covered by #1097.

**Comment by kwonoj** [comment]
Closing this issue by #1097 is checked in now.
