### ISSUE TITLE
debounceTime doesn't work with Subject

### ISSUE THREAD

**Issue by tandu** [ReactiveX/RxJS#1081]
We had a discussion here https://github.com/angular/angular/issues/5925. It seems that `throttleTime` works with `Subject` and `debounceTime` doesn't work with `Subject`.
`throttleTime`: http://jsfiddle.net/bo6ynqf7/1/
`debounceTime`: http://jsfiddle.net/8g968xh7/1/

**Comment by kwonoj** [comment]
Would you elaborate bit more detail of 'doesn't work'?  I tried this
http://jsfiddle.net/8g968xh7/2/ which has slightly modified such as below

```
const { Subject } = Rx;

const button = document.querySelector('button');
const pre = document.querySelector('pre');

var sub = new Subject()

sub.debounceTime(1000)
	.subscribe(_=> pre.innerHTML += _);
  
button.addEventListener('click', function(){
  sub.next('a');
});
```

and could see `debounceTime` emits. Does doesn't work means emitting behavior is not expected, or is it not emitting at all?

**Comment by tandu** [comment]
Hm, it seems that `sub.next()` is working for `throttleTime` but for `debounceTime` it should pass any value. So for `debounceTime` `sub.next()` is not fired but if you send anything like `sub.next(0)` or `sub.next('a')` it works as expected.

**Comment by tandu** [comment]
By doesn't work I meant it was not emitting at all.

**Comment by kwonoj** [comment]
Ah, that's currently expected behavior from implementation of `debounceTime()`. Looking at implementation,

```
...
if (this.lastValue != null) {
      this.destination.next(this.lastValue);
      this.lastValue = null;
    }
```

it only emits if it explicitly have values to be emitted. So while subject emits `next` without any value, debounceTime simply skips it since there's no value. Feeling this need to be checked if this need to be changed or not.

**Comment by chicoxyzzy** [comment]
looks inconsistent

**Comment by kwonoj** [comment]
Behavior perspective it does. Few things to be considered are,

- `Subject::next()` requires value as paramater, it should not be skipped. So in case of above example, calling `next(any)` ensures operator behavior.

- Edge case in this issue is case of emitting `undefined` as value, since `next()` is same as `next(undefined)`. This is case shows different behavior compare to RxJS4.

**Comment by staltz** [comment]
@kwonoj debounceTime should have a hasValue-based implementation, like e.g. distinctUntilChanged:

```ts
class DistinctUntilChangedSubscriber<T> extends Subscriber<T> {
  private value: T;
  private hasValue: boolean = false;
```

So this bug is legit it seems.

**Comment by kwonoj** [comment]
@staltz , Yes, @mattpodwysocki suggested same approach in current PR (https://github.com/ReactiveX/RxJS/pull/1083#issuecomment-165037981). I'm updating PR to reflect suggestions.
