### ISSUE TITLE
missing operator shareReplay

### ISSUE THREAD

**Issue by landuber** [ReactiveX/RxJS#1110]
Why is the shareReplay operator missing from this version of RxJS? Is there a specific reason for not implementing it?

**Comment by blesh** [comment]
It's not implemented because it's behavior differs from `share`, and there's still some debate about how it should behave. Specifically, retry and repeat should work with share, but won't work, or work with unexpected side effects when it comes to shareReplay.

There is discussion of a `cache` operator to meet the needs of `shareReplay`.

I'm on my phone or I'd link the above conversations. You can find them in the issues.

**Comment by blesh** [comment]
As you were just asking about "Why", and I've answered, I'm going to close the issue. Please feel free to reopen if you're unsatisfied.
