### ISSUE TITLE
Subclassing Observable - Observable SubClasses extend Observable rather than MyObservable

### ISSUE THREAD

**Issue by Nupf** [ReactiveX/RxJS#1124]
I want to subclass Observable and extend it. 

The [documentation on this](https://github.com/ReactiveX/RxJS/blob/0a069933f4ba778b112b74b4698c4453c9b4e74a/doc/operator-creation.md) shows how to  subclass observable and extend it with custom operators, however I run into problems whenever an operator / static method of MyObservable returns an instance of a different class.

All other Observable classes (e.g. ArrayObservable, ConnectableObservable) extend the original Observable class rather than MyObservable, meaning my custom operators will not be available.

    class MyObservable extends Observable {
      lift(operator) {
        const observable = new MyObservable(); //<-- important part here
        observable.source = this;
        observable.operator = operator;
        return observable;
      }
    
      customOperator() {
        /* do things and return an Observable */ 
      }
    }

    // customOperator is not defined as the observable instance is not a subclass of MyObservable but Observable
    MyObservable.of(42).customOperator() 

    // returns a ConnectableObservable, meaning customOperator is again not available.
    myObservable.publish().customOperator()

**How is subclassing meant to be used?**

Overwriting the methods to wrap the returned Observable in an instance of MyObservable feels dirty.

    class MyObservable extends Observable {
      lift(operator) {
        const observable = new MyObservable();
        observable.source = this;
        observable.operator = operator;
        return observable;
      }
    
      customOperator() {
        return this;
      }
    
      static of() {
        const observable = new MyObservable();
        observable.source = Observable.of(...arguments);
        return observable;
      }
    }
    
    
    MyObservable.of(1,2,3)
      .customOperator()
      .subscribe(value => console.log(value));

**Comment by kwonoj** [comment]
This is related with https://github.com/ReactiveX/RxJS/issues/642. Current modularity streategy does not correctly support extended definitions due to creation of observable (i.e, of, etcs..) always directly created `Observable` as you've mentioned above. It's not resolved 100% in current codebase and trying to find feasible way.

**Comment by blesh** [comment]
```js
MyObservable.of(42).customOperator() 
```

This wouldn't work on any type you subclassed in ES6.

Imagine this simplified form: 

```js
class A {
  foo() {
    console.log('foo from A');
  }
  
  static of() {
    return new A();
  }
}

class B extends A {
  foo() {
    console.log('foo from B');
  }
}


var x = B.of();

console.log(x.foo()); // "foo from A"
```

While `B` gets `A`'s static `of` method, it's not going to change the type returned by `of`, because it's not going to call different code to create a `B` instead of an `A`. This is because there really isn't an automatic way to have this type of psuedo higher-kinded typing in JavaScript. If you want to do this, you have to override the static methods.

**Comment by blesh** [comment]
On the `ConnectableObservable` front. We _could_ implement something that dynamically creates that type by extending `this.constructor` or something with ES5 internal to the `publish` method, but if we did this, we'd end up creating a new class for each `publish` call. That's probably not going to optimize very well.

**Comment by blesh** [comment]
@Nupf does the above information help you?

**Comment by kwonoj** [comment]
While I was trying mixin approach in PR https://github.com/ReactiveX/RxJS/pull/643, I came to thought above scenario (maybe) possible in combination of enhanced typescript support (relates to https://github.com/ReactiveX/RxJS/issues/846). It was very vague idea at the moment and still not concrete clear due to known limitataions, reason bringing #642 is related. Even without direct static creator (`of`, etcs), Observable creation limits extended behavior regarding type definition perspective while runtime behavior's updated via patch operators.

**Comment by trxcllnt** [comment]
This is what `let` is for. As long as your custom Observable subclass can accept a source and return an instance of itself, it will work:

```es6
Observable.of(42)
  .let(o => MyObservable.from(o))
  .customOperator()
  .subscribe()
```

**Comment by Nupf** [comment]
Thanks for taking the time.

@kwonoj: Thanks, I'll have a look at those.

@blesh: Yep, I was just hoping there was a way I didn't know about and/or I was just doing something wrong.

@trxcllnt: Thanks, I didn't know about that operator. As far as I can tell, it's waiting to be merged in #1105, so I can't test it but it looks like it merely invokes the provided function on the source observable

    export function letProto<T, R>(func: (selector: Observable<T>) => Observable<R>): Observable<R> {
      return func(this);
    }

As MyObservable.from returns the same thing Observable.from (@blesh's comment) returns, this (as far as I can tell) won't convert o into an instance of MyObservable.

**Comment by trxcllnt** [comment]
@nupf ah, I was assuming `MyObservable.from` would be your own `from` implementation that returns an instance of `MyObservable`. You could also accept a source Observable in the constructor instead, and return `new MyObservable(o)` from the `let` selector.

**Comment by Nupf** [comment]
@trxcllnt I thought about that but ran into problems with ConnectableObservable / publish. Is that how you would have implemented it?

    class MyObservable extends Observable {
      constructor(observable) {
        super();
        this.source = observable;
      }
    }

It works great as long as the source observable only has a subscribe method. ConnectableObservable destroys the illusion.

    let observable = Observable.of(42).publish();
    let myObservable = new MyObservable(observable);
    myObservable.source.connect(); // rather than myObservable.connect();

I assume there are more cases where observables have methods other than subscribe that would have to be copied over. It would work, but it doesn't feel clean and and I don't know enough about the codebase to predict how much monkey patching will be required...
