### ISSUE TITLE
docs links broken

### ISSUE THREAD

**Issue by born2net** [ReactiveX/RxJS#1137]
as in
https://github.com/ReactiveX/RxJS/blob/master/doc/index.md

**Comment by rudijs** [comment]
+1

**Comment by luisgabriel** [comment]
Yeah, these links are broken. You can access the documentation here while this is not fixed: http://reactivex.io/RxJS/

**Comment by rudijs** [comment]
Ah OK .. great. Thanks Luis.

**Comment by born2net** [comment]
ok tx... but as fo the links, these docs have no samples :(

**Comment by blesh** [comment]
@born2net yes, we're working on adding more (and better) documentation during beta. Those links in that file are just stubs, and that file's real intent is to be used as part of esdoc generation.

@luisgabriel was right on with where he pointed you. In fact the index page of that is what `index.md` is being used for.

I'm going to close this for now, since it's not really an issue to be fixed, but rather an ask that we add more documentation, which we're actively working on.

Feel free to reopen if I'm misunderstanding.

**Comment by born2net** [comment]
sweet!
