### ISSUE TITLE
Type Definitions of operators are less friendly than RxJS v4

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/RxJS#1173]
I think this would diminish the usability of static typing solutions (e.g. compilation, or autocomplete). As my feeling which was working to migrate [my project to RxJS v5](https://github.com/karen-irc/karen/pull/520), autocomplete and type inference.

For example:

1. `Observable.crate() = Function` is too generic type.
   - It is recognized as just a `Function`. So autocomplete cannot suggest a callback signature. This is a frustration...
2. `zip()`/`combineLatest()` type definitions are `any`.
  - In RxJS v4, they have more descriptive type definitions:
    - https://github.com/Reactive-Extensions/RxJS/blob/master/ts/core/linq/observable/zip.ts
    - https://github.com/Reactive-Extensions/RxJS/blob/master/ts/core/linq/observable/combinelatest.ts
  - But at now, v5's one are still poor if we pass a many observables to them.
    - https://github.com/ReactiveX/RxJS/blob/7a679b64893eccf402e3705b40322021d1015951/src/Observable.ts#L283
    - https://github.com/ReactiveX/RxJS/blob/7a679b64893eccf402e3705b40322021d1015951/src/Observable.ts#L199-L201

And in the range my worked, [`Observable.race()`'s type definition](https://github.com/ReactiveX/RxJS/blob/7a679b64893eccf402e3705b40322021d1015951/src/Observable.ts#L250) is different from [RxJS v4's one](https://github.com/Reactive-Extensions/RxJS/blob/master/ts/core/linq/observable/amb.ts) and it caused my frustration (But fortunately, we may be able to fix the case of `race()` easily).

These difference would be able to be a _regression point_ of full-rewrittned v5.
How we can resolve this problem?

**Comment by kwonoj** [comment]
You may want to check PR https://github.com/ReactiveX/RxJS/pull/1087 especially problem # 2 you have addressed. 

It is known current codebase of RxJS5 has some level of weakness to deal with type definitions, trying to enhance it as much as possible. For general type definition enhancements effort, there's PR https://github.com/ReactiveX/RxJS/pull/826 and https://github.com/ReactiveX/RxJS/pull/667 is being considered to have correct interface when interface's composed.

If you have particular enhancement have in mind currently, creating PR to be always welcomed.
Is this answers (at least partially) for you?

**Comment by saneyuki** [comment]
@kwonoj 

Thank you for your quickly replying.

I wanted to confirm 1) do we have any concrete approach to resolve this problem? 2) How do we have a progress about it?. 

> If you have particular enhancement have in mind currently, creating PR to be always welcomed.

Of course, I'll send a pull request if I success to crate a nice patch!

> Is this answers (at least partially) for you?

At least, I'm trying to fix the issue of `race()`.
And I have not read #826 and #667. I might write some comment to them.

Lastly, do we have any meta tracking issue this problem?

**Comment by kwonoj** [comment]
1) 2) both, by nature of type definition there won't be single concrete resolution could solve it all. For instance, like operator has 1 to N possible argument (problem # 2) could be resolved via definition generators. Else operators which doesn't have correct type definition while it's composed, it may need to be hand crafted per cases. 

For latter and prior both, having test covering type definition will help those in general since it'll make code contributor should verify its type definition while updating codebases.

There are couple of issue filed per each cases to track, 

https://github.com/ReactiveX/RxJS/issues/661 - test coverage for type definition
https://github.com/ReactiveX/RxJS/issues/642 - type definition errorneus behavior for rx.kitchensink
https://github.com/ReactiveX/RxJS/issues/1060 - general roadmap issue includes type definition enhancement

**Comment by david-driscoll** [comment]
I've been working to help the team plug some of the typing declaration holes.  The only thing I haven't sat down and looked at "what would this take to fix" is `Observable.create`/`Subject.create` since they both have unique signatures, but essentially share the same static field.

**Comment by blesh** [comment]
Can we identify specific type signatures that we need to improve and create separate issues for them? This issue is so generic I'm not sure how it could be "resolved" completely. There are likely going to be ongoing tweaks to type signatures across the library.

@saneyuki can we close this and set up more specific issues?

**Comment by saneyuki** [comment]
@blesh 

okay. I'll close this, and file a issue if I find a new compatibility issue.
