### ISSUE TITLE
ISSUE: startWith, of, and Scheduling

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1196]
Related #857 #855 and #854 

So the problem is this: What if I wanted to create an Observable of schedulers, or I wanted to start and Observable with a Scheduler, but I don't want to _schedule_:

```TypeScript
Observable.of(scheduler1, scheduler2, scheduler3);
source.startWith(scheduler1, scheduler2, scheduler3);
```

How do we differentiate between `scheduler3` above being a value to emit and being a scheduler to use?

There are a few solutions:

1. Separate methods (e.g. `of` and `ofScheduled`)
2. Guidance to use `subscribeOn` and `observeOn` for those operators, and have them not take schedulers.
3. Implement a `Scheduler.none` that can be used to flag that scheduling is not to be used (e.g. `if (!scheduler || scheduler instanceof Scheduler.none) { /* don't schedule */ })`). Then the *last* scheduler could always be assumed to be the scheduler argument, and people could just specify it:  `Observable.of(scheduler1, scheduler2, scheduler3, Scheduler.none)`

**Comment by trxcllnt** [comment]
@blesh this seems like _such_ a rare case that it's probably not worth complicating API over. I'm not saying it can't happen, but let's be honest: it doesn't happen often.

On the off-chance you do need to synchronously enumerate a series of schedulers, you have two options: 

1. Use `fromArray([scheduler1, scheduler2, scheduler3])`
2. Pass `undefined` as the last argument to `of`

What's the difference between forcing someone to pass `undefined` vs. `Scheduler.none`? Either way they have to know that `of` expects a Scheduler as its last argument, and they need to do something special since they're enumerating an arguments list of Schedulers.

As for the `Scheduler.none` type itself, would it be the non-reentrant tail-recursive scheduler we discussed before, or would we still loop in creation operators? I'd wager all the extra function invocations introduced by the first option would wipe out a good deal of our perf gains on synchronous dispatch, but who knows, I've been wrong about JITs before.

**Comment by blesh** [comment]
@trxcllnt, I agree, mostly.

I don't think passing `undefined` as the last argument of `of` will work, though, because we're checking arguments in reverse to see if they're `instanceof Scheduler` I think. If it's `undefined` then that answer will be `false` and it will not only assume there is no scheduler, but it will assume that `undefined` is one of the values you should emit from the Observable.

More likely the solution would be to work around it like:

```js
// (compare to example in first comment)
Observable.from([scheduler1, scheduler2, scheduler3]);
Observable.from([schedluer1, scheduler2, scheduler3]).concat(source);
```

**Comment by trxcllnt** [comment]
> @blesh it will assume that undefined is one of the values you should emit from the Observable

You're right, and normally I'd be concerned, but I guess I just don't care about this problem. People should use `Observable.from` or `Observable.fromArray` because their signatures lend themselves better to this specific problem. We shouldn't have to junk up `Observable.of` just because the polymorphic signature isn't perfect in this one rare case.

**Comment by blesh** [comment]
@trxcllnt completely agree. As far as I'm concerned, `startWith` is really the only one that is a little gross in this scenario. Then again, an Observable of Schedulers is pretty gross.

**Comment by blesh** [comment]
Closing this issue as stale.
