### ISSUE TITLE
Support for Async Delivery?

### ISSUE THREAD

**Issue by vsavkin** [ReactiveX/RxJS#12]
In Rx2 both subscription (subscribe) and delivery (onNext) can be made async.

This is not the case in Rx3.

The following will fail with:
expected [ 'next:1', 'received:1', 'next:2', 'received:2' ] to equal [ 'next:1', 'next:2', 'received:1', 'received:2' ].

```
    var loggedValues = [];

    var generator;
    var observable = new Observable(g => {generator = g;}, new NextFrameScheduler());

    observable.observer({
      next: value => loggedValues.push(`received:${value}`),
      return: () => {
        expect(loggedValues).toEqual(['next:1', 'next:2', 'received:1', 'received:2']);
        done();
      }
    });

    setTimeout(() => {
      loggedValues.push(`next:1`);
      generator.next(1);

      loggedValues.push(`next:2`);
      generator.next(2);

      generator.return();
    }, 0);
```

Are there plans to allow async delivery?

Should not async delivery be the default? After all It is async when dealing with promises.

```
     var loggedValues = [];

     var resolve;
     var p = new Promise((r) => {
       resolve = r;
     });

     p.then(value => {
       loggedValues.push(`received:${value}`);
       expect(loggedValues).toEqual(['before', 'after', 'received:42']);
       done();
     });

     setTimeout(() => {
       loggedValues.push(`before`);
       resolve(42);
       loggedValues.push(`after`);
     }, 0); 
```

**Comment by trxcllnt** [comment]
Observables are referentially transparent, so they can be optionally async. If you encapsulate all state within the Observable operators, your code will work the same whether it runs synchronously or asynchronously.

Promises (etc.) force asynchrony because they are stateful. This is sometimes called [Releasing Zalgo](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony), and is a problem people encounter when they write programs that rely on mutable external state.

One solution is to always force asynchrony (at the cost of performance). The other (and better imo) solution is to write code that doesn't rely on side-effects.

**Comment by vsavkin** [comment]
Hey, Paul. I don't see why promises are stateful and, let's say, hot observables are not. Can you expand on that?

**Comment by trxcllnt** [comment]
You're right, hot Observables are the definition of stateful. Most side-effects can still be encapsulated inside the Monad and multicast correctly, but if not, you can always switch to subscribing (or observing) on an asynchronous scheduler at that point.

**Comment by vsavkin** [comment]
Makes sense.
