### ISSUE TITLE
Supporting returning single values from callbacks that return Observable/Promise/etc.

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1247]
As we know, `mergeMap` and `switchMap`, etc. will support returning other types that can be made into observables. I've been asked a few times why we don't support returning other values here, and I frankly don't have a great answer.

Perhaps @mattpodwysocki has some design reasoning I haven't considered? 

Otherwise, I'd like to discuss the following:

``` js
const delayTheOdds = Observable.range(0, 10).mergeMap(x => x % 2 === 0 ? x : Observable.of(x).delay(1000));
```

Obviously that won't work, and obviously I should wrap `x` in `Observable.of(x)` ... but why? Promise support converting values to promises as such:

``` js
function delay(value, time) {
  return new Promise(resolve => {
    setTimeout(() => resolve(value), time);
  });
}

somePromise.then(x => {
   return x % 2 === 0 ? x : delay(x, 1000);
});
```

**Comment by trxcllnt** [comment]
@blesh because the return type of `>>=` (monadic bind) isn't polymorphic. This is essential in statically typed languages (both for type safety and so the compiler can magically optimize parts of the program), but likely less so in JavaScript. The strongest argument may be that it enables JIT optimizations, but I lack insight into whether that's the case.

**Comment by plievone** [comment]
> As we know, mergeMap and switchMap, etc. will support returning other types that can be made into observables.

I like the explicitness of current behavior (needing to wrap arraylike return values with `Observable.fromArray`, for example), but it would be good to document this in https://github.com/ReactiveX/RxJS/blob/master/MIGRATION.md for the time being?
