### ISSUE TITLE
Migration Operator Splits

### ISSUE THREAD

**Issue by ronag** [ReactiveX/RxJS#1253]
Seems that the RxJS4 and RxJS5 columns are exactly the same?

**Comment by blesh** [comment]
Hi @ronag! Can you elaborate on your issue?

**Comment by kwonoj** [comment]
Let me close this issue since it's not updated quite while, and current migration guide contains correct operator splits in https://github.com/ReactiveX/RxJS/blob/master/MIGRATION.md#operator-splits . @ronag , please feel freely reopen if there's additional details you can provide to continue discuss.
