### ISSUE TITLE
Query Expressions?

### ISSUE THREAD

**Issue by staltz** [ReactiveX/rxjs#1272]
What would it take for us to be able to serialize an Observable chain of operators in the "Query Expression" style? This was mentioned/promised long ago https://github.com/Reactive-Extensions/RxJS/issues/54 but didn't end up happening.

Here's some motivation behind this feature: https://twitter.com/andrestaltz/status/693743424562974721

**Comment by jadbox** [comment]
Can you provide a mock serialized output of what you're thinking? Do operation/selector functions get serialized too (see below) or is the QE only flow based?
```
{
   entry: { 
     op: "map",
     selector: "function(x) { return x * 2; }",
     chain: {
        op: "map".
        selector: "function(x) { return x / 2; }",
     }
   }
}
```
or just flow:
```
{
   entry: { 
     op: "map",
     chain: {
        op: "map"
     }
   }
}
```
or maybe with descriptors (manually specified when serializing):
```
{
   entry: { 
     op: "map",
    selector: "multi 2",
     chain: {
        op: "map",
        selector: "divide 2",
     }
   }
}
```

Either way, I'm hoping to be able to apply QE to something like my [rxjs-cluster](https://github.com/jadbox/rxjs-cluster) lib so that I can automatically distribute stream execution among processes (albeit that every function is pure). My alternative plan to to use the new RxJS 5 extension mixin (same system you use for stream graphing) to redirect data flow to threads, although that will be as efficient as I think.

**Comment by mattpodwysocki** [comment]
@staltz that's not quite true that it wasn't implemented, the parser of Bonsai trees to JavaScript works quite well and is located here: https://github.com/Reactive-Extensions/RxJS/tree/master/src/core/expressions  What we haven't done is the inverse which is taking say a TypeScript or JavaScript AST and turning it into the Bonsai trees

**Comment by HighOnDrive** [comment]
Serialization with operation/selector functions would be excellent. It would be fantastic actually, what is the status of this issue?

**Comment by blesh** [comment]
@staltz this discussion has gone stale, so I'd like to close the for now. Not as a rejection of the idea, but mostly just to clean up our issues list.

**Comment by Widdershin** [comment]
I personally would love to see this implemented, even if it's just so it's easy to serialize and deserialize the state of a Cycle.js app

**Comment by blesh** [comment]
Cycle has its own observable library now.
