### ISSUE TITLE
Detecting RxJS5 from RxJS4

### ISSUE THREAD

**Issue by akauppi** [ReactiveX/RxJS#1275]
Packaging systems probably would cover this, but if I load RxJS globally (see #1274 ), into the browser, it would be nice to be able to tell RxJS5 apart from RxJS4. This allows me to make a library that would know how to work with either.

All I'd want is a suggestion on what feature is a good candidate to check for.

**Comment by staltz** [comment]
The lift() is pretty unique for this library, so checking if an Observable has lift() might be one way of duck typing.

**Comment by blesh** [comment]
If you're looking for interop with any Observable type, I highly recommend looking for `Symbol.observable`, while I don't think it's implemented in Rx 4, yet, it would be a trivial add for @mattpodwysocki. It should already exist in Most.js, Bacon, etc.

In the short-term, you could just test for `subscribe` and then always call it with three functions (not an Observer, because that signature has changed).

I'd strongly caution against making assumptions about Observable types provided by third parties, and wrap whatever you get in a type you know from your own library. Any give Observable implementation may have slightly different methods available on it, or scheduling, etc. It's best to keep control of those things yourself within the internals of your library.

**Comment by jayphelps** [comment]
@blesh any reason not to start exporting a version number?

```js
import Rx from 'rxjs/Rx';
Rx.VERSION === '5.0.0-beta.1'
```
Common pattern amongst libs, as I'm sure you know (but others reading this may not)

**Comment by jayphelps** [comment]
Also--I'm still of the opinion he should be feature testing instead of version checking though, if reasonable. If you need a certain feature or expect a certain API, test to see whether provided Observable meets that need. Provides better experience when users may want to use your library with other Observable libs that happen to meet those requirements. But without knowing what exactly he's doing, it obviously depends.

**Comment by blesh** [comment]
@jayphelps we can export a version number, sure. No good reason other than it's not a priority and I'd want it to be automated.

Otherwise, @akauppi what @jayphelps is saying is totally accurate. You should probably feature test before using features from types provided by a third party. The "shape" of the Observable `subscribe` is going to be the same if your passing functions (and not Observers). But the return value to the `subscribe` will either have `dispose` or `unsubscribe` so test for that.

If you wanted a simple test testing for `Rx.Subscriber` by itself would be a huge flag that it's RxJS 5. Otherwise you could test Subjects for `onNext` vs `next` or something.

**Comment by akauppi** [comment]
I ended up doing this, i.e. checking for the `.subscribe` name change:

```javascript
  var RxJS5 = (function() {   // tbd. can autodetect this if we want to support both RxJS4 and 5
    var sub = new Rx.Subject();
    (sub.unsubscribe || sub.dispose)();
    return !!sub.unsubscribe;
  })();
```

My use case is a bit special. I'm moving a library to RxJS5 and want to keep the old code base (where it differs) along for a while, in case there are problems. But so far, RxJS5 seems solid and I don't intend to actually test and support both.
