### ISSUE TITLE
Add materialize

### ISSUE THREAD

**Issue by ktrott** [ReactiveX/RxJS#132]

**Comment by blesh** [comment]
@mattpodwysocki, @trxcllnt ... is there any valuable reason that `Notification`s of `kind` `"N"` put their values in `value` but notifications of `kind` `"E"` put their values in exception?

It seems like the `Notification` type in general could use some refactoring. It could be immutable, and `value` and `exception` could just be `value` since they're mutually exclusive when paired with `kind`.
