### ISSUE TITLE
[Type] cannot subscribe observable from array of promise's concatAll()

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#1436]
```js

const sources = Rx.Observable.fromArray([
  new Promise((res: any) => { res(0); }),
  new Promise((res: any) => { res(1); }),
  new Promise((res: any) => { res(2); }),
  new Promise((res: any) => { res(3); }),
]);

sources.concatAll().subscribe();
```

won't be allowed as

>31     sources.concatAll().subscribe(
                           ~~~~~~~~~
error TS2339: Property 'subscribe' does not exist on type 'Promise<{}>'.

This issue does not affect operator behavior.

**Comment by kwonoj** [comment]
I've thought this bit more and start to think this is somewhat expected, since via `concatAll` flattening and trying to access `<T>` directly here. It's same for other type of object as well such as `number`, `string` which in non-subscribable - I'd consider this as case for requiring explicit casting if nessary.

@david-driscoll - would you mind share opinion here? I looked into RxJS 4's type definition and seems it behaves similar.

**Comment by david-driscoll** [comment]
The signature for `concatAll()` looks like:
```
export interface ConcatAllSignature<T> {
  (): T;
}
```

Ideally we could do something like:
```
interface Observable<U, T extends ObservableInput<U>> {
    concatAll(): Observable<U>;
}
```

The problem is, with TypeScript anyway, there is no way to make a specific prototype method have a different generic constraint than the class it's attached to.  So in this scenario the only thing we can do is to return T and assume `T` is an `Observable<U>`.

To help with this problem, we can certainly make the interface a little better, so that the manual type can be given.

```
export interface ConcatAllSignature<T> {
  (): T;
  <R>(): Observable<R>;
}
```
