### ISSUE TITLE
repeatWhen missing?

### ISSUE THREAD

**Issue by ronag** [ReactiveX/rxjs#1456]
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/repeatwhen.md

**Comment by kwonoj** [comment]
As [migration guide](https://github.com/ReactiveX/RxJS/blob/master/MIGRATION.md) states, not all of operators are migrated into RxJS5 yet. (just noticed retryWhen is missing in table though..)

**Comment by luisgabriel** [comment]
I think this operator was added recently to RxJS4: https://github.com/Reactive-Extensions/RxJS/commit/871f6d31315366e62a8e372b68e29fed1e5b398d

**Comment by kwonoj** [comment]
Ah, that's reason migration guide does not include it yet maybe? :)

**Comment by mattpodwysocki** [comment]
@kwonoj I think we need to update the table, especially for variant overloads such as `.catch` is missing the `.catch(...Observables)` overload

**Comment by kwonoj** [comment]
@mattpodwysocki Yes, current migration document are somewhat fall behind compare to current status. Need to be updated.

**Comment by blesh** [comment]
@mattpodwysocki since `catch(...observables)` will be wildly different in it's internals from `catch(fn)` we should probably follow the suit of `map`/`mapTo` and implement it separately. `catch` performs pretty well right now. What do you think? I must say that `catchTo` seems ugly, maybe `catchWith` or something? Or even `errorTo`, I dunno?

Thoughts?

**Comment by blesh** [comment]
`repeatWhen` exists now.
