### ISSUE TITLE
EmptyError is driving us nuts

### ISSUE THREAD

**Issue by omerts** [ReactiveX/RxJS#1467]
**RxJS version:**

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**

**Comment by blesh** [comment]
LOL... is there anything we can help you with @omerts?

**Comment by omerts** [comment]
@blesh It would be great if there was some way to know where the error is coming from.
In our case we had many observables up the line, and one of them some how emitted a good value the first time, and an empty error the second time. It took us forever to find where it was coming from (we still don't understand why it is happening though). Some additional information with the errors could be really helpful.

**Comment by tdsmithATabc** [comment]
For anyone's future reference (since I just had to figure this out):

`EmptyError` is emitted by the operators `first`, `last`, and `single` when the observable completes before any values are sent (or if it completes before any values match the predicate, if one was provided). These operators are effectively asserting that there will be *at least one* value (or *exactly* one, in the case of `single`), so having zero values emitted is an error condition and needs to be treated as such downstream.
