### ISSUE TITLE
Not all operators are importend in rx/Rx.ts

### ISSUE THREAD

**Issue by brabadu** [ReactiveX/RxJS#1495]
**RxJS version:** 5.0-beta2

**Code to reproduce:**
```
var Rx = require('rxjs/Rx');
Rx.Observable.of(1,1,1).distinct()...
```

**Expected behavior:**
Readme says `require('rxjs/Rx');` is used to get "all core functionality". But such basic operator as `distinct` is not exported, while `distinctUntilChanged` is. 

I'm looking if it would be hard to migrate rather big codebase from rxjs4 to 5. I know how to fix this, but I thought that Rx.ts should expose all existing operators. 

Is it made on purpose? Otherwise that`s a good place to make my first PR ;)

**Comment by kwonoj** [comment]
Yes, `distinct` is not included in core on purpose. You may refer initial discussion [here](https://github.com/ReactiveX/RxJS/issues/1156), it was by its behavior can be achieved via common operators.

If you'd like to import it as well, you can import `Rx.KitchenSink` instead of `Rx`. `Rx.KitchenSink` is intended to be all batteries included has all operators in it.

**Comment by brabadu** [comment]
Got it. 
Should've look closer through issues before asking. Thanks!
