### ISSUE TITLE
Rx.Observable.merge not compatible with Rx 4 (concurrency) - mergeMap

### ISSUE THREAD

**Issue by g00fy-** [ReactiveX/RxJS#1499]
With RxJS v4 merge accepted concurrency parameter so it was possible to run following code:
```typescript
import * as Rx from 'rxjs';

const Observable = Rx.Observable;

Observable.of(1)
    .map(url => Observable.of(url)) // simulate async
    .merge(1) // merge stream of streams with concurrency 1
    .subscribe((result) => console.log(result)) // RxJS v5 fails  - result is an Observable
```
with RxJS v5 in the first example `merge` doesn't `flatMap` - and produces stream of Observables.
I know that expected result can be acheived by using `mergeMap` operator

```typescript
import * as Rx from 'rxjs';

const Observable = Rx.Observable;

Observable.of(1)
    .mergeMap(url => Observable.of(url), (x, value) => value, 1)
    .subscribe((result) => console.log(result))
```

Still I think it is inconsistent - has `Rx.Observable.merge` operator changed or is this just a bug ?

Ps.
The first example in RxJS v5 causes `console.log` to print out an `Observable` instance which results in

```
RangeError: Maximum call stack size exceeded
    at formatValue (util.js:209:21)
    at formatValue (util.js:221:13)
    at formatValue (util.js:221:13)
    at formatValue (util.js:221:13)
    at formatValue (util.js:221:13)
    at formatValue (util.js:221:13)
    at formatValue (util.js:221:13)
    at formatValue (util.js:221:13)
    at formatValue (util.js:221:13)
    at formatValue (util.js:221:13)
```

**Comment by blesh** [comment]
Hey @g00fy-! Your code above is a little off. `merge` should be `mergeAll`

https://jsbin.com/yoqumi/edit?html,js,output

```js
import * as Rx from 'rxjs';

const Observable = Rx.Observable;

Observable.of(1)
    .map(url => Observable.of(url)) // simulate async
    .mergeAll(1) // merge stream of streams with concurrency 1
    .subscribe((result) => console.log(result)) 
```

Also, `//simulate async` isn't currently accurate, as `Observable.of` is synchronous by default in the current RxJS 5 implementation.

**Comment by blesh** [comment]
For your call stack problems, I'd have to see the code you're executing, but it sounds like you're creating a complete synchronous observable sequence (likely for testing purposes) and it's call stack is getting too deep (via `repeat` or `retry` or something, maybe?) You should try scheduling where appropriate with `subscribeOn` before a `repeat` or `retry` on such a list. Or perhaps pass a scheduler to whatever Observable creation method you're using (`Observable.range` for example).

Since I can't replicate your problem without additional information, I'm going to close this issue for now. Please don't hesitate to reopen this issue or open a new one if you think you've found a legitimate bug, your feedback is very important to us.

If you just have questions or code that doesn't work, I'd suggest using [StackOverflow](http://stackoverflow.com), as it's a better forum for Q&A.

**Comment by g00fy-** [comment]
@blesh 
Please see following jsbin code - it shows that v4 `merge` accepts concurrency parameter and v5 not.

same code:
v4 : https://jsbin.com/yuxudugame/1/edit?html,js,console
prints 1
v5 : https://jsbin.com/vayezewiyi/1/edit?html,js,console
prints Observable


```typescript
function fetch(url){
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(url), 1000);
  })
}

Rx.Observable.of(1)
    .map(url => Rx.Observable.defer(() => fetch(url))) // simulate async
    .merge(1) // merge stream of streams with concurrency 1
    .subscribe((result) => console.log(result)) // RxJS v5 fails  - result is an Observable
```

In RxJS v4 the result is `1` , using RxJS v5 the result is an `Observable`

**Comment by g00fy-** [comment]
So it seems that in v5 `merge` the method signature has changed - it does not accept concurrency parameter
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-merge

**Comment by david-driscoll** [comment]
`merge` was split into `merge(...observables)` and `mergeAll(concurrency)`.  For your use case you want `mergeAll`.  This also applies similarly to `concat` and `concatAll`
