### ISSUE TITLE
Line numbers, or some kind of pinpointing info when getting errors

### ISSUE THREAD

**Issue by omerts** [ReactiveX/rxjs#1514]
Hello,

Whenever we have some kind of error using RX, it is very hard to pinpoint the problematic line, or observable. In large scale apps, with tens of observables this is a lot harder. 

This is a very simple example, but imagine having an error like that somewhere in a very nested observable hierarchy:

``` javascript
const timerOne = Rx.Observable
                .interval(1000)
                .map(x => x + 1)

const timerTwo = Rx.Observable
                .interval(1000)
                .map(console.log)

const timers = Rx.Observable.merge(timerOne, timerTwo)

timers.subscribe(::console.log, ::console.log)
```

Looking at the error have no clue where it is coming from:
![image](https://cloud.githubusercontent.com/assets/4996164/13949014/cd8aae5a-f02b-11e5-87c4-2af8fea6e199.png)

**Comment by blesh** [comment]
@omerts in the example given, you can see that the error occurred in the `MapSubscriber`. That's the workhorse for the `map()` operator. The specific scenario you used to cause the error would be particularly problematic to provide "pinpointing" as you've requested because you're passing `console.log` unbound straight in as the projection function to `map()`. If you were to pass a named function in that threw the error, it would be easier to read the call stack, and the error would occur in _your_ code.

```js
const log = console.log;
someObservable.map(function logData(x) { log(x) };
```

In this case, you'd say `logData` at the top of your call stack, most likely.

As for the call stack you're showing, it reads very cleanly compared to prior art, but it's something you need to learn to digest:

1. A Scheduler scheduled a `FutureAction`, so that means something that's happening at a later time, (perhaps `delay`, `timer` or `interval`?). If you want information about what happened before that, you'll need to check the `async` checkbox in chrome debugger.
2. That action invoked a mapping operation (`MapSubscriber.next`) and I didn't hit user code, but there was an "illegal invocation" so I can bet that someone handed `map` a projection function that got detached from it's parent native object and lost context. 
3. 99% of the time "illegal invocation" comes from misuse of `console.log` without binding it (`console.log.bind(console)`), but sometimes it comes from other native calls.

... so I'm probably looking for a call like `map(console.log)`.

**Comment by blesh** [comment]
@omerts do you have any specific ideas or suggestions on how you'd improve the error information? Ideally, this issue would have something actionable to it that we can work on to close the issue.

**Comment by omerts** [comment]
@blesh, thanks for the detailed answer.
It seems like we have to take heuristic measures to debug, which could be quite simple for the above scenario, but for scenarios where we have nested observables (with combinLatest), and one of them down the line is throwing an empty error, it is much harder to make an educated guess where it might be coming from, or why even we are having an empty error. 

I have no clue how this library is implemented, and I presume getting line numbers, and a better stack trace is impossible, but some way of knowing which observable is the problematic one would be great. Maybe even, make the rx api get an observableId as a last argument, and this id would be used when throwing exceptions.

**Comment by blesh** [comment]
One idea is to dynamically add some instrumentation and provide some sort of tooling to visualize what's going on in the observable. There are some projects in the pipeline at Netflix, but I couldn't begin to estimate a delivery date.

**Comment by blesh** [comment]
closing as inactive.

**Comment by masaeedu** [comment]
@benlesh I'm still pretty interested in this. Is it possible to have console.log or whatever appear in the stack trace, or somehow artificially insert an entry for the call site?
