### ISSUE TITLE
Change in repository name

### ISSUE THREAD

**Issue by aayushkapoor206** [ReactiveX/rxjs#1531]
Hi, why was the name of the repo lowercased? :smile:

**Comment by staltz** [comment]
Because of how Github pages work, URLs are case-sensitive. It was named `RxJS` before, but the URL `reactivex.io/rxjs` did not work, but `reactivex.io/RxJS` would work. Because it would be more common to use lowercase URLs, we had to change. Now, `reactivex.io/rxjs` works, but `reactivex.io/RxJS` does not.

**Comment by blesh** [comment]
I think @staltz answered this adequately. Good question @aayushkapoor206
