### ISSUE TITLE
subscribing should return a safer Subscription

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#1532]
**RxJS version:** 5.0.0-beta.3

**Code to reproduce:**

``` js
const subscription = Observable.never().subscribe(::console.log);

subscription.next('haha');
```

**Expected behavior:**

It should throw an error because `next` doesn't exist.

**Actual behavior:**

Console logs `"haha"`.

**Additional information:**

This is a byproduct of our Subscriber architecture.

**Comment by blesh** [comment]
I'm labeling this as a "discussion" for now. Any changes here will likely come at the cost of a nasty refactor and precious, precious speed.

Even simply wrapping the `Subscriber` in a Subscription on it's way out breaks a dozen or more tests, because we have operators that are relying on the return value of `subscribe` as being the Subscriber.

**Comment by staltz** [comment]
Hmmm. This is tricky. I would vote for leaving it and not telling anyone. Those who use it will know they are doing something weird and abusing it.

**Comment by kwonoj** [comment]
I still would like to introduce changes, not immediately but gradually at some point. Behaviorwise it's anyway not expected, there's no breaking changes will be introduced. Problem is effort of refactoring, cost of performance, etcs as already pointed out.

**Comment by blesh** [comment]
This is no longer going to block release.

Since it's not documented anywhere that people can use the returned subscription as though it were a subscriber, it's not a necessarily a breaking change for anyone but people that are abusing that API (which at that point should be private).

When we change this at a later point (if we change it) it will be a minor version change perhaps, and we can add deprecation messages to the APIs we're removing.

**Comment by blesh** [comment]
This is still an issue. We're leaking implementation details with the Subscription. Leaving it open for now.
