### ISSUE TITLE
debounce/debounceTime events bug?

### ISSUE THREAD

**Issue by rickmed** [ReactiveX/rxjs#1577]
**RxJS version:**
beta 4
**Code to reproduce:**
```javascript
Input$ //observable of keyboard events
      .do( x=> console.log(x))
      .debounceTime(1000)
      .do( x=> console.log(x))
````
result:
![image](https://cloud.githubusercontent.com/assets/7104786/14255553/5920655e-fa5e-11e5-88b7-8d2644e99d97.png)

**Expected behavior:**
The event object to be passed as it was received

**Actual behavior:**
All values are passed as null

**Additional information:**
with throttleTime it works as expected
```javascript
Input$  //observable of keyboard events
      .do( x=> console.log(x))
      .throttleTime(1000)
      .do( x=> console.log(x))
````
![image](https://cloud.githubusercontent.com/assets/7104786/14255625/ba344bee-fa5e-11e5-8f87-a4015af9e06a.png)

**EDIT**: Idem with debounce.

**Comment by staltz** [comment]
Seems like a legit bug IMO. @kwonoj @blesh this is interesting, it seems those properties are lost just because the value `this.lastValue` is stored as a property of DebounceTimeSubscriber https://github.com/ReactiveX/rxjs/blob/master/src/operator/debounceTime.ts#L71 while in RxJS the value `x` is passed to the scheduled dispatch through the closure: https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/debounce.js#L45

**Comment by kwonoj** [comment]
yes, interesting. I'll look this on my end too.

**Comment by staltz** [comment]
@rickmed I assumed you used Chrome. But which version?

**Comment by rickmed** [comment]
@staltz Version 49.0.2623.110 m

**Comment by blesh** [comment]
`SyntheticKeyboardEvent` <--

This is because you're using React. In React, you need to call `e.persist()` on events or they will mutate. 

[For more information see the React documentation](https://facebook.github.io/react/docs/events.html)
