### ISSUE TITLE
Installing beta.5 implicitly requires typings package installed

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#1580]
**RxJS version:**
Beta.5

**Code to reproduce:**
create empty repo, do `npm install @reactivex/rxjs`

**Actual behavior:**

```sh
> @reactivex/rxjs@5.0.0-beta.5 install Z:\github\test\node_modules\@reactivex\rxjs
> typings install

'typings' is not recognized as an internal or external command,
operable program or batch file.
```

**Additional information:**

Latest change 
https://github.com/ReactiveX/rxjs/commit/41a1bbc43908f5e99c24b8c142bf6cd9d8aaa435#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R51

overrides behavior of `install`. Recommended practice is not to use `install` script, 
>Don't use install. Use a .gyp file for compilation, and prepublish for anything else. You should almost never have to explicitly set a preinstall or install script. If you are doing this, please consider if there is another option. The only valid use of install or preinstall scripts is for compilation which must be done on the target architecture. 
(https://docs.npmjs.com/misc/scripts#best-practices)

and current script already utilizes `prepbulish` (https://github.com/ReactiveX/rxjs/blob/1b8600001f4226655afc54f3699ed3d0bfb0308d/package.json#L90) for lifecycle hooks.

**Comment by kwonoj** [comment]
@blesh , is there specific reason to override `install`? otherwise I can take this to revert back.

**Comment by staltz** [comment]
Yeah, let's not override `install`. Neither `postinstall`, it bites back, because it also executes when projects that depend on the library are npm installed, the `postinstall` for our library would run (which is not what I think most of us would expect. We expect `postinstall` runs only when we are npm installing explicitly only reactivex/rxjs as a project)

**Comment by kwonoj** [comment]
I've made changes for now, leaving issue open for further discussion if needed.

**Comment by blesh** [comment]
> @blesh , is there specific reason to override install? otherwise I can take this to revert back.

The reason I did that was because the typings install was not running when I went to publish the packages that time. It seems like that was the wrong way to solve the problem. :) I'm okay with changing it back, as long as we're sure that if you clear out your typings and your node_modules, you can run all of the pre-publish steps fine.

**Comment by kwonoj** [comment]
I'll check this by myself locally and if there's issue, will think about way.

**Comment by SomeKittens** [comment]
This may be related to an issue I just ran into:

```
$ npm install @reactivex/rxjs
npm ERR! cb() never called!
```

I do not have typings installed (globally or locally) and this is all the error message I get on beta.5 and beta.6.

I'd be strongly for reverting this (or adding typings as a dependency) because it's impossible to determine what's going wrong from the current error.

**Comment by kwonoj** [comment]
@SomeKittens this is already reverted in b.6. for npm error you're experience, you may refer https://github.com/ReactiveX/rxjs/issues/1623 - seems it's related with node / npm version.

**Comment by SomeKittens** [comment]
Huh, figured it was attached here because installing typings globally fixed the problem

**Comment by kwonoj** [comment]
I'm leaving this issue opened bit more to ensure any other issues are occurring along with verify 

>  as long as we're sure that if you clear out your typings and your node_modules, you can run all of the pre-publish steps fine.

too.

**Comment by kwonoj** [comment]
`npm install && npm prepublish` works so far after clear up `node_modules` and `typings` both. Let me close this for now - @blesh , please ping me anytime if there's issues - I'll look into immediately.
