### ISSUE TITLE
RxJS Observable.ajax cross domain issue  

### ISSUE THREAD

**Issue by techniq** [ReactiveX/rxjs#1732]
**RxJS version:**
5.0.0-beta.8

**Code to reproduce:**
[Codepen example](http://codepen.io/techniq/pen/XKrmKb?editors=0012)
```js
const { Observable } = Rx;

/*
XMLHttpRequest cannot load https://www.reddit.com/r/reactjs.json.
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://s.codepen.io' is therefore not allowed access.
*/
Observable.ajax(`https://www.reddit.com/r/reactjs.json`)
  .catch(err => console.log('Observable.ajax error', err))
  .subscribe(res => console.log('Observable.ajax', res))

// Same error
Observable.ajax({ url:`https://www.reddit.com/r/reactjs.json`, crossDomain: true })
  .catch(err => console.log('Observable.ajax error', err))
  .subscribe(res => console.log('Observable.ajax', res))

// Success!
Observable.from(fetch(`https://www.reddit.com/r/reactjs.json`))
  .subscribe(res => console.log('window.fetch', res))
```

**Expected behavior:**
Unable to request third party APIs using `Observable.ajax(...)`, although using `window.fetch` with `Observable.from` works as expected

**Actual behavior:**
Determine if this is a bug with RxJS's Observable.ajax, or just a configuration issue.

**Additional information:**

**Comment by kwonoj** [comment]
As error message mentions, seems like default factory of XHR in `ajaxObservable` sets `withCredentials` to true by default (https://github.com/ReactiveX/rxjs/blob/ceb99904c6b56a5d2e832fdd9e07dcf58cb2ad3d/src/observable/dom/AjaxObservable.ts#L28-L29) causes this issue.

> A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true.

as an immediate workaround, can provide custom factory to XHR such as 

```js
Observable.ajax({ 
    url:`https://www.reddit.com/r/reactjs.json`, 
    crossDomain: true, 
    createXHR: function () {
      return new XMLHttpRequest();
    }
})
```

allows bypassing default configurations. 

I'm not sure if this is expected behavior to set credential by default, or at least need to allow user level configurations to those flags - CC'ing @trxcllnt for asking helps as original author.

**Comment by techniq** [comment]
thanks @kwonoj, this works.  I'm interested in what @trxcllnt has to say about the defaults as well

**Comment by trxcllnt** [comment]
@kwonoj @techniq while I helped with an initial port of the ajax method from [RxJS-DOM](https://github.com/Reactive-Extensions/RxJS-DOM), I believe @blesh is responsible for the version that actually made it into the library. It seems we should be doing something similar to the fix for [RxJS-DOM#95](https://github.com/Reactive-Extensions/RxJS-DOM/issues/95), and switch [how we create the XHR](https://github.com/Reactive-Extensions/RxJS-DOM/blob/35271e7ddd7e68838d181beae3cee696b657f7f4/src/ajax/ajax.js#L214) based on the `crossDomain` flag.

**Comment by kwonoj** [comment]
Let me try to update implementations.

**Comment by stevematdavies** [comment]
This is not fixed: 

There is still an error the above example, when using rxjs 5+ and redux-observable.


```
const fetchTestReportsEpic = (actions) => {

    const requestSettings = {
        url:'http://localhost:3001/testReports', 
        crossDomain: true,
        body: {},
        responseType:'json',
    }

    return actions.ofType(ActionTypes.FETCH_TEST_REPORTS)
        .switchMap(() => 
            Observable.ajax(requestSettings)
            .map(payload => { 
                console.log(payload);
                fetchTestReportsFulfilledAction(payload) 
            }));
}
```

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3001/testReports. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Comment by EFGeorgiMirchev** [comment]
Hi guys,
I too face the same issue. There was an example using:
`import {ajax} from "rxjs/observable/dom/ajax";`
And just calling whatever `ajax.getJSON("http://...")` will result in an error that Access-Control-Allow-Origin header is missing.
