### ISSUE TITLE
toPromise behavior when observable ends without having emited any value

### ISSUE THREAD

**Issue by sledorze** [ReactiveX/rxjs#1736]
When executing the code below, the result of x is 'undefined'.

``` typescript
Rx.Observable.of().toPromise().then(x => console.log("x is undefined!!! " + x));
```

I think that a promise derived from an observable which is terminated and has not emitted any event should emit an error and not emit an undefined.

Otherwise, this would mean that all future usage of toPromise will result into a 'T | undefined'.

**Comment by sledorze** [comment]
Another problem is that it is not clear what would the meaning of an undefined be; if it would have been emitted by the observable or because there was no values.

I can, on the other side, understand the appeal that a type directed approach - without having to check for errors and only take care of undefined.

An expressive (and educative) proposition:
Offer the caller to provide an optional function to generate the alternative promise value in case the observable didn't emitted any values on completion.

**Comment by blesh** [comment]
> Offer the caller to provide an optional function to generate the alternative promise value in case the observable didn't emitted any values on completion.

I'm not opposed to this idea.

**Comment by blesh** [comment]
@zenparsing @domenic @jhusain Does this seem like a case for having a promise notify of "cancellation"? I'd argue "no", because it seems more like it's a completion without value (similar to a function default returning `void`)... but I'd love your opinions, and thought you might find the issue interesting.

**Comment by david-driscoll** [comment]
Well by the nature of the method, `Observable.of()` is going to emit undefined, and the type will be `{} | undefined`.  All `toPromise()` is just going to forward that along, with the result being `{} | undefined`;

Likewise if you do `Observable.empty()` it's going to be `{} | undefined`, and it's to promise will be the same.  In addition you can solve the case of `Observable.empty().toPromise()` with `Observable.empty().defaultIfEmpty(value).toPromise()`

I don't see the lack of emitted value as a direct issue of the promise integration.  Another confusing case is that `toPromise()` only returns the last value emitted, even if you emitted 20 before.  This is because it just tracks the last value emitted, and resolves at completion.

**Comment by staltz** [comment]
I think this is what we should do:

> I think that a promise derived from an observable which is terminated and has not emitted any event should emit an error and not emit an undefined.

For two reasons: (1) a promise represents an eventual *value*, so a lack of a value should be treated as an error, because no such error will be delivered; (2) `toPromise` behaves like `last()` operator in that it only emits the last value, and the `last` operator throws if the source completes before any `next` was sent. `last` also takes a defaultValue. Making `toPromise` match `last` semantics may help users understand one or the other operator. I don't see why we should give different semantics to `toPromise`. Principle of least surprise.

**Comment by sledorze** [comment]
@staltz I agree with every single bit.

**Comment by blesh** [comment]
Looking at what RxJS 4 does, I think we should stick with that for now. I have concerns about the implications of people converting code that used to go down the "success" path that now go down the error path.

In Rx, `observer.complete()` implies a _successful resolution_ of the observable sequence, that is totally independent of whether or not the observable has emitted a value.

Imagine you represent an async process with an Observable. This process' job is to monitor a sensor for input for 20 minutes. If 20 minutes pass and the sensor never emits a value, the observable will complete. Now imagine we need to consume that completion with some API that takes a promise. Was that completion an error *simply because* no values were emitted? No. The process did it's job.

**Comment by blesh** [comment]
cc/ @mattpodwysocki

**Comment by corps** [comment]
I tend to agree with @blesh.

I would argue that Promises are not eventual values, but /async work/ that /can/ pass a value.  The vast majority of the usage of Promises is about awaiting the completion of some work, and then scheduling more work.  I mean, part of the whole point of Promises is that a correct implementation should if anything /prevent multiple calls to resolve/ BECAUSE of the need for guaranteeing a certain execution behavior.

It's this difference of focus between Promises (which are about controlling execution flow) and Observables (are about controlling data flows) that makes this tricky.

I really argue that if you are going to use a Promise, it's probably because you care most about the execution aspect; when X is done do Y unless an error occurred.  At least, that's most of my use cases.

Providing a simple default value can help clarify ambiguous cases, but I'm definitely against no-value observables mapping to error promises.

**Comment by sledorze** [comment]
@corps @blesh you're dodging the crux of it.

const prom = Observable.of().toPromise()

What behaviour are you proposing?

I'm still in favor of a solution taking an alternative default promise.

**Comment by corps** [comment]
The behavior I would expect for the above Observable.of().toPromise() would be equivalent to

```
new Promise(function(res, rej) { res(); });
```

Along with the proposal of being able to provide a default (but not error even if one is not given).

The reasoning?  *Promises are not eventual values*.  They're async try {} catch {} blocks that /can/ return a value.  It's worth considering that in traditional javascript semantics, not returning a value from a function does not result in execution throwing an exception, even if that function "should" have returned a value, and it's impossible to distinguish `return undefined` from a lack of a return.  This is analogous in every way to a Promise of an Observable that 'returns' no value.  It's only important that the Observable completed without error.

While that behavior may be "bad" design, it /is/ standard behavior for Javascript execution, and a Promise is 99% about controlling execution flow, not data flow.  If you made the change of "erroring" a Promise on an empty observable, I am certain there will be many developer surprised and frustrated by this behavior.

**Comment by sledorze** [comment]
@corps
What you're proposing is that a promise could have 4 states:

- pending.
- returning a value (success).
- returning an error (failure).
- returning nothing (?).

*This* is your own definition of Promise.

Here's the standard for Promise A+:
https://promisesaplus.com/

Stating:
"A promise must be in one of three states: pending, fulfilled, or rejected."

Now, that this is clear, we're back with our 3 states:
1) pending.
2) returning a value (success).
3) returning an error (failure).

So it would be normal, not having a value (case 2), to either stay pending (case 1) or throw an error  (case 3) - again, based on the very definition of promises states.
From those alternatives, the later one is the most expressive (you can implement the other behaviour from it).

But yes, I agree with you, this is inconvenient and we want to address this, not by bending the semantic with specific use cases in mind, but by design at the API level so that the developper understand the case, have maximum expressive capabilities and in a nice way.

**Comment by corps** [comment]
@sledorze 

I'm not sure how you have arrived at the conclusion of 4 states.  I thought my answer to your question is pretty clear; the state I propose is the same as a function "that doesn't return a value" in javascript: the state of returning a value "undefined".  That means 3 states.

1.  Pending (execution is complete)
2.  Maybe returning a value (execution was succesful)
3.  Maybe returning an error (execution failed)

I'm not sure how familiar with javascript you are, but how would you describe the state of `b` the following  script being executed?

```
function addTwo(a) { if (a > 10) return a + 2; }
var b = addTwo(1);
```

Now it is strange, indeed, that a method that is expected to return a value, seemingly doesn't.  But what matters in Javascript functions is merely execution: addTwo "can" return a value, but if it doesn't, "undefined" is given once execution is complete.  

This mimics an Promise that provides no value, but whose execution completes, as below (which is valid javascript and will execute with any valid implementation of the Promise spec):

```
var p = new Promise(function(resolve, reject) { resolve(); });
p.then(function(v) { console.log(v); });
```

I believe you may be misunderstating the Promise spec to believe that resolve with no value should somehow not result in a successful resolution with the value undefined.

**Comment by david-driscoll** [comment]
> Promise States
> A promise must be in one of three states: pending, fulfilled, or rejected.

> When pending, a promise:
>  * may transition to either the fulfilled or rejected state.
>
> When fulfilled, a promise:
>  * must not transition to any other state.
>  * must have a value, which must not change.

> When rejected, a promise:
>  * must not transition to any other state.
>  * must have a reason, which must not change.
> Here, “must not change” means immutable identity (i.e. ===), but does not imply deep immutability.

The key point is `must have a value, which must not change.`  No where in the spec does it say the value must be truthy, just that it must have a value.  `undefined` is a valid value, just as valid as `null`.

As stated before if we were to make this change it would break countless consumers both currently using Rxjs5 and anyone porting over from rxjs4.

If you want to add in a default value to `.toPromise()` we accept PRs and I'm sure we could work it in, as long as it doesn't affect performance very much.

**Comment by sledorze** [comment]
Ok so let's put 42 as a value then; It's ok with the spec! :)

That is strange that having not received anything we transition to the 'fulfilled' state and not the 'rejected' one.

I'm lowering my expectations as long as the case is clear to the developper, I'm fine.
So, you're proposing to adapt the Promise type signature to 'T | undefined' at least?

**Comment by blesh** [comment]
Closing as inactive.

**Comment by sledorze** [comment]
Sorry lost into beating the averages........

**Comment by josh-sachs** [comment]
This was an amazing read.  Thanks guys!
