### ISSUE TITLE
Look into groupBy test

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1743]
In #1701, there was a test I commented out because its intent wasn't entirely clear, but it was broken after changes to Subject (to match Rx4 semantics) effected the subjects returned by `groupBy`.

Here is the test: https://github.com/ReactiveX/rxjs/blob/e9445c9c16898945b3b958bca729c1e76629fada/spec/operators/groupBy-spec.ts#L1126-L1204

We need to capture it's purpose and drop, refactor or rewrite the test as necessary.

cc/ @staltz

**Comment by blesh** [comment]
Closing this issue as stale.

**Comment by staltz** [comment]
I'm reopening this as I'm now refactoring/rewriting it.

The purpose is: make sure that the inner Observables (GroupedObservables) emitted are hot Observables, backed by a Subject, so late subscribers lose past events.

Why it is broke after the Subject rework: because the group duration subscriber subscribes before the "late subscriber", and the duration subscriber is a TakeOperator, which means once it receives the second `next`, it completes the GroupedObservable before the late subscriber is able to get that `next` event.

I'm working on rewriting this test.

**Comment by staltz** [comment]
Closing because the PR was merged.
