### ISSUE TITLE
Bug in buffer or bufferCount operation when used with subject

### ISSUE THREAD

**Issue by iFadey** [ReactiveX/rxjs#1754]
**RxJS version:** 5.0.0-beta.8

**Code to reproduce:**
https://jsfiddle.net/iFadey/qahvL1dm/

``` javascript
let section = document.querySelector('section');
let subject = new Rx.Subject();

Rx.Observable.fromEvent(section, 'click')
.subscribe(e => subject.next(e))
;

subject.buffer(subject.bufferCount(2))
.subscribe(x => console.log(x))
;
```

**Expected behavior:**
On first two clicks on section element must print pair of two event objects.

**Actual behavior:**
It prints single event object on first two clicks. Afterwards it starts printing correct pair.

**Additional information:**
I verified it in RxJS 4 and it works correctly with that version.

**Comment by blesh** [comment]
To narrow this down, what you're seeing is happening in `buffer`. The same behavior occurs with `subject.buffer(subject.take(2))`. This seems a little edge-casey, and might be a quirk with changes to default scheduling, but, for now I'll label it as a bug until we can confirm otherwise, since it is odd.

**Comment by Podlas29** [comment]
Currently on 
```
const source = Observable.from([1,2,3,4,5,6]);
source.buffer(source.take(2));
```
RxJS 4 returns:
```
[1]
[2]
[]
// complete
```
This last array is last opened buffer, which did not have time to be populated with values, since right after it's opening `take(2)` completes stream.

The same code in RxJS 5 results in:
```
[]
[]
// complete
```

There are actually two differences here: first is obvious subscription order bug, that was fixes here: https://github.com/ReactiveX/rxjs/pull/2195

On that branch results are: 
```
[1]
[2]
// complete
```
So second problem is that last one array. Currently code
```
Observable.never().buffer(Observable.empty());
```
in RxJS 4 results in
```
[]
// complete
```
and in RxJS 5
```
// complete
```
So real question here is: **when selector stream completes do we want to return last initiated buffer?**
