### ISSUE TITLE
Strange behavior: published observable emit value in wrong order

### ISSUE THREAD

**Issue by hatelove85911** [ReactiveX/rxjs#1789]
**RxJS version:**
5.0.0-beta.7
**Code to reproduce:**
```
const A = new Rx.Subject()

const B = Rx.Observable.zip(Rx.Observable.of(6,7,8,9,10), A, (x, y) => x).startWith(5).publish()

const C = Rx.Observable.interval(1000).publish()


const D = new Rx.Subject()

const E = Rx.Observable.merge(D.mapTo(-1), B).scan((acc,curr)=> acc + curr, 0).publish()


E.filter(x=> x===0).subscribe(A)
C.subscribe(D)


E.subscribe(x=>console.log(x))

E.connect()
C.connect()
B.connect()
```

**Expected behavior:**
in the console, it should log 5, 4, 3, 2, 1, 0, 6, 5, 4, 3, 2, 1...

**Actual behavior:**
5, 4, 3, 2, 1, **6, 0**, 5, 4, 3, 2, 1...
when it reaches 0, the next value 6 is emitted before zero to the subscriber.

**Additional information:**
I'm writing a small snake eat food game

**Comment by trxcllnt** [comment]
@hatelove85911 Rx is working as expected. If you move `E.subscribe(x=>console.log(x))` to before `E.filter(x=> x===0).subscribe(A)` instead of after, the events are logged in the order you want. If not, the event where `x===0` is emitted to the `A` Subject before it's logged to the console, which synchronously pushes a value through `B`, `E`, and the second subscription, then the stack unwinds back to the point where `0` is emitted to the second subscription.

**Comment by trxcllnt** [comment]
@hatelove85911 sorry for prematurely closing the issue, I accidentally hit the "Comment and close" button :/

**Comment by hatelove85911** [comment]
@trxcllnt, I don't quite understand, If I put a log at the end of E observable:
`const E = Rx.Observable.merge(D.mapTo(-1), B).scan((acc,curr)=> acc + curr, 0).do(x=>console.log('E:' + x)).publish()` 

in the cosole, I see

> "E:0"
> "E:6"
> 6
> 0

It clearly says that E observable emits 0 and then 6. How come the subscriber of this observable get the 6 first and then 0??

Even though 0 and 6 is synchronously emitted, it should still stay in order, right? Or Not?

I don't quite understand 

>  the stack unwinds back to the point where 0 is emitted to the second subscription.

Could you try elaborate into more details ?

**Comment by trxcllnt** [comment]
@hatelove85911 yes, that is what I see as well. When you change the subscription order from
```es6
E.filter(x=> x===0).subscribe(A)
C.subscribe(D)
E.subscribe(x=>console.log(x))
```

to
```es6
E.subscribe(x=>console.log(x))
E.filter(x=> x===0).subscribe(A)
C.subscribe(D)
```

you should see:
```
E:0
0
E:6
6
```

This is due to the order of your subscriptions to the published `E` Observable. By publishing `E`, you've inserted a Subject between the `E` Observable source (which as you can see from the `do` log is emitting values in the expected order), and the two subscriptions to `E`.

Subjects emit values to their subscribers in the order in which the subscriptions occur. If you subscribe the `A` Subject to the `E` Observable first, then when `x === 0`, `A` will be notified before the `console.log(x)`.

Since `A` feeds back into the zipped `B` Observable at the top, and `B` is merged with `D` (and run through the scan), the `x === 0` event emitted to A is **synchronously** pushed through your Observable workflow _before_ `0` can be logged to the console.

**Comment by hatelove85911** [comment]
@trxcllnt, thanks a lot for the explanation. Now I totally get it when I think more into details of implementation.

So for those who might encounter this kind of issue:

As trxcllnt said above, after publish, behind the scene, there's a subject stands in between the source and subscriber. I guess it's using an array to store all the subscribers. 

In my case, the subscribers to E observable will be (conceptually ) 
`[ E.filter(x=> x===0).subscribe(A),   E.subscribe(x=>console.log(x)) ]
`

Now when 0 arrives, the call sequence will be as following: 
```
E.next(0) ->
           |-> E.filter.next(0) -> A.next(0) -> B.next(6) -> E.next(6) ->
           |                                                            |->E.filter  |stopped
           |                                                            |->E.subscribe(6=>console.log(6))
           |
           |-> E.subscribe(0=>console.log(0))
```


E.filter(x=> x===0).subscribe(A)    ----> A  -----> B -----> E ----> 6 -----> E.filter(x=> x===0) -----> E.subscribe(x=>console.log(x))

**Comment by hatelove85911** [comment]
I've come up with a solution for this problem, I don't know if it's the right way, but I'll share it here:
`E.filter(x=> x===0).delay(10).subscribe(A)`
I delay the E stream for a very short time and then emit the value to A stream.

then it solves the synchronous emit values issue.
