### ISSUE TITLE
Consider adding operator that aliases map().distinctUntilChanged() and pluck().distinctUntilChanged()

### ISSUE THREAD

**Issue by MikeRyan52** [ReactiveX/rxjs#1832]
In a couple of "state as an observable" libraries there is an implementation of an operator typically called something like `select` that acts like an alias for `map(fn).distinctUntilChanged()` or `pluck(...keys).distinctUntilChanged()`. 

See:
ngrx/store: https://github.com/ngrx/core/blob/master/lib/operator/select.ts
ng2-redux: https://github.com/angular-redux/ng2-redux/blob/master/src/components/ng-redux.ts#L105
fluorine: https://github.com/philpl/fluorine/blob/master/src/distinctSelector.js

It would be great if a common, consistent version of this operator were in rxjs proper.

cc @robwormald @SethDavenport @e-schultz @philpl

**Comment by philpl** [comment]
I'm not sure if I have an opinion on this, but I'm here to mention that the `distinctSelector` doesn't do the same thing as ngrx/store's or ng2-redux's `select`.

Rather than selecting a single (optionally nested) property, it extracts a set of properties in an emitted object and only emits when one of these changes. So it basically selects a sub-set of an object and applies a reference equality check to each property.

**Comment by blesh** [comment]
closing as inactive
