### ISSUE TITLE
switchMap behavior differs from Rx 4 flatMapLatest

### ISSUE THREAD

**Issue by chalin** [ReactiveX/rxjs#1855]
In the [Operators Renamed or Removed](https://github.com/ReactiveX/RxJS/blob/master/MIGRATION.md#operators-renamed-or-removed) section of the **RxJS 4 to 5 Migration Guide**, it is written that
- `flatMapLatest` has been renamed to `switchMap`

but the **the behaviors of these two operators differ** for the simple sample code given below (adapted from the [flatMapLatest docs](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/flatmaplatest.md). **Is this difference expected (a feature) or is it a bug?** If the former, it should probably be documented.

**RxJS version:**
 - 4.1.0 (`flatMapLatest`) vs
 - 5.0.0-beta.10 (`switchMap`)

**Code to reproduce:**

Here are **JSBin sources:  [Rx 4](http://jsbin.com/razihirete/edit?js,console) and [Rx 5](http://jsbin.com/rajagegopi/edit?js,console)**; the 5.x version is reproduced here:
```ts
var source = Rx.Observable
  .range(1, 2)
  .do(x => console.log('src: ' + x))
  .switchMap(x => Rx.Observable.of(x + 'a', x + 'b'));

var subscription = source.subscribe(
    x => console.log('Next: ' + x),
    err => console.log('Error: ' + err),
    () => console.log('Completed'));
```

**Actual behavior:**

Output for `flatMapLatest` is:
```
src: 1
Next: 1a
src: 2
Next: 2a
Next: 2b
Completed
```
Output for `switchMap` is:
```
src: 1
Next: 1a
Next: 1b
src: 2
Next: 2a
Next: 2b
Completed
```

**Additional information:**

If the map function argument is changed to `x => Rx.Observable.of(x + 'a', x + 'b').delay(0)` then both have the same behavior, generating output:
```
src: 1
src: 2
Done
Next: 2a
Next: 2b
Completed
```

**Comment by jayphelps** [comment]
This is actually not related to the `flatMapLatest` vs. `switchMap` and instead related to a change in the default scheduler used.

You can make v5 behave like v4 by providing the `Rx.Scheduler.queue` scheduler to both `.range()` and `.of()`: http://jsbin.com/juxeye/edit?js,console

AFAIK it's not possible to make `Observable.of()` in v4 behave like v5 because in v4 it does not accept a custom scheduler.

v4 defaults to `Rx.Scheduler.currentThread` (aka trampoline scheduler, now known in v5 as `Rx.Scheduler.queue`) but v5 defaults to [no special scheduling at all](https://github.com/ReactiveX/rxjs/blob/master/src/observable/RangeObservable.ts#L89-L106); sometimes known as "recusive scheduling" which is just a fancy name for normal syncronous JavaScript.

For posterity, here are the [name changes to the schedulers](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md#schedulers-renamed) and [their docs](https://github.com/ReactiveX/rxjs/blob/master/doc/scheduler.md)

The migration guide doesn't make this clear enough IMO, so that's something actionable for us I think.

**Comment by jayphelps** [comment]
There is now a section in MIGRATION about how the default scheduling changed: https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md#default-scheduling-changed

**Comment by chalin** [comment]
> This is actually not related to the `flatMapLatest` vs. `switchMap` and instead related to a change in the default scheduler used.

I had a suspicion that it my be unrelated to the operators themselves.

@jayphelps, thanks for the clear explanation and for updating the migration guide!
