### ISSUE TITLE
[proposal] add TS type definition for users who use cdn 

### ISSUE THREAD

**Issue by ichpuchtli** [ReactiveX/rxjs#1879]
**RxJS version:**
5.0.0-beta.11

**Code to reproduce:**
app.ts
```ts
///<reference path="../node_modules/rxjs/Rx.d.ts" />

var todos = Rx.Observable.of([{id: 1, title: 'Todo item', complete: false},...])
...
```
index.html
```html
<script src="https://npmcdn.com/@reactivex/rxjs@5.0.0-beta.11/dist/global/Rx.umd.js"></script>
<script src="app.js"></script> <!-- app.ts -->
```

**Expected behavior:**
Type definition providing a global Rx module like RxJS 4 rx.all.d.ts

https://github.com/Reactive-Extensions/RxJS/blob/master/ts/rx.all.d.ts

rx.all.d.ts
```ts
declare module Rx {

    // Type alias for observables and promises
    export interface Observable<T> { 
        from<T>(any) : Observable<T>;
        ...
    }
    ...
}
```
**Actual behavior:**
Type definitions require your app to physically depend on RxJS using ES6 import syntax rather than allow to acknowledge an ambient version acquired through external bundle or cdn etc..

**Additional information:**
I'm building a TodoMVC implementation using simply typescript and rxjs and want to use RxJS 5 but I can't figure out how to compile my app.ts with rxjs from npm into one file.

**Comment by kwonoj** [comment]
There was similar discussion in https://github.com/ReactiveX/rxjs/issues/1481, please refer if you'd like to have more details.

Basically, ambient module declaration in RxJS 4 and others (such as in definitelyTyped) is handcrafted, while external type definition in current RxJS 5 is not. Due to typescript's module definition, it is not possible to generate both at this moment. 

As comment in https://github.com/ReactiveX/rxjs/issues/1481#issuecomment-213625847 suggests, there is possibility to support UMD directly in typescript compiler which allows to consume type definition generated - plan is revisit UMD build generate script once 2.0 goes public.

Appreciate for proposal, let me track this issue via original #1481, closing this as duplicate. If you have additional suggestion or it has different scope than #1481, please feel freely reopen to continue discussion.

**Comment by ichpuchtli** [comment]
ah all good thank you.
