### ISSUE TITLE
Distinct operator doesn't work as expected

### ISSUE THREAD

**Issue by vlad-bezden** [ReactiveX/rxjs#1881]
**RxJS@5.0.0-beta.11**

** Code to reproduce:**
```
'use strict'
const Observable = Rx.Observable;

Observable.of({id: 1, value: 42}, 
							{id: 2, value: 24}, 
							{id: 3, value: 42}, 
							{id: 4, value: 24})
	.distinct(x => x.value)
	.subscribe(x => console.log(x), 
						 err => log(err), 
						 () => 'complete')

```
**Expected behavior:**
```
Object {
  id: 1,
  value: 42
}
Object {
  id: 2,
  value: 24
}

```
**Actual behavior:**
```
Object {
  id: 1,
  value: 42
}
```
**Additional information:**
You can find examples of the code:
[RxJS 4.1 Distinct Operator](http://codepen.io/vlad-bezden/pen/LkqZzJ?editors=0012)
[RxJS @5.0.0-beta.11 Distinct Operator](http://codepen.io/vlad-bezden/pen/yJkpzr?editors=0012)

**Comment by kwonoj** [comment]
It's because of RxJS 5 splits behavior of `distinct` to reduce polymorphic behavior by introducing `distinct` and `distinctKey`, latter allows to accept key selector as below signature

`distinctKey<T>(key: string, compare?: (x: T, y: T) => boolean, flushes?: Observable<any>)`

so in above code snippet, if you change it into `distinctKey` such as

```js
Observable.of({id: 1, value: 42},
                            {id: 2, value: 24},
                            {id: 3, value: 42},
                            {id: 4, value: 24})
    .distinctKey('value')
....
```

then it'll work as key selector with distinct in RxJS 4.

Please give it a try and feel freely reopen if this doesn't solve issue. Meanwhile you can look discussions in https://github.com/ReactiveX/rxjs/pull/1180. (noticed migration document doesn't reflect it yet)

**Comment by vlad-bezden** [comment]
@kwonoj , thank you very much. Indeed changing code to 

```
    .distinctKey('value')
```
solved the issue.

Thank you again.

**Comment by bentaly** [comment]
Since this has been removed what is the solution?
