### ISSUE TITLE
Suggestion: rename the Subject class into something like PublishSubject

### ISSUE THREAD

**Issue by Ptival** [ReactiveX/rxjs#1897]
I would like to raise this as a suggestion, even though I'm sure it's been considered before, at least to know the rationale behind this decision.

It seems to me that having a concrete class `Subject` is confusing for a beginner.
It seems to me that there exists an abstract notion of a `Subject` of which there are many possible instantiations like `BehaviourSubject`, `ReplaySubject`, `AsyncSubject`.

The doc for RxJS 4 was very perplexing for me in that it did not indicate what the `Subject` class was actually doing. It turns out that other Rx implementations often name it `PublishSubject` to make it clear that it is a variant of the `Subject` interface.

I think this would help beginners, help discussions by not conflating the two notions, help the documentation be more clear, etc.

**Comment by blesh** [comment]
This is an interesting suggestion. I'll leave it open for comment from the community.

**Comment by kevinvandervlist** [comment]
I agree with @Ptival, especially because the [main docs page](http://reactivex.io/documentation/subject.html) is also using an explicit PublishSubject name.

**Comment by xareelee** [comment]
My suggestion:

### 1. Use `Bridge` or `Proxy`as the name instead of `Subject`

 The [documentation has demonstrated what `Subject` is](http://reactivex.io/documentation/subject.html):

> "A Subject is a sort of **bridge** or **proxy** that is..."

The best naming is knowing what it is without a documentation. The name `Subject` is a little confused. If it is a sort of **bridge** or **proxy**, why not just use the name? 

I'd like to use `Bridge` rather than `Proxy` because it is usually used for connecting two different worlds. 

### 2. Varieties of subject should be renamed too

For example:

       RxJS 4         |  recommended in RxJS 5                   |  Docs
-----------------|------------------|---------
`Subject` (`PublishSubject`)               | `StatelessBridge` (won't hold any **state**; just pass events throught) | Don't preserve values or states. It just passes what it get to current subscribers immediately. Latter subscriber will not receive the current state (former value). <br><br>The name `Stateless` is important to remind you that this `Bridge` will not hold any values.
`BehaviorSubject` | `StatefulBridge` (keep the latest **state**; not the latest **value**) | Have a state to preserve value and pass it to its subscribers. Any new/latter subscriber will get the latest (current) state. <br><br>The name `Stateful` reminds you that it needs an initial state when creating it. <br><br>Furthermore, when `StatefulBridge` ends the stream (with `complete` or `error`), it won't hold the latest **value** (from `next`) anymore, because the latest **state** is `complete` or `error`.
`ReplaySubject`    | `BufferedReplayBridge`, `BufferedHistoryBridge`, or `BufferedValueHistoryBridge` (keep a buffered **value** history) | Act as `StatefulBridge`  but have a buffer size and/or window size to keep the latest states in the history. Any latter subscribers will replay the buffered history from oldest to latest. <br><br>The name `Buffered` is important to remind you that it needs a buffer size when creating it. <br><br>`Rx.BufferedHistoryBridge(1)` is similar to `Rx.StatefulBridge` to hold only one latest state, but they acts differently at the begin and the end: <br><br> 1. `Rx.StatefulBridge` has an initial state but `Rx.BufferedHistoryBridge(1)` doesn't. <br><br> 2. `Rx.BufferedHistoryBridge(1)` will hold the last `next` value when it has completed (or been interrupted by an error), but `Rx.StatefulBridge` won't. `Rx.StatefulBridge` only hold the latest `state` not the latest `value`. <br><br>I think the name should contain `Value`, e.g. `BufferedValueHistoryBridge`, to remind you it holds **values** not **states**.
`AsyncSubject`     | `FinalValueBridge` (only send the final **value** and the following `complete` signal) | Keep the latest **value** from upstream but not sending it to downstream (subscribers) until it receives `complete`. After receiving `complete`, `FinalValueBridge` send the final **value** and the `complete` signal to current and latter subscribers.


I'm not English native speaker, but I think this naming would be easier to understand. The original naming in RxJS 4 makes me easy to forget what its functionality is. 

For Rx beginners, we should tell them the difference between a `Bridge` holding a **state** and a **value**:

* states: `next` state with a value, `error` state with an error, or `complete` state.
* values: the value from `next` event.


### 3. Class Inheritance 

```
Bridge (abstract class/interface) 
      | -- StatelessBridge
      | -- StatefulBridge
      | -- BufferedValueHistoryBridge
      | -- FinalValueBridge
```


### 4. Suggestion on `multicast()`, `publish()`, `connect()`, `refCount()` and `share()`

Since `multicast()` and `publish()` are making a `ConnectableObservable`, they should have the same keyword in the naming, e.g. `publish`:

* rename `multicast()` to `publishTo(aBridge)` 
* rename `publish()` to `publishStateless()` (`publishTo` + `StatelessBridge`)
* rename `publishBehavior(...)` to `publishStateful(...)` (`publishTo` + `StatefulBridge`)
* rename `publishReplay(...)` to `publishBufferedValueHistory(...)` (`publishTo` + `BufferedValueHistoryBridge`)
* rename `publishLast(...)` to `publishFinalValue(...)` (`publishTo` + `FinalValueBridge`)

> The rule easy to be remembered: **Any `publish`-prefixed method will return a `ConnectableObservable`.**

Additionally, `connect()` and `refCount()` are for `Connectable`, they should also have the same keyword in the naming:

* rename `refCount` to `autoconnect()` for its behavior

> The rule easy to be remembered: **A `ConnectableObservable` should use any `connect` method to start receiving upstream values/events.**

Finally, I suggest the `share()` should be renamed to `autocastStateless` (`autocast` = `publish` + `autoconnect`).

* `.autocast(aBridge)` = `.publishTo(aBridge).autoconnect()`
* `.autocastStateless(...)` = `.publishStateless(...).autoconnect()`
* `.autocastStateful(...)` = `.publishStateful(...).autoconnect()`
* `.autocastBufferedValueHistory(...)` = `.publishBufferedValueHistory(...).autoconnect()`
* `.autocastFinalValue(...)` = `.publishFinalValue(...).autoconnect()`

> The rule easy to be remembered: **Any `auto`-prefixed method will return an Observable autoconnected according to its reference count.**

Also, we could provide `cast()` methods  (`cast` = `publish` + `connect`):

* `.cast(aBridge)` = `.publishTo(aBridge).connect()`
* `.castStateless(...)` = `.publishStateless(...).connect()`
* `.castStateful(...)` = `.publishStateful(...).connect()`
* `.castBufferedValueHistory(...)` = `.publishBufferedValueHistory(...).connect()`
* `.castFinalValue(...)` = `.publishFinalValue(...).connect()`

Sometimes we just want a Observable starts with a plan subscriber (do nothing in the subscription), because some upstream Observables will introduce side-effects and we don't care the results.

```js
// just start right away before any other subscription; make it hot.
var hotStartSubscription = observable.castStateful();  

// pseudo code: get the `Observable` which the subscription subscribe to (`StatefulBridge` in this case).
var statefulBridge = hotStartSubscription.upstream 

...

// Now we apply a subscriber to the hot Observable
var subscriptionA = statefulBridge.subscribe(subscriberA);

// Unsubscribe subscriptionA, but the upstream Observables are still hot!
subscriptionA.unsubscribe();

// Now we terminate the hot Observables
hotStartSubscription.unsubscribe();
```

Conclusion:

```
Observable ---(`.publish()`)---> ConnectableObservable ---(`.autoconnect()`)---> SharedObservable 
Observable ---(`.autocast()`)---> SharedObservable
```

Maybe we could have aliases for those old methods.

**Comment by blesh** [comment]
While I appreciate all of the great thought out into this issue. I don't think we really want to bike shed this particular name.

I'm interested to see what @mattpodwysocki and others think. @staltz @jayphelps @trxcllnt @kwonoj

**Comment by staltz** [comment]
I disagree with this one. One of the biggest benefits of keeping the API as such is to maintain parity with other Rx libraries like RxJava, RxSwift, Rx.NET, etc. This means your Rx knowledge is transferable across languages/platforms.

I myself would prefer some names to be different. That is one of the reasons why I built http://staltz.com/xstream/. But when it comes to Rx, please, let's keep it as it is.

**Comment by Ptival** [comment]
I also find this change too disruptive. I still maintain my proposal for PublishSubject, as it would align RxJS with RxJava (at least, maybe others?) and remove some ambiguity in discussions.

**Comment by blesh** [comment]
> would align RxJS with RxJava

@Ptival ... so you know, RxJava 1 is probably the most divergent Rx dialect. I say this while sitting in the same building as many of the people who authored it. It has a lot of idioms that are simply different.

FWIW, you can always alias it in your projects if you find that makes your code easier to follow:

```js
import { Subject as PublishSubject } from 'rxjs/Subject';
// or
const PublishSubject = Rx.Subject;
```

I'll remember this suggestion, I think it was thoughtful, and I think we've considered it fully, but I think I will respectfully close this issue. Thanks again @Ptival, and I hope you continue to contribute your thoughts and efforts to RxJS!

**Comment by Ptival** [comment]
@blesh I don't care too much about it nowadays, now that I understand the distinction.

It was more annoying as a beginner when I didn't notice that "Subject" was not only the name of the interface, but also the name of one default implementation.

Anyway, I'll just make sure that documentations are a little more explicit about this.
