### ISSUE TITLE
Observable.ajax error 0

### ISSUE THREAD

**Issue by blakef** [ReactiveX/rxjs#1926]
**RxJS version:**
5.0.0-beta.11

**Code to reproduce:**
```javascript
const notService = 1234
Rx.Observable
  .ajax(`http://localhost:${notService}/foo`)
  .subscribe(x => {}, err => console.log('Err:', err.message))
;
```
**Expected behavior:**
Output: Err: ajax network error

**Actual behavior:**
Output: Err: ajax error 0

**Additional information:**
At the moment if you encounter a [network error](https://xhr.spec.whatwg.org/#request-error-steps), the xhr spec requires a response with [status 0](https://fetch.spec.whatwg.org/#concept-network-error).

I'd argue that the error message is opaque, and we should look use the text 'network error' in place of just 'status 0' in the `AjaxError`.

Thoughts?

**Comment by jayphelps** [comment]
I think `ajax error 0` is fine because it's consistent. Any errors have the same message format, `ajax error <status>`. AFAIK a zero status code could mean more than a network error and we don't really have a great way of knowing which one it is.

* User started to leave the page, so it was aborted by the browser
* Timeout
* Network errors

Basically it's set to zero to start with, and doesn't change until it gets an HTTP status code back from the response.

**Comment by blakef** [comment]
It's not unreasonable to argue that my reading of the error message was naive, expecting an HTTP error code and getting a 0 instead (and being confused by it).

@jayphelps you've made a reasonable case for sticking with 0.

**Comment by iansinnott** [comment]
I notice that the original error object is also discarded. Is there any way we could improve the ajax error handling to give more context into these errors? I'd be happy to PR something but not sure what best approach would be. The only thing that came to mind is passing the original XHR error through.

**Comment by OliverJAsh** [comment]
> The only thing that came to mind is passing the original XHR error through.

Agreed. In the case of a network error, the observable will emit an error from `onreadystatechange` instead of the original XHR error in `onerror`.

A 0 status code doesn't just imply a network error but many other things: https://stackoverflow.com/a/26451773/5932012

Therefore I don't see any reliable way to infer whether an error was caused by a network error or something else.

**Comment by stevematdavies** [comment]
There appears to be bigger issues with the latest ajax functionality, but nothing is truly being addressed. IN fact the docs for the latest api show an example that fails , yet no one has addressed the issue, despite many issue reports. I love rxjs observable but the lack of consistency is creating a situation where our project will soon be dropping it.

**Comment by jayphelps** [comment]
I don’t enjoy people threatening to stop using things I make. It’s free software that I do in my personal time and don’t get a single cent for. Being abusive just makes me to want to help even less.

**Comment by stevematdavies** [comment]
I am sorry you thought it a threat, it was certainly never intended as such. It was simply an observation and personal opinion. Of course there is a degree of frustration, and the library is generally appreciated. However it is not anything personal, I do not partake in such things.

**Comment by stevematdavies** [comment]
@jayphelps, please do not take such criticism as abuse, I can't really see how it could have been construed as such, but I apologise if that's how you took it.

**Comment by stevematdavies** [comment]
I also fully admit it could well be my misunderstanding of the API / docs, I'd if so, I gladly hold my hands up as the guilty party

**Comment by jayphelps** [comment]
clarification: I thought this conversation was on redux-observable’s issue tracker as you also commented there and I mixed them up https://github.com/redux-observable/redux-observable/issues/84#issuecomment-348978299. So my statements here aren’t entirely applicable as rxjs is much more of a community project and I left the core team a while ago (time constraints). So they do not necessarily reflect the opinions of the core team and I’m sorry for confusing the two.

As a fellow community member I still think such comments are abusive and counterproductive.

**Comment by aranda-adapptor** [comment]
I'm also getting this error and now wondering whether URL parameters are supported in rxjs' `ajaxGet` function. I can't seem to find any examples of it.

**Comment by OliverJAsh** [comment]
@aranda-adapptor AFAIK you have to append them yourself to the URL.

**Comment by iansinnott** [comment]
@aranda-adapptor yup, as mentioned above you need to construct the query string yourself. This is pretty trivial though since there are a number of libraries to do this, including the built in `querystring` which is what I use with rxjs: [querystring docs](https://nodejs.org/api/querystring.html#querystring_querystring_stringify_obj_sep_eq_options).

**Comment by aranda-adapptor** [comment]
@OliverJAsh @iansinnott I am indeed appending them (just using string interpolation) and still getting this error. Reading the comments above implied that it may not be supported. Thanks for clarifying that it *is* supported. I guess my issue lies elsewhere!

**Comment by jayphelps** [comment]
@aranda-adapptor Try Chrome Dev Tools. It should say in the console why the XMLHttpRequest errored was refused. 👍
