### ISSUE TITLE
.groupBy mishandles upstream error?

### ISSUE THREAD

**Issue by vekexasia** [ReactiveX/rxjs#1929]
**RxJS version:** 5.0.0beta.11

**Code to reproduce:** 

``` typescript
import {Observable} from 'rxjs';
Observable.range(0, 10)
  .flatMap(item => item == 7 ? Observable.throw('seven reached') : Observable.of(item))
  .groupBy((item: number) => {
    console.log(typeof(item), `Item: ${item}`);
    return item % 2 == 0 ? 'even' : 'odd'
  })
  .flatMap(groupedObs => {
    return groupedObs
      .catch(e => {
        console.log(`Error in here type: '${groupedObs.key}'`, e);
        return Observable.throw(e);
      });
  })
  .subscribe(
    n => console.log(n),
    e => console.log(e),
    () => console.log('completed')
  )
```

**Expected behavior:** Should not _group_ the error. (Also why does the error get grouped to 'even'?)

**Actual behavior:** error is grouped

**Additional information:** log output:

```
number Item: 0
0
number Item: 1
1
number Item: 2
2
number Item: 3
3
number Item: 4
4
number Item: 5
5
number Item: 6
6
Error in here type: 'even' seven reached
seven reached
```

**Comment by trxcllnt** [comment]
GroupBy emits upstream errors to the inner groups, then also emits the error to the groupBy Subscriber. GroupBy must emit upstream errors to the inner groups, because otherwise their subscriptions would never terminate.

In your example, flatMapping the grouped Observables makes it appear as if the error is being emitted to only one of the inner groups, but that's because flatMap terminates all inner subscriptions if any inner subscription emits an error. It seems like the [order in which each inner group is notified](https://github.com/ReactiveX/rxjs/blob/master/src/operator/groupBy.ts#L138) of the error is determined by the Map implementation.

**Comment by vekexasia** [comment]
Hello @trxcllnt, thanks for your reply.

While i didn't quite get the reason why error must be passed within the grouped observable, i don't get why the error is grouped using the 'even' key.

Also is there a way i can bypass groupBy? so that if an error is triggered on the chain the groupby does not get the "error" and that gets forwarded directly to the end of the chain?

**Comment by trxcllnt** [comment]
@vekexasia if `groupBy` didn't emit errors to the inner the GroupedObservables, you'd end up with memory leaks from subscriptions that never get disposed:

```es6
Observable
  .range(0, 10)
  .do((i) => if (i === 7) { throw i; })
  .groupBy((i) => i % 2)
  .subscribe((group) => {
    group.subscribe(
      ::console.log,
      (err) => console.error(`inner error ${err}`)); // <-- `groupBy` must notify each group of outer error, otherwise this subscription won't get GC'd
  },
  (err) => console.error(`outer error: ${err}`));
```

Since the groups are notified of the errors before the outer subscriber, and `flatMap` is flattening all the groups (and their errors) into a single Observable, `flatMap` is being notified of the error from the inner groups before `groupBy` has a chance to notify `flatMap` of the outer error.

You can make `flatMap` ignore errors from the inner groups by returning `Observable.empty()` to catch on each Observable returned from the `flatMap` selector:

```es6
Observable
  .range(0, 10)
  .do((i) => if (i === 7) { throw i; })
  .groupBy((i) => i % 2)
  .flatMap((groupedObs) => groupedObs.catch(() => Observable.empty()))
  .subscribe(
    n => console.log(n),
    e => console.log(e),
    () => console.log('completed')
  );
```

Hope this helps.

**Comment by blesh** [comment]
I think @trxcllnt answered this adequately.
