### ISSUE TITLE
[Typings] AjaxObservable also accepts window.URL

### ISSUE THREAD

**Issue by rgbkrk** [ReactiveX/rxjs#1934]
**RxJS version:**

5.0.0-beta.12

**Code to reproduce:**

```js
var url = new URL('https://jsonplaceholder.typicode.com/comments');
url.searchParams.set('postId', 1)
Rx.Observable
  .ajax.getJSON(url)
  .subscribe(console.log.bind(console), console.error.bind(console))
```

**Expected behavior:**

Accepts the `URL` as a valid parameter.

**Actual behavior:**

Works fine when run! Yay!

However, the typings specify `string` when this can take `string | URL` - it passes straight on through to the underlying XMLHttpRequest. If we switch our codebase to TypeScript (or if someone referenced our code), they will get type errors.

Would you like a PR updating the type to `string | URL` on the `url` parameter to the ajax functions?

**Comment by jayphelps** [comment]
We don't _intentionally_ support `window.URL` objects. It just happens to work because `window.URL` instances have a `.toString()` that returns the URL and that only works for the helpers that assume the `url` param is a string.

In  regular `Observable.ajax(url)` (which has an object options) overload instead of always assuming string) there is [at least one spot](https://github.com/ReactiveX/rxjs/blob/f63dde9fed737c0f5f5e70e89b86abeb1961b2c6/src/observable/dom/AjaxObservable.ts#L158-L169) that it will go down the wrong code path and since no `url` property exists on it, it makes a GET call to `/undefined`

We could consider adding support for it though. Is that something you want?

**Comment by rgbkrk** [comment]
Aww, that's too bad. It's quite alright, I also wanted to make sure I wasn't doing something that could break in the future. I think for the time being I'll coerce to string before using these methods.

**Comment by jayphelps** [comment]
@rgbkrk 👍  closing for now
