### ISSUE TITLE
Rename do back to tap (or atleast re add alias)

### ISSUE THREAD

**Issue by BLamy** [ReactiveX/rxjs#1958]
Choosing a reserved word just seems like it's asking for problems. 

I can't for the life of me figure out how to get do to work with function bind syntax.

![image](https://cloud.githubusercontent.com/assets/324928/18639359/989bb9b8-7e61-11e6-887b-31997e4758c0.png)

`import { _do } from 'rxjs/operator/do';`
Seems to work but the underscore makes me a little cautious.

**Comment by staltz** [comment]
Look serious/legit.

**Comment by jayphelps** [comment]
This isn't specific to `do`, we have numerous operators which are reserved words in this context.

We're going to try to be more aggressive in releasing v5 final asap, so the ship has most likely sailed for v5 on this--but we can discuss solutions for v6.

In the future I'd personally like to see us move completely away from reserved words, instead of aliasing. This will be tough to bikeshed since most (or all?) of these are inherited from other Rx implementations so changing them causes us to diverge even further from the common "reactive extensions" operator names. But we have unique usage and requirements around JS so I think it's still appropriate to do what's right for JS.

**Comment by staltz** [comment]
There's so many names that coincide with reserved words. Observable.`of` to begin with. :(

**Comment by jayphelps** [comment]
@staltz `of` isn't a reserved word 😄

**Comment by jayphelps** [comment]
@BLamy remember that you can easily alias imports


```js
```

**Comment by staltz** [comment]
Ah, I assumed it was, as you can do nowadays `for (var key of obj)`

**Comment by BLamy** [comment]
The only two operators which conflict with reserved words I could find that were `let` and `do`. 

As jay said aliasing was a simple workaround but is using function bind still the preferred approach? I was only using it because it's labeled as the recommended approach but it's my first time ever using it.

**Comment by jayphelps** [comment]
I believe this is an exhaustive list:

* `catch`
* `switch`
* `do`
* `finally`
* `let`
* `throw`

I think we need to remove the recommendation around using bind operator because I think it is too prescriptive considering it's still stage-0 and somewhat controversial among TC39. We can certainly still show it as an option, but we should clarify and not suggest it as the best solution. People take what we say as gospel without knowing the costs.

**Comment by blesh** [comment]
> I think we need to remove the recommendation around using bind operator because I think it is too prescriptive considering it's still stage-0 and somewhat controversial among TC39. We can certainly still show it as an option, but we should clarify and not suggest it as the "best" solution. People take what we say as gospel without knowing the costs.

This seems actionable.

> catch
> switch
> do
> finally
> let
> throw

Renaming these would make migrations more painful, and is perhaps out-of-scope for v5.0? Particularly painful would be `catch` and `finally`, which are idioms from `Promise`. It seems like this is more of an issue for people pulling in the operators one-by-one and using them. At this point, I'm more in favor of recommending people use the operator patching modules (`rxjs/add/operator/do`, for example), as I've found them to be most beneficial to apps I've worked on.

**Comment by jayphelps** [comment]
@blesh removing that recommendation was done in #1962 👍 

Regarding the reserved word issue, I think it's more of an issue for library authors like ng2, redux-observable, etc who need to consume operators in their code but don't want to attach them to the prototype because it would cause confusion and bugs with people depending on certain operators behind available in one release (because of implementation details) and then later it gets removed because it isn't need internally.

e.g. if ng2 uses `.switch()` in the code base but then one day refactors to no longer need it, if it was added to `Observable.switch` etc it could break user code who were depending on this--even though they shouldn't, it could have just been an accident.

I don't feel this is a blocking decision for v5, but we can discuss collectively at our rxjs meeting next week.

**Comment by kwonoj** [comment]
We did this with pipe operator.
