### ISSUE TITLE
`cache()` behaves unexpectedly with non-terminating sources

### ISSUE THREAD

**Issue by chirayuk** [ReactiveX/rxjs#1959]
**RxJS version:** v5.0.0-beta.12

**Code to reproduce:**

```
var t$ = Rx.Observable.timer(0, 10).cache(1);
t$.take(5).subscribe();
// Wait until the previous subscription has ended.
// NOTE: t$ has NOT completed.
// So the following log should print one item from the cache and continue reading the rest from the timer.
// It should definitely NOT complete. But it does—prints a single item from the cache and completes.
setTimeout(() => t$.subscribe((x) => console.log(x)), 100);
```

**Expected behavior:**
Never ending console logs.

**Actual behavior:**
Single console log.

**Additional information:**
It's surprising behavior and undocumented (unless you read the code.)  It definitely bit me and I'd consider it a bug.

**Comment by blesh** [comment]
Looks like the issue is that when `take()` unsubscribes, it reduces the [ref count to zero, and kills the source subscription](https://github.com/ReactiveX/rxjs/blob/646b38ddad9c8123bc5cc8db2008f5dddfc0a61d/src/operator/cache.ts#L54-L55)

Doesn't seem like a hard fix... just requires a little thought.

**Comment by blesh** [comment]
In fact, I think it requires thought to figure out if this is a bug, or just counter-intuitive behavior.

**Comment by blesh** [comment]
Thinking about it, it seems like this isn't a bug, so much as it is counter-intuitive behavior.

consider:

```js
const source = Observable.interval(1000).cache(1)
```

That part alone is a really strange use of `cache`, most likely... using it on an un-ending observable.

In the above case we're saying `source` is a ref-counted, hot observable. So it's not going to do anything until the first subscription to it. Since it's refCounted, we're going to stop the source when the subscriber count reaches zero.

If you use `take(5)` on it, and it completes before there are other subscribers to `source`, it's going to unsubscribe from the interval we're caching from.


### Questions

Do we want a "refCounting" behavior with `cache`?  Or shall we just say it goes until it `complete`s? What are the implications of that on other operations that could be performed? How does that affect our primary use case (which is mostly caching AJAX, I think)

**Comment by blesh** [comment]
cc/ @jayphelps @trxcllnt @mattpodwysocki @jeffbcross @robwormald @kwonoj @staltz

**Comment by jayphelps** [comment]
If we can't reach consensus quickly, we might consider removing the operator entirely for v5 and try to get it (or something like it) into v6 or some kitchen sink library.

The cache operator appears to have a history of confusion #839 #1541 #1940 #1765 which isn't surprising because an operator named "cache" is pretty ambiguous since there are so many strategies.

**Comment by chirayuk** [comment]
@blesh—right on abut the counter-intuitive behavior.

My expectation is that the refCount going back to 0 when the source hasn't yet completed would still keep the subscription to the source until it actually terminates, and only then unsubscribes and get into the mode of returning cached behavior.

In my repro case, for instance, if I don't have the setTimeout in the last line, or it doesn't wait until the take() unsubscribes, then that 2nd subscribe never terminates.

While I used a never ending sequence, it doesn't have to be one, just one that terminates after `take()` has already unsubscribed.

**Comment by trxcllnt** [comment]
I honestly think the `cache` operator in its current form should be scrapped and re-thought entirely. Imo an operator that maintains a cache should abide by standard caching semantics (insertion, update, and invalidation), and would be memory-safe when the subscription to the cached Observable is closed.

Here's an example of what I mean:

```es6
import { Observable, ReplaySubject } from 'rxjs';

Observable.prototype.cache = function cache(
    keySelector,
    project,
    evictionSelector = () => Observable.never(),
    map = {}) {
    return this.groupBy(
        keySelector,
        (element) => element,
        (elements) => evictionSelector(elements)
            .ignoreElements()
            .finally(() => {
              console.log(`forgetting ${elements.key}`);
              delete map[elements.key];
            })
    )
    .mergeMap((elements) =>
        map[elements.key] || (
        map[elements.key] = project(elements)));
}

const cached = Observable
    .interval(100)
    .cache(
        (value) => value,
        (values) => {
            return values
                .multicast(new ReplaySubject())
                .refCount()
        }
    );

console.log('first subscribed');
cached
  .take(20)
  .subscribe(
    (i) => console.log(`first subscriber: ${i}`),
    (e) => console.error(e),
    ( ) => console.log('first complete')
  );

setTimeout(() => {
  console.log('second subscribed');
  cached
    .take(20)
    .subscribe(
      (i) => console.log(`second subscriber: ${i}`),
      (e) => console.error(e),
      ( ) => console.log('second complete')
    );
}, 1000);
```

**Comment by blesh** [comment]
At this point, I'm in favor of pulling the `cache()` operator prior to a 5.0 release. This way we have time to reach a consensus what strategy we want to use around cache.

The goal was to provide an operator that could be used with AJAX use-cases that gave a simplistic caching behavior, similar to what one might find with promises, but providing the ability to abort the request, and the ability to retry the request.

Any other use case that might fall under "caching" wasn't really in this operator's design, however I can understand the confusion.

Alternatively, we could rename it to something like `preserve`...

**Comment by benlesh** [comment]
cache no longer exists. LOL.
