### ISSUE TITLE
Is Rx.Observable.ajax work like Rx.Observable.defer, create a new one when being subscribed?

### ISSUE THREAD

**Issue by maple-leaf** [ReactiveX/rxjs#1990]
Version: rxjs@5.0.0-beta.12

[Demo](http://codepen.io/maple-leaf/pen/XjaWmw?editors=1010#0) on codepen.

Code:

    const deferObservable$ = Rx.Observable.defer(() => fetch('https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty'));
    const mergedObservable$ = Rx.Observable.of(1).merge(deferObservable$);

    deferObservable$.subscribe(console.log);
    mergedObservable$.subscribe(console.log);

    const ajaxObservable$ = Rx.Observable.ajax.getJSON('https://hacker-news.firebaseio.com/v0/item/12601471.json?print=pretty');
    const mergedObservable2$ = Rx.Observable.of(2).merge(ajaxObservable$);

    ajaxObservable$.subscribe(console.log);
    mergedObservable2$.subscribe(console.log);

Then check the network panel, `topstories.json` being requested twice as expected, while `12601471.json` being requested fourth, two `options` and two `get`. If we ignore the `options`(while this is not likely a needed request for `get`), `Rx.Observable.ajax.getJSON` fire request and return a new observable when sbuscribed, is this expected? Is there a doc about ``Rx.Observable.ajax.getJSON``.

And last, it seems obvious that `merge` will subscribe the merged observable, am I right?

Thanks :)

**Comment by blesh** [comment]
@maple-leaf this is because `fetch` has built-in caching behavior similar to what your browser would have. I suspect this is what you're seeing in this case. [There is more documentation on fetch here](https://hacks.mozilla.org/2016/03/referrer-and-cache-control-apis-for-fetch/)

Rx's `ajax` on the other hand wraps XHR, which supports `abort`-ing the request, where `fetch`, TMK, does not. Therefor, Rx's ajax impl is much more low-level and doesn't make assumptions about how you might like to cache your values.

Since this is a question and not an actual issue with the library, I'm going to close this issue, but feel free to keep discussion going if you feel the need.
