### ISSUE TITLE
cache: Weird behaviour on throw

### ISSUE THREAD

**Issue by Kamshak** [ReactiveX/rxjs#2006]
**RxJS version:** 5.0.0-beta.12

**Code to reproduce:** 
```
const throwsInstantly = Rx.Observable.throw("E");

throwsInstantly.cache(1).subscribe(
  x => console.log(x),
  error => console.error("Cache", error),
  () => console.log("Done")
);
```
Example: https://codepen.io/Kamshak-1472390889/pen/gwowkZ?editors=0010#0

**Expected behavior:** Console prints "Cache E": The error is passed on.

**Actual behavior:** No output.

**Additional information:** Is this expected? The behaviour is different if the observable throws after the cache is subscribed (error is passed on).

**Comment by blesh** [comment]
I think this is a clincher for removing cache until we can further refine the desired behaviors.

**Comment by Dorus** [comment]
This fails for `Rx.Observable.throw("E", Rx.Scheduler.queue);` but works correct under `Scheduler.asap`, `Scheduler.async`, `Scheduler.animationFrame` and `new Rx.TestScheduler()`.

**Comment by jayphelps** [comment]
@Dorus we ended up removing the `.cache()` operator [for RC1](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#500-rc1-2016-10-11) because in it's current state it was too confusing and [poorly] trying to solve too many problems.

We do plan to revisit in the future and possibly provide one or more operators that have differing forms of caching.
