### ISSUE TITLE
Distinct operator performance issues.

### ISSUE THREAD

**Issue by bafolts** [ReactiveX/rxjs#2009]
**RxJS version:**
5.0.0-rc1

**Code to reproduce:**
Create a distinct observable with 100k unique items, it will progressively get slower as internally a serial search for the item is used.

```
var rx = require("rxjs/Rx");

var s = new rx.Subject();

s.distinct()
    .count()
    .subscribe((n) => {
        console.log(n);
    });

for (var i = 0; i < 100000; i++) {
    s.next(i);
}

s.complete();
```

**Expected behavior:**
This code should finish under 1 second.

**Actual behavior:**
This code takes minutes to run.

**Additional information:**
The internals of `distinct` needs to utilize a set to determine if the item has already been observed. The serial search will not scale. I stumbled upon this issue by not fully understanding how `distinct` worked.

**Comment by jadbox** [comment]
"RxJS version: most recent" Can you be specific: Is it RC1?

**Comment by bafolts** [comment]
https://github.com/ReactiveX/rxjs/blob/master/src/operator/distinct.ts#L68-L73

Whatever version this would be is using the for loop which will lead to the poor performance.

**Comment by blesh** [comment]
@bafolts Yeah, that is a problem. I'm surprised it made it this long without being pointed out. The `distinct` operator was added during a phase where we were trying to get functional parity with v3. However, that operator even changed since then for v4. I think we can add the `keySelector` and probably entirely drop the `comparer`. I'm not sure who wants to check for distinct in that way anyhow.

I should have a PR for this later today. 

We'll probably:

- Add `keySelector`
- Drop `distinctKey` operator entirely.

**Comment by blesh** [comment]
cc/ @mattpodwysocki @staltz @trxcllnt @jayphelps

**Comment by jayphelps** [comment]
My completely [_unscientific_ testing](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Clatest%2Cstage-0%2Cstage-2%2Cstage-3&experimental=false&loose=false&spec=false&playground=true&code=console.clear()%3B%0A%0Aconst%20count%20%3D%20100000%3B%0A%0Aconst%20set%20%3D%20new%20Set()%3B%0Aconst%20arr1%20%3D%20%5B%5D%3B%0Aconst%20arr2%20%3D%20%5B%5D%3B%0A%0Afunction%20next_Set(value)%20%7B%0A%20%20if%20(!set.has(value))%20%7B%0A%20%20%20%20set.add(value)%3B%0A%20%20%7D%0A%7D%0A%0Afunction%20next_indexOf(value)%20%7B%0A%20%20if%20(arr1.indexOf(value)%20%3D%3D%3D%20-1)%20%7B%0A%20%20%20%20arr1.push(value)%3B%0A%20%20%7D%0A%7D%0A%0A%0Afunction%20next_loop(value)%20%7B%0A%20%20for%20(let%20i%20%3D%200%2C%20l%20%3D%20arr2.length%3B%20i%20%3C%20l%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(arr2%5Bi%5D%20%3D%3D%3D%20value)%20%7B%0A%20%20%20%20%20%20return%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20arr2.push(value)%3B%0A%7D%0A%0Afunction%20test_fill(work)%20%7B%0A%20%20const%20start%20%3D%20performance.now()%3B%0A%0A%20%20for%20(var%20i%20%3D%201%3B%20i%20%3C%3D%20count%3B%20i%2B%2B)%20%7B%0A%20%20%20%20work(i)%3B%0A%20%20%7D%0A%20%20%0A%20%20console.log(work.name%2C%20(performance.now()%20-%20start).toFixed(2)%20%2B%20'%20ms')%3B%0A%7D%0A%0Afunction%20test_primedhit(work)%20%7B%0A%20%20const%20start%20%3D%20performance.now()%3B%0A%0A%20%20work(count)%3B%0A%20%20%0A%20%20console.log(work.name%2C%20(performance.now()%20-%20start).toFixed(2)%20%2B%20'%20ms')%3B%0A%7D%0A%0Aconsole.log('%3E%20fill%20up%20buffer%2C%20simulating%201000%20unique%2C%20sequential%20values%20(no%20buffer%20hits)')%3B%0Aconsole.log('---')%3B%0Atest_fill(next_Set)%3B%0Atest_fill(next_indexOf)%3B%0Atest_fill(next_loop)%3B%0A%0Aconsole.log('')%3B%0A%0Aconsole.log('%3E%20primed%20buffer%2C%20testing%20buffer%20hit%20for%201000%20(last%20item)')%3B%0Aconsole.log('---')%3B%0Atest_primedhit(next_Set)%3B%0Atest_primedhit(next_indexOf)%3B%0Atest_primedhit(next_loop)%3B%0A&stage=0) suggests to me that we should indeed utilize a set of some kind, ideally in modern browsers use an [ES6 Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) and but fall back to an array with an `indexOf` check for older platforms like IE9-10.

Again, not scientific but I feel pretty safe in my belief that Sets are super fast compared to any approach that uses Arrays--at least in Chrome.

```
next_Set 25.91 ms
next_indexOf 2775.84 ms
next_loop 4547.62 ms
```

The downside to using this would be that we could no longer accept the same `compare` function we do today, because that relies on arbitrary comparison of _each individual item_ aka a loop. `compare = (prev, next) => prev !== next`.

In some distant future when we only support IE11+ we could accept a compare function that is provided the Set and then expected to do something with it like the default `(set, value) => set.has(value)` which would allow you to iterate over each item in the Set if you _really_ wanted to.

Would love to hear others thoughts on this and if they have alternative, IE9+ supported solutions. Without proof, I feel that 99% of people using `distinct` do not need a `compare` callback, and if true I'd rather the perf of the default implementation be literally 100x better and lose that feature.

**Comment by bafolts** [comment]
A set is definitely the way to go. Instead of a `compare` method, we could use a method that generated the hash key for the item. If the hash key had to be a string then `IE9` could use generated Object properties as a set. I bet people may use the `compare` callback to select a property to compare on an object. They could use `pluck` but then they may lose their original object. With a `compare` callback they can get distinct objects without losing their original object. If users could provide a function for how to hash their Object I think they could convert their current `compare` methods fine. If a `string` return type was enforced we should also be fine for all browsers. IE9 users would have to provide the callback function.

```
Observable.fromEvent(document, "mousemove")
     .distinct((event: MouseMoveEvent) => {
          return `${event.clientX}:${event.clientY}`;
     });
```

Internally IE9 can now use the poor man's hash from days of yore `{} and Object.prototype.hasOwnProperty`.
