### ISSUE TITLE
ES2015 Module Exporting (ala Angular 2)

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#2030]
So the proposal from @IgorMinar that we need to canary at Netflix is...
### Proposal
1. `rxjs` should have all ES2015 modules with ES5 code in it except the UMD file.
2. `main` should tell CJS users to use the UMD file
3. `module` should point ESM users to a file that only exports the primitives.
### Advantages
- Better rollup tree-shaking
### Risks
- Breaking deep imports for CJS users.
- Breaking deep imports for Webpack 1 users. (But not Webpack 2)
### Details

Add the following to `package.json` in the `rxjs` package

```
"main": "bundles/Rx.umd.js",
"module": "index.js",
"typings": "index.d.ts",
```

`some-new-file` needs to basically just the export the primitives.

```
export { Observable } from './Observable'
export { Subscription } from './Subscription'
// and other primitives BUT NO OPERATOR DECORATION
```

**Comment by blesh** [comment]
cc @IgorMinar ... we still need a detailed explanation of the challenges the Angular team will face without this change.

**Comment by IgorMinar** [comment]
I'll hack on this and provide it to you tomorrow evening. I won't be able
to get to this before then.

**Comment by IgorMinar** [comment]
@alxhub tried various configurations with rollup and it seems that using the commonjs rollup plugin (https://github.com/rollup/rollup-plugin-commonjs) works fine. There is no significant payload increase.

That means that the only two downsides of not shipping esm are:

1/ users will need to do a special configuration for rxjs in order for rollup to be able to understand it
2/ the plugin doesn't work for all npm packages because of the nature of esm, so it's possible but unlikely that some future changes to rxjs will break the setup

Unless there are new findings I'm fine delaying the implementation of this change until a later version of RxJS. I do believe that it's the right change in the long-term, but it's not a show-stopper right now.

**Comment by alxhub** [comment]
My rollup config:
```
 rollup
    .rollup({
      entry: 'entrypoint.js',
      plugins: [
        nodeResolve({jsnext: true, main: true}),
        commonJs({
          include: 'node_modules/**',
          namedExports: {
            'node_modules/angular2-universal/browser.js': ['UniversalModule', 'prebootComplete', 'platformUniversalDynamic'],
          }
        }),
      ],
    })
    ...
```

**Comment by kwonoj** [comment]
AFAIK angular no longer need explicit ES2015 via https://github.com/ReactiveX/rxjs/pull/2546, closing.
