### ISSUE TITLE
Timeout operator doesn't work on extended Http class

### ISSUE THREAD

**Issue by MurhafSousli** [ReactiveX/rxjs#2031]
**RxJS version:** 5.0.0-beta.12

In Angular 2
When I extend `Http` class to add a timeout setter using rxjs, the timeout operator doesn't work when I import it like `import 'rxjs/add/operator/timeout'`

`
Error: Uncaught (in promise): TypeError: _super.prototype.get.call(...).timeout(...).catch is not a function(…) 
`

It only works when I load the entire rxjs library, here is a [live plnkr](https://plnkr.co/edit/kQTFLWjZ8lEtlN3Oe1wu?p=preview)

I have opened [this issue](https://github.com/angular/angular/issues/12258) on Angular repo and they said it doesn't fall into their bug reports.
I also opened it on [SO](http://stackoverflow.com/q/40013024/1015648) with `rxjs`, `rxjs5` and `angular` tags, couldn't get a solution

**Comment by kwonoj** [comment]
This isn't bug in ng2, neither bug of RxJS by trying out your plunkr.

1. Please ensure you imported 'all' operators / creation method you use
- `catch`, `finally` has not imported in your plunkr code

2. `timeout` signature does not accept string as duetime, while you're invoking it with ` .timeout("500", ...` via string.

Primary reason your code works with full Rx import is due to 1, by missing import to operator being used.

**Comment by kwonoj** [comment]
Adding bit more detail how to decrypt error message, in error it says

TypeError: _super.prototype.get.call(...).timeout(...).**catch** is not a function(…) 

that observable cannot lookup `catch` operator, not timeout.

**Comment by MurhafSousli** [comment]
@kwonoj It fixed now, thank you so much
