### ISSUE TITLE
Export ajax-helper in the released module

### ISSUE THREAD

**Issue by rgbkrk** [ReactiveX/rxjs#2045]
**RxJS version:**

5.0.0-rc1

**Additional information:**

I'd love to be able to fully test a module I'm working on, where I make a call to `webSocket` (yet don't use it). I noticed that [the websocket tests](https://github.com/ReactiveX/rxjs/blob/418d59769e8e61d5a7dc37235fe3862494ea35a3/spec/observables/dom/webSocket-spec.ts) use a [`MockWebSocket` from ajax-helper](https://github.com/ReactiveX/rxjs/blob/418d59769e8e61d5a7dc37235fe3862494ea35a3/spec/helpers/ajax-helper.ts). Could that be exported so Rx users can rely on it for their own testing?

**Comment by kwonoj** [comment]
There is ongoing effort to expose public interface for creating test (https://github.com/ReactiveX/rxjs/issues/1775), it may discussable to include those helper to public or not. 

For me it's bit on fence if it's needed to include those mock object or not, since those are generally easily mockable via existing mocking framework (based on test framework, like `sinon`, or `jest`, etcs).

**Comment by blesh** [comment]
cc @jayphelps

**Comment by blesh** [comment]
@rgbkrk this might even be worth just busting into it's own module, honestly. It's not really specific to RxJS.

**Comment by kwonoj** [comment]
I was actually recently thought of get rid of those mocks and using `sinon` instead.

**Comment by jayphelps** [comment]
I'm not a testing pro--but I've recently started testing the websocketsubject with redux-observable by just mocking the API I provide.

```js
class FakeWebSocket extends Observable {
  constructor(response$) {
    this.response$ = response$;
  }

  multiplex(sub, unsub, messageFilter) {
    this.subMsg = sub();
    this.unsubMsg = unsub();
    return this.response$.filter(messageFilter);
  }
}
```

So say you have an API
```js
// api.js
export const ticketSocket = Observable.webSocket('ws://whatever');
```

and an epic
```js
export const stockTickerEpic = (action$, store, { ticketSocket }) =>
  action$.ofType('START_TICKER_STREAM')
    .mergeMap(action => 
      ticketSocket.multiplex(
        () => JSON.stringify({ sub: action.ticker }),
        () => JSON.stringify({ unsub: action.ticker }),
        msg => msg.ticker === action.ticker
      )
      .map(tick => ({ type: 'TICKER_TICK', tick }))
    );
```

(injecting the api utilities to [epics described here](https://github.com/redux-observable/redux-observable/pull/115))

Then you can test it like

```js
const action$ = ActionsObservable.of({
  type: 'START_TICKER_STREAM',
  ticker: 'NFLX'
});
const response$ = Observable.of(
  { ticker: 'IGNORED', price: 0 },
  { ticker: 'NFLX', price: 100 },
  { ticker: 'IGNORED', price: 0 },
);
const api = {
  ticketSocket: new FakeWebSocket(response$)
};
const observer = sinon.stub();

stockTickerEpic(action$, null, api).subscribe(observer);

expect(api.ticketSocket.subMsg).to.deep.equal(JSON.stringify({ sub: 'NFLX' }));
expect(api.ticketSocket.unsubMsg).to.deep.equal(JSON.stringify({ unsub: 'NFLX' }));
expect(observer.args).to.deep.equal([
  [{
    type: 'TICKER_TICK',
    tick: {
      ticker: 'NFLX',
      price: 100
    }
  }]
]);
```

I don't really think you need to test that small of a utility, but if you want to it's as simple as:

```js
// so testing this vvvvvvv
export const ticketSocket = Observable.webSocket('ws://whatever');

// by doing
expect(ticketSocket.url).to.equal('ws://whatever');
```

Because any further testing is _literally testing whether or not RxJS correctly implemented WebSocketSubject_. Which I'm told is needless, though certainly you could find bugs in Rx that we didn't know of 😆 

Again, I'm not a testing pro so I have no idea if this is _good_ or a really bad idea.

**Comment by kwonoj** [comment]
I have changed to not to expose internal mock module anymore to avoid possible confusions.
