### ISSUE TITLE
Uncaught TypeError: this.durationSelector is not a function

### ISSUE THREAD

**Issue by stochris** [ReactiveX/rxjs#2053]
**RxJS version:**
5.0.0-rc.1
**Code to reproduce:**
https://jsfiddle.net/98mq5u13/2/
**Expected behavior:**
```throttle``` should work normally
**Actual behavior:**
```throttle``` throws the error in the title
**Additional information:**

**Comment by kwonoj** [comment]
This is because supplied time delay into `throttle` which expects `durationSelector`. v5 splits throttle's polymorphic behavior to `throttle(durationSelector)` and `throttleTime(delay)`, so in this case throttleTime is probably what you expected. (https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md)

p.s: I noticed operator split missing throttleTime in migration document..it need to be updated.
