### ISSUE TITLE
repeatWhen completes() subscriber immediately when notifier completes()

### ISSUE THREAD

**Issue by davidwdan** [ReactiveX/rxjs#2054]
**RxJS version:** 5.0.0-rc.1

**Code to reproduce:**

``` JS
Rx.Observable.interval(500)
    .take(3)
    .repeatWhen(attempts => attempts.delay(1000).take(1))
    .subscribe(
        x => console.log('Next: %s', x),
        err => console.log('Error: %s', err),
        () => console.log('Completed')
    );
```

**Expected behavior:**

```
Next: 0
Next: 1
Next: 2
//waits 1 second
Next: 0
Next: 1
Next: 2
Completed
```

**Actual behavior:**

```
Next: 0
Next: 1
Next: 2
//waits 1 second
Completed
```

**Additional information:**
RxJS 4 matches the expected behavior

**Comment by jayphelps** [comment]
Confirmed. This behavior differs from v4, not immediately clear whether that's from intentional changes or a bug.

Here's a demo comparing v4 to v5: http://jsbin.com/zehuqo/edit?html,js,output

While I certainly could be wrong, but it appears the difference in implementation is that v5 will `complete()` the source _right_ when the notifier observable completes, even if it was in the middle of doing something. Whereas when v4 `retryWhen` receives a `complete()` from the notifier, it seems to let the source finish gracefully.

So in the presented example what is happening is that your notifier says to `take(1)`, which means it will resubscribe to the source, then _immediately complete_ the downstream subscriber. Meaning it repeats the source synchronously and then also synchronously completes the downstream subscriber. So since the topmost source is an interval, there's nothing for it to emit in time, because it schedules for 1000 in the future. However, if the source emits things synchronously (no async scheduling) then indeed it will emit them before retryWhen gets a chance to `complete()`

What I'm talking about can be demo'd by sources which do not schedule async:

http://jsbin.com/caxiso/edit?html,js,output

```js
Observable.of(1, 2, 3)
  .repeatWhen(attempts =>
    attempts
      .delay(1000)
      .take(1)
  )
  .subscribe(
    x => console.log('Next: %s', x),
    err => console.log('Error: %s', err),
    () => {
      console.log('Completed');
    }
  );
```

```
Next: 1
Next: 2
Next: 3
//waits 1 second
Next: 1
Next: 2
Next: 3
Completed
````

(both v4 and v5 produce the same behavior for that demo)

Which behavior is "right" and expected? I can see people wanting either, depending on use cases. Either behavior we choose it probably should be documented more clearly. My gut tells me the v4 behavior is more intuitive for the most common cases.

**Comment by slavugan** [comment]
I have got similar bug with code (v5):
```
let obs = Rx.Observable.create(observer => {
    observer.next(1);
    observer.next(2);
});
obs.subscribe({
    next: x => console.log(`got ${x}`),
    error: err => console.log('error: ', err),
    complete: console.log('complete')
});
```
and response:
```
complete
got 1
got 2
```

**Comment by jayphelps** [comment]
@slavugan your code logs complete because you're not actually passing a function,  you're calling console.log immediately. Looks like a typo.

**Comment by slavugan** [comment]
@jayphelps you are right, it's a typo, I have forgotten parentheses with arrow () =>. Maybe I should delete my previous comment and this one as they have no sense?

**Comment by jayphelps** [comment]
@blesh has volunteered to dig into this. 👍

**Comment by mattpodwysocki** [comment]
@jayphelps the correct behavior is v4 as it conforms directly to the Java implementation which is the original implementation, so yes, this is a bug.
