### ISSUE TITLE
Why don't you join the original project instead?

### ISSUE THREAD

**Issue by josersleal** [ReactiveX/rxjs#2055]
**RxJS version:**

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**

**Comment by jayphelps** [comment]
If you're referring to the original v4 repo, the separate repo was intentional because we knew v5 would take a while to flesh out and didn't want confusion with issues, PRs, merging issues maintaining a separate branch, permissions, etc. It's a long story, but we do indeed plan to deprecate v4 and its repo/npm package in a clear way when v5.0.0 final is released. Thanks!
