### ISSUE TITLE
merge sequence

### ISSUE THREAD

**Issue by xareelee** [ReactiveX/rxjs#2056]
**RxJS version:** rxjs@5.0.0-rc.1 

**Code to reproduce:**

``` js
  const source$ = Rx.Observable.from([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);

  const odd$ = source$
    .filter(x => x%2 === 1)
    .do(x => console.log('odd:', x))
    ;

  const even$ = source$
    .filter(x => x%2 === 0)
    .do(x => console.log('even:', x))
    ;

  // four kinds of `merge` ways
  const output$ = 
    Rx.Observable.merge(odd$, even$)
    //Rx.Observable.merge(even$, odd$)
    //odd$.merge(even$)
    //even$.merge(odd$)
    ;

  output$.subscribe();
```

**Expected behavior:**

```
even: 0
odd: 1
even: 2
odd: 3
even: 4
odd: 5
even: 6
odd: 7
even: 8
odd: 9
even: 10
```

The execution sequence should be the same as the sequence in the source array.

**Actual behavior:**

```
even: 0
even: 2
even: 4
even: 6
even: 8
even: 10
odd: 1
odd: 3
odd: 5
odd: 7
odd: 9
```

or 

```
odd: 1
odd: 3
odd: 5
odd: 7
odd: 9
even: 0
even: 2
even: 4
even: 6
even: 8
even: 10
```

Depends on how to merge.

**Comment by trxcllnt** [comment]
@xareelee see this issue + comment https://github.com/ReactiveX/rxjs/issues/1994#issuecomment-251004187

**Comment by xareelee** [comment]
@trxcllnt thank you. Adding `Rx.Scheduler.asap` to the source does fix my problem.

I still wonder why emitting synchronously from the same source into two downstream Observables will cause an Observable waits another until that Observable completes. I think this is not the same situation as #1994.

**Comment by trxcllnt** [comment]
@xareelee Because RxJS 5 is critically focused on performance, we made the decision early on to change the default scheduling behavior from queueing (or trampolining) to recursive. If you're familiar with prior versions of Rx, this is equivalent to using `Scheduler.recursive` for all dispatches by default.

In RxJS 5, synchronous Observables created without a scheduler will fall back to [synchronous imperative loops](https://github.com/ReactiveX/rxjs/blob/master/src/observable/ArrayObservable.ts#L123) to emit values. Doing this by default is much faster than using the queue or asap schedulers, but exhibits the same behavior as the recursive Scheduler from previous versions, but without the risk of stack overflows!

Observables are lazy, stateless, and immutable, just like functions are. Declaring an Observable is like declaring a function. The Observable doesn't do any work until you subscribe to it, just like a function doesn't do any work until you call it. And along that vein, the Observable will _re-execute_ the work it does inside the subscribe function each time you subscribe to it (just like a function will re-execute each time you call it).

 Taking all this into account, your example code is effectively no different than two sequential `for` loops, the order of which is determined by their argument positions to the merge call.

**Comment by blesh** [comment]
I believe that @trxcllnt has adequately answered this question. Closing the issue for now. Thanks @xareelee for your feedback!
