### ISSUE TITLE
Obtain response on ajax() call, even if there's a 404

### ISSUE THREAD

**Issue by rgbkrk** [ReactiveX/rxjs#2059]
**RxJS version:**

5.0.0-rc.1

**Code to reproduce:**

```js
import { Observable } from 'rxjs';
import { ajax } from 'rxjs/observable/dom/ajax';

const asdf = ajax("https://api.github.com/asdf")
               .catch(err => err.xhr ? Observable.of(err) : Observable.of('.___.'))

asdf.subscribe(x => console.log(x)); 
```

**Expected behavior:**

On a 404, I expect to be able to get the payload/response. With the "API" I used above, I'd want to have:

```json
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

With `fetch` I get the response.

**Actual behavior:**

Result, that can be `.caught`, is an `AjaxError` and has rough structure (note no response):

```json
{
  "message": "ajax error 404",
  "xhr": {},
  "request": {
    "async": true,
    "crossDomain": false,
    "withCredentials": false,
    "headers": {
      "X-Requested-With": "XMLHttpRequest"
    },
    "method": "GET",
    "responseType": "json",
    "timeout": 0,
    "url": "https://api.github.com/asdf"
  },
  "status": 404
}
```

I want the response body. Is there any way to surface it?

**Comment by jayphelps** [comment]
@rgbkrk seems to work for me? http://jsbin.com/duwuwi/edit?js,console

![image](https://cloud.githubusercontent.com/assets/762949/19616372/e1fcc80e-97c5-11e6-9994-aabcce8c230e.png)

Am I confused?

**Comment by rgbkrk** [comment]
Well, I did run a `JSON.stringify` on the `AjaxError` in order to dump it here in the issue.

Now I see. In order to make this consistent further on, I need to:

```js
  .catch(err => Observable.of(err.xhr))
```

In order to have it have the same format as a response with a 2xx status code.

**Comment by rgbkrk** [comment]
Now that I see how to use this, it makes me wish I posted this as a StackOverflow issue instead. :wink: 

For the sake of me helping others in open source, around the web, and on my team - what's the reasoning behind making 404s and others turn into errors?

**Comment by jayphelps** [comment]
@rgbkrk ohhh I think I see, you're talking about the fact that error vs non-error objects differ

```js
// error
{
  message: "ajax error 404",
  status: 404,
  xhr: { ... },
  request: { ... }
}

// success
{
  status: 200,
  xhr: { ... },
  request: { ... },
  response: { ... },
  responseType: "json",
  originalEvent: { ... }
}
```

It's not immediately clear if this is intentional or if just an oversight. I can't see any problem with having the response stuff on the top-level error object.

**Comment by jayphelps** [comment]
@rgbkrk 

> what's the reasoning behind making 404s and others turn into errors?

Do you mean why is it an exception you have to catch or why is does the exception not have the response at the top level like the success object does?

**Comment by rgbkrk** [comment]
> Do you mean why is it an exception you have to catch 

Yes.

**Comment by rgbkrk** [comment]
> It's not immediately clear if this is intentional or if just an oversight. I can't see any problem with having the response stuff on the top-level error object.

If the response was in the top-level object I certainly wouldn't have gone to the documentation or issues, I would have just passed it on with a `catch` - it would be apparent to me as a user how to work with it.

**Comment by jayphelps** [comment]
I don't have true backstory on why, but I can make several guesses: v4 [did it that way](https://github.com/Reactive-Extensions/RxJS-DOM/blob/master/src/ajax/ajax.js#L76-L81) and no one has likely challenged it AFAICT. Also that this is common for ajax utils, e.g. `jQuery.ajax` does this with the promise returned, taking you down the reject path (which is also used for exceptions).

That said, the `window.fetch()` API _does not_ go down the reject path for non-200's which some [have actually complained about](https://github.com/whatwg/fetch/issues/18)

> A fetch() promise will reject with a TypeError when a network error is encountered, although this usually means permission issues or similar — a 404 does not constitute a network error, for example.

I think which one a person prefers really depends on the person and the use case. Most of the time a non-200 really is _exceptional_ and I personally prefer the exception path for these because then my "happy path" isn't cluttered with error checks and also I can let unhandled errors propagate and catch in a single place instead of it going down the happen path, throwing a reference error and losing the what would have been on the error object.

This is probably all debatable though. We might, for instance, default to similar to behavior as `fetch()` and provide a config to say what is and isn't happy like `ajax(url, { successCode: '2xx' })`.

**Comment by rgbkrk** [comment]
That makes perfect sense. In terms of ideal Rx flows, `next` and `error` stay very true to purpose. This informs me as to what our API in [`rx-jupyter`](https://github.com/nteract/rx-jupyter) should do with errors: nothing. We'll let folks handle them as they want to, documenting the way in which the errors work (which we'll happily defer to RxJS docs when we can). /cc @jdetle
