### ISSUE TITLE
providing .sample() the same observable it samples produces stale output

### ISSUE THREAD

**Issue by poyannabati** [ReactiveX/rxjs#2075]
Thanks for the skeleton @jayphelps 

**RxJS version:**
5.0.0.beta-12

**Code to reproduce:**
http://jsbin.com/sapuju/4/edit?js,console,output

**Expected behavior:**
Open the console. 3

**Actual behavior:**
2

**Additional information:**

**Comment by jayphelps** [comment]
@blesh Is this possibly related to our change in default schedulers? That was my initial hunch, but then I thought that the order should still be the same, even if it's no longer scheduled on the microtask. My latest guess is that this is primary due to the `.sample()` and the observable provided to `.sample()` both subscribing to the same subject, and in v4 perhaps it has a subtle difference in subscription order compared to v5? i.e. the sampleObservable `item$.filter(item => item === 3)` is subscribed to _before_ the `.sample()` operator subscribes to the subject, so when it receives values, `.sample()` has not yet received that value yet, hence why it outputs 2 instead of 3.

***

For other's reference:

RxJS v4 defaulted to micro-task scheduling (was called [AyncScheduler](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/schedulers/scheduler.md#rxschedulerdefault) but in v5 this is called `AsapScheduler` and AsyncScheduler in v5 is different!). In v5, for performance reasons, we [default to having no scheduler](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md#default-scheduling-changed), doing things now, synchronously. (that was called `ImmediateScheduler` in v4). This is all confusing, we realize, but the changes were thoroughly bikeshed and made for good reasons.

[More info on v5 schedulers](https://github.com/ReactiveX/rxjs/blob/master/doc/scheduler.md#scheduler-types)

**Comment by jayphelps** [comment]
I think it's more clear to reproduce this without the filter. http://jsbin.com/coreni/edit?js,output


```js
const item$ = new Rx5.Subject();

item$
  .sample(item$)
  .subscribe(value => {
    console.log(value);
  });

item$.next(1);
item$.next(2);
item$.next(3);
```

v4: 1..2..3
v5: 1..2

**Comment by blesh** [comment]
I'll take a look at this
