### ISSUE TITLE
Proposals destroy of Observable API

### ISSUE THREAD

**Issue by sculove** [ReactiveX/rxjs#2090]
**RxJS version:** rxjs5.0-rc1

**Code to reproduce:**
```js
function makeObservable() {
    let startTime = performance.now();
    let duration = 1000;
    let from = 100;
    let to = 200;
    let distance = Math.abs(to-from);
    let next = (to - from) < 0;
    return Rx.Observable.generate(
        performance.now(),
        x => x <= startTime + duration,
        x => performance.now(),
        x => (x-startTime)/duration,
        Rx.Scheduler.animationFrame
    )
    .map(p => from + (p * (next ? -distance: distance)))
    .concat(Rx.Observable.of(to))
    .distinctUntilChanged()
    .last();
}

function onMemory() {
    for(let i=0; i<1000; i++) {
        console.log("create observable", i, makeObservable());
    }
}
```
demo link : http://jsbin.com/hohoxifipu/1

**Expected behavior:** unused observable is released in memory.

**Actual behavior:** : I suspect memory-leak
before
![2016-10-28 2 11 21](https://cloud.githubusercontent.com/assets/1383952/19795738/7a22ffa6-9d19-11e6-9c33-98d8247f72b1.png)

after
![2016-10-28 2 11 14](https://cloud.githubusercontent.com/assets/1383952/19795746/81b156aa-9d19-11e6-8c74-ddfb29f4686f.png)

allocation timeline
![2016-10-28 2 22 02](https://cloud.githubusercontent.com/assets/1383952/19795787/f8a9468c-9d19-11e6-8118-cf0a1aa60a3c.png)

**Additional information:**
I want to make the animation action. so, I create Observable every time.
I pace a memory problem.

Is this right? or Did I muff it?
I couldn't find destroy API. 
How about support `destroy` of Observable API?

**Comment by kwonoj** [comment]
In general if you let subscription unsubscribes by its operator behavior (i.e, limiting source observable by take, etcs) or explicitly unsubscribe as needed, each subscription's lifecycle is completed. Please note it's lifecycle of `subscription`, since most cold observable can be subscribed anytime and each'll create subscription. (http://reactivex.io/rxjs/class/es6/Subscription.js~Subscription.html)

I'd like to ask about usecase in here bit more, since it seems bit unexpected to create several Observable to create certain animation behavior. Do you have minimal-reproducible repo of animation implemented, explains reason to create multiple observables?

**Comment by trxcllnt** [comment]
@sculove I'd imagine the Observables are sticking around in memory because you're handing them to `console.log`

**Comment by sculove** [comment]
@trxcllnt Wow. Thank you. very much.
I did check it!
demo : http://output.jsbin.com/zijegiwexe

![2016-10-28 3 07 07](https://cloud.githubusercontent.com/assets/1383952/19796561/5290ffe0-9d20-11e6-91b3-01bcf3a99708.png)
![2016-10-28 3 08 48](https://cloud.githubusercontent.com/assets/1383952/19796590/797f0f48-9d20-11e6-87ed-7575eb190b2e.png)

Could you explain this situation briefly?

**Comment by jayphelps** [comment]
when you console.log something, you can always go to the Console section of your devtools to view that log message, including any objects you logged. So exactly _because_ you could always view them, they cannot be collected otherwise...you couldn't view them 😜

Believe me, I've forgotten about this many many many times and spent hours trying to "find the leak" in my apps.

**Comment by sculove** [comment]
@jayphelps @trxcllnt thank you!
