### ISSUE TITLE
Typescript Signature for Observable<Promise<T>>::concatAll returns Promise, not Observable

### ISSUE THREAD

**Issue by Fiveside** [ReactiveX/rxjs#2136]
**RxJS version:**
RxJS version 5.0.0-rc.3
Typescript version 2.0.7

**Code to reproduce:**
```typescript
import {Observable} from "rxjs";
let o = Observable.of(1, 2, 3, 4, 5).map(x => Promise.resolve(x));
o.concatAll().forEach(x => console.log(x));
```

**Expected behavior:**
I expect it to compile without any errors

**Actual behavior:**
`test.ts(3,15): error TS2339: Property 'forEach' does not exist on type 'Promise<number>'.`

**Additional information:**
The compiler command I'm using is
`tsc --target ES6 --moduleResolution node --module commonjs test.ts`

The file compiles with errors, but the resulting js file runs without issue indicating that `.concatAll` is actually returning an Observable.

**Comment by david-driscoll** [comment]
Unfortunately this is a limitation on the type system as it exists.   There is no neat way to unwrap `Promise<T>` to get `T` so that we can return `Observable<T>`.

Instead we do our best try, which is to just return `T`.  In this case if `T` is not an observable you get this behavior.  (This also applies to arrays or iterators as well)

The easiest way around it is to use `concatMap` instead of `concatAll`.

```typescript 
import {Observable} from "rxjs";
let o = Observable.of(1, 2, 3, 4, 5).concatMap(x => Promise.resolve(x));
o.forEach(x => console.log(x));
```

or return an observable explicitly.

```typescript
import {Observable} from "rxjs";
let o = Observable.of(1, 2, 3, 4, 5).map(x => Observable.from(Promise.resolve(x)));
o.concatAll().forEach(x => console.log(x));
```

**Comment by kwonoj** [comment]
I don't see lot of actionable regarding this specific cases unfortunately. @Fiveside , does @david-driscoll 's comment clarifies your question?

**Comment by Fiveside** [comment]
Hmm, unfortunate that its just a limitation of the type system.  In my practical case, promises are generated earlier in the observable chain from a `.scan` call.  However the trick @david-driscoll posted still works, though it looks a little strange:
```typescript
observable.concatMap(x => x)
```

Thanks for your help here!
