### ISSUE TITLE
xhrreadystate fires before ontimeout causing the wrong error to be caught

### ISSUE THREAD

**Issue by samueljseay** [ReactiveX/rxjs#2149]
I'm using redux-observable with rxjs and I'm noticing the behaviour of xhr described here: http://stackoverflow.com/questions/1018705/how-to-detect-timeout-on-an-ajax-xmlhttprequest-call-in-the-browser#comment-63406804 which is that xhrreadystate is fired before ontimeout, and so the error I catch is a plain `AjaxError` with status 0.. this is obviously not the desired behaviour, but I'm wondering what solution or workaround there could be to handle it in my situation? 

The best I can achieve at the moment is guessing that the 0 status error that I get from this situation is my timeout.. however that doesn't cover some other legitimate error cases where the status is 0.

**RxJS version:** 5.0.0-beta.12

**Code to reproduce:**

```javascript
export default action$ =>
  action$
    .ofType("FETCH_DATA")
    .mergeMap(action => {
      return Observable.ajax({
        url: action.url,
        timeout: 50000
      })
      .map(payload => {
        return {
          type: "FETCH_DATA_FULFILLED",
          payload
        }
      })
      .startWith({ type: "FETCH_DATA_PENDING" })
      .catch((error) => {
        // error is AjaxError not AjaxTimeoutError
      })
    })
```

**Expected behavior:** The error caught should be `AjaxTimeoutError`

**Actual behavior:** The error caught is a `AjaxError`

**Additional information:** Note that I've confirmed via console that the AjaxTimeoutError is created in the ontimeout handler later than the `AjaxError` returned by `onreadystatechange` handler.

EDIT: the workaround I used here was to do a `Observable.race` between a delay with the timeout and the ajax call itself.

**Comment by benlesh** [comment]
So sorry to respond to this more than a year later. :(

This is the native behavior of XHR. It's tricky because we need to use readystatechange to support older browsers, rather than onload, etc.

It's probably best to just use the `timeout()` operator instead:  `ajax(url).pipe(timeout(2000), map(fn), ...)`

We might want to remove the `timeout` option all together, or re-implement the ajax stuff so that `timeout` isn't supported in browsers that require `onreadystatechange`, I'm not sure? Either way, using the `timeout` operator is going to behave more consistently. 

Closing for now.

So sorry again for the ridiculously slow response, @samueljseay
