### ISSUE TITLE
feat(operator): add concurrency parameter to switchMap

### ISSUE THREAD

**Issue by staltz** [ReactiveX/RxJS#215]
This issue is just a heads-up about an operator that _could_ be added to RxJS Next. I can also see this used through `lift` instead of bundling it straight in the library.

Basically flatMapLatestWithMaxConcurrency:

http://stackoverflow.com/questions/32233408/how-to-implement-rxjs-flatmaplatesttwo

What do you think?

**Comment by blesh** [comment]
Hmm... I think flatMap and flatMap latest should support concurrency limits regardless. Considering they're basically sugar for `map(x => obs).mergeAll()` and merge definitely supports concurrency limits.

**Comment by staltz** [comment]
Oh cool! I didn't know mergeAll() had a concurrency param. It doesn't in Reactive-Extensions/RxJS. That's great.

**Comment by blesh** [comment]
So `flatMap` has a concurrency argument already... It seems more like we don't have `flatMapLatest` implemented... that surprises me a bit as I thought we had that checked off on #100. That one is a top priority for me.

**Comment by blesh** [comment]
so it should be:

```TypeScript
function flatMapLatest<T, R>(project: (value:T) => Observable<R>, concurrent: number = Number.POSITIVE_INFINITY): Observable<R>
```

again this is a top priority for what I need, so if someone doesn't pick this up in the next few minutes I'm all over it.

**Comment by staltz** [comment]
Bikeshedding: why the `concurrent: number` as the last parameter?

**Comment by xgrommx** [comment]
As I understood:

```
flatMap => flatMapWithMaxConcurrent(Number.POSITIVE_INFINITY)
flatMapConcat => flatMapWithMaxConcurrent(1)
```

**Comment by blesh** [comment]
So digging into this... what is the point of the `concurrent` parameter in `flatMapLatest`? How can you concurrently be subscribed to inner observables if you're only ever subscribed to the latest one.

I'm not sure how I missed that, I was more freaking out that it hadn't been implemented yet.

**Comment by staltz** [comment]
> How can you concurrently be subscribed to inner observables if you're only ever subscribed to the latest one.

with `concurrent = 2` you would be subscribed to the latest **two** inner observables.

**Comment by blesh** [comment]
> with concurrent = 2 you would be subscribed to the latest two inner observables.

Oh... interesting. Yeah, I don't see why not. I guess it should default to *one* then ;) haha.

**Comment by xgrommx** [comment]
Hi @blesh. Where can I take a look on all implemented methods(some list of methods)?

**Comment by blesh** [comment]
So, we have `flatMapLatest`, it's just been conflated into `switchLatest` for whatever reason. I didn't catch that before. This goes back to bike-shedding those names to make them more predictable. It doesn't have the concurrency bit though, I can probably add that.

**Comment by blesh** [comment]
@xgrommx you can find them all either in `src/operators` or in `src/Rx.ts` or `src/Observable.ts`

**Comment by staltz** [comment]
Oh yeah how could I forget that flatMapLatest was renamed to switchLatest. We talked so much about mergeMap/switchMap/concatMap. By the way, will switchLatest be named switchMap?

**Comment by blesh** [comment]
> By the way, will switchLatest be named switchMap?

I think this requires a lot more discussion, honestly.

Digging into this issue, to do it properly is non-trivial. I've found a few other issues I'd like to refactor before I tackle this. I'll need to think about this a little more.

**Comment by trxcllnt** [comment]
@blesh @staltz since `SwitchLatestSubscriber` extends `FlatMapSubscriber`, and `FlatMapSubscriber` extends `MergeSubscriber`, we could extend the `concurrent` behavior to `SwitchLatestSubscriber` (it currently defaults to `Number.MAX_VALUE`).

At first glance, I think we'd only need to make the following four changes:

1. track inner subscriptions locally
2. change [`_innerComplete`](https://github.com/ReactiveX/RxJS/blob/master/src/operators/merge.ts#L109) to accept the inner `Subscription`, so we can remove it from the local subscriptions list (we're already planning to do this so we can remove it from the shared `Subscription`)
3. change when `SwitchLatestSubscriber` [switches](https://github.com/ReactiveX/RxJS/blob/master/src/operators/switchLatest.ts#L35) to a new inner `Observable`
4. parameterize how we [dequeue](https://github.com/ReactiveX/RxJS/blob/master/src/operators/merge.ts#L119) the next inner `Observable` (`SwitchLatestSubscriber` would want to `pop` instead of `shift`)

**Comment by blesh** [comment]
I've renamed this issue to make it more accurate as to the request.

**Comment by blesh** [comment]
Closing in favor of #347
