### ISSUE TITLE
Inconsistent execution order when calling BehaviorSubject.next inside the subscription

### ISSUE THREAD

**Issue by peterbakonyi05** [ReactiveX/rxjs#2155]
Hi,

I have found a strange issue. The code below does not call the subscriber in the expected order.

```js
const Rx = require('rxjs');

const dispatcher = new Rx.BehaviorSubject();
dispatcher.next("INITIAL");

let did = false;

dispatcher
	.do(() => {
		if(!did) {
			did = true;
			dispatcher.next("FIRST");
		}
	})
	.subscribe((state) => {
		console.log(state);
	});

dispatcher.next("SECOND");

```

Expected: "INITIAL", "FIRST", "SECOND"
Actual: "FIRST", "INITIAL", "SECOND"

Tested with `rxjs@5.0.0-rc.4` and `rxjs@5.0.0-beta.12`.

Can you please explain if it is a design decision or a bug?

Thanks,
Peter

**Comment by kwonoj** [comment]
I think this is kind of expected. It seems there is synchronous re-entrant which causes to subscription execution happens immediately for `first`, then observer is being called for initial value. If you're making observe non-synchronous reentrant like 

```js
dispatcher.observeOn(Rx.Scheduler.async)
.do(() => {
  if(!did) {
    did = true;
    dispatcher.next("FIRST");
  }
})
.subscribe((state) => {
  console.log(state);
});
```

then you can see `first` is not synchronously subscribed. 

I'll leave this open and /cc @jayphelps , @trxcllnt in case I did understand something wrong. (I do wrong thing frequently. :) )

**Comment by blesh** [comment]
Just looking at this, I'd say it's a bug. But I'll have to dig more. Thanks.

**Comment by rob3c** [comment]
Labeling that "INITIAL" is a bit misleading, especially when doing things synchronously like that. The way to truly initialize a `BehaviorSubject` is via the constructor:
```javascript
const dispatcher = new Rx.BehaviorSubject("INITIAL");
dispatcher.next("THIS IS SOMETHING ELSE BASED ON THE SCHEDULER");
```

**Comment by peterbakonyi05** [comment]
Maybe it is confusing, but even if I do the way you are suggesting, it won't change the behavior. `"INITIAL"` will come after `"FIRST"`.

I am not defending the code because I know that the example is bad code. I also understand why it is happening, it will do something like this under the hood:
```js
let did = false;

function a(data) {
  if (!did) {
    did = true;
    a("FIRST");
  }
  console.log(data);
}

a("INITIAL");
```
It is trivial that "FIRST" will come before "INITIAL" in the example above.

I would like to know if this behavior is a bug or the expected behavior of a `BehaviorSubject`. To me it is not expected, because I expect that the subscriber will get that data according to the timeline, even if the `next` calls are nested synchronously. At least that's how a stream should work in my opinion.

**Comment by trxcllnt** [comment]
This is not a bug. Subjects don't protect against reentrancy because to do so would necessitate unbounded buffers. You can either do `dispatcher.observeOn(Scheduler.asap)` or do `dispatcher = new ReplaySubject(1, null, Scheduler.asap)`

**Comment by peterbakonyi05** [comment]
Thanks for the conclusion. In my case it is not that trivial to replace it, because we use the `ngrx/store` library, that is implemented using `BehaviorSubject`. At least I know that it is not a bug so we can refactor our code accordingly and create a standard to be able to avoid future issues related to this behavior.

Thanks again!

**Comment by rob3c** [comment]
@peterbakonyi05 I've been experimenting recently with `ngrx/store` and `ngrx/effects` (and their current rxjs 5 implementation limitations), and I've been able to get correct ordering of typical REQUEST/PROGRESS/CANCEL/SUCCESS/FAILURE actions/events, even when they're interdependent and nested.

For example, a simple nesting where maybe a SELECT requires a LOAD might be:
- `SELECT_REQUEST->PROGRESS->LOAD_REQUEST->PROGRESS...->LOAD_SUCCESS->SELECT_SUCCESS->PROGRESS`
- `SELECT_REQUEST->PROGRESS->LOAD_REQUEST->PROGRESS...->LOAD_FAILURE->SELECT_FAILURE->PROGRESS`
- `SELECT_REQUEST->PROGRESS->LOAD_REQUEST->PROGRESS...->SELECT_CANCEL->PROGRESS`

To do it, I use the async scheduler via `observeOn(async)`, `takeUntil` for cancellation, `switchMap`, etc. 
Since this is a bit off-topic (although it did motivate your creation of the issue), feel free to ask over on stackoverflow using the `ngrx` tag if you're interested in further details.

**Comment by peterbakonyi05** [comment]
@rob3c I think based on your valuable inputs we will be able to find the best possible solution. I was hoping that we can resolve our issue in general, but then we need to spot these kind of issues case-by-case and apply the suggested fixes.

off-topic: Probably the best thing to do is to move dispatching of the action from the selector into another effect and add `observeOn(async)` to prevent concurrency and isolate the business logic from the view even better.

**Comment by rob3c** [comment]
@peterbakonyi05 Keep in mind that ngrx store dispatches the `Observable<Action>` returned by an ngrx effect. I mention it here, because I think others will also hit this issue when trying to manually dispatch actions directly inside `do` (and other operators) or `subscribe` like this, instead of using something like `switchMap` to return a new `Observable<Action>` to dispatch. Of course, that new returned sequence can use any rxjs magic to dispatch one or more new actions to the store.

You may find my SO answer [here](http://stackoverflow.com/a/40899875) useful as illustration. It shows a simple effect that waits on an async service while emitting progress and a success/fail result while listening for cancellation.
