### ISSUE TITLE
predicate return object for truthy doesn't work on some operator

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#2173]
**RxJS version:**
latest

**Code to reproduce:**
```js
interface Bar {
  bar?: string;
}
class Foo implements Bar {
  constructor(public bar: string = 'name') {}
}

let foo2: Bar = new Foo();

Observable.of(foo2)
    .filter(foo => foo) //compiler does not accept object `foo` as truthy
    .subscribe(foo => console.log(foo.bar));

Observable.of(foo2)
    .filter(foo => !foo) //this one works, as !foo considered as falsy
    .subscribe(foo => console.log(foo.bar));
```

**Additional information:**

So far I tried on few changes around, this seems *NOT REGRESSION* caused by recent changes.

**Comment by rob3c** [comment]
@kwonoj Good catch! I found a fix that addresses this case for `filter` while preserving the previous cases. Now I'm going to take a look at the other recently-modified operator typings, as well.

**Comment by rob3c** [comment]
@kwonoj I guess it was late and I missed the _NOT REGRESSION_ bit at the end, so I'm glad I didn't seem to break anything yet with the new type guard additions :-) (maybe the _ALL CAPS_ wasn't big enough for my aging eyes lol)

Anyway, the 'fix' I mentioned would really be adding a new behavior, as you mentioned. It changes the `filter` predicate to return `any` instead of `boolean`. I'm a bit worried that we lose the strong typing hints from the compiler, which is probably why typescript definitions originally didn't allow this case for `Array.filter`.

However, the typescript team seems to have eased off of this a bit and allowed it in TS 2.0 as of [this commit in April](https://github.com/Microsoft/TypeScript/commit/3e2fff2150cc7c0488fa91da574b16c863877b6c). If this is an important case, I think it would mainly require swapping `boolean` predicate return values for `any` like the `Array.filter` changes.

**Comment by kwonoj** [comment]
I don't think there are lot of actionable things at this moment other than loosening type to `any`. For a workaround, we could use truthy check like `xxxx.filter(x=>!!x)` (way I use it for now).
