### ISSUE TITLE
rc5 breaks expected Observable.prototype.timeout behavior

### ISSUE THREAD

**Issue by mmcgahan** [ReactiveX/rxjs#2176]
Simple use of `Observable.prototype.timeout` throws a `TypeError: this.scheduler.schedule is not a function` error in rc5 but not in rc4

**RxJS version:**

5.0.0-rc.5

**Code to reproduce:**

```js
Rx.Observable.of(1)
  .timeout(50, new Error('fail-town'))  // note, no scheduler supplied, should use default
  .subscribe(x => console.log(x), null, () => console.log('done'))
```

- [JSBin running 5.0.0-rc.5](http://jsbin.com/jegamuyuma/1/edit?html,js,console,output) - throws Error
- [JSBin running 5.0.0-rc.4](http://jsbin.com/cuyukagoti/1/edit?html,js,console,output) - same code executes without error

**Expected behavior:**

No TypeError

**Additional information:**

I haven't worked with schedulers much, but supplying `Rx.Scheduler.asap` as the third arg to `.timeout` doesn't appear to affect whether or not the error is thrown.

It looks like [all of the `timeout` unit tests](http://reactivex.io/rxjs/test-file/spec-js/operators/timeout-spec.js.html) supply a `rxTestScheduler` as the third arg - I'm not sure where this is defined but it's probably worth adding unit tests that don't include optional args to make sure the default behavior is applied correctly. If this is a real bug, that kind of unit test would have caught it.

**Comment by kwonoj** [comment]
as noted in release changelog, (https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#breaking-changes) from rc.5 `timeout` no longer accept custom error but throws `timeoutError` by default. so supplying error object will bring unexpected behavior. It is expected breaking change. 

Test cases in document is bit outdated since it's not updated after rc.5 is released, latest spec (https://github.com/ReactiveX/rxjs/blob/master/spec/operators/timeout-spec.ts#L17) is updated accordingly with breaking changes.

**Comment by mmcgahan** [comment]
Ah, I didn't the release notes correctly, thanks for the clarification @kwonoj

**Comment by samal84** [comment]
In that case then the migration guide needs to be updated: https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md

It still says that timeout accepts an errorToSend parameter.
