### ISSUE TITLE
shared observable does not emit error to second subscriber if first one did not provide error handler.

### ISSUE THREAD

**Issue by foxel** [ReactiveX/rxjs#2180]
**RxJS version:**
5.0.0-rc.1 - 5.0.0-rc.5

**Code to reproduce:**
```
const source = new Subject();

const stream = source.map((v) => {
  console.log('Map: ' + v);
  if (v == 2) {
    throw 'error';
  }
  return v;
}).share();

stream.subscribe(v => {
  console.log('Sub1: ' + v);
});

stream.subscribe(v => {
  console.log('Sub2: ' + v);
}, err => {
  console.log('Err2: ' + err);
});

Observable.range(1, 3).subscribe(v => {
  source.next(v);
});
```

**Expected behavior:**
I expect to see 
```
Map: 1
Sub1: 1
Sub2: 1
Map: 2
Err2: error
```

**Actual behavior:**
Second subscriber does not receive error
```
Map: 1
Sub1: 1
Sub2: 1
Map: 2
```

**Additional information:**
Note when i add error handling in first subscriber like this:
```
stream.subscribe(v => {
  console.log('Sub1: ' + v);
}, () => {
});
```
I get my expected behaviuor.

**Comment by kirkhoff** [comment]
+1 

This issue existed with `singleInstance` in rxjs 4.x as well. A colleague of mine logged it here: https://github.com/Reactive-Extensions/RxJS/issues/1341

As a stopgap in rxjs 4.x, we modified the default error block (https://github.com/Reactive-Extensions/RxJS/blob/master/src/modular/observer/create.js#L6) to just log the error instead of `throw(e)`. Not ideal, but it worked for us while we investigate a longer term fix.

**Comment by mukunku** [comment]
I also agree with @foxel 's assesment that this shouldn't be the behavior. If a subscriber isn't interested in handling errors, this should affect subsequent subscribers.

**Comment by cartant** [comment]
Closing this, as 6.3.2 behaves as expected and outputs the following:

```
$ ts-node index.ts
Map: 1
Sub1: 1
Sub2: 1
Map: 2
Err2: error
```
