### ISSUE TITLE
Record perf results vs RxJS 4, then drop RxJS 4 from perf testing

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#2198]
It's time to move on. Future versions of this library need to be compared against previous versions of itself, not Rx4.

We need to

1. Record and keep the perf results vs RxJS 4, if for no other reason than documentation purposes.
2. Fix the perf tests to target a previous version of RxJS 5.

**Comment by blesh** [comment]
cc @kwonoj @jayphelps

**Comment by manekinekko** [comment]
Hi @blesh are you still planning to use Benchpress for future perf tests? I'm actually building a tool called Perfy, on top of Benchpress which allows to keep track of previous tests campaign, which is exactly what you need. The tool lives here :https://github.com/manekinekko/perfy.

If this is something you wanna try out, I can prepare a POC for RxJS.

**Comment by blesh** [comment]
@manekinekko that sounds awesome. I'd love to see it in action. I have a feeling our benchpress tests have probably fallen into disrepair. 

Do note, though, that we have both micro perf and macro perf tests.

**Comment by manekinekko** [comment]
alright. I'll begin working on that just right after christmas 🎅

**Comment by manekinekko** [comment]
@blesh here is a quick draft... Please tell if this is what you had in mind?
![image](https://cloud.githubusercontent.com/assets/1699357/21467873/3324c2b4-c9fc-11e6-9468-542bb09d3b9a.png)

**Comment by kwonoj** [comment]
@manekinekko I'm curious if we could create github webhooks to display some critical info per each PR (let's not think about ergonomics like where to run server, etcs for now)

**Comment by manekinekko** [comment]
@kwonoj yep I think it's doable. 

Here are some facts about Perfy:
- It runs after protractor/benchpress has ended executing specs tests.
- It overrides benchpress config in order to make benchpress outputs JSON files.
- It reads those JSON files and merges them into a single JSON file which serves as a database.
- It has a CLI interface.

Here is the complete workflow:

`npm run tests --> protractor --> benchpress --> perfy --> charts`

One thing I'm missing here is how we'll be able to provide a subset of spec tests to benchpress. Typically, we will need to:
1) run only the tests that are affected by the specific PR that is being created. 
2) Or do we need to run the whole tests? 

I think 2) would be a good approach 🤔

**Comment by claudiordgz** [comment]
Is benchpress still being supported? I don't see it in the latest modules in angular, it's supposed to be @angular/benchpress, but it's missing after angular 2.4. Seems like we need to overhaul all protractor and benchpress test code too if we want to move forward with this.

**Comment by benlesh** [comment]
This is just old now.

**Comment by manekinekko** [comment]
Haha! I totally forgot about this experiment 😁
