### ISSUE TITLE
TakeUntil does not stop source stream when notifier completes

### ISSUE THREAD

**Issue by masimplo** [ReactiveX/rxjs#2304]
**RxJS version:**
v5.0.0-beta.12

**Code to reproduce:**
```
Observable.interval(1000)
  .takeUntil(notifier2)
  .subscribe((i)=>console.log('notifier 2: ' + i), null, ()=>console.log('complete'));

setTimeout(()=>{
  console.log('Notifier2 will now complete, original stream should complete')
  notifier2.complete();
}, 4100);
```
**Expected behavior:**
Console should print
"notifier 2: 0"
"notifier 2: 1"
"notifier 2: 2"
"notifier 2: 3"
"Notifier2 will now complete, original stream should complete"
"complete"

**Actual behavior:**
Console prints
"notifier 2: 0"
"notifier 2: 1"
"notifier 2: 2"
"notifier 2: 3"
"Notifier2 will now complete, original stream should complete"
"notifier 2: 4"
"notifier 2: 5"
and so on...

**Additional information:**
I think a test like the following should be passing as well:

```
  it('should take values until notifier completes', () => {
    const e1 =     hot('--a--b--c--d--e--f--g--|');
    const e1subs =     '^            !          ';
    const e2 =     hot('-------------|          ');
    const e2subs =     '^            !          ';
    const expected =   '--a--b--c--d-|          ';

    expectObservable(e1.takeUntil(e2)).toBe(expected);
    expectSubscriptions(e1.subscriptions).toBe(e1subs);
    expectSubscriptions(e2.subscriptions).toBe(e2subs);
  });
```

but it is not. TakeUntil states that the source Observable should stop if the notifier emits a complete notification

> If the notifier emits a value or **a complete notification**, the output Observable stops mirroring the source Observable and completes.

But there is no test for what happens when the notifier completes, which is what I am seeing not working in some sample code I am running trying out takeUntil.

Here is a jsbin demonstrating my case:
http://jsbin.com/lagoquz/2/edit?js,console

**Comment by Dorus** [comment]
Possibly related? #2160

**Comment by jayphelps** [comment]
Indeed this is expected behavior, at least for now. See #2160, which the outcome of was that we need to update the docs to call this out specifically and ask that the reactivex website clarify that not all Rx implementations stop taking on notifier complete (e.g. Rx.NET doesn't either). We brought this up again and decided to keep things as-is for now: [meeting notes](https://github.com/ReactiveX/rxjs-core-notes/blob/master/2016-12/december-05.md#takeuntil-does-not-stop-taking-when-notifier-completes-2160)

People can make arguments for and against either side, but the number one reason we chose to keep the existing behavior is because it's always been that way in prev RxJS versions. It certainly wasn't the _only_ reason, but it was a major factor. Hope everyone understands!

(thanks @Dorus!)
