### ISSUE TITLE
64kb Growth from RxJS 4 -> RxJS 5?

### ISSUE THREAD

**Issue by jayzawrotny** [ReactiveX/rxjs#2333]
| file         |  Version 4 | Version 5 |              
| -------- | ---------- | --------- |
| rx.min.js | 74kb        | 138kb      |

After cloning the repo and running the necessary build commands it seems that the size has increased substantially. 

This isn't so much a complaint, after all if leveraged properly it can reduce a lot of LoC through out an application. I am just curious how that came to be since so many operators got canned and many others were split into several different methods for performance purposes.

**Comment by paulpdaniels** [comment]
For an apples-to-apples comparison I think you would need to compare rx.all.min.js to the new version. If I remember correctly rx.min.js in RxJS 4 contained a "core" set of components so it isn't directly analogous to the newer version.

**Comment by kwonoj** [comment]
I haven't done direct comparison but assume even comparing with v4's .all dist will shows v5 dist size is slightly (or maybe bit more) larger than v4 does. This is due to architecture design of RxJS v5 was intended to improve performance in terms of ops in general, while applying performance optimization we had allows some trades offs related with byte size, like explicit class implementation instead of function with closures, etcs. 

It is notable core team just started discussion to find right balance between of two to improve time-to-interactive performance as well, also refer simple PR https://github.com/ReactiveX/rxjs/pull/2243 to have more aggressive optimization to reduce existing byte size as well.

**Comment by jayzawrotny** [comment]
I see, thanks for the explanations. In making functions performant and splitting some of the functions that take ambiguous arguments there may be some slightly duplicated code. 

@paulpdaniels Ack! Good catch. Below is an updated table.

| file                |  Version 4 | Version 5 |              
| ------------ | ---------- | --------- |
| rx.min.js       | 74kb         | -              |
| rx.all.min.js  | 141kb        | 138kb      |      

In which case Rx 4's rx.all.min.js is bigger than Rx 5, so that's cool!

**Comment by jayphelps** [comment]
Feel free to reopen if this wasn't answered.
