### ISSUE TITLE
Possible bug using observeOn to trap unhandled errors in multicast observables

### ISSUE THREAD

**Issue by NMinhNguyen** [ReactiveX/rxjs#2345]
**RxJS version:** 5.1.0

**Code to reproduce:**
```javascript
const source$ = Rx.Observable.interval(1000)
  .share()
  .observeOn(Rx.Scheduler.asap); // magic here
const mapped$ = source$.map(x => {
  if (x === 1) {
    throw new Error('oops');
  }
  return x;
});
source$.subscribe(x => console.log('A', x));
mapped$.subscribe(x => console.log('B', x));
source$.subscribe(x => console.log('C', x));
```

**Expected behavior:**
According to @blesh's [On The Subject Of Subjects article](https://medium.com/@benlesh/on-the-subject-of-subjects-in-rxjs-2b08b7198b93), the output should be:

```javascript
// "A" 0
// "B" 0
// "C" 0
// "A" 1
// Uncaught Error: "oops"
// "C" 1
// "A" 2
// "C" 2 
// "A" 3
// "C" 3
// ... etc
```

Notice how `"C" 1` appears after `// Uncaught Error: "oops"`

**Actual behavior:**
```javascript
// "A" 0
// "B" 0
// "C" 0
// "A" 1
// Uncaught Error: "oops"
// "A" 2
// "C" 2 
// "A" 3
// "C" 3
// ... etc
```
where the `C` observer is able to carry on the next time a value is emitted (`2`), but misses out on the `1`

**Additional information:**
JS Bin: https://jsbin.com/ruxeporisa/edit?js,console

I realise that a 
> a Subject [is being used] to loop over a list of observers and notify them

However, the article does seem to imply that the `C` observer should receive that `1`. I am not 100% sure whether this is an issue, or it's "working as intended".

Interestingly, in RxJS 4.1.0 ([JS Bin](https://jsbin.com/qineraleta/edit?js,console)), the output is as described in the article, and `C` does receive a `1`.

**Comment by trxcllnt** [comment]
@NMinhNguyen intuition tells me this is an artifact of the asap and animationFrame scheduler implementations, rather than a bug in observeOn. Each of these schedulers maintain a queue of all the actions scheduled before the next tick/animation frame callback are invoked. When the next tick does happen, they drain the queue, but [will stop draining](https://github.com/ReactiveX/rxjs/blob/master/src/scheduler/AsapScheduler.ts#L18) if an error is encountered.

In your case, the `share` is synchronously notifying three distinct `observeOn` operators, each of which schedules an action with the asap scheduler. Since they all schedule their actions before the next tick, the actions are bucketed to run together. When the queue is flushed, and the `mapped$` observable throws, the action scheduled to notify `"C"` is not run.

I remember not having many strong arguments for or against this scheduler behavior, and decided to keep it consistent with the Queue scheduler unless we found a reason to break with tradition.

The more I think about it, not interrupting the queue when an error happens would be consistent with the native setImmediate/requestAnimationFrame behavior, although it would make throwing errors harder. Alternatively, we could do away with queueing altogether and call setImmediate/rAF for each scheduled action, like we already do in the AsyncScheduler.

**Comment by benlesh** [comment]
This is no longer an issue in RxJS 6, as unhandled errors are thrown on a different stack.

Closing this issue.
