### ISSUE TITLE
Schedulers - is their behaviour arbitrary per operator? Is it possible to use them meaningfully without knowing operator implementation details?

### ISSUE THREAD

**Issue by Podlas29** [ReactiveX/rxjs#2350]
Hi.

So currently I am learning about schedulers and writing some docs for operators at the same time.

All this time I was convinced that scheduler behaviour is very predictable in every operator and it is just me (and maybe lack of good tutorials/docs) that does not know these rules.

And although it is true on very high level / from general perspective, the more I read source code and go into details, the more I am convinced that only good way to describe what scheduler does in general is "It schedules... Something. Sometimes. You want to know what exactly? Read our extremally long operator doc entry with all gory details, edge cases etc. Or just read source."

I'll give two examples of what I mean:

**scheduling async subscriptions to Observables in combineLatest and merge static functions**

Both `combineLatest` and `merge` accept collection of observables and subscribe to them one by one. Both accept optional schedulers. When using async scheduler, in one operator every subscription to input Observable happens in separate "task" in event loop, while second operator will ignore scheduler and simply iterate over Observables synchronously and subscribe to each in that loop.

Can you guess which one is which? How about without looking into code?

**queueScheduler in of and combineLatest**

```ts
Observable.combineLatest(
   Observable.of(1, 2, 3, schedulerA),
   Observable.of(4, 5, 6, schedulerA),
   null,
   schedulerB
)
```
You have four combinations of queue Scheduler and immediate Scheduler (think - no scheduler at all):

schedulerA - queue, schedulerB - immediate
schedulerA - immediate, schedulerB - queue
schedulerA - queue, schedulerB - queue
schedulerA - immediate, schedulerB - immediate

What will be the outcome of that obervable in all this combinations? Why?

**My questions**

* Can you - after gaining some proficiency in Rx - use schedulers reliably without looking too much into actual implementations of operators?
* Can you combine/stack different schedulers in different operators to have very fine-grained control when things will happen in your app? Or are schedulers usable and predictable only in simplest scenarios and you should stick only to those, when coding?
* When you implement new operator, are there clear rules what should be scheduled and how?
* Is it even possible to write operator that works predictably with every possible scheduler?
* Can you schedule in operator differently, depending on which scheduler you were passed, so that behaviour of every scheduler in operator is always reasonable? (for example when you have queue, schedule something one way, but when you have async, schedule something differently)
* Why in many operators it is subscription moment to input observable that is scheduled and not the moment when observable actually "nexts" value? I was always under the impression that it will be only value emiting, completion and errors that are scheduled. Again, there are no clear rules what will be scheduled in operator.

Thanks in advance and have a great day!

**Comment by blesh** [comment]
> * Can you - after gaining some proficiency in Rx - use schedulers reliably without looking too much into actual implementations of operators?

Yes. For the most part, any operator that schedules due to requiring some time-based delay will use the AsyncScheduler, any other operator will default to no scheduling at all (calling recursively) unless otherwise instructed by a passed scheduler (if possible)

> * Can you combine/stack different schedulers in different operators to have very fine-grained control when things will happen in your app? Or are schedulers usable and predictable only in simplest scenarios and you should stick only to those, when coding?

Yes. Although heavy scheduler use is pretty rare. A more common case might be forcing everything to use the same scheduler for virtualized results.

> * When you implement new operator, are there clear rules what should be scheduled and how?

If it involves delay, default to AsyncScheduler. Otherwise no scheduler

> * Is it even possible to write operator that works predictably with every possible scheduler?

Most operators don't touch schedulers at all. But the predictability is all in the scheduler. For example, the QueueScheduler is much more predictable than the AnimationFrameScheduler

> * Can you schedule in operator differently, depending on which scheduler you were passed, so that behaviour of every scheduler in operator is always reasonable? (for example when you have queue, schedule something one way, but when you have async, schedule something differently)

The scheduler controls the scheduling. Not the operator.

> * Why in many operators it is subscription moment to input observable that is scheduled and not the moment when observable actually "nexts" value? I was always under the impression that it will be only value emiting, completion and errors that are scheduled. Again, there are no clear rules what will be scheduled in operator.

In most operators that have scheduling, it's an operator that is subscribing to some child observable (or "inner observable"). In that case, it's *when* it gets subscribed to that matters more than when it nexts. It's easy enough to control the nexting with `observeOn`. Arguably, you can control when it's subscribed to with `subscribeOn` too.

I hope that answers your questions, they're great questions, @Podlas29.. I'm going to close this one for now.

**Comment by Podlas29** [comment]
@blesh Thanks for the response.

I feel like I have thrown too much problems at once, so to scale back a little bit:

Going back to the fact that `combineLast` and `merge` schedule their subscriptions differently. One always iterates synchronously, second one uses scheduler to schedule every subscription. It means you have to look into code to find out what effects scheduler will have on that operator, am I right or am I missing something?

**Comment by trxcllnt** [comment]
@podlas29 you're not wrong. combineLatest and zip (and operator version of forkJoin, when we get it) have to wait for the source Observable to complete before they subscribe to the inner sources, because they can't do any work until they know all the sources they should subscribe to.

Once it has though, it's debatable whether they should subscribe using the supplied scheduler. I think they don't because they didn't in <= RxJS v4 (or that's how I remember it, but could be wrong).
