### ISSUE TITLE
AnimationFrameScheduler - shouldn't it requestAnimationFrame also when scheduled with delay?

### ISSUE THREAD

**Issue by mpodlasin** [ReactiveX/rxjs#2379]
Hi.

Currently when scheduled with delay, `AnimationFrameScheduler` delegates work to `AsyncScheduler`. So for example if I use it with `Observable.interval`, `window.requestAnimationFrame` will not be used to schedule interval ticks.

But what if I want to make an animation where - for example - every second div changes position randomly? Wouldn't then using  `window.requestAnimationFrame` for delayed tasks make that animation more smooth? 

Shouldn't `AnimationFrameScheduler` delay given task asynchronously but then - when it is time to do that task - delay it a little bit more with  `window.requestAnimationFrame`?

Answers, links to answers and links to links to answers are all welcome.

Thanks in advance and have a great day.

**Comment by trxcllnt** [comment]
@Podlas29 great questions! Let me start by saying the Schedulers are by no means sacred. Many decisions were made early on either because that's how they worked in <= v4, or to minimize surprises. The answer to your question is a mix of the two, and applies equally to the ASAP scheduler. As a side note, if you use `Observable.interval(0, Scheduler.animationFrame)`, the interval _will_ be scheduled via rAF, so you can build smooth animations.

Whenever possible, Schedulers should delegate as much of the timing control to the platform, as the platform will take into account variables the Schedulers can't know. This is why we've opted to use `setInterval` instead of `setTimeout`, even in the case the interval is canceled after the first execution. Assuming operators clean up after themselves, this leads to more consistent timer synchronization than we could get from concurrent pending setTimeouts.

With respect to the principle of least surprise, unlike setTimeout/setInterval, neither setImmediate nor requestAnimationFrame accept a due-time parameter. We relied on this omission as guidance, and opted not to implement custom timing logic on top of these methods, which would effectively redefine the behavior of these methods for Rx users. Implementing due times with serially scheduled next ticks/animation frames would necessitate scheduling as many ticks as necessary until the due time, which isn't 

I do see a potential alternative to what we have today, where scheduling on the asap/animationFrame scheduler with a due time > 0 would schedule a timeout for the due time, and follow-up with a setImmediate/rAF when the timeout resolves.

**Comment by trxcllnt** [comment]
Also forgot to mention: setImmediate executes in at the end of the current event loop, so scheduling nextTicks until the due time would synchronously block the event loop until the due time. At one point this was also how the <= v4 `currentThread` scheduler behaved, and led to much wailing and gnashing of teeth until it was changed ;-j

**Comment by blesh** [comment]
I think the question @Podlas29 might be asking is "why doesn't it use an animation frame after the scheduled time?" ... so like: `setTimeout(() => requestAnimationFrame(doAThing), 3000)`

**Comment by trxcllnt** [comment]
@blesh b/c the platform method isn't spec'd with respect to time, it's always been implemented this way. not arguments against doing that, as I said at the end, just that it hasn't been proven in prod.

**Comment by Podlas29** [comment]
@trxcllnt thank you for detailed response. 

I will play around some more when I have the time and try to find out if there will be noticable differences in how animations run with regular and customized  `animationFrame` scheduler.
