### ISSUE TITLE
Observer.create, Observable.from and so on not working with Typescript

### ISSUE THREAD

**Issue by Deviad** [ReactiveX/rxjs#2429]
I am a novice in RxJS, but I think this might be a consequence of https://github.com/ReactiveX/rxjs/issues/2369

Anyways, your help is appreciated, even because I do not know where to look for updated docs or info on this matter.

**RxJS version:** 5

**Code to reproduce: https://github.com/Deviad/fbmetascraperandcrudapits

**Expected behavior:** I should be able to use static methods like from, create using Typescript as in plain vanilla JS. 

**Actual behavior:** I cannot use functions like Observer.create (have to use Subscriber.create instead), Observable.from() and others.

**Additional information:**

**Comment by kwonoj** [comment]
`Observer` is not a implementation but only interface, even TypeScript user cannot use `Observer.Create()` since there isn't those creation method. Basically usecases between TS user and JS user is not different, the only difference is TS user has some more tooling support like intellisense. Codewise both should be identical. 

For creation method, `Observable<T>` has static creation method `Observable.create` (http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-create), and as commented `Observable.from` (http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-from) and other variant of creation methods provides way to create other than raw creation method. Though it is not complete, you can refer documentation at http://reactivex.io/rxjs/, and test case serves references usecases as well (https://github.com/ReactiveX/rxjs/tree/master/spec), and if you're familiar with v4 interfaces, migration guide provides difference between breaking version update. (https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md).

**Comment by Deviad** [comment]
@kwonoj 
I did not quite understand this part:

> Basically usecases between TS user and JS user is not different, the only difference is TS user has some more tooling support like intellisense. Codewise both should be identical.

In fact, in my experience, since JS does not have any kind of control on types, with JS you can still use Observer.create() hence generating confusion. Somehow the developers should forbid the use of Observer.create() or throw a warning via console.log()  that the use of Observer.create() has been deprecated in favor of Subscriber.create() as specified in the reference manual for migration that you kindly attached.

Thank you for your answer.

Cheers,
Davide

**Comment by kwonoj** [comment]
While I don't get the idea of `on vanilla JS Observer.create() still works without any problem.` means whole since v5 doesn't have any implementation for this, I believe question itself has been answered to point out starting point. Still documentation issue is being opened and will be tracked to remove further confusions between different versions with breaking changes.
