### ISSUE TITLE
Ship a System bundle, for single-request SystemJS/Plunkr consumption

### ISSUE THREAD

**Issue by kylecordes** [ReactiveX/rxjs#2458]
Some months ago, RxJS used to ship a System bundle, which could be conveniently consumed as a single HTTP request using SystemJS, and a clunker or other scenario where browser-based tooling is desirable but many small HTTP requests are not.

(This most often comes up in the context of Angular, which itself is shipped in the form of one bundle (actually several forms of bundle) for each major part of Angular. So for example it is currently usually possible to get all the parts of Angular one needs in a half dozen HTTP requests, but then require dozens more to obtain some of RxJS.)

The old SystemJS bundle went away, discussion in #1776.

I had suggested linking to an external SystemJS build in #2381, an idea rightfully panned all around. But several project members indicated openness to bring it back.

There is a related item #2335 about including a ES2015-in-ES2015 build. Although these two formats are completely different, the idea of providing several additional formats beyond CommonJS perhaps should be planned jointly?

There is a mostly orthogonal question about *what* package could contain these multiple formats. One idea was to retain `rxjs` as a legacy-ish CommonJS-only package, and have the newer `@reactivex/rxjs` package include all of the desirable bundle and module formats.

**Comment by kwonoj** [comment]
As I'm not SystemJS user, would like to add few high-level questions for quick elaboration.

1. Does SystemJS user blocked to use RxJS by not having its own package?
2. If not, what strong benefit by having separate systemjs package? Issue describes it as 'one http request' - is my understanding correct systemjs user does not installs package / bundle but just request to npm package when browser is loaded? if not, how does those http request helps loading module via systemjs?
2.1 Especially issue describes `for single-request SystemJS/Plunkr consumption` - is this case limited to plunkr usecase only?
3. In case of other packages doesn't provide systemjs build, how does this being resolved?

**Comment by kylecordes** [comment]
1. No one is blocked, but they do need to wait for extra HTTP requests.

2. Yes, that is correct! The target user (every user of every Plunkr Angular example) is most often loading the code from unpkg, the NPM CDN, or similar source. (There are a few narrower target users, myself included, who need a System bundle locally, and are building it locally.)

3. Not limited to Plunkr only, applies to all of the other similar tools. Also applies to most any other case where someone is running Angular code via SystemJS in the browser.

4. RxJS is unusual in how much and why this matters!

Consider [ngrx/store](https://github.com/ngrx/store), a popular add-on library use with Angular. Store used to have the same difficulty, Store was published only in the form of various individual files. But it now [uses Rollup to provide](https://github.com/ngrx/store/blob/master/rollup.config.js) a UMD build.

RxJS already provide something similar to that, available here:

https://unpkg.com/rxjs@5.2.0/bundles/Rx.js

However, this module format is **not** suitable to consume via Angular and SystemJS, because Angular code is full of references to deeper modules of RxJS, something like:

```
import 'rxjs/add/observable/of';
```

...and so on. These deep references do not work with UMD, but they do work with a System bundle. This is why RxJS is unusual - it is intended for consumption in this fine-grained deep way, it does not have its public API elevated to a flat top level façade. Putting all these ideas together, because of the shape of the RxJS API, a System bundle is the only format that makes it possible to load as a single file in this common scenario. So instead, currently is consumed as many separate requests.

It's possible that I simply care more than anyone else about the numerous extra HTTP requests and slower loading of example programs and Plunkrs that use RxJS via Angular.

**Comment by kwonoj** [comment]
So, if I understood correctly this also can be solved in other direction to let UMD bundle provides export paths as same as ngrx/store does, since Rx already uses rollup for umd build (https://github.com/ReactiveX/rxjs/blob/master/tools/make-umd-bundle.js#L12) not only solves systemjs issue but also resolves UMD users issue like https://github.com/ReactiveX/rxjs/issues/2185 ? 

Is there reason to not go in those paths but need to publish separate build? Some limitation with Rx's build pipeline?

**Comment by kylecordes** [comment]
@kwonoj As far as I know, the UMD format does not support deep export paths. The various libraries package that ship effectively as UMD have a flat "façade" in which all of the functionality anyone imports is only one layer deep. For example, Angular itself earlier in development had various functionality exposed via deeper imports, but then later changed to a façade approach. Among other things this yielded compatibility with UMD.

Yes, this is the problem the user is having in #2185.

**Comment by martinsik** [comment]
I think there's one more reason to use SystemJS bundle. Since SystemJS `0.20.*` they [removed the wildcard `*` option in `paths` options](https://github.com/systemjs/systemjs/issues/1039).

Right now the Angular2 is still using the older SystemJS `0.19.*` where you can use the following to redirect all import to `rxjs/*` to a single bundle:

```
paths: {
  'rxjs*': 'node_modules/rxjs/bundles/Rx.min.js'
}
```

You can see that this works and loads just a single `Rx.min.js` file in this updated plnkr with the default Angular2 demo app (see `systemjs.config.js` file): https://plnkr.co/edit/tzLQmZ17ZMJHyBVrmzN9?p=preview

However this is not possible since SystemJS `0.20.*` systemjs/systemjs#1039 but I think this could be solvable if RxJS was bundled as a SystemJS bundle and then imported with [`bundle` config option](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#bundles). Then I could include it a via `<script>` tag or by predefining that for example `rxjs/Observable` and `rxjs/Subject` are both it the same bundle.

I read the problem in #2185 but to be honest I don't understand what's the issue there and maybe it's something different to my example above.

**Comment by kylecordes** [comment]
@martinsik Very interesting, I hadn't seen or used this capability of System 0.19. I've been using "bundles", with a (local) System bundle build of RxJS, something like this:

```
  bundles: {
    "libs:rxjs.system.js": [
      "rxjs",
      "rxjs/*",
      "rxjs/operator/*",
      "rxjs/observable/*",
      "rxjs/scheduler/*",
      "rxjs/symbol/*",
      "rxjs/add/operator/*",
      "rxjs/add/observable/*",
      "rxjs/util/*"
    ]
  },
```

... which should also work with .20.

**Comment by martinsik** [comment]
@kylecordes This is exactly what I thought.

I just found out that when using bundles in SystemJS you're not limited to only `system` format and it works with `amd` modules as well (although it's not very obvious from the documentation).  
The AMD bundle can be easily generated by just `tsc` so no SystemJS Builder is needed.

```
$ ln -s src rxjs
$ node node_modules/.bin/tsc -t ES5 -m amd --outFile rxjs.amd.js --rootDir . --lib es5,es2015.iterable,es2015.collection,es2015.promise,dom rxjs/Rx.ts
```

I had to make a symlink to `rxjs` directory and set `--rootDir .` that will generate all modules prefixed with `rxjs`.

I tested this with the Angular2 demo on plnkr and it works: https://plnkr.co/edit/JChO8ugk6vXh1EHlaM0y?p=preview

```
map: {
  'rxjs-bundle': 'rxjs.amd.js',
},
bundles: {
  'rxjs-bundle': [
    'rxjs/*',
    'rxjs/symbol/*',
    'rxjs/add/operator/*',
    'rxjs/add/observable/*'
  ]
},
```

So maybe this is even easier way of using the RxJS as a bundle in both 0.19 and 0.20 versions.

**Comment by kylecordes** [comment]
@martinsik Yes, that is right, AMD bundles are also easy to generate with just `tsc`. Incidentally, `tsc` can produce System bundles in the same way. I don't recall why I found using system-builder worked better for my use case.

Either way though (one-line `tsc` command, 10-line system-builder config), the main idea here is the benefit of RxJS shipping with one of these SystemJS-compatible formats that support deep import "in the box".

**Comment by jayoungers** [comment]
I just stumbled on this after re-visiting our situation:  since our group is all new to RxJs, it's way simpler just to import 'RxJs/Rx' and view everything, opposed to trial and error trying to figure out what operators we need.

Locally we're using SystemJS as the module loader, and as a part of the build we're generating a SystemJS bundle and referencing it via the bundles config (like in @kylecordes example).  However, just generating that bundle can take 20-30 seconds.

I was looking into options to get around that 20-30 second build, but I don't think any of them are going to be really great.  Ideally the RxJs package would come with a bundle like this ready to go

**Comment by kwonoj** [comment]
I'm going to close this, I know there are some demands around this but given complex sets of our build pipeline extending it isn't trivial at this moment. I'm trying to tackle to simplify those things a bit, to see if it allows some extendability in further but can't guarantee things at this moment.
