### ISSUE TITLE
Add Single, Maybe and Completable

### ISSUE THREAD

**Issue by passsy** [ReactiveX/rxjs#2469]
RxJava 2 has the concept of [`Single`](http://reactivex.io/documentation/single.html), [`Maybe`](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#maybe) and [`Completable`](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#completable). They got quickly adopted by [RxSwift 3.3.0](https://github.com/ReactiveX/RxSwift/releases/tag/3.3.0).

I couldn't find anything about those reactive types in rxjs. Are they planned?

**Comment by kwonoj** [comment]
No, it's not planned. It is not a goal of v5 to create full-compliant operator set to other languge bindings or even v4, and there are some added opeator or dropped operator between. Once there is suffecient usecase and demand it can be obviously discussed in further.

**Comment by aluanhaddad** [comment]
I'm also not sure I would look to RxJava for inspiration. Java is severely lacking in expressive power, even with its recent editions. JavaScript has long had better expressiveness as have most other languages.

**Comment by kwonoj** [comment]
I'm closing this issue for now, haven't got subsequent details of operator to initiate discussion to be included in core sets. If this operator seems need to be included in core operator sets, please refer https://github.com/ReactiveX/rxjs/issues/2299 and https://github.com/ReactiveX/rxjs/pull/2524 as starting baseline to include details for discussions.

**Comment by passsy** [comment]
Just want to make sure this issue didn't got closed accidentally. It's not about new operators. It's about other base classes besides `Observable`

-`Observable`: 0..N flows, no backpressure
- `Single`: a flow of exactly 1 item or an error
- `Completable`: a flow without items but only a completion or error signal
- `Maybe`: a flow with no items, exactly one item or an error

**Comment by kwonoj** [comment]
@passsy yes, while attached references are saying only about `operators`, you can consider same for any other cases like this one, or either removing, changing existing operator behavior as well. There is no big differences of having new operator, or either new base class in perspective of discussing it to add into core set.

**Comment by whymarrh** [comment]
If y'all are open to a bit of discussion on the topic, I do think there are use cases for a type analogous to RxJava's [`Completable`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Completable.html):

> Represents a deferred computation without any value but only indication for completion or exception.

That said, the workaround isn't too bad right now, one can (assuming the stream is hot) filter all of the values (e.g. `.filter(() => true)`).

### Example use case

In a [redux-observable](https://redux-observable.js.org/) epic, if you want to dispatch an event after some chain of other actions.

A bit of setup using [the example they have on their website](https://redux-observable.js.org/docs/basics/Epics.html):

```js
const PING = 'PING';
const PONG = 'PONG';

const ping = () => ({ type: PING });

const pingEpic = action$ =>
  action$.ofType(PING)
    .delay(1000)
    .mapTo({ type: 'PONG' });

const pingReducer = (state = { isPinging: false }, action) => {
  switch (action.type) {
    case 'PING':
      return { isPinging: true };

    case 'PONG':
      return { isPinging: false };

    default:
      return state;
  }
};
```

Now if you wanted to dispatch an action after `count` number of `PONG` actions have occurred:

```js
const START_ROUND_TRIPS = 'START_ROUND_TRIPS';
const END_ROUND_TRIPS = 'END_ROUND_TRIPS';

const endRoundTrip = (count) => ({type: END_ROUND_TRIPS, payload: {count}})

const roundTripEpic = action$ =>
  action$.ofType(START_ROUND_TRIPS)
    .concatMap((action) => Observable.concat(
      Completable.from(action$.ofType(PONG).take(action.payload.count)), // Up for discussion
      Observable.of(endRoundTrip(action.payload.count))
    ))
```

It's important that the inner observable not actually contain the `actions$.ofType(PONG)` values because that would re-dispatch those actions. It's arguable whether this is preferable over `.filter(() => true)` (I think it's a touch more readable) but I do think is a use case.

**Comment by trxcllnt** [comment]
@passsy @whymarrh isn't this already possible w/ the `single()`, `defaultIfEmpty()` and `ignoreElements()` operators?

**Comment by whymarrh** [comment]
(I had forgotten about `ignoreElements()`, that works better than the `.filter(() => true)`, thanks!)

> [I]sn't this already possible w/ the `single()`, `defaultIfEmpty()` and `ignoreElements()` operators?

Some combination of those work as a replacement for a hypothetical `Completable`, yup.

**Comment by WowMuchName** [comment]
From a pure technical point of view one might argue that a completeable is unnecessary since an observable can be used for the job.
However when designing an api it is useful to know whether 0, 1 or N objects can be emitted by a stream. While this should be documented in the jsdoc or javadoc, knowing that by looking at the class of stream makes it a lot easier. It is also useful if those classes enforce those cardinality-constraints so you don't accidentally break your api-contract.
As the rx guy in our team I would also like to point out that there is a barrier of entry you tend to forget about when having worked with rx for some time. Having classes that are called completable, single and maybe - even if they are all essentially observables under the hood - is much easier for rx beginners to understand and work with.

**Comment by darkyelox** [comment]
You can simple create the objects in next releases, is useful to have them for some cases and also makes the code more readable (knowing for what a Completeable, Single and a Maybe are for)

**Comment by ptitjes** [comment]
@trxcllnt Just wanted to point out something. Yes, all of this is possible with combinations of `single()`, `defaultIfEmpty()` and `ignoreElements()`. But I guess having types like `Single`, `Maybe` and `Completable` isn't about runtime expressiveness. It is about what they convey in the type system: why have only `void` when you can also have `null`, `undefined`, `never`, etc. Whether they should be expressed as classes or type alias is another problem (I'd bet on type alias however).

**Comment by sawthompson** [comment]
Would it be possible to revisit this? I think @WowMuchName makes some compelling points. Personally I have found that using Observables as Singles, while technically possible, creates ambiguity and leads to bugs.

**Comment by jaumard** [comment]
+1 on this, Single/Maybe and Completable make it more understandable and maintainable by explicitly saying what behavior you'll have. Having just Observable is for me as bad as saying Any on return type of a method, you don't know what you'll have except if you actually look the implementation...
