### ISSUE TITLE
TestScheduler seems to use bogus values for `frameTimeFactor`

### ISSUE THREAD

**Issue by memelet** [ReactiveX/rxjs#2475]
**RxJS version:**
5.2.0

The value `frameTimeFactor` seems to be a static on VirtualTimeScheduler and used in some places in TestScheduler.

In some places its  used as a static, TestScheduler.ts:35
```
    return indexOf * TestScheduler.frameTimeFactor;
```

But in others its used on `this` when there is no `this:

TestScheduler.ts:149
```
      const frame = i * this.frameTimeFactor;
```

TestScheduler.ts:199
```
    const frameOffset = subIndex === -1 ? 0 : (subIndex * -this.frameTimeFactor);
```

TestScheduler.ts:212
```
      const frame = i * this.frameTimeFactor + frameOffset;
```

Changing `this.frameTimeFactor` to `TestScheduler.frameTimeFactor` seems to fully allow for adjusting the resolution of time intervals. I believe there is a issue to that as part of testing improvements, but this is an easy fix standalone.

**Comment by CrazyBS** [comment]
I agree with this request.   In order to fully control the time factors and max frames, I need to either ensure all time is overridable to 10ms increments or extend VirtualTimeScheduler myself and not use TestScheduler for testing.   I have retry logic that waits several seconds that I'd like to test without injecting new delays into the source code.

**Comment by jayphelps** [comment]
`this.frameTimeFactor` is the same as `TestScheduler.frameTimeFactor`

```ts
class TestScheduler {
    static frameTimeFactor = 1;
    static kickDog() {
        return this.frameTimeFactor;
    }
}

// compiles to

var TestScheduler = (function () {
    function TestScheduler() {
    }
    TestScheduler.kickDog = function () {
        return this.frameTimeFactor;
    };
    return TestScheduler;
}());
TestScheduler.frameTimeFactor = 1;
```

In TS and JS, classes are objects themselves (not just the instances of those classes) so using when calling a function, `this` will refer to the object in which the function was called on.

`TestScheduler.kickDog()` is the same as `TestScheduler.kickDog.call(TestScheduler)`, so `TestScheduler` is the context, used as `this`.

***

Are you actually seeing cases where `this.frameTimeFactor` is erroring out with `Cannot read property 'frameTimeFactor' of undefined`?

**Comment by jayphelps** [comment]
You might also like https://www.npmjs.com/package/@kwonoj/rxjs-testscheduler-compat which was made by one of the core team members to experiment with bringing a similar api as v4 back to v5

**Comment by patrickkunka** [comment]
Regarding @CrazyBS comment about fully controlling `frameTimeFactor`, I'd also like to be able do this.

Say I have a stream with `.throttleTime()` applied, which throttles a provided input stream so that it emits only every 20 seconds (the 20s duration is arbitrary, and is provided externally).

I'd like to test it with a marble diagram like the following, where each dash represents 5000ms instead of 10ms:

`INPUT:  -a-b-c-d-`
`OUTPUT: -a---c----`

I feel like this would be possible if I could override `frameTimeFactor` to equal `5000`, on a TestSchedular instance basis, but because it is static I can not.

Does this make sense as a feature request, or am I missing an easier way to do this?

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/issues/3231 and https://github.com/ReactiveX/rxjs/pull/3314 tracking this.

**Comment by patrickkunka** [comment]
@kwonoj fantastic, thanks!

**Comment by benlesh** [comment]
This is resolved with `TestScheduler` "run mode". https://rxjs.dev/guide/testing/marble-testing
