### ISSUE TITLE
Observers are cloned without state

### ISSUE THREAD

**Issue by robey** [ReactiveX/rxjs#2525]
It looks like observers are shallow-cloned using `Object.create()` when passed to `subscribe()`. As a result, any state changes occur in the clone, not the original object. An observer may be processing a stream to maintain an internal state for its side effects (like a ring buffer, or an entropy pool).

For anyone reading this bug with the same issue, you can work around it by creating a new anonymous object with no state, and arrow functions that refer to the original object. Hand out the fake observer instead of implementing Observer yourself -- like this:

```typescript
    this.observer = {
      next: (snapshot: Snapshot) => this.next(snapshot),
      error: (error: Error) => this.error(error),
      complete: () => this.complete()
    };
```

**RxJS version:** 5.3.0

**Code to reproduce:**

```typescript
import { Observable, Observer } from "rxjs";

class RingBufferObserver<T> implements Observer<T> {
  ring: T[];
  index: number;
  size: number;

  constructor(size: number) {
    this.index = 0;
    this.size = size;
  }

  next(item: T) {
    if (this.ring === undefined) {
      // this happens on a clone, not the actual object:
      this.ring = new Array<T>(this.size);
    }
    this.ring[this.index] = item;
    this.index = (this.index + 1) % this.ring.length;
  }

  error(error: Error) {
    // pass
  }

  complete() {
    // pass
  }
}

const rb = new RingBufferObserver<number>(3);
const source = Observable.of(1, 2, 3, 4);
source.map(n => n * 10).subscribe(rb);

// this should be [ 40, 20, 30 ], but it's undefined.
console.log(rb.ring);
```

**Expected behavior:** The object passed to `subscribe` is preserved.

**Actual behavior:** The object is cloned shallowly.

**Additional information:** The bug appears to be here: https://github.com/ReactiveX/rxjs/blob/master/src/Subscriber.ts#L186

**Comment by kwonoj** [comment]
This seems legit to me, but maybe I'm missing some point of observer contract. @trxcllnt , what was main reason we were doing this in safesubscriber and can we just pass reference of observer?

**Comment by trxcllnt** [comment]
@robey as an interim solution, you should be able to extend `Subscriber` instead of implementing `Observer`.

The internal SafeSubscriber is created to wrap "anonymous" Observers, or any Observer that doesn't extend Rx.Subscriber. It's not my favorite, but it allows us to invoke next/error/complete on these anonymous Observers [in the context of an instance that has an `unsubscribe` method](https://github.com/ReactiveX/rxjs/blob/master/spec/Observable-spec.ts#L398). We use `Object.create()` here so we don't add the `unsubscribe` method to the external Observer instance, which was causing problems elsewhere.

It also ensures the source subscription is [torn down if an error is thrown while synchronously emitting values](https://github.com/ReactiveX/rxjs/blob/master/spec/Observable-spec.ts#L111), which would normally unwind the stack all the way back to the source's `observer.next()` call, stopping the `subscribe` callback from returning the `teardown` value.

To be honest, I'm not sure how important it is to have access to the `unsubscribe` method in next/error/complete. From what I recall, we did it as an alternative to implementing a `start(subscription)` method on the Observers, essentially so an anonymous Observer can unsubscribe from a synchronously emitting source.

**Comment by kwonoj** [comment]
Maybe we could say `recommend to extend subscriber if you'd like to have maintain observer's state`, which'll be probably breaking difference between v4. I do not mind personally to extend subscriber as necessary though, it may be confusing someone who thought implemention `Observer<T>` would be sufficient contract. /cc @benlesh as well for visibility.

**Comment by benlesh** [comment]
Closing as stale
