### ISSUE TITLE
startWith() type definitions don't allow mixing types

### ISSUE THREAD

**Issue by martinsik** [ReactiveX/rxjs#2544]
**RxJS version:** 5.3.0

**Code to reproduce:**

```
Observable.of(42)
    .startWith('a', 'b')
    .subscribe(console.log);
```

**Expected behavior:**

It should compile without errors.

**Actual behavior:**

Throws the following error when compiling with `tsc 2.2.1`:

    error TS2345: Argument of type '"a"' is not assignable to parameter of type 'number | IScheduler'.

**Additional information:**

The current type definitions for the `startWith()` operator expect that I'll always start with values of the same type as the source Observable. For example the following is correct:
```
Observable.of(42)
    .startWith(1, 2)
    .subscribe(console.log);
```

But if I want to use for example `startWith('a', 'b')` I have to force generics such as `<number | string>`:
```
Observable.of(42)
    .startWith<number | string>('a', 'b')
    .subscribe(console.log);
```
This works but I think it could be avoided if the `startWith()` operator was declared with two types already. For example like this:

    export function startWith<T, R>(this: Observable<T>, v1: R, v2: R, scheduler?: IScheduler): Observable<T | R>;

**Comment by kwonoj** [comment]
While I totally agree this is somewhat painful issue, I don't think proposed solution is way to go.

Main reason for this is `startWith` has highly polymorphic parameter configuration, so there are huge variant forms of param, for example

```js
Observable.of(1).startWith(2); //currently only supported type signature
Observable.of(1).startWith(2, 'a');
Observable.of(1).startWith('a', {custom: string})
Observable.of(1).startWith('a', {custom: string}, 3, {otherType:number} ...)
``` 
is allowed invocation as well, each param can have different types of values. Means, with your proposal it can resolve your specific cases but doesn't provide correct type for legit behavior of operator. I don't think current compiler can support these kind of definitions without having huge variant of overload signatures. hesitate to have specific overload cases.

I'll leave this opened bit to get second opinion from @david-driscoll .

**Comment by david-driscoll** [comment]
So what is the problem you're trying to solve by starting with something that is a different type than you will expect later down the line?

I ask, because while it's totally possible to do, my problem is I can't wrap my head around _why_ you would really want that.  I suppose if you want some sort of indication that this is the first event, but in reality you could do that just before you subscribe anyway.

I'm all for ensuring that the typings are as broad as possible, so that we can capture all the possible different solutions.  There are some scenarios however I feel like an error is more important for a developer to see, instead of just passively allowing them to propagate.

We just had a similar case in regards to `do`.  Even though `do()` is a perfectly valid call, since it doesn't subscribe, it essentially is a noop.  In most cases you almost certainly didn't mean to call it with no arguments.   So `do` enforces a `next` method or `observer` to be passed in.  subscribe on the other hand does allow no arguments, because that call makes sense.

Take this arbitrary case for example.

```typescript
type Request<T> = { id: number; data: T };
type Container<T> = { request: Request<T>; };
let a: Request<number>;
let b: Container<number>;
let o: Observable<Request<number>>;
let o2 = o.startWith(a);
let o3 = o2.startWith(b);
// more than likely they meant to...
// let o3 = o2.startWith(b.request);
```

Given these changes `o3` would be a valid type, where the union would essentially be empty (for intellisense).  I think it would more confusing to the developer when they notice that real type of `o3` is `Observable<Request<number> | Container<number>>` minutes if not hours later.

It would be much easier if we simply error out and let the developer know that they passed in the wrong type, which may have not meant to add in.  If they intend the type to be different, then they can simply ensure that the inbound type is the union they are expecting. It's a fine line, and I think we have to be thoughtful to ensure that we don't cause more confusion by accident.

**Comment by martinsik** [comment]
@kwonoj I think you're right. It didn't occur to me there might be other combinations as well. So I guess in this situation the easiest way is to force set my own generics directly to the operator.
