### ISSUE TITLE
zip operator never complete observable

### ISSUE THREAD

**Issue by Jerry-Hong** [ReactiveX/rxjs#2558]
Dear 
zip operator looks like never complete 

**RxJS version: 5.3.0**

**Code to reproduce:**
```javascript
const interval = Observable
.interval(2000)
.take(3)
.do((next) => {console.log(next)}, () => {}, () => console.log('complete'))

Observable.from([
    { title: 'react' },
    { title: 'vue' },
    { title: 'angular' }
])
.zip(interval, (x, y) => x)
.subscribe(value => {
    aDOM.innerHTML = JSON.stringify(value)
})
```

**Expected behavior:**
interval should be complete and console show

```bash
1
2
3
complete
```

**Actual behavior:**
interval is never complete and console show 
```bash
1
2
3
```

https://jsbin.com/hiwawej/edit?js,console,output

thank you

**Comment by JaminFarr** [comment]
When any source of a zip operator completes it waits for the other sources to emit the same amount of values and then unsubscribes from them.

In this case the `Observable.from` emits 3 values and completes. Zip then waits for the `interval` source to emit 3 values and unsubscribes immediately.

'complete' is never logged because the `interval` observable is unsubscribed before it can complete.

If the `do` is moved after the zip operator it will log 'complete' as expected.
Also adding an extra item to the from array also lets the `interval` complete because then zip is waiting for 4 items. `.take(2)` will do the same.

If `.take(3)` has only been added to match the item count of the array then it is not necessary. Zip will unsubscribe and clean up the rest of the sources automatically.

**Comment by Jerry-Hong** [comment]
I got it, thank you!
