### ISSUE TITLE
Subscribe handler fires early than subscribe() method

### ISSUE THREAD

**Issue by interist32** [ReactiveX/rxjs#2566]
Version 5.3.0
**Code to reproduce:**
```js
var source$ = Rx.Observable.of([1,2,3]);

console.log('start');
var subscription = source$.subscribe(i=>{
    console.log('success');
    // subscription.unsubscribe(); --> subscription is undefined here
});
console.log('end');
```
I've prepared some [JS Fiddle](http://jsfiddle.net/nqxc7o8q/) for code above.

**Expected behavior:**
Subscribe handler is expecting to be called after .subscribe() method, isn't it? So I expect to have such output:
```js
// 'start'
// 'end'
// 'success'
```

**Actual behavior:**
```js
// 'start'
// 'success'
// 'end'
```

**Comment by kwonoj** [comment]
So this is basically due to `of`, which does emit all values synchronously as soon as it subscribes.

https://github.com/ReactiveX/rxjs/blob/e38711379f357f55290ead7fabcf8c70c5b31961/src/observable/ArrayObservable.ts#L36-L41

If you're subscribe other than synchronous one or either specify async scheduler like `Observable.of(...value, Scheduler.asap) //now value will be emitted via asap scheduler`, you'll see subscription will occur asynchronously.
