### ISSUE TITLE
What's the different between a hot observable and a subject

### ISSUE THREAD

**Issue by code-tinker** [ReactiveX/rxjs#2604]
```javascript
const a = Rx.Observable.create().share();
const b = new Rx.Subject();
```
> * What's the different between a & b ? Hope someone can help me 🙏

**Comment by trxcllnt** [comment]
A cold Observable is an Observable that re-executes its `subscribe` handler every time it's subscribed to:
```javascript
const cold = new Observable(function subscribe(observer) {
  console.log('subscribed');
  observer.next(Math.random());
  observer.complete();
});
// > subscribed
// sub 1: 0.1231231231231
cold.subscribe((num) => console.log('sub 1:', num));
// > subscribed
// sub 2: 0.09805969045
cold.subscribe((num) => console.log('sub 2:', num));
```

A hot Observable is a source Observable (cold or otherwise) that has a Subject between the source and subscribers. When a hot Observable is subscribed to, the subscription is internally routed to the inner Subject transparently, and the Subject is subscribed to the source Observable. This ensures the source Observable only has one subscriber (the Subject), and the Subject ensures the same value is shared with many Subscribers:

```javascript
const cold = new Observable(function subscribe(observer) {
  console.log('subscribed');
  observer.next(Math.random());
  observer.complete();
});

const hot = cold.publish();
hot.subscribe((num) => console.log('sub 1:', num));
hot.subscribe((num) => console.log('sub 2:', num));
hot.connect(); // <-- this subscribes the inner Subject to the cold source
// > subscribed
// > sub 1: 0.249848935489
// > sub 2: 0.249848935489
```

You can make an Observable hot via `multicast`, which takes a function that returns a Subject to use when its connected. There are also variants of multicast for convenience (such as `publish`) that create specific types of Subjects. `publish()` is a convenience method for `multicast(() => new Subject())`

In addition to `connect()`, which subscribes the inner Subject to the source and returns the underlying Subscription, you can call `refCount()`, which returns an Observable. When the Observable returned by `refCount()` is subscribed to at once, it will automatically call `connect()` internally, and subsequent subscriptions won't reconnect. When all subscribers unsubscribe, `refCount` will automatically unsubscribe the inner Subject from the source. `share()` is a convenience method for `source.publish().refCount()`.

**Comment by code-tinker** [comment]
@trxcllnt 
Thank you ! It really helps me a lot !😄

**Comment by RoyiNamir** [comment]
@trxcllnt This is the best simplest answer including the new changes (IMHO) where a subject is in the middle.
