### ISSUE TITLE
Should we update to TypeScript 2.1 or 2.3 for v6 (beta to be released soon)?

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#2613]
I suspect that there are probably quite a few people stuck on TS 2.1 that wouldn't be able to upgrade to the next major version, but I have no usage statistics to back that up. Since it's a breaking change, and there for in a major version bump, it might not matter to most people, and usually only people that want to be on the bleeding edge are early adopters of new major versions.

I believe Angular is now on TS 2.3, so that might play a factor in the decisions.

Thoughts?

**Comment by benlesh** [comment]
related #2606, #2612

**Comment by DanielRosenwasser** [comment]
What are the changes you're concerned about that make sticking to 2.1 more appealing?

**Comment by cport1** [comment]
I think most of us are using 2.3.2  already...

**Comment by benlesh** [comment]
> What are the changes you're concerned about that make sticking to 2.1 more appealing?
@DanielRosenwasser: it's more of a matter of concern that many people are stuck on TS 2.1 for one reason or another. It's probably unfounded.... this is why I'm asking the community

**Comment by hccampos** [comment]
I vote for going with 2.3. Mapped typed, generic defaults and so many other goodies that are hard to live without once you've used them a bit.

**Comment by paulbakker** [comment]
If there are no reasons why upgrading > 2.1 is difficult (and I don't think there are), I don't see a reason why RX should stick with an older version.

+1 for 2.3

**Comment by DanielRosenwasser** [comment]
If you need, we have [our Breaking Changes](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes) page. I would say that by and large, you'd be better off taking the latest one since we haven't drastically changed anything.

The biggest "gotchas" will be when you use a newer feature whose declarations aren't supported in older versions of TS (e.g. the non-primitive `object` type, or mixin classes).

I'd say one thing you may want to do is at least test on 2.4, but build with 2.3. TypeScript 2.4 will have some stricter variance checks which can catch legitimate bugs in declarations and usage, especially with Observables.

**Comment by staltz** [comment]
I'd vote for v2.3, I don't think we'll have significant migration headaches inflicted on users, *because* our current migration bottleneck is getting users from v4/reactive-extensions to v5/reactivex. Like seriously, [this chart is worrisome](http://npmcharts.com/compare/rx,rxjs).

**Comment by kwonoj** [comment]
I'm on 2.3 as well, as this is breaking changes I don't see strong reason to stay with 2.1. there are few features we'd like to adapt long time like default generics.

**Comment by benlesh** [comment]
Looks like most voices at Google are saying 2.3 as well...

**Comment by david-driscoll** [comment]
👍 to 2.3... we then work on integrating default generics, keyof and mapped types too! :)

**Comment by benlesh** [comment]
# I think we're settled on 2.3 

closing

**Comment by rajinder-yadav** [comment]
Infinity and beyond!
