### ISSUE TITLE
when does Zip emit Error?

### ISSUE THREAD

**Issue by wbpmrck** [ReactiveX/rxjs#2617]
**RxJS version:**
Rxjs 5
**Code to reproduce:**

```

        var error =Rx.Observable.throw('Oop!');
        var age$ = Rx.Observable.concat(Rx.Observable.of(21,22,23),error);
        var sex$ = Rx.Observable.of("male","male","female","female");
        var name$ = Rx.Observable.of("jack","john","james","lucy");
        var example = Rx.Observable.zip(age$,sex$,name$,(age,sex,name)=>{ return {age,sex,name} });

        example.subscribe({
            next: (value) => { console.log(value); },
            error: (err) => { console.log('Error: ' + err); },
            complete: () => { console.log('complete'); }
        });
```
**Expected behavior:**
expected output is:
```
{age:21,sex:"male",name:"jack"}
{age:22,sex:"male",name:"john"}
{age:23,sex:"female",name:"james"}
Error:Oop!
```
**Actual behavior:**
just one line,`with out` any output value.
```
Error:Oop!
```
**Additional information:**
none

Does anyone know:`when does the Zip operator emit error`

**Comment by wbpmrck** [comment]
I had put this question in [stackoverflow](https://stackoverflow.com/questions/44196044/rx-jswhen-does-zip-operator-emit-error) and got answer:
```
zip synchronously receives all of the observable's values and the concatenated error. It then emits its own error and is done.
```
this can explain the `results` of my demo,but i still think the implement of `zip` is weird.
I also check the [spec doc](http://reactivex.io/documentation/operators/zip.html) and it does't mention when should zip emit error.

**Comment by kwonoj** [comment]
>  i still think the implement of zip is weird.

: would you elaborate more detail why it's weird? above snippet's behavior is not cause of behavior of `zip`, cause of you supplied synchronous observable as sources of operator. In RxJS 5, synchronous observable supposed to emit immediatly unless you're scheduling otherwise. For asynchronous observable sources, `zip` explains it via test cases. 

https://github.com/ReactiveX/rxjs/blob/da96b6af6472947b8428b5a341d5c6acef0960df/spec/operators/zip-spec.ts#L534-L556

**Comment by wbpmrck** [comment]
@kwonoj Thanks for pointing out the key.
