### ISSUE TITLE
Chinese localization for the official document site

### ISSUE THREAD

**Issue by SangKa** [ReactiveX/rxjs#2654]
First of all it is a idea to discuss rather than a bug report.

Hi, @benlesh @kwonoj @staltz and so on . Thanks for all of you for rewriting the awesome RxJS.
RxJS is so cool and so many people love it so much, personally I believe its potential.
But because of its high learing curve, a lot of developers which interest in it still standing outside of the door. So I want to help more developer which come from China to get started with RxJS by reducing the learning curve and I translate the  official document site of RxJS into Chinese. The purpose is making the community of RxJS stronger.

I hope it can be added into the repo's README as a link.
The form can be like this:

### Translations:
  * Chinese or 中文

#### Appendix:
docs: [http://cn.rx.js.org](http://cn.rx.js.org)
repo: [https://github.com/RxJS-CN/RxJS-Docs-CN](https://github.com/RxJS-CN/RxJS-Docs-CN)

**Comment by kwonoj** [comment]
I'm labeling this as discussion for now.

One Q: is there specific reason this should be included in official docs? what blocks to share this document with local readers if not the case?

**Comment by SangKa** [comment]
First and the most important concern is that the most local readers may be not know the existence of the local document. RxJS itself is hard as its high learing curve, and for the readers that not good at English is harder than ever. It may frustrate them.
Last allowe me to describe on scenario:
One RxJS beginner which come from China starts to read the offical repo or docs, once them find there is already a Chinese localization for them, I trust them will be happy to read it to improving their learning speed.

**Comment by kwonoj** [comment]
I am in general welcoming effort related with documentation, around translations I had couple of concerns on some other projects I worked on.

- First, it is really hard to find proof-reader
: if translation is not reflecting original documentation, it may lead readers incorrect understandings. For original (English in here) we have several contributors can proof read on PRs, but when in comes to translation it is really not easy to find someone can do. I do not say you'll translate something not as expected, it is just we probably can't have review process for this.

- Documentation can be bit behind and outdated
: Our original documentation is already behind to code implementation. In case translation, it could be behind to original documentation even.

Due to above reasons, one of module I'm using is providing my own language docs, I barely not referencing it but heading to original documentation directly, lot of cases I find translated docs are not matching with original documentation.

Once we link your documentation as 'official' link to docs, it means it is under the responsibility of maintainer to make documents latest and correct. I am not sure how we can keep up those with current working pipeline. Don't get me wrong, your contribution is super great & appreciate - I'm thinking maintainable pipeline process for further.

**Comment by SangKa** [comment]
I thought I got your concern point. You have to be responsible for all of your work.

For the first, I agree with you, it may not be resolved for now. Although we have two guys to translate and proof reading each other, but compare to you guys which are contributors, the understanding of RxJS for us is not as deep as yours. 

And for the second, it won't be a promble, since we decided to do the translation work, we'll make it better and not quit easily to let it  be a one-time work. We are tracking the original repo for syncing the document diff continuously.

In the end, I want to say 'Thank You' to all of you guys for the awesome work. 
For the result of discussion, I'm fine. Oneday you guys need the translation, I'll back for it.
All I have done is to make RxJS better and more and more developers to get started with it.
