### ISSUE TITLE
how can i  get eventObject object after mergeAll  

### ISSUE THREAD

**Issue by fukai007** [ReactiveX/rxjs#2746]
**RxJS version:**
5.2.0
**Code to reproduce:**
```
var clicks = Rx.Observable.fromEvent(document, 'click');
var higherOrder = clicks.map((eventObject) => Rx.Observable.interval(1000));
var firstOrder = higherOrder.mergeAll();

now x is count  . not is eventObject. how to get  eventObject  ?

firstOrder.subscribe(x => console.log("mergeAll------------------------->",x));
```
**Expected behavior:**
x is  eventObject
firstOrder.subscribe(x => console.log("mergeAll------------------------->",x));

**Actual behavior:**
x is  interval-count
firstOrder.subscribe(x => console.log("mergeAll------------------------->",x));

**Additional information:**

**Comment by crunchie84** [comment]
You are losing your clickEvents because you are mapping your `eventObject` to an Observable of interval emissions. A simple `.mapTo(eventObject)` will resolve this.

```
Rx.Observable.fromEvent(document, 'click')
  .map(evtObj => Rx.Observable.interval(1000).mapTo(evtObj))
  .mergeAll()
  .subscribe(val => console.log('evtObj: ' + val));
```

Note that without a `take(x)` on your interval every `click` will result in a new interval simultaneously emitting their own clickEvent on repeat until infinity.
