### ISSUE TITLE
Docs: ES6 Installation

### ISSUE THREAD

**Issue by djskinner** [ReactiveX/rxjs#2762]
The docs (http://reactivex.io/rxjs/manual/installation.html) say to install `rxjs-es` and import `rxjs`. This doesn't work as the import needs to match the npm module name. Github suggests installing `rxjs`. Which is correct?

Also, it might be worth clarifying this bit:

> To import what you need and use it with proposed bind operator:

Does that apply if you import the full set of functionality or only if you import what you need?

Happy to PR this when I get time once I have clarification on the above.

**Comment by kwonoj** [comment]
The latest document actually already reflects those changes (to not to use rxjs-es) https://github.com/ReactiveX/rxjs#installation-and-usage , but it's not yet published to website unfortunately. We need to update it, just taking some time.

**Comment by IanVS** [comment]
Note, this is still an issue on the website, which also uses the `@reactivex` namespace (e.g. `import {Observable} from '@reactivex/rxjs/es6/Observable.js'` [here](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html)).  It's pretty difficult as a new user to find the "correct" way to install and use this library.  

I suggest that this issue be reopened due to:

>it's not yet published to website unfortunately. We need to update it, just taking some time.

The issue is about the website, and it seems that it isn't fixed yet.
