### ISSUE TITLE
Could Subscription.add() method accept multiple tear down functions at once?

### ISSUE THREAD

**Issue by martinsik** [ReactiveX/rxjs#2769]
**RxJS version:** 5.*

**Actual behavior:**

I often find myself adding multiple `Subscription`s into a single `Subscription` so I can later unsubscribe with a single `unsubscribe()` call (for example in Angular).

This means I need to do for example the following:

```
const subscription = new Subscription();

const sub1 = Observable...subscribe();
const sub2 = Observable...subscribe();
const sub3 = Observable...subscribe();

subscription.add(sub1);
subscription.add(sub2);
subscription.add(sub3);

...

subscription.unsubscribe();
```

**Desired behavior:**

It would be helpful to me if I could add all tear down functions into `subscription` at once. For example similarly to `Array.push()` function that accepts multiple items:

```
subscription.add(sub1, sub2, sub3);
```

**Comment by kwonoj** [comment]
This was discussed before https://github.com/ReactiveX/rxjs/issues/1583 , without concrete conclusion at the moment. Personally I think current interface mostly works, either via chaining (`sub.add().add()....`) for simply using array `[].forEach(sub.add)` - but will leave this opened to see if there's other opinion.

**Comment by martinsik** [comment]
Using `sub.add().add()` is probably enough.
I think `[].forEach(sub.add)` won't work because it'll loose `this` context.

**Comment by larrifax** [comment]
I recently discovered that ```sub.add(another)``` doesn't return ```sub```, but ```another```. This means that chaining can have adverse effects if one of the chained subscriptions ends before the root subscription does:

```
const sub = new Rx.Subscription();

sub
  .add(Rx.Observable.interval(1000).do(x => console.log("Interval 1", x)).first().subscribe())
  .add(Rx.Observable.interval(1000).do(x => console.log("Interval 2", x)).subscribe());

setTimeout(() => sub.unsubscribe(), 5000);
```
In this case, "Interval 2" never logs to the console, as "Interval 1" effectively unsubscribes "Interval 2" when it ends due to the ```first()``` operator.

**Comment by benlesh** [comment]
In RxJS 5.X  `sub.add().add()` does NOT work like you'd expect. Returning a subscription from `add()` is a byproduct of legacy behavior, and should be avoided.

**Comment by benlesh** [comment]
To answer this OP issue:

I don't think we'll be adding an `addTo` method because:

1. There isn't a reason for it in the library.
2. If you have a handle to both subscriptions `a.add(b)` and and `b.addTo(a)` are basically the same thing, so `addTo` probably isn't necessary.

I'm closing this one for now, and thank you so @martinsik for the idea.
