### ISSUE TITLE
Proposing a PullSubject variation

### ISSUE THREAD

**Issue by bd60** [ReactiveX/rxjs#2783]
This is a proposal for an extension of subject called something like a PullSubject. The goal is to replicate a variation on the classic observer pattern that is very useful, but difficult to accomplish in RxJS.  The pattern is to get a response from all observers and return to the caller like:

    function collectAll() {
        var responses = [];
        for (let obs of this.observers)
            responses.push(obs.next());
        return responses;
    }

This is very useful in any situation where there is a master "smart" component of a variable number of "dumb" components, especially when the number of dumb components is dynamic in nature, and the master needs to request information from all of it's sub components, and when and only when all observers have responded.

One such use case is a dynamic form with several components and a centrally triggered save function that must collect the value from every sub component.  

Another potential case could be some service responsible for positioning many elements that must ask a number of dynamic components for their current position.

I suggest an implementation of PullSubject would require any observers' next function to return a value (or perhaps an observable).  The pull subject would expose a special pull() observable that the master would subscribe to, and calling the next() method on the subject would cause the PullSubject to gather every direct observers response and once all have responded, pass it to the pull() observers in an array, or as as observable stream that completes when all have responded.

As it stands, this functionality is overly difficult to replicate in rxjs, and I feel this would be a very useful addition.

**Comment by kwonoj** [comment]
Aside from usefulness of suggested operator itself, I'd first argue if you have to `pull` something from subscriber you may need to revisit the current design of application's observable chain. 

For operator, we do recommend to publish it as a separate module, but your proposal seems require breaking changes into core interface to observer - which means you probably can't do without modifying codebases. I would suggest to follow draft in https://github.com/ReactiveX/rxjs/issues/2299#issue-201963204 fill in detail since it requires fundamental changes. 

I can't say more in detail with given information at this moment if Rx really needs this changes or not, but rough assumption is this could be resolved via application design level instead of changing design of library itself.

**Comment by bd60** [comment]
I'm definitely open to hearing an alternative application design.  There have been a few cases already where I needed to get a response from all subscribers and aggregate their responses.  

One case was a dynamic dashboard with widgets that a user could add, remove, resize, and reposition. I had a service that handled collision detection and directed the components where to move to avoid each other.  In this situation I did not know how many components I had on the page, and the traffic controller couldn't effectively control traffic without knowing every component's position.  I couldn't effectively solve this with rxjs.  

Thanks for the response though. I'll look into what it will take. My goal is certainly not to change the design of the library as it is fantastic. I only want to extend it with this extra piece of functionality that I believe is very useful in many common application uses.

**Comment by kwonoj** [comment]
I'm going to close this issue for now as I believe we may need more detail to kick off this discussion actually, while I also believe there isn't strong argument that we need to introduce pull based design in core library. If you have more details around proposals, please reopen issues as needed.
