### ISSUE TITLE
Typing of of Observable.create

### ISSUE THREAD

**Issue by pelotom** [ReactiveX/rxjs#2788]
RxJS version: 4.5.2

The TypeScript signature for `Observable.create` is just:

```ts
static create: Function;
```

Is there a reason it can't be given a richer type?

**Comment by david-driscoll** [comment]
Because TypeScript does not let static properties type change from parent to base classes, and subject's `create` method takes 2 arguments.

https://github.com/ReactiveX/rxjs/blob/d2a32f9a18ebbf65bea798f558364571c91a9d79/src/Subject.ts#L42

FWIW I've just switched to using the constructor and it works just fine, and frankly that's all `create` is doing anyway.
```
new Observable<T>(o => {
});
```

**Comment by pelotom** [comment]
I'm confused, what's wrong with

```ts
static create: <T>(subscribe: (observer: Observer<T>) => TeardownLogic) => Observable<T>
```

I just changed the definitions locally and it compiled fine.

**Comment by pelotom** [comment]
Ah, that's unfortunate. Would you accept a PR to add a comment to that effect to the documentation above the signature?

**Comment by kwonoj** [comment]
@pelotom for documentation comment PR, it'd be surely feasible.

**Comment by david-driscoll** [comment]
The original issue that ben filed is https://github.com/Microsoft/TypeScript/issues/4628

**Comment by kwonoj** [comment]
I'm going to close this issue for now as non-actionable, until upstream issue being resolved.
