### ISSUE TITLE
Issue using Rx.scheduler.asap

### ISSUE THREAD

**Issue by rave-ibm** [ReactiveX/rxjs#2793]
**RxJS version:**
5.4.1
**Code to reproduce:**
return Observable.of(asap.schedule(() => {//doSomething}));
**Expected behaviour:**
When I make a call to the function this should "//doSomething"
**Actual behaviour:**
Not getting any errors but the scheduled task is not performed.
**Additional information:**
When I replaced asap.schedule with setTimeout (as shown below), then the code is working fine.
return Observable.of(setTimeout(() => {//doSomething}, 0));

**Comment by kwonoj** [comment]
![image](https://user-images.githubusercontent.com/1210596/29228715-c7e9be20-7e8f-11e7-9dd5-e0506178e363.png)

I can make action works for both cases,  I'd like to ask to provide reproducible code snippet other than just single line.

**Comment by rave-ibm** [comment]
This code id defined in **highlightService**:

highlightElement(elementId: string): Observable<any> {
			return Observable.of(asap.schedule(() => {
				console.log('I am here');
				document.getElementById(elementId).classList.toggle('highlight');
			}));
		}

This is defined in a **component** where I created an instance of highlight service

this.highlightService.highlightElement(id).subscribe(next => {
				console.log('TOGGLED');
		}, error => {
				console.log('Failed');
		});

During more analysis, I found out the highlightElement() is being called out twice(I see, 2x 'I am here') for each call. And the 'TOGGLED' in Observer is not getting printed at all.

**Comment by rave-ibm** [comment]
Just to be clear, I double checked and the Observer code is called only once.

@component
highlightElement() {
		console.log('Adding class');
		this.highlightService.highlightElement(id).subscribe(next => {
				console.log('TOGGLED');
		}, error => {
				console.log('Failed');
		});
	}

**Comment by rave-ibm** [comment]
Hi @kwonoj  I created a plunkr and am able to reproduce the issue, can you please have a look. Specifically, follow the flow of "Add class" button. Also, note that issue is not there when using setTimeout function.
https://plnkr.co/edit/RFwuAZXMHBh61nLpCpDV?p=preview

**Comment by paulpdaniels** [comment]
@rave-ibm So the issue here appears to be that you are passing the result of `scheduler.schedule()` to `Observable.of` which under the hood attempts to create an `ArrayObservable`, however because you are passing an `Action`, `of` thinks it is a scheduler and is mapping the value to the scheduler [here](https://github.com/ReactiveX/rxjs/blob/master/src/observable/ArrayObservable.ts#L65). 

Since the array is now empty it then returns an `EmptyObservable` [here](https://github.com/ReactiveX/rxjs/blob/master/src/observable/ArrayObservable.ts#L77) with the `Action` as its scheduler. Since the action is then being used as a faux `scheduler` it gets recycled and re-executed when you attempt to subscribe to the resulting Observable *instead* of forwarding any messages downstream.

One could argue that we shouldn't be relying on the kind of duck-typing to determine whether an element is a scheduler but in the end I don't think there is a way around it given the looseness of the JS type system.

Without going into too much detail (Stack Overflow would be a more appropriate place if you have a usage question) I would suggest rethinking your approach to try avoiding the use of schedulers explicitly like that.

**Comment by kwonoj** [comment]
@rave-ibm @paulpdaniels explained reason of execution occurs multiple time thoroughly, so I believe it explains reason why. 

In addition, I also strongly agree his suggestion to not to use explicit scheduler, especially I wouldn't recommend to trying to trigger side effect in creation method - you could look for some other approaches which doesn't hit by scheduler actions's behavior.
