### ISSUE TITLE
The Observable created with `of` and `from` has a different behavior when use `repeatWhen`.

### ISSUE THREAD

**Issue by keifergu** [ReactiveX/rxjs#2802]
**RxJS version:** 5.0.0-beta.12

**Code to reproduce:** https://jsfiddle.net/keifer/gyyv329f/

**Expected behavior:**
```javascript
from:1
from:1
from:1
...
```
**Actual behavior:**
```javascript
from:1
```
**Additional information:**
When I use the `of` operator to create an `Observable`, the behavior is right. But when I do it with `from`, I think the result is wrong.

**Comment by kwonoj** [comment]
`of` and `from` is different api for handling - `from` should supply Array-like object. Due to string is considered as array-like, supplying `1` doesn't raises compilation error but it should be `[1]` instead to achieve desired behavior. 

For example, if you do 
```
Rx.Observable.from('123').map((x) => x + 'x').subscribe(console.log.bind(console));
```
output will be `1x`, `2x`, `3x`

while 
```
Rx.Observable.of('123').map((x) => x + 'x').subscribe(console.log.bind(console));
```
will be `123x`.

**Comment by keifergu** [comment]
@kwonoj thanks for your comment,and sorry to reply to you so late.I had created a [new fiddle](https://jsfiddle.net/keifer/m0e0k6dr/) to explain my question.

When we use `repeatWhen`, the observable that created with `Observable.from(<String>)` or  `Observable.from(<Array>)` have a different behavior.The `<String>` observable will only repeat once. But the `<array>` will repeat at intervals of 2000ms.You can reproduce the problem in that fiddle.

Looking forward to your reply.

**Comment by paulpdaniels** [comment]
@kwonoj @keifergu might have a point it looks like there is some inconsistent behavior here. The `IteratorObservable` generates the iterator during construction rather than during subscription (see [here](https://github.com/ReactiveX/rxjs/blob/master/src/observable/IteratorObservable.ts#L55)). Was there a behavioral reason that this needed to be done?

**Comment by kwonoj** [comment]
@paulpdaniels check https://github.com/ReactiveX/rxjs/pull/2497 for those.
