### ISSUE TITLE
[Question] Is `next` branch broken?

### ISSUE THREAD

**Issue by gund** [ReactiveX/rxjs#2892]
Hi,

I was trying to contribute to the `next` branch but stuck when ran tests on CI as [they failed](https://travis-ci.org/gund/rxjs/jobs/282753506#L1986).

So my question is the `next` branch broken?
And if so how can I contribute to the beta version (because changes will require TS>2.1 and in current master branch it is set to 2.0.x)?

Thanks in advance and sorry if this was already asked/answered somewhere.

**Comment by kwonoj** [comment]
So our current beta version is `master` branch, and `next` is for next major version (6.x). 

And as you mentioned it's currently somewhat broken state due to we are trying to stablize 5.5 beta first, and release it. Our current plan is once we ship 5.5 public, cherrypick changes into next branch and stablize it and continue major breaking changes there. Core team have quick discussion around status of versioning world bit before (https://github.com/ReactiveX/rxjs-core-notes/blob/master/2017-09/September-11.md#discussed) that you can refer.

And no need to sorry always. 👍

**Comment by gund** [comment]
@kwonoj Thanks for quick reply.

Just to clarify:
`master` is the beta but it points to fixed TypeScript version 2.0.x.  
If I my changes require TS 2.1 or above I then should target `next` branch, right?

**Comment by kwonoj** [comment]
@gund correct, we have decided bump up TSC for next major cause we have breaking changes.
