### ISSUE TITLE
distinctUntilChanged operator not working

### ISSUE THREAD

**Issue by Tiedye** [ReactiveX/rxjs#2980]
**RxJS version: 5.5.0**

**Code to reproduce:**
```ts
Observable.of('66e4b95a-5277-4930-bae0-0c7a55c982b3', '66e4b95a-5277-4930-bae0-0c7a55c982b3')
    .distinctUntilChanged()
    .subscribe(x => console.log(x));
```

**Expected behavior:**
The code should only print once.

**Actual behavior:**
It prints twice.

**Additional information:**
I haven't been able to test that example code specifically for this issue, its occuring in a angular component in this code:
```ts
      route.params.filter(params => params['id'] != null).map(params => <string>params['id']).distinctUntilChanged().do(id => {
        store.dispatch(new guard.FetchOneAction(id));
        this.resetChanges(id);
      })
```
And I've check before and after the `distincUntilChanged` the value in the pipe, and I am absolutely certain that there are no values being passed between the two identical strings.  If anyone has a good plunker template for rxjs I could make a plunker (I dont have time rn to do it myself)

**Comment by montella1507** [comment]
There are several critical issues in 5.5.0:
https://github.com/ReactiveX/rxjs/issues/2977

**Comment by Tiedye** [comment]
Alright, so downgrade for the time being?

**Comment by montella1507** [comment]
I would say yes. We did not upgrade to 5.5.0, unfortunately everywhere is "range cavet" version (in our case we had ^5.4.3 so it has been automatically updated to 5.5.0). Change to pinned version 5.4.3 fixed all problems.

**Comment by kwonoj** [comment]
I don't think it's related with 5.5 and I just confirmed operator itself behaves same as before - like below output. 

![image](https://user-images.githubusercontent.com/1210596/31796058-fcc0c2b4-b4dc-11e7-9efe-1d4506a123fb.png)

Please provide reproducible code, without framework is involved. Plain node based github repo is usually best.

**Comment by montella1507** [comment]
@kwonoj  well.. it is not so easy to detect which is involved in our errors -  i cannot simulate the problem in pure rxjs, i tried today. :-/

Is it possible to try reproduce steps here:
https://github.com/angular/angular/issues/19799

i dont want you to debug my application,  just to start one run, maybe rxjs 5.5.0 is in conflift with zone.js ?

**Comment by kwonoj** [comment]
I can't guess, or debug into code you've posted in issue you shared. Except module loading ergonomics, operator side 5.5 has not changed especially specific operator in this issue, also isolated code works fine reason I think this is application side issue instead of library side issue. I'll keep opening issue, but can't say I can dig this with current state.

**Comment by montella1507** [comment]
@kwonoj  ok, unfortunately i am not able to debug it, i think it needs strong knowledge of how Angular+angular-cli work (atleast in my case, i cannot tell everyone else is using any framework), so i can only wait for response from angular team. 

I have just hoped you would be able to detect the issue, because there are only rxjs calls in callstack.. However i know it very difficult, because everything can change (monkeypatch) anything and conflict anything...  :-(

**Comment by Tiedye** [comment]
Found the issue, there was an additional subscription in my code that I had forgotten about, sorry to bother you.  `share` solved the issue.

**Comment by Tiedye** [comment]
That took waaaay to long to figure out.
