### ISSUE TITLE
Mor Better (testing) Documentation..

### ISSUE THREAD

**Issue by michahell** [ReactiveX/rxjs#3195]
Why is it that every time I'm searching for a way to `Do It Right The First Time` in RXJS,

I end up finding outdated RXJS v4 documentation? Where can I find RXJS V5 documentation regarding testing ? More specifically, testing time-based operators such as `.delay()` and `.debounceTime()` and the like...

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/testing/testscheduler.md

is ^ still relevant ?

**[edit]** just see this: https://github.com/ReactiveX/rxjs/issues/1791

**Comment by jonlambert** [comment]
+1. I would add it's pretty frustrating to see '**This is RxJS v4. Find the latest version here**', only for the link to take you to the root of the v5 repository, rather than the relevant article. 

Even though I know it's the case, I almost always still instinctively go through the [Google](https://www.google.co.uk/search?q=testing+in+rxjs) -> [relevant v4 article](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/testing.md) -> [root of v5](https://github.com/reactivex/rxjs) flow.

**Comment by benlesh** [comment]
This is something we're working on over at github.com/reactivex/rxjs-docs

cc @ladyleet @jayphelps

**Comment by ladyleet** [comment]
@benlesh GET TO THAT ISSUE CLOSING! :D I see the notifications. :P

**Comment by jonlambert** [comment]
@benlesh Awesome, that’s great to hear 😊
