### ISSUE TITLE
currentTarget is null issue

### ISSUE THREAD

**Issue by Mek89** [ReactiveX/rxjs#3214]
Hi,

I hope someone could help my problem. I need to call some third party function which is waiting a MouseEvent with currentTarget.
```

const canvasMousedown$ = Rx.Observable.fromEvent(chart, 'mousedown');
const canvasMousemove$ = Rx.Observable.fromEvent(chart, 'mousemove');
const canvasMouseup$ = Rx.Observable.fromEvent(chart, 'mouseup');

const canvasSelection$ = canvasMousedown$.concatMap((startEvent) => {
  return canvasMousemove$.takeUntil(canvasMouseup$).map((endEvent) => [startEvent, endEvent])
});

canvasSelection$.subscribe((events) => {
    getElements(chart, events);
});

function getElements(chart, events) {
    return events.map((event) => thirdpartyFunction(event));
}
```

But the original event might have been partially discarded at the time I process it. And the currentTarget is null. Any idea how can I avoid this properly?

My workaround would be just simple overwrite the currentTarget with the original elemenent:
event.currentTarget = somethingEl

but I use typescript and the event is a const: "Cannot assign to 'currentTarget' because it is a constant or a read-only property". Or any idea how can I clone the event properly?

Thank you for the help!

**Comment by kwonoj** [comment]
I don't think this is rx side issue - per documentation (https://developer.mozilla.org/en-US/docs/Web/API/Event/Comparison_of_Event_Targets) says `As the event capturing and bubbling occurs this value changes.`, `currentTarget` will not persist over time but will change based on event state. 

I tried your example and could see when aggregate `[startEvent, endEvent]` first eventTarget's missing while other one's available also directly subscribing to each individual event observable (down$, move$, up$) correctly allows to access currentTarget. you may need capture reference to target in somewhere instead of try to reassign it to access it later (rough pseudo like `map(e => ({event: e, target: e.currentTarget})`, or use different event target instead.
