### ISSUE TITLE
Exportable configuration and testing tools

### ISSUE THREAD

**Issue by ajcrites** [ReactiveX/rxjs#3293]
Now that pipeable operators are available and becoming more popular, there is a lot of opportunity for third parties to create modules that export pipeable operators. I think this is desirable, and I think that a few of things can be done by rxjs to support this better.

Currently, if you want to create a pipeable operator module you will have to create your own TypeScript configuration, linting, building, and set up testing support for yourself if you want to do it. These are built into rxjs, but they could function as separate modules -- i.e. the compiling and testing scripts could be separate modules imported into rxjs and used by other libraries.

Right now if you want to create a pipeable operator module you can create a tsconfig like this:

```
{
    "extends": "./node_modules/rxjs/src/tsconfig.json",
    "files": ["index.ts"],
    "compilerOptions": {
        "outDir": "dist"
    }
}
```

This isn't bad, and actually it would be great to see more things like this that would simplify third party creation of pipeable operators as separate modules that would confirm to rxjs's own development standards and provide consistency across a lot of different modules.

Here is what I think would help:

1. Make `tsconfig.json` a bit easier to import
2. Export `tslint.json` or create a module for it.
3. Create a module for testing dependencies and scripts. Otherwise third party devs have to set this up themselves which creates a barrier for testing which makes it less likely.
4. Create a module for building dependencies and scripts. Same reasoning as point 2.
5. Documentation

A template would also help, but my imaginary project would be able to do something like

```
// package.json
{
  "dependencies": {
    "rxjs": "*"
  },
  "devDependencies": {
    "@reactivex-scripts/build": "*",
    "@reactivex-scripts/lint": "*",
    "@reactivex-scripts/test": "*"
  },
  "scripts": {
    "build": "rxjs-scripts-build src",
    "lint": "rxjs-scripts-lint src",
    "test": "rxjs-scripts-test spec",
  }
}
```

Then you would just need the source and tests without much additional setup.

**Comment by kwonoj** [comment]
3 is covered by https://github.com/ReactiveX/rxjs/issues/3231 (probably can include 5 as well), but except those I don't see reason for 1 / 2 should be handled by core. Core's configuration is highly tamed for producing multiple library bundle, not intended to be used for common source of third party. Moreover, it is _good_ to share common compilation rules, it is not something enforced. Since this is JS anyway, any 3rd party can choose own rules or configurations.

There's some discussions around `bootstrapping` for custom and I think this is also falls into those category, while I think that's also territory of 3rd party modules or so. I don't think core lib itself will ship something included in library as ooto for these kind. One day we achieve monorepo config we could have those 3rd party pkg comes into single repo though. 

I'm closing this issues for now, as we are targeting testing / other ergonomics enhancement in existing issues. Once we have those things ready, we can discuss remaning things separately.
