### ISSUE TITLE
"rxjs@5.5.6" pulls out the old version of "symbol-observable" (1.0.1)

### ISSUE THREAD

**Issue by a13531a** [ReactiveX/rxjs#3313]
**RxJS version:**
5.5.6

**Code to reproduce:**
npm install rxjs@5.5.6 --save-exact

**Expected behavior:**
I expected to see the "symbol-observable" package of the version 1.2.0 or something like this (at least higher than 1.0.4).

**Actual behavior:**
The installed "symbol-observable" package is of the version 1.0.1.

**Additional information:**
Before I upgraded the rxjs package from 5.4.2 to 5.5.6, the rxjs@5.4.2 depended on symbol-observable@1.0.4.

Thank you.

**Comment by kwonoj** [comment]
5.4.2 had just caret to allow minor bump (https://github.com/ReactiveX/rxjs/blob/892700dd4f5d5e5f9ae9276ede32208f4390c5e9/package.json#L209) but due to some errands we've seen we pinned all dependencies (https://github.com/ReactiveX/rxjs/blob/0d0422c8ccf59256220da9d8099292cc66bfd1ab/package.json#L222), so expected behavior.

**Comment by a13531a** [comment]
Thanks for the prompt response.
