### ISSUE TITLE
Test suite doesn't tsc type-check

### ISSUE THREAD

**Issue by IgorMinar** [ReactiveX/rxjs#3411]
The current test suite under `spec/` is being transpiled to JS and executed, but no type-checking is currently being enforced. As a result of that, lots of typing errors have been introduced into the test suite.

Repro:
```
yarn tsc -p spec/tsconfig.json
```

Expected: no type errors
Actual: lots and lots of errors

Once this problem is resolved, the tsc typecheck should be added to the CI suite so that we can avoid introduction of new errors in future commits.

**Comment by kwonoj** [comment]
@david-driscoll is working on this. https://github.com/ReactiveX/rxjs/pull/3329 . I've accidentally closed https://github.com/ReactiveX/rxjs/issues/3020 .

**Comment by kwonoj** [comment]
I think we can use this one until it's resolved, #3020 doesn't have additional detail specifically worth to reopen.

**Comment by cartant** [comment]
I can't cope any longer with the test suite's not being type checked. I see that #3329 has been closed:

> ... in favor of a more incremental approach.

I'm going to start work on an incremental approach now. Unless anyone has objections, I plan on doing the following:

* Create a temporary `spec/tsconfig.check.json` file.
* Specify an `include` in said file so that files can be incrementally checked and fixed. E.g. `'include': ['spec/operators/a*.ts']`
* Create a temporary `script` named `test_check` (or whatever) in the `package.json` to run a no-emit  `tsc` build that uses `spec/tsconfig.check.json`.
* Include `npm test_check` in the `.travis.yml` configuration file so that the CI build runs it.
* Incrementally update the `-spec.ts` files so that they pass the check. That is, update them with individual PRs or, at least, in very small batches.
* When all `-spec.ts` files pass, remove the temporary scripts from the `package.json` and the `.travis.yml` files, delete the `spec/tsconfig.check.json` file and set the [`TS_NODE_TYPE_CHECK` environment variable](https://github.com/TypeStrong/ts-node/blob/v6.0.3/src/index.ts#L100) in the `test` script so that `ts-node` will throw an error if TypeScript errors are introduced into the tests.

Once the test suite is again type checked, I'd like to extend the type tests to include snippet-based testing, as  discussed [here](https://github.com/ReactiveX/rxjs/pull/3053#issuecomment-342885852) and as done [here](https://github.com/cartant/react-streams/blob/automate-test-args/src/index.test.ts).

**Comment by david-driscoll** [comment]
👍  Let me know if you have any questions.  I had worked in a bunch of changes before there were some large refactors.

Interestingly most of the required changes to fix the type checking (and enhance the typings themselves) usually boiled down to some simply regex replace with a little bit of manual clean up.

**Comment by cartant** [comment]
It seems Microsoft have come through with the goods and built a tool for testing type expectations and errors. This looks like it will be pretty useful: [Microsoft/dtslint](https://github.com/Microsoft/dtslint)
