### ISSUE TITLE
repeatWhen operator broken since 5.5.6

### ISSUE THREAD

**Issue by wwjhu** [ReactiveX/rxjs#3444]
**RxJS version:**
5.5.6, 5.5.7

**Code to reproduce:**
https://jsfiddle.net/jy5fj6r8/16/

**Expected behavior:**
No errors, see
https://jsfiddle.net/cm6abypb/3/

**Actual behavior:**
Throws error `Rx.min.js:234 Uncaught TypeError: Cannot read property 'next' of null`

**Additional information:**
It appears that changes in 5.5.6 broke the repeatWhen operator. The fiddle mentioned as "code to reproduce" uses 5.5.7 while the one in "expected behavior" uses 5.5.5.

When the unit test is slightly modified (as shown below) by wrapping the code in a try..catch, the error is also visibile in the tests.

```
  it('should retry when notified and complete on returned completion', (done: MochaDone) => {
    try {
      const expected = [1, 2, 1, 2];
    Observable.of(1, 2)
      .map((n: number) => {
        return n;
      })
      .repeatWhen((notifications: any) => Observable.empty())
      .subscribe((n: number) => {
        expect(n).to.equal(expected.shift());
      }, (err: any) => {
        done(new Error('should not be called'));
      }, () => {
        done();
      });
    }
    catch (e) {
      done(new Error('should not throw'));
    }
  });
```

**Comment by benlesh** [comment]
Thank you for reporting this, @wwjhu!

**Comment by cartant** [comment]
I've had a quick peek at this. The `repeatWhen` implementation in 5.5.6 is unchanged from that in 5.5.5 - so 5.5.5 has the error, too.

However, prior with the change made in [this PR](https://github.com/ReactiveX/rxjs/pull/3161), the error was swallowed.

The problem is that `_unsubscribeAndRecycle` [sets](https://github.com/ReactiveX/rxjs/blob/5.5.5/src/operators/repeatWhen.ts#L103) `this.notifications` to `null`, but `this.notifications.next()` [is called](https://github.com/ReactiveX/rxjs/blob/5.5.5/src/operators/repeatWhen.ts#L83-L84) immediately after `_unsubscribeAndRecycle`.

**Comment by kemsky** [comment]
Does this error exist in the latest RxJS (6.0.0-beta) version?

**Comment by cartant** [comment]
> Does this error exist in the latest RxJS (6.0.0-beta) version?

Yes. And no. There is still an error in the beta, but - as in 5.5.5 - the error is swallowed.

My comment above was overly simplistic. This is what happens:

* When the source observable completes, the `complete` implementation in the `repeatWhen` subscriber wires up the notification observable by calling [`subscribeToRetries`](https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/repeatWhen.ts#L78).
* When [`subscribeToResult` is called](https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/repeatWhen.ts#L120) in the `subscribeToRetries` implementation, the completion of the notification observable sees the inner subscriber [call `notifyComplete`](https://github.com/ReactiveX/rxjs/blob/master/src/internal/InnerSubscriber.ts#L25-L28) on the `repeatWhen` subscriber (the outer subscriber).
* `notifyComplete` then [calls `super.complete`](https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/repeatWhen.ts#L67-L71) which calls the `repeatWhen` subscriber's `_unsubscribe` and `this.notifications` is set to `null`.
* Then, later in the `complete` implementation in the `repeatWhen` subscriber, the [call to `this.notifications.next()`](https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/repeatWhen.ts#L84) fails due to `this.notifications` being `null`.

The same problem occurs in 5.5.5, 5.5.6, 5.5.7 and in the beta, but the error is swallowed in versions other than 5.5.6 and 5.5.7.

It seems to me that [the test](https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/repeatWhen.ts#L68) in `notifiyComplete` is the wrong way around and should be:

```ts
notifyComplete(innerSub: InnerSubscriber<T, R>): void {
  if (this.sourceIsBeingSubscribedTo) {
    return super.complete();
  }
}
```

Thoughts?

Note there would still be the problem that errors are being swallowed in some versions.
