### ISSUE TITLE
Clarification on `pipe()` + non-operators

### ISSUE THREAD

**Issue by matthewwithanm** [ReactiveX/rxjs#3445]
As mentioned in #2995, the [pipeable operators docs](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md) state:

> The former `toPromise()` "operator" has been removed because an operator returns an `Observable`, not a `Promise`. There is now an `Observable.toPromise()` instance method.

Hoever, `pipe` does (imo rightly) work with non-operators:

```js
typeof of(1,2,3).pipe(() => 5) // "number"
```

Since the idea is to eventually move to `|>`, I'd really love for the documentation to be clear it's a supported usage and for the type defs to be updated accordingly. ❤️

**RxJS version:** 6.0.0-alpha

**Comment by benlesh** [comment]
Your're totally right. 

The problem was (in the short term) that many users were very confused by `source.pipe(map(fn), toPromise(), filter(x => x))`, for better or worse. So I was trying to get people to think in terms of "piping" operators, and not further complicate things by having them pipe to other types.

Maybe my babying there is a little over zealous.

There's, of course, also the matter of TypeScript typings, and how to get proper inference through there, pipe already has some issues in that department.

I'll try to figure something out soon.

**Comment by matthewwithanm** [comment]
Awesome, thanks @benlesh!

**Comment by benlesh** [comment]
:+1:
