### ISSUE TITLE
Get response url from response.xhr on ie11

### ISSUE THREAD

**Issue by l-pawliczak** [ReactiveX/rxjs#3472]
**RxJS version:**
5.5.6

Observable version: 
0.18.0

**Code to reproduce:**

```ts
export default response => Observable.if(
  () => response.xhr.responseURL.indexOf(URL_PART) !== -1,
  Observable.throw('redirect'),
  Observable.of(response.response),
);
```

**Expected behavior:**
return response or redirect (works fine in ff and chrome)

**Actual behavior:**
"Exception thrown and not caught" in file Observable.js, line 165 in IE11

There is any other way to get response URL on IE11? Or Someone see something wrong in my code? I tried babel-polyfill but still same error.

**Comment by JacobChang** [comment]
The problem is IE11 and old Edge don't have responseURL property on XMLHttpRequest object. Lots of frameworks will use request url as a fallback, but this will fail when 30x redirects happens.  The only reliable solution maybe is the backend server set some custom header to indicate response url, so I don't think rxjs need to solve this

**Comment by benlesh** [comment]
I agree. This isn't something we can fix on the RxJS side.
