### ISSUE TITLE
Why there are no result after `CombineLatest` like this?

### ISSUE THREAD

**Issue by mimoning** [ReactiveX/rxjs#3574]
Just like demo2, I don't know what's the difference between demo1 and demo2? Why there is no result by demo2?

**RxJS version:**
5.3.0

**Code to reproduce:**
demo1:
```javascript
const a$ = new Rx.BehaviorSubject(1);
const b$ = new Rx.Subject();
b$.combineLatest(a$).subscribe(console.log);
b$.next(1);
```
demo2:
```javascript
const a$ = new Rx.BehaviorSubject(1);
const b$ = new Rx.Subject().combineLatest(a$);
b$.subscribe(console.log);
b$.next(1);
```

**Expected behavior:**
demo1:  [1,1]
demo2: [1,1]

**Actual behavior:**
demo1: [1,1]
demo2: nothing

**Additional information:**

**Comment by ibedard16** [comment]
Shouldn't `b$` be an observable, since it's being set to the return result of `combineLatest()`?

You may need to do something like

**Comment by mimoning** [comment]
I think you are talking about the thing what `demo1` did. @ibedard16 
But my point is, why they are different?

**Comment by ibedard16** [comment]
The second example is different because `b$` is set to the return value of `combineLatest()` in the second example - which is an observable, not a subject. So, the `b$.next()` call doesn't actually do anything - it even generates a type error when using `rxjs` with `Typescript`. 

In order for `combineLatest()` to fire, all of the observables provided to it need to have fired at least once. In the second example, the `Subject()` never emits anything - so anything watching the `b$` observable will never fire.

**Comment by mimoning** [comment]
OK, Thank you very much! I got your point! @ibedard16

**Comment by cartant** [comment]
Actually, the problem is rather subtle and I'd say it's a bug, but perhaps not a particularly high-priority one.

`Subject` implements `lift` so the return value from the `combineLatest` operator will actually be a `Subject` instance - it's just that this cannot be represented with the TypeScript types.

With this code:

```js
const a$ = new Rx.BehaviorSubject(1);
const b$ = new Rx.Subject().combineLatest(a$);
console.log(`b$ instanceof Rx.Subject = ${b$ instanceof Rx.Subject}`);
b$.subscribe(console.log);
b$.next(1);
```

the output will be:

```
b$ instanceof Rx.Subject = true
```

So `b$` is a `Subject` and `next` can be called.

If you look at the [implementation of `Subject.lift`](https://github.com/ReactiveX/rxjs/blob/5.5.10/src/Subject.ts#L46-L50), you'll see that an `AnonymousSubject` is returned. Note that `this` is passed to the `AnonymousSubject` constructor as the `destination`.

The [implementation of `AnonymousSubject.next`](https://github.com/ReactiveX/rxjs/blob/5.5.10/src/Subject.ts#L141-L146) calls `destination.next` if it's defined. Otherwise, it does nothing.

The problem is effected because the [implementation of `combineLatest`](https://github.com/ReactiveX/rxjs/blob/5.5.10/src/operators/combineLatest.ts#L87) doesn't pass the source - the `Subject` - as the context for the `lift` call; it passes another observable and that observable has no `next` method, so nothing happens when `next` is called.

Not all operators are implemented this way. For example, if the `delay` operator is used instead, it will work as you'd expect. The following will write `1` to the console:

```js
const c$ = new Rx.Subject().delay(0);
c$.subscribe(console.log);
c$.next(1);
```

**Comment by mimoning** [comment]
OK, I understand. It seems that I need to learn more about the internal implementation of RxJS. Thank you very much! @cartant
