### ISSUE TITLE
About LTS

### ISSUE THREAD

**Issue by wKoza** [ReactiveX/rxjs#3672]
Suppose I use Angular 5 that is now in LTS. It is January 2nd, 2019 and a critical security vulnerability is detected on _RxJS 8.1.0_ (but that was already present in rxJS 5.5). Maybe _RxJS 8.1.1_ will not be compatible with Angular 5, I don't know...
What will happen then? Is there a plan for this? Will RxJS have an LTS?
//cc @benlesh @IgorMinar

**Comment by benlesh** [comment]
There is no RxJS 8.1.1 ...

**Comment by IgorMinar** [comment]
While possible, it's highly unlikely that such critical security vulnerability will be discovered in a library like RxJS because it has very limited interaction with DOM and [doesn't use `eval`](https://github.com/ReactiveX/rxjs/blob/e91d113e49acc9b0e12e2524040fa84cf3fa2c78/.eslintrc#L71) anywhere in the code base.

Even though it's unlikely, if this situation does indeed happen, we'll evaluate it and determine the right course of action.

RxJS is run as a project independent of Angular, so the Angular team is not at the moment comfortable providing an absolute guarantee in the form of extending Angular LTS to RxJS, but rest assured that we won't stand still should Angular users be affected.

**Comment by wKoza** [comment]
Ok @IgorMinar , Thanks for the clarification. Of course, the problem isn't specific to RxJS (even if it's the more represented in an application), it's a general problem.

Let's the topic open to know the policy of LTS on RxJS

**Comment by kwonoj** [comment]
It's opened for a long time without active discussion, I'm going to close for now.

In short, RxJS itself doesn't have documented policy around `lts` support. It'll be judged per-cases by time we'll have actual incident with multiple version we need to support at the time of fix required. As mentioned already, rxjs itself have very limited surface of attack so generally we don't expect security update will happen frequently.
