### ISSUE TITLE
Subscription undefined when trying to unsubscribe from BehaviorSubject

### ISSUE THREAD

**Issue by Katur7** [ReactiveX/rxjs#3689]
**RxJS version:**
6.1.0
**Code to reproduce:**
[https://stackblitz.com/edit/typescript-dap5kd](https://stackblitz.com/edit/typescript-dap5kd)

**Expected behavior:**
subscribe() should always return a subscription that can be used to call unsubscribe()

**Actual behavior:**
Calling unsubscribe() only works the first time. The second time I get an error, "Cannot read property 'unsubscribe' of undefined". It works if I wait 1 ms before calling unsubscribe() with setTimeout().

**Comment by martinsik** [comment]
I don't think this is a bug but just a little clumsy usage of `BehaviorSubject`. 

When you call `waitUntilOne()` after `subject.next(1)` it subscribes to `subject` but since this is `BehaviorSubject` it immediatelly emits its stored value which is `1`. This happens inside `subject.subscribe` but at that point `subscribe` function hasn't finished yet so it couldn't return anything to be assigned to `const subscription`.

For the same reason it works with `setTimeout` because it lets `subscribe` finish and return an unsubscription object and then calls `ubscription.unsubscribe()` in another JS frame.

**Comment by cartant** [comment]
@Katur7 As Martin has pointed out, the problem is due to attempting to unsubscribe upon the synchronous emission of a value. There is a mechanism for doing this using the `this` context with which the callback passed to `subscribe` is called:

```js
source.subscribe(function (value) {
  if (/* something */) {
    // This will unsubscribe even if the source emits a value synchronously:
    this.unsubscribe();
    return;
  }
  /* ... */
});
```

However, you'd likely be better off implementing it using `takeWhile` or something similar.

IIRC, there's a recent issue where this was mentioned/discussed. I'll see if I can find it.

**Comment by cartant** [comment]
@Katur7 See [this comment](https://github.com/ReactiveX/rxjs/pull/3230#issuecomment-361113247) from Paul Taylor.

**Comment by Katur7** [comment]
Thank you. I did not know I could do that with RxJs. I will close this issue.

I ended up with this:
```
function waitUntilOne() {
  return new Promise((resolve) => {
    subject.pipe(
      first(x => x === '1')
    ).subscribe(() => resolve());
  });
}
```
