### ISSUE TITLE
Strange behavior with `merge`, `switchMap` and `catchError`

### ISSUE THREAD

**Issue by iget-master** [ReactiveX/rxjs#3754]
**RxJS version:** 6.2.0

**Code to reproduce:**

    merge(this.subjectA.asObservable(), this.subjectB.asObservable())
      .pipe(
        startWith(0),
        // My provider parses the value, but only accepts positive numbers, throwing errors when negative.
        switchMap((value) => { return this.someProvider.willFailWithNegativeNumbers(value); })
        // I don't want the user know this error, so I will just return an empty result
        catchError(() => { return observableOf([]); })
      )
      .subscribe(result => { console.log(result); }
    
    this.subjectA.next(1);
    // will console log some valid result, [ ... ]
    this.subjectA.next(-1)
    // will console log the expected empty array []
    this.subjectA.next(1);
    // will not enter in the subscribe.

See this stackblitz: https://stackblitz.com/edit/rxjs-yz1cqh?file=app/hello.component.ts

Load console to see the problem!
Note that I emit values for the observable 3 times, but only two of them works.
  
**Expected behavior:**

Since the failed call was catch, it should just keep working for subsequent emited values, right?

    this.subjectA.next(1); // [ ... ]
    this.subjectA.next(-1); // []
    this.subjectA.next(1); // [ ... ]

**Actual behavior:**

    this.subjectA.next(1); // [ ... ]
    this.subjectA.next(-1); // []
    this.subjectA.next(1); // nothing happens

**Additional information:**

**Comment by kwonoj** [comment]
No, 

This is common gotcha around catch operator and it can confuse time to time. Catch allows to handle error, but doesn't change nature of observable - error is terminal condition to given observable so emission will stop. Catch allows to emit desires value when it occurs instead of raising observer's error callback.

In here, catch is handled in main stream, so error raised in inner observable (in switchmap) bubbles up to main stream, substituted into handled value, then completes (stops). If you handle error in inner observable like 'switchmap(x => x.catch())' then error raised in innerobervable will not bubble up, so won't stop main observable.

**Comment by metasong** [comment]
@kwonoj , you are right!!
with you clue, i found a solution to do error handling at the end ot the pipe operators:
instead of write:
```js
    catchError(() => { return of(obj); })
```
we should write:
```js
    map(o=>obj), // or other operators
    catchError(err,caught)=>{ return caught;} //return the caught observable to retry.
```
