### ISSUE TITLE
comprehensive marble tests for window

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#376]
Should duplicate the current RxJS 3/4 tests

Should adhere to our contribution guidelines and operator authoring docs.

**Comment by staltz** [comment]
I can take this one.

**Comment by staltz** [comment]
I'm almost done with this. Now I'm adding tests for the basic cases (empty, never, etc), but since these cases are not specified in RxJS legacy tests, I actually don't know what to expect.

E.g. is this what we should expect?
```js
  it('should return empty Observable if source is empty and closings are basic', function () {
    var source = cold('|');
    var closings = cold('--x--x--|');
    var expected = '|';

    var result = source.window(closings);

    expectObservable(result).toBe(expected);
  });
```

The actual execution is:
```js
  it('should return empty Observable if source is empty and closings are basic', function () {
    var source =   cold('|');
    var closings = cold('--x--x--|');
    var expected =      '(w|)';
    var w =         cold('|');
    var expectedValues = { w: w };

    var result = source.window(closings);

    expectObservable(result).toBe(expected, expectedValues);
  });
```

**Comment by staltz** [comment]
This one can be closed.

**Comment by staltz** [comment]
@blesh some input here would be good. (RxJS legacy tests don't specify the following, by the way)

This tests passes for `window`:
```js
  it('should return a single empty window if source is empty and closing is empty', function () {
    var source =   cold('|');
    var closings = cold('|');
    var expected =      '(w|)';
    var w =         cold('|');
    var expectedValues = { w: w };

    var result = source.window(closings);

    expectObservable(result).toBe(expected, expectedValues);
  });
```

This test passes for `windowCount`:
```js
  it('should return a single empty window if source is empty', function () {
    var source =   cold('|');
    var expected =      '|';

    var result = source.windowCount(2, 1);

    expectObservable(result).toBe(expected);
  });
```

Notice the inconsistency: one returns an empty observable, the other returns an observable with one window, and the window is empty.

We should probably try to make these uniform across the variants of window, otherwise people can get quite confused for no good reason. But to which direction? Should we prefer `|` or `(w|)`?

**Comment by staltz** [comment]
Ok, I now discovered by trying out code in JSBin that RxJS legacy does this:

```js
var source = hot('^----a--b--c--d--e--f--|');
var expected =   '-----x-----y-----z-----|';
var x = cold(    '-----a--(b|)            ');
var y = cold(               'c--(d|)      ');
var z = cold(                     'e--(f|)');
```

RxJS Next does this:
```js
var source = hot('^----a--b--c--d--e--f--|');
var expected =   '-----x-----y-----z-----|';
var x = cold(         'a--(b|)            ');
var y = cold(               'c--(d|)      ');
var z = cold(                     'e--(f|)');
```

I'd consider RxJS Next's `windowCount` behavior a bug, because it's inconsistent with RxJS legacy and also with Next's `window` and `windowTime`.

I think this issue can be closed, because the bug is related to #378.

**Comment by blesh** [comment]
> I'd consider RxJS Next's windowCount behavior a bug

I completely agree, and I wrote it. I think I was working with `bufferCount` in mind, or perhaps I was trying to be too efficient.

This test would fail with RxJS 5, and it shouldn't. (It's probably worth adding for that reason alone)

```js
var source = hot('^----a-----');
// windowCount(2,1)
var expected =   'x----------';
var x = cold(    '-----a-----');
```

**Comment by blesh** [comment]
Or testing against `Observable.never()`... again... that would probably fail in RxJS 5 right now.

```js
var source = Observable.never();
// windowCount(2,1)
var expected =   'x----------';
var x = cold(    '-----------');
```

**Comment by staltz** [comment]
Please close
