### ISSUE TITLE
Upgrade Shared Lib to rxjs 6, still support rxjs 5?

### ISSUE THREAD

**Issue by alandsverk** [ReactiveX/rxjs#3762]
I couldn't think of a concise way to write the title. Is it possible for me to upgrade a shared library to RxJS 6.x but still be able to support Angular apps running on RxJS 5.x?

**Comment by kwonoj** [comment]
Not sure if I understood question correctly. Are you saying you have ng app depends on v5, while some other dep you use depends on v6?

**Comment by alandsverk** [comment]
I have application A, which is on rxjs 5.x. I want to upgrade my shared library (separate from the application A) to rxjs 6.x. 

Can I use the upgraded library with application A (which is still on rxjs 5.x)?

**Comment by kwonoj** [comment]
>  I want to upgrade my shared library (separate from

This is part I was not getting it correctly I guess. You mentioned it's shared but separate from application - what is exactly shared? how does dependency is organized? 

```
Application(A)
|
- SharedLib
|      |
|      - Rx v6
- Rx v5
```

is this correct?

**Comment by alandsverk** [comment]
Oh sorry.

Application(A)
|
- Rx v5

SharedLib
|
- Rx v6

I want to use SharedLib inside Application(A).

**Comment by kwonoj** [comment]
So for these cases, there's no immediate answer like it'll work or not (while it's likely possible some problem might occur if application have interop observable instance between app to lib). It depends on some conditions like how lib / app is bundled, if observable instance is passed between those 2 different versions (this is part probably will break), if there's import paths being shared, etcs.

rxjs-compat pkg in v6 will try to make most things compatible, but since application is running on v5 it can't know what's changed in v6 and you may need to adjust those differences.

**Comment by alandsverk** [comment]
Thanks for the response!
