### ISSUE TITLE
Rxjs use of instanceof breaks subscription with multiple bundles

### ISSUE THREAD

**Issue by Avocher** [ReactiveX/rxjs#3828]
## Bug Report

**Current Behavior**
Hi, we are building a components that exposes rxjs observables for plugins to connect to. Our component is primarely used prebundled, which means that our plugin creators might have double of some parts of rxjs. Though, somewhat wastefull this worked fine with rxjs 5, but after upgrading to rxjs 6, things started breaking in Firefox and Chrome Canary 69. Here's the error message they get when trying to subscribe:
```
TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
```
Which pointed at the subscribeTo function, where I suspect that this line is the culprit: https://github.com/ReactiveX/rxjs/blob/80ceea00cc86b8634047ad0201a90115ce97bb34/src/internal/util/subscribeTo.ts#L15

`instanceof` seems to be a bit unreliable and appears to work differently under the hood in each browser, especially if the class appears twice and originated from the same source.

**Reproduction**
1. Create two bundles referencing rxjs 6.2.0, one exposing an observable, another subscribing to it and using its own operators. 
2. Try to subscribe.

**Expected behavior**
Should subscribe since there is nothing (?) stopping it from doing so.

**Environment**
- Chrome 69 & Firefox 60
- RxJS version: 6.2.0

If anyone knows a workaround I'd be happy with that, since I know some would probably regard this as a non-issue.

**Comment by benlesh** [comment]
It sounds like you're bundling two instances of RxJS. That's not going to be good for your app size. Your libraries shoudl have RxJS as a peer dependency, and that will solve the problem most likely.

However, there are workarounds:

1. Load a polyfill for Symbol.observable.  RxJS 5 used to polyfill it for you. RxJS 6 doesn't, because libraries shouldn't be doing that. If `Symbol.observable` is present, then each copy of RxJS will coerce to it's own Observable type using that.

2. Use a `from` call to wrap observables you think come from other libraries.


... but the real solution here is that you'd want RxJS to be a peer dependency.

**Comment by benlesh** [comment]
We might start using our `isObservable` implementation internally, and they could solve this issue, but it's also sort of a smell in the usage here. We'll discuss it at the next core team meeting.

**Comment by Avocher** [comment]
Thank you for the help Ben! Yes, our current setup isn't ideal. Your suggestions will have to serve as a band aid for the time being until we get our distribution setup sorted out.

**Comment by benlesh** [comment]
After some discussion with the team today, we've decided to leave the `instanceof` checks as is. Because:

1. There are performance implications of moving away from `instanceof` checks
2. The work around is as easy as polyfilling `Symbol.observable`.
