### ISSUE TITLE
Can't add properties to Observer's this from error/next/complete

### ISSUE THREAD

**Issue by Telem** [ReactiveX/rxjs#3871]
## Bug Report

**Current Behavior**
`this` is not correctly preserved when calling the `Observer.error` method. Presumably, this affects `next` and `complete` as well.

**Reproduction**
- REPL or Repo link: https://angular-nlbcya.stackblitz.io
Click the button and look at the console logs : `this` is not the same in the property accessor for `emittedError` and the `error` handling function.

**Expected behavior**
the `error` function should be called providing the object they were found on for `this`

**Environment**
- Runtime: Chrome
- RxJS version: 6.1.0

**Possible Solution**
not using Object.create [here](https://github.com/ReactiveX/rxjs/blame/df0ea7c78767c07a6ed839608af5a7bb4cefbde5/src/internal/Subscriber.ts#L194) ? I assume it was used to overcome side-effects elsewhere, as I didn't spot any modification of the context in the SafeSubscriber implementation ?
The change came [from this commit](https://github.com/ReactiveX/rxjs/commit/a1778e0dc6b8c3c41d06aa48b3bd72db51873b6d).

**Suggested Workaround**
(thanks to @cartant)
- Subclassing Subscriber instead of implementing Observer from scratch
- putting data that needs modifying in an Object sub-property of the observer

**Comment by cartant** [comment]
The `next`, `error` and `complete` callbacks are called with the `SafeSubscriber` as the context by design. See [this comment](https://github.com/ReactiveX/rxjs/pull/3230#issuecomment-361043385) and [this comment](https://github.com/ReactiveX/rxjs/pull/3230#issuecomment-361113247).

**Comment by cartant** [comment]
The call to `Object.create` appears to be used because an `unsubscribe` method is added to the observer. For the reason why, see [this comment](https://github.com/ReactiveX/rxjs/pull/3230#issuecomment-361113247).

The call to `Object.create` sees the passed observer used as the prototype for the object created for the `context`. That results in properties on the observer being accessible - via the `context`'s prototype - and methods on the observer being callable.

The use-the-observer-as-the-prototype mechanism should work fine for methods that don't mutate the observer, but I can see that for those that do mutate the observer, the mutation end up happening to an unexpected `this`.

You should be able to work around this be putting the `_error` and `_complete` properties in your `CollectingObserver` class inside another property. E.g. put them in `_workaround` property. When the observer is then used as a prototype, the `_workaround` property will be read via the prototype and the `_error` and `_complete` properties will be written to it - and not to the unexpected `this`.

I suspect the `_values` will work fine as-is, as it should be read via the prototype and then should have `push` called on it.

Hopefully, that makes sense.

**Comment by Telem** [comment]
Thanks for the details @cartant.
It can indeed be worked around (I went the "force a bind() on all methods of that object" route), or easily fixed by subclassing Subscriber. ([here a fork that works](https://stackblitz.com/edit/angular-q3qo17?file=src%2Fapp%2FCollectingObserver.ts))

I guess the best resolution for this is documenting on the Observer interface that users should create Subscriber subclasses whenever they need to use a mutable Observer ?

**Comment by cartant** [comment]
I don't think users should be encouraged to subclass `Subscriber`. In fact, the ability for users to do so should probably be removed.

Your doing so sees [this test](https://github.com/ReactiveX/rxjs/blob/6.2.1/src/internal/util/toSubscriber.ts#L12) pass in `toSubscriber` - which is called in [`subscribe`](https://github.com/ReactiveX/rxjs/blob/6.2.1/src/internal/Observable.ts#L196) - but that just circumvents all of RxJS's internal error handling. With `next`, etc. being reimplemented in the subclass, if an error is thrown, it won't be caught and won't be handled as an RxJS error notification, etc. Not good.

I don't think there is going to be a satisfactory resolution for this issue:

* mutating the observer is bad and I doubt that an efficient mutate-and-restore mechanism could be put in place (as the context would need to be mutated and restored before and after each method call).
* using the observer as the context's prototype works for most situations and only fails when a method assigns a property to `this`.

I think it might have to stay as-is, as an accepted quirk/bug.

At some stage - perhaps in the next release - it should no longer be necessary to have `unsubscribe` callable via `this` within a `next` handler. There has been some discussion, in other issues, about alternative methods of unsubscribing synchronously within `next`.

**Comment by kwonoj** [comment]
It's mostly answered, known behavior of not explicitly binding context into provided observers. We may revisit this later possibly, but nothing's concrete.
