### ISSUE TITLE
Direct subscribing to Subject does not receive piped values

### ISSUE THREAD

**Issue by echoes221** [ReactiveX/rxjs#3886]
## Bug Report

Found something odd with subscribing to `Subject`. I'm aware that subjects are meant to handle multiple subscribers, but this should still be a valid use case. Unsure if this is expected behaviour or not, if it is, please close ticket.

**Current Behavior**
When creating a `new Subject()` with a direct subscription on it, subscription does not receive piped values, only receives original `.next` value.

**Reproduction**
```js
import { Subject } from 'rxjs';
import { mapTo } from 'rxjs/operators';

const subject = new Subject().pipe(
  mapTo('bar'),
).subscribe(console.log);

subject.next('foo');
// --> incorrectly returns 'foo';

const subject1 = new Subject().pipe(
  mapTo('bar'),
);

subject1.subscribe(console.log);

subject1.next('foo');
// --> correctly returns 'bar'

```

**Expected behavior**
When creating Subject with direct subscription it receives piped values.

**Environment**
- Runtime: Chrome Latest
- RxJS version: v6.2.1

**Comment by cartant** [comment]
This looks, to me, to be the best expected behaviour. `subscribe` returns a `Subscription` - not a `Subject` - so you should not be calling `next` on it. `next` just happens to be callable because the subscription is a `SafeSubscriber` instance. With TypeScript, this code would effect a compile-time error.

**Comment by kwonoj** [comment]
@cartant is correct.

**Comment by echoes221** [comment]
@cartant Thanks!

**Comment by hitmands** [comment]
Hi, 
I'd like to better understand the idea of a `SafeSubscriber`, 
[why does it need to comply with the Observable contract](http://reactivex.io/RxJava/javadoc/rx/observers/SafeSubscriber.html) ?

Resources:
 - [The Observable Contract](http://reactivex.io/documentation/contract.html)

**Comment by cartant** [comment]
@hitmands The point of the `SafeSubscriber` is to wrap `try`/`catch` statement around caller-specified functions so that errors can be caught and can be reported via error notifications. And so that automatic unsubscription can be effected.

That's what's necessary to fulfil the Observable Contract.

Compare and contrast the `next`, `error` and `complete` implementations [in `Subscriber`](https://github.com/ReactiveX/rxjs/blob/6.2.1/src/internal/Subscriber.ts#L93-L153) with those [in `SafeSubscriber`](https://github.com/ReactiveX/rxjs/blob/6.2.1/src/internal/Subscriber.ts#L208-L266). (When doing so, it's simplest to ignore the deprecated, synchronous error handling.)

Note also that a `SafeSubscriber` is used [only when necessary](https://github.com/ReactiveX/rxjs/blob/6.2.1/src/internal/Subscriber.ts#L72-L84).
