### ISSUE TITLE
TestScheduler cold() values and errors parameters are type any

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/rxjs#3921]
## Bug Report

**Current Behavior**
https://github.com/ReactiveX/rxjs/blob/41107115355eaaba7b6545c68e0655da3d56c57b/src/internal/testing/TestScheduler.ts#L48

Using the TestScheduler for the first time, I don't understand what these parameters accept. The documentation doesn't mention it either: https://github.com/ReactiveX/rxjs/blob/master/doc/marble-testing.md#api

What are they?

**Expected behavior**
I expect them to have a type declaration

**Environment**
- RxJS version: 6.2.2

**Comment by kwonoj** [comment]
it's this:
https://github.com/kwonoj/rx-sandbox/blob/master/src/scheduler/TestScheduler.ts#L77

`value` is `Record<string, T>` type where T is typeof value you'd like to specify, `error` is literrally `any`.

For example, say have marbles
`---a---b---c---#--`
and would like to have corresponding value to `a: 1, b: 2, c: 3`, and raise error to something like `boo!`

then 
`values: { a: 1, b:2, c:3 }, error: 'boo!'`

it can be bit improved (`values` specifically), otherwise need some documentation around usages.

**Comment by kwonoj** [comment]
hmm expected link to unfurl.

```
public createColdObservable<T = string>
(marble: string, value?: { [key: string]: T } | null, error?: any): ColdObservable<T>;
```

**Comment by felixfbecker** [comment]
Is there any reason why it's not typed like that?

**Comment by felixfbecker** [comment]
`key` could be named `marble` for extra clarity

**Comment by kwonoj** [comment]
just old legacy. reason I made typed for my codes when I wrote it. Test cases written at the moment already, so haven't take deep look around types afaik.

**Comment by felixfbecker** [comment]
Btw, I just realised if the diagram was an array instead of a string, we could actually make it type safe:
```ts
public createColdObservable<T = string, M extends string>
(marbles: (M | '#' | '-')[], values?: Record<M, T>, error?: any): ColdObservable<T>;
```
Would ensure that `values`, if provided, contains exactly one entry for every letter in the `marbles` array.
