### ISSUE TITLE
Doc pages missing / misleading directions in README?

### ISSUE THREAD

**Issue by robations** [ReactiveX/rxjs#3953]
### Documentation Related To Component:

RxJS

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist OR
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

In the doc/README.md page it says:

> These files are not meant for reading directly in GitHub, they are just source code for generating the official page. You should find the docs at http://reactivex.io/rxjs/, containing all the documentation.

However, either most pages in the doc/ directory are missing from the reactivex.io site, or they're really hard to find. For example, I was looking for a page to match "writing-marble-tests.md" but can only see: Overview, Installation, Migration and the auto-generated API docs.

Would guess either:

- README.md is wrong — you are better off reading directly in GitHub at the moment;
- Some work needed to add these files to the docs site; or
- The docs are there somewhere and navigation can be improved.

Sorry if this is in the wrong place or a duplicate, I spent a few minutes looking through existing bugs open and closed but didn't see anything similar.

P.S. It seems like the doc/ folder is in the process of being phased out in favour of the work in docs_app/ ? Might suggest a note is added to clarify.

**Comment by mattyao1984** [comment]
@JWO719 please check this issue and let me know anything I can help with.

**Comment by JWO719** [comment]
Hi @robations, so basically we are currently reworking the documentation. And yes you are right, docs_app is what we label "new docs". We don't want to migrate all the stuff, because many of those are outdated, or not easy to understand and stuff like that. But at this moment it would be really helpfull if you could say what you are struggeling with/ searching for so that we can cover those parts in some kind of tutorial or something likewise. Is there anything else the new docs "http://rxjs-dev.firebaseapp.com/" could help you with this issue?
Regarding the reactivex.io page. I think the root will redirect to the "new docs" but if you directly try to open some of the urls this should work.

**Comment by JWO719** [comment]
So personally improving the developer experience is my main goal, therefore I try to improve the documentation :D So thank you very much for this valuable feedback, I'll take care of it

**Comment by ajcrites** [comment]
@JWO719 are there plans to migrate particular pages? The current docs are missing a lot of the useful "Overview" pages including the Observable and Subject (e.g. https://github.com/ReactiveX/rxjs/blob/master/doc/subject.md). I would like to help to update some of these documentation pages to new examples, but I'm not sure of the progress on that or whether there are plans to do away with some of these pages.

**Comment by JWO719** [comment]
It is planed to migrate those informations to the new docs. I think we actually didn't started with that. So there are a lot of pages to migrate :) I would really welcome any contributions on that. If you need help with that, just ping me. I'm always glad to help.

**Comment by BioPhoton** [comment]
@JWO719 as the PR is merged we could close this issue

**Comment by robations** [comment]
Looks good to me.
