### ISSUE TITLE
TestScheduler subscriptions log - incorrect unsubscription

### ISSUE THREAD

**Issue by TPReal** [ReactiveX/rxjs#3955]
## Bug Report

**Current Behavior**
Sometimes `expectSubscriptions` counts unsubscriptions incorrectly. I don't know what is the general rule when the incorrect behaviour occurs, please see the example.

**Reproduction**
https://stackblitz.com/edit/rxjs-testscheduler-unsubscribe-bug?file=index.ts

```js
const doNotUnsubscribe = (source: Observable<any>) => {
  return new Observable<any>(subscriber => {
    const sourceSub = source.subscribe(subscriber);
    return { unsubscribe: () => { } };
  });
};

testScheduler.run(({ cold, expectSubscriptions }) => {
  const source = cold(' --b----|');
  const unsub = cold('  ----u')
  const expSourceSub = '^------!';
  source.pipe(doNotUnsubscribe, takeUntil(unsub)).subscribe();
  expectSubscriptions(source.subscriptions).toBe(expSourceSub);
});
```
The test fails: ```Actual: [{"subscribedFrame":0,"unsubscribedFrame":4}], expected: [{"subscribedFrame":0,"unsubscribedFrame":7}]```, which means that source is unsubscribed from at `unsub`, even though this should be blocked by the operator.

**Expected behavior**
The source is passed through `doNotUnsubscribe` which should prevent it from ever being unsubscribed, or at least it should prevent it from being unsubscribed from until the source finishes. So I expect that either this test passes, or a test with `expSourceSub = '^-';` should pass (i.e. never unsubscribe).

**Environment**
- RxJS version: 6.2.2

**Additional context/Screenshots**
Implementation of `ColdObservable` seems to operate with subscriptions in some strange way. I would expect it to call its own `subscribe` and then return a wrapper around unsubscribing somehow. I don't understand what it actually does, but it looks to me that it's a hack that breaks sometimes.

**Comment by benlesh** [comment]
This actually doesn't have to do with the test scheduler... in the name of efficiency, for RxJS 5 and 6, we bound the Subscriber directly to the Subscriptoin, so that it basically threads one Subscriptoin through the entire chain.

In order to break that chain, you'll need to implement your `doNotUnsubscribe` such that it doesn't subscribe directly with the subscriber (because then it's detected and threads through).

I'm going to see what I can do to fix this for v7, because I agree it's confusing, if a bit corner-casey.

[Here is a demo](http://jsbin.com/wusiyo/edit?js,console,output)

```ts
const doNotUnsubscribe = () => source => new Observable(subscriber => {
  source.subscribe({
    next(x) { subscriber.next(x); },
    error(err) { subscriber.error(err); },
    complete() {
      subscriber.complete();
    }
  });
});
```

I hope that helps.
