### ISSUE TITLE
[Docs] RxJS is still too big

### ISSUE THREAD

**Issue by bcherny** [ReactiveX/rxjs#4011]
## Bug Report

**Current Behavior**

Importing `Observable` from RxJS pulls in 12kb of code after Uglifying and Gzipping, when compiling to a CommonJS module:

```ts
import {Observable} from 'rxjs'
```

```sh
webpack -p && cat ./test-minify/bundle.js | gzip | wc -c # 12234
```

Importing the internal type instead, the size drops to a more manageable <4kb:

```ts
import {Observable} from 'rxjs/internal/Observable'
```

```sh
webpack -p && cat ./test-minify/bundle.js | gzip | wc -c # 3671
```

**Reproduction**

https://github.com/bcherny/typed-rx-emitter/commit/50a457d296bad3d32608b257b52f294cec3c8ba1#diff-ed009b6b86b017532ef0489c77de5100R2

`yarn test`

**Question**

Reading all the RxJS docs, the canonical way to pull in `Observable` is straight from `rxjs`. However, unless you're compiling to ES2015 modules, this surprisingly pulls in a lot of unexpected code.

`/internal/Observable` does not seem to be documented, and it seems wrong to rely on it. As the path name implies, it's an implementation details that might change in the future.

What this means is that those of us that are still using CommonJS for whatever reason see really big bundle sizes.

So - What's the correct path to import `Observable` from, if you're using CommonJS?

**Comment by pertrai1** [comment]
@cartant would you be able to give feedback to this question?

**Comment by kwonoj** [comment]
Answer in here for v6 is let webpack or other bundler properly tree shaking it, i.e in given config (https://github.com/bcherny/typed-rx-emitter/commit/50a457d296bad3d32608b257b52f294cec3c8ba1#diff-d901c9ce0f05c56372ba31dd2215b7b7R17) it should be able to specify webpack / ts-loader uses `esNext` to enable treeshaking via rxjs's esm module, instead of transpiling whole ES2015 modules. ESM doesn't add burden to transpile module under `node_modules` but enables tree shaking correctly, which aim to solve this specifics.
