### ISSUE TITLE
shareReplay test has a questionable expectation

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#4117]
## Bug Report

**Current Behavior**

Ben has pointed out that [this test](https://github.com/ReactiveX/rxjs/blob/514a870de5e510e68794524d8996dac0382a9b4b/spec/operators/shareReplay-spec.ts#L145) includes a questionable expectation:

>if `retry` gets notified of two errors, then it should forward the error along to the third subscription

Figure out exactly what is going on and what the expected behaviour should be.

**Comment by benlesh** [comment]
So the explanation for this one is a bit hard to understand I think:

1. The first two subscriptions occur during the first shared subscription, they each have their own retry.

```
    const subscriber1 = hot('a|                                ').pipe(mergeMapTo(shared));
    const expected1   =     '-1-2-----3--1-2-----3-#           ';
    const subscriber2 = hot('    b|                            ').pipe(mergeMapTo(shared));
    const expected2   =     '    (12)-3--1-2-----3-#           ';
```

2. The third subscription occurs during the shared subscription that belongs to the retry from the first two... and that third subscription, itself, has it's own retry.

```
    const subscriber3 = hot('               (c|)               ').pipe(mergeMapTo(shared));
    const expected3   =     '               (12)-3--1-2-----3-#';
```

This is expected behavior, but perhaps the test isn't super readable? Either way, there's no issue here, so I'm going to close this.
