### ISSUE TITLE
Publish as rxjs to npm?

### ISSUE THREAD

**Issue by robwormald** [ReactiveX/RxJS#419]
Appears to be available, and the `@reactivex/rxjs` namespace is kind of annoying to work with (in regards to tooling and such). I realize that's not exactly the most descriptive issue, but I'll happily expand if need be. The namespace makes sense for something like `@cycle/core` where there's multiple packages under a namespace, but as far as I can tell, there's only ever going to be rxjs. 

Sorry.

**Comment by blesh** [comment]
@robwormald I think this is going to be an issue that remains open for some time... There is more to work out with @mattpodwysocki and friends.

Theoretically, though, we could publish to the same npm, it's just that I *think* `package.json` only allows for one repository field. So it might be best to wait until 5.0.0 is out of beta.

**Comment by staltz** [comment]
We could either close this issue or tag it as discussion.

**Comment by cwmrowe** [comment]
I cannot install ```@reactivex/rxjs``` via [Artifactory](https://www.jfrog.com/open-source/) and I suspect it is because of the @ symbol but it could equally be the forward slash. NPM install also failed for ```@cycle/core```.

While this is probably a problem with Artifactory it might be better for the community to solve this problem here.

**Comment by robwormald** [comment]
@cwmrowe generally that means you (or artifactory) is using an older version of NPM that doesn't support namespacing. Might want to see about upgrading.

**Comment by cwmrowe** [comment]
@robwormald thanks for your help. Now I know its related to scoped packages I have discovered that Artifactory has an issue with the forward slash. The [fix is here](https://www.jfrog.com/confluence/display/RTF/Npm+Repositories#NpmRepositories-NpmScopePackages) for others that hit the same problem.

**Comment by blesh** [comment]
@cwmrowe thanks for posting the fix for Artifactory for others that arrive here. If you use StackOverflow at all, it might be worth posting a community wiki question and answer there, as it might help people find the answer they're looking for faster.

As for this issue, I think I'm going to close it, as it's not really an "issue" with the library at this time.
