### ISSUE TITLE
pipe() has an apparent limit of 9 operators (TypeScript)

### ISSUE THREAD

**Issue by jamespearce2006** [ReactiveX/rxjs#4221]
I've just upgraded my project from rxjs 6.2.2 to 6.3.3, and a couple of my longer pipes are now throwing a compiler error of the form:

```error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<boolean>'. Type '{}' is not assignable to type 'boolean'.```

After some trial and error, I discovered it seems to happen with any pipe that has more than 9 operators. For example, the following typescript has the problem:

```ts
    public samplePipeline(): Observable<boolean> {
        return of(true).pipe(
            tap(b => { }),
            tap(b => { }),
            tap(b => { }),
            tap(b => { }),
            tap(b => { }),
            tap(b => { }),
            tap(b => { }),
            tap(b => { }),
            tap(b => { }),
            tap(b => { })
        );
    }
```

Remove one of the tap operators, and the compiler error goes away. 

I'm compiling with Typescript 2.7.2, but have also tried 2.9 and 3.0.
Rxjs version is 6.3.3

**Comment by cartant** [comment]
This is by design. Once you have more than 9 operators a rest parameter is used, the inference between consecutive parameters stops, and `pipe` returns `Observable<{}>`.

If you use more than 9 operators, you will need to use a type assertion to indicate the `Observable` type. E.g. `as Observable<Boolean>` in your snippet.
