### ISSUE TITLE
[support] Spying on `observableThrowError` - unit testing

### ISSUE THREAD

**Issue by whyboris** [ReactiveX/rxjs#4225]
Previously in _RxJS_ 5 in our file: `service.ts` we had:
```js
import { Observable } from 'rxjs/Observable';

// in our method we had:
return Observable.throw({ error: 'lol' });
```
Using _Jasmine_ it was tested `service.spec.ts` thus:
```js
spyOn(Observable, 'throw');

// in the test
expect(Observable.throw).toHaveBeenCalledWith({error: 'lol'});
```

Now with _RxJS_ 6 our file `service.ts` has:
```js
import { throwError as observableThrowError } from 'rxjs';

// in our method we have:
return observableThrowError({ error: 'lol' });
```

But how do you spy on `throwError` or `observableThrowError`? 😖

**Comment by jgbpercy** [comment]
Obviously I can't see all of your code in context there, but I believe it would be better to test that the Observable your service returns throws, rather than testing that the throw method was called. It seems like you're testing an (RxJS v5 dependent) implementation detail of your service rather than the actual result you want from your service?

So the jasmine test that does what you want it to under RxJS 6 would look something like
```
it('should throw an error', (done: DoneFn) => {
  serviceUnderTest.methodThatReturnsThrowingObs().subscribe({
    error: (err) => {
      expect(err).toEqual({ error: 'lol' });
      done();
    }
  })
});
```
(didn't write that code in an editor, may contain typos!)

Also, while I'm not a maintainer here, I believe that somewhere like Stack Overflow is a better place 'how to' for queries like this (mainly in that you are likely to get more eyes on the problem and a faster answer).
