### ISSUE TITLE
Unable to combine streams of objects into an array.

### ISSUE THREAD

**Issue by phantomodm** [ReactiveX/rxjs#4269]
## Bug Report

**Current Behavior**
I am attempting to convert of objects, flatten them into an array of objects. However prior rxjs version that would flat and combine does not work in new version
```
flatMap(results => Observable.combineLatest(results))

```
Now that combineLatest is no longer an operator, the equivalent would be:

```
const original$ = observable.pipe( 
    map( result => result.map(queryThatReturnObject.pipe(
      map(r => Object.assign( { key: r.obj, ...r.val() } ) ),
    );
const final$ = combineLatest(original$);

return final$;
```
But this does not work.

**Reproduction**
- REPL or Repo link:
(you can use https://stackblitz.com/ to create one to attach here)

[Stackoverflow post](https://stackoverflow.com/questions/52837165/combine-angular6-rxjs-observable-stream-from-angularfire5?noredirect=1#comment92623264_52837165)

[Stackblitz - Angular service code](https://stackblitz.com/edit/vendor-app-a9wcu8?file=src%2Fapp%2Fcore%2Fservices%2Forders.service.ts)

[Stackblitz - Frontend html that corresponds with problem code](https://vendor-app-a9wcu8.stackblitz.io/orders/101)

[Stackblitz - Angular component ](https://stackblitz.com/edit/vendor-app-a9wcu8?file=src%2Fapp%2Fdashboard%2Forders%2Forder-detail%2Forder-detail.component.ts)

```
return order$.pipe(
      switchMap(result => 
       this.db.list('productsPerOrder/'+ result.key).snapshotChanges().pipe(
         map(res => res.map(c => ({key: c.key}))),
      )),
      take(1),
      map(result => result.map(result => 
        this.db.object('incoming_order_details/' + result.key).snapshotChanges().pipe(
          distinctUntilChanged(),
          map(action => Object.assign( {key: action.key, ...action.payload.val()} ) )
        ).subscribe(items => {console.log(items)}))
      ), // Subscribe call to console, shows the objects correctly
      mergeMap(results => results),
      tap(console.log)    
    );

//Console logs tap(console.log):
[Subscriber, Subscriber, Subscriber, Subscriber,]
```

**Expected behavior**
In prior
```
//From Stream:
{ order:1, option_value:"a"}
{ order:2, option_value:"a"}

//To:
[{
 order: 1,
 option_value: "a"
},
{
 order: 2,
 option_value: "a"
}]
```
I can then ngFor against the property subscribed to the stream. 

**Environment**
- Runtime: Angular 6
- RxJS version: 6.2.2
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jgbpercy** [comment]
I'm not trying to be rude, just to offer some constructive feedback, but I've read both this post and the Stack Overflow and I'm having a hard time understanding exactly what it is you're asking, what used to work (under which rxjs version) and what doesn't work now. It seems like folks on SO are having similar issues too... Maybe try to pinpoint exact what the issue is, and post some code that is as minimal as possible while still showing the problem you're having.

However, I *think* you're under the impression that combineLatest no longer exists in rxjs 6, and you're trying to implement a replacement? That isn't the case! combineLatest is alive and well, but all of the 'creation functions' (I think that's the right terms for them) like of, combineLatest, forkJoin, zip that used to be static methods on Observable are now standalone functions, which are just imported from just 'rxjs'.

So if you previous had code that looked like:
```
import { Observable } from 'rxjs/Observable';
// ...
  flatMap(results => Observable.combineLatest(results))
// ...
```

You now want some code that looks like:
```
import { combineLatest } from 'rxjs';
// ...
  flatMap(results => combineLatest(results))
// ...
```

Hope this helps!

**Comment by phantomodm** [comment]
@jgbpercy 

Hello Joe,

Thanks for reply.. I've been working from Stackblitz using rxjs 6,2 and yes, I'd been trying the same combineLatest statement as restated, but it was not working..

In the meantime after I posted.. I prepped a new environement with 6.1 and the rxjs-compat libraries and on the first try all worked..

I rebuilt on stackblitz with 6.1 and 6.3.3 versions and it worked..   Something was just wrong with the environment.

Growing pains.. Apologies and thanks.
