### ISSUE TITLE
Transfer Operators Guide

### ISSUE THREAD

**Issue by JWO719** [ReactiveX/rxjs#4284]
In the old docs ('/docs') there is documentation about the operators ('/docs/operators.md'). This file needs to be transfered to the new docs ('docs_app/content/guide'). Also it might be that links need an update inside this file and furthermore the content might be updated to be about rxjs 6

**Comment by commitshappen** [comment]
I've reviewed the page, as well as the operator doc files being generated. There's _a lot_ going on here  and I have the following clarifications prior to submitting a PR.

I also figured it would be easier to discuss these changes first, since you will not see the diffs between the new doc and the previous, but rather the addition of the file. If you'd rather I submit a PR that we tweak from there, I'm more than happy to do that as well.

## Operators Being Removed
These operators were listed in the previous version of the docs, but are no longer a part of RxJS or being documented. Can you please confirm the removal of these operators?

Also, do you want me to remove the links to the deprecated operators? As of right now, I'm still showing them, since they're generated docs.

- `create`
- `fromPromise`
- `throw`
- `distinctKey`
- `switch`
- `catch`
- `do`
- `toPromise`

## Operators Being Added
I have relinked all the current operators to their newly generated doc files, with the following list being new ones. I wasn't 100% sure which category each one of these falls into, but provided my best understanding for each. Can you please let me know how you would like these categorized?

- `catchError` (Error Handling Operators)
- `endWith` (Utility Operators)
- `finalize` (?)
- `flatMap` (Transformation Operators)
- `onErrorResumeNext` (?)
- `refCount` (Mathematical & Aggregate Operators)
- `sequenceEqual` (Conditional Operators)
- `shareReplay` (Utility Operators)
- `switchAll` (Transformation Operators)
- `tap` (Utility Operators)
- `throwIfEmpty` (Error Handling Operators)

## Content Changes
These items will be more apparent / easily digestible in the PR.

- Moved over the marble anatomy diagram
- Updated code examples to no longer include removed / deprecated methods
- Removed mention of removed / deprecated methods from paragraph content

## Content Questions
- This page references a `decision-tree-widget` that was built out for the previous docs. Am I simply copy and pasting that over? Is this widget still relevant to this content or does it need to be updated too? (I'm struggling to find a working example)
- I noticed your docs are now generated some of the previous operators within a (`/functions`) directory. Does this mean we should no longer be showing these on the page? This would essentially be _all_ the "Creation Operators" with the exception of `repeat` and `repeatWhen`. You also have `pipe`, along with a few other newly generated docs, under this same ('/functions') directory. For the sake of this page, can I consider each of these as operators?
- Similarly to the (`/functions`) directory, there's now an (`/async`) directory. Should I include all these items as operators as well, since `async` was originally listed?

**Comment by pertrai1** [comment]
@commitshappen great overview of what you have seen and worked on. @JWO719, I think it would be best to get the PR in and then work from there so we can see the changes that we all can contribute feedback too.

**Comment by commitshappen** [comment]
Feel free to close the PR I submitted. It seems there's a current PR solving this issue that I must have missed, which was opened mid-September. #4151 

If there's any help still needed on that one, I'm happy to do so.

**Comment by JWO719** [comment]
I close this issue now as it seems like we fixed the issue described above, if not feel free to reopen it
