### ISSUE TITLE
Add theme color for windows desktop app

### ISSUE THREAD

**Issue by vickmeng** [ReactiveX/rxjs#4406]
hello，respect for every engineers.
can we change desktop app theme color to pink...it looks unharmonious
![8a3780ef732077b2305d2f702eb39e9](https://user-images.githubusercontent.com/19486247/49561006-e7b60b00-f94f-11e8-942d-f7947d449425.png)

**Comment by vickmeng** [comment]
@pertrai1 
theme_color in ngrx looks right 
![image](https://user-images.githubusercontent.com/19486247/49706624-ec393700-fc61-11e8-96a7-13aaaf9b8f28.png)

and I try to set theme_color in my own pwa,it is useful.
![image](https://user-images.githubusercontent.com/19486247/49706559-995f7f80-fc61-11e8-9cd5-8df66a6115d6.png)

**chrome70.0.3538.102
window 10**

**Comment by def14nt** [comment]
It's just a `<meta>` tag. Support doesn't matter because unsupported `<meta name=x>` values are ignored IIRC.

**Comment by pertrai1** [comment]
@def14nt that is correct. But I wonder why the need to file an issue for something that has very little support. And, because the issue was filed, I asked him to take it on. Anyone who sees this issue, it is open to tackle and do a PR.

**Comment by def14nt** [comment]
@pertrai1 It's more of a niggle. It isn't important, but when you have extra time (when you're not working on smth important) you could file an issue I guess.

@vickmeng Thanks for filing the issue, but if you know how to fix this annoyance then you could have easily filed a pull request.

**Comment by JWO719** [comment]
I changed the title of this issue to be more specific. I hope that's fine. Please correct me if I missunderstood this issue

**Comment by alinnert** [comment]
I'd like to provide a PR. I've noticed that a color is already defined because the default color in Chrome for Windows is gray, not the current blue. So it just need to be changed (instead of added).

But before I do that I have one question: I've noticed that the navigation header uses two different shades depending on which page is active. The homepage uses `#d81b60` while the pages "Overview", "Reference" etc. use `#c2185b` which is slightly darker. (Is there a reason for that?)

I'd use the darker version if that's fine for everyone. I think a darker title bar over a lighter page header looks better than vice versa. On the sub pages the colors would match, which is also fine. Alternatively, I could use a third shade that's darker than the two other colors. What do you think?

**Comment by PDavid** [comment]
This seems to be fixed:
![image](https://user-images.githubusercontent.com/1415396/67148231-9b409900-f29d-11e9-878a-8d1f40e85b3b.png)
