### ISSUE TITLE
API List page drop-down on rxjs.dev

### ISSUE THREAD

**Issue by rendall** [ReactiveX/rxjs#4481]
### Documentation Related To Component:

[API List page](https://rxjs.dev/api) "Type" drop-down 

### Description Of The Issue

This is both a request for comment and an offer to contribute. 

Currently, the "Type" drop-down on the [API List page](https://rxjs.dev/api)  allows the user to filter by these types: 

- Class
- Const
- Enum
- Function
- Interface
- Type Alias

Speaking personally, I find this to be unintuitive.  I have never needed to filter documentation in that way. I nearly always need to filter by "Operator" or "Observable".  

What do we think about adding library-specific terms to the API drop-down?  e.g.

- Operator
- Observable
- Observer
- Single
- Subject
- Scheduler
- etc? 

If the community comes to a consensus about this, I would be willing to code this and submit a pull-request. 

Thoughts?

(*edit*: I just noticed that either https://rxjs.dev is not a public repo, or I couldn't find it. Is a PR request on it possible?)

**Comment by benlesh** [comment]
This would require a lot of discussion. I'm not sure what a "Single" would be, for example... and we have to consider newbies that have no idea what an Operator even is.

**Comment by JWO719** [comment]
In general I like the idea. Newbies also doesn't care if a subject is a function, a class or a what ever. I think adding some filter could improve the usability. Also we could consider adding a filter for groups of operators, e.g. 'map operators', 'timing operators'... similar to the 'find your operator' widget. But also I'm not sure how often such a feature would be used. Because most of the time you are searching for a specific operator and just want to dig into that one, at least I am doing it this way :D Not sure if it's worth the effort

**Comment by rendall** [comment]
Agreed, and this is the motivation for my offer: I personally do not find the current categories intuitive or useful, and wonder if other library consumers have the same experience. I find myself trawling http://reactivex.io and then attempting to transliterate to https://rxjs.dev

Is the rxjs.dev website written *for* the library developers as opposed to *consumers*?  I'm not easily imagining a use case where library consumers of whatever experience would need to filter 'functions' or 'const', otherwise. Types of Observables, or various types of Operators, yes.
