### ISSUE TITLE
image onerror by document in china

### ISSUE THREAD

**Issue by cocody** [ReactiveX/rxjs#4594]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
1. url: https://rxjs.dev/api/index/function/merge
2. open imageURL: https://rxjs.dev/merge.png
3. tips: 
Page Not Found
This file does not exist and there was no index.html found in the current directory or 404.html in the root directory.

Why am I seeing this?
You may have deployed the wrong directory for your application. Check your firebase.json and make sure the public directory is pointing to a directory that contains an index.html file.

You can also add a 404.html in the root of your site to replace this page with a custom error page.

even if I can access Google Facebook Youtube and so on

**Comment by JWO719** [comment]
So thanks for mentioning this. We are already aware that all the marble diagrams are broken. Hopefully it is fixed with the next deployment of the docs, but I already hoped so for the other releases. But we are already working on this, therefore I close this. If the problem occurs after the next docs deployment, feel free to re-open this issue.
