### ISSUE TITLE
Breaking change in SwitchMap 6.3.3 -> 6.4.0

### ISSUE THREAD

**Issue by snebjorn** [ReactiveX/rxjs#4632]
### Documentation Related To Component:

SwitchMap

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

Version 6.4.0 contains a breaking change when coming from 6.3.3 that is not mentioned in the CHANGELOG.md. The culprit is this change:

> switchMap: support union type returns (32d35fd)

This introduced a breaking change if you used the generic types

Before:
```ts
switchMap<string, Foo[]>(...)
```

After:
```ts
switchMap<string, Observable<Foo[]>>(...)
```

I also spotted something odd here https://github.com/reactivex/rxjs/commit/32d35fd#diff-2890e8018eeca17541f08afe9bc0bc2eL9

The test says "should support a projector that takes an index" but the index parameter was removed. That doesn't look right to me. I'm assuming prettier or something like that removed the unused parameter 🤔

**Comment by jgbpercy** [comment]
[Stackblitz working in 6.3.3.](https://stackblitz.com/edit/rxjs-qj3m28)

[Same code failing type checking in 6.4.0.](https://stackblitz.com/edit/rxjs-i76rcv?file=index.ts)

**Comment by benlesh** [comment]
### Core Team Meeting Notes

SInce using the generic arguments to cast is really an anti-pattern in TypeScript in general, We will:

- Document what to do when you need to cast an operator 
- Introduce a new type to make it more ergonomic to cast at various points in the `pipe` chain when developers encounter problems, for example:

```ts
source$.pipe(
  switchMap(fn) as RxOp<number>,     // effectivly OperatorFunction<any, number>
  map(n => n + n),                   // fine because of the cast above
)
```

It's an issue for people, but the generics changes were to fix other bugs with typings in the library, and we don't want to undo that, because we would be punishing people who were indeed using the library properly. So we'll prioritize getting this new type out there and documenting it.

**Comment by alex-okrushko** [comment]
@snebjorn 
If you really need to provide an explicit type (instead of inferred) I suggest to specify it in the return type of the function:

instead of 
```ts

**Comment by snebjorn** [comment]
Thanks for the tip.

**Comment by clivend** [comment]
does it affect people not using typescript?
