### ISSUE TITLE
People could tag their rxjs operators on npm

### ISSUE THREAD

**Issue by StephenFluin** [ReactiveX/rxjs#4710]
It might be nice guidance to suggest rxjs-operator authors use a consistent tag on npm to aid in future search / discovery.

**Comment by benlesh** [comment]
This is a great idea, @StephenFluin... I think it goes along well with some of the ideas @kwonoj has been kicking around about organizing the rxjs community contributions in some way.

**Comment by kwonoj** [comment]
As we do strongly encourage to create user-level operator / any other implementations around core, I do agree this is very important and it's one of topic core team has been discussed continuously. We wanted to reach some high level agreement of organization for community-driven effort around

- code level organization: how can we aggregate some community driven, recommended codes in single place so anyone can easily refer as needed
- libaray level organzation (as this issue suggests): how can we create single entry point to user level implementations for easier visibility
- maintainability: how can we ensure all (or most) of implementations gathered in here assures compatibility across major breaking changes in core, or correctly deprecate if needed
- and vice versa.

I (or anyone interested) probably may need write some proposal documentation for organization in general.

**Comment by benlesh** [comment]
@StephenFluin Can you add a little more information about what sort of approach you're recommending?

**Comment by StephenFluin** [comment]
I was specifically proposing just a standard and recommendation that people tag their NPM packages with `rxjs-operator` when they are offering operators that are reusable by other developers. Right now it can be hard to find cool operators, but if people tagged them consistently, we could search for them, or later build a library of great operators.

**Comment by benlesh** [comment]
So we finally discussed this again in the core team meeting, and while it's a cool idea, we just don't have anything we can do with it. We don't really want to create a generated list on the website, because it's something that can be exploited and we don't have any bandwidth to moderate it. Likewise, there's not really a lot of great ways to ensure quality or that anything is keeping up with the latest breaking changes or best practices.

However, if someone wanted to create their own third party site to help users locate and advertise their custom rxjs operators and doodads, that would be super cool.
