### ISSUE TITLE
@ in @reactivex/rxjs maybe causing some issues...

### ISSUE THREAD

**Issue by tenowg** [ReactiveX/RxJS#472]
Been trying to get angular2 installed with asp.net and @reactivex/rxjs keeps getting marked as not available by npm on install, after much playing around and head banging, I was able to get reactivex to install manually, which is a fail for asp.net (npm just needs to work on publishing), it seems that the @ symbol is ignored by package restore.

I am going check this out more, and will also drop an issue at asp.net.

**Comment by kwonoj** [comment]
Maybe related with this https://github.com/ReactiveX/RxJS/issues/458?

**Comment by tenowg** [comment]
I did read that issue, but as it seems that he is trying to install with npm, and not though another service just as Visual Studio, I didn't feel it was that same, but it might be related.

**Comment by kwonoj** [comment]
Would you able to share brief steps? I have VS2015 installed on my machine, can give it a try also to see what's happening.

**Comment by tenowg** [comment]
sure thing,

add, "angular2": "2.0.0-alpha.39" to package.json in a new MVC 6 project, and restore the package, it will look for reactivex/rxjs instead of @reactivex/rxjs giving a 404 Not Found error and a nice message say to bug reactivex to add to npm.

Some additional steps I have tried, manually installing with npm install in project directory, will install, but will still not register, but will show it is installed. Further restores will failed to finish with not found for reactivex

**Comment by kwonoj** [comment]
@tenowg Yes, seems you're correct that #458 is not directly related.

Problem was caused by default node.js packaged in VS2015's web tool's outdated, specifically npm version is about 1.4.x that does not supports some of issues resolved after those version. There are similar issues reported (https://github.com/npm/npm/issues/7496) in npm.

To resolve this, you may need to let Visual Studio use latest known good version of node / npm instead of default package. Simplest way would be redirect lookup order as documented [here] (http://blogs.msdn.com/b/webdev/archive/2015/03/19/customize-external-web-tools-in-visual-studio-2015.aspx), allows to look for external node / npm installation prior to default.

I could confirm those redirection works on VS2015 with installation of node v0.12.7 / npm v3.3.4. I don't think you necessarily need to v3 beta of npm, guess v2 would be sufficient.

**Comment by tenowg** [comment]
@kwonoj Very good catch, this is something I would never have looked for. I glazed over the version numbers in the logs, and indeed the version was 1.4.x that was causing the error. Presumably it was because I had just upgraded my installation of node/npm on my machine.

Changing to use PATH first fixed the issue, thanks
