### ISSUE TITLE
BehaviorSubject with publish and refCount - next is called only for first subscription

### ISSUE THREAD

**Issue by srghma** [ReactiveX/rxjs#4729]
## Bug Report

**Reproduction**
- REPL or Repo link:
(you can use https://stackblitz.com/ to create one to attach here)

```js
import { of, zip, interval, merge, BehaviorSubject } from "rxjs";
import { map, publish, refCount, tap } from "rxjs/operators";

const source$ = new BehaviorSubject(1).pipe(
  map(x => {
    console.log('map called', x)
    return x + 1
  })
);

const s = source$
  .pipe(
    publish(),
    refCount()
  )

s.subscribe({
    next: (x) => console.log('1 = ', x)
  });

s.subscribe({
    next: (x) => console.log('2 = ', x)
  });

source$.next(2)
source$.next(3)
```

**Current Behavior**
```
map called 1
1 = 2
map called 2
1 = 3
2 = 3
map called 3
1 = 4
2 = 4
```

**Expected behavior**
```
map called 1
1 = 2
2 = 2
map called 2
1 = 3
2 = 3
map called 3
1 = 4
2 = 4
```

**Environment**
- RxJS version: 6.4.*

**Additional context**:
![2019-04-24-13:45:52-screenshot](https://user-images.githubusercontent.com/7573215/56653844-4d085f80-6697-11e9-9f8e-24150a18520d.png)

**Comment by trxcllnt** [comment]
Hi @srghma. The behavior you're seeing is correct for the given operators. The publish operator inserts a Subject between your two destination subscriptions and the BehaviorSubject source.

When the first source subscribes, `refCount` connects this intermediate Subject to to the source BehaviorSubject, which then produces the first value you see.

When the second subscription occurs, `refCount` has already connected the intermediate Subject to the BehaviorSubject source. Since the first subscription is still active, it does not resubscribe the intermediate Subject to the source BehaviorSubject (this functionality is where the "refCount" operator gets its name).

**Comment by srghma** [comment]
@trxcllnt

**Comment by cartant** [comment]
@srghma You can get the behaviour you appear to be looking for by using `publishReplay(1)` in place of `publish`.

**Comment by srghma** [comment]
tnx, @trxcllnt @cartant , `publishReplay` works
