### ISSUE TITLE
rxjs/webSocket.lift() does not behave as expected

### ISSUE THREAD

**Issue by davidgengenbach** [ReactiveX/rxjs#4752]
## Bug Report
I try to create a WebSocket subject which reconnects on failures.

**Current Behavior**
When using the `lift` method to create a WebSocket subject, it does not emit data (or even connect to the WebSocket).

**Reproduction**
https://stackblitz.com/edit/rxjs-lfrx95

**Expected behavior**
The lifted WebSocketSubject subject should behave just like the underlying subject

**Environment**
- Runtime: Chrome v74.0.3729.108 (Official Build) (64-bit)
- RxJS version: 6.4.*

**Possible Solution**

**Additional context/Screenshots**

**Comment by cartant** [comment]
Closing this because that is not how `lift` is supposed to be used.

[`lift`](https://github.com/ReactiveX/rxjs/blob/986be2f1a1186cbbd1b2dc68fe6d11ba1f32247e/src/internal/Observable.ts#L59-L71) is not a method that should be called from user code. It's used in [operator implementations](https://github.com/ReactiveX/rxjs/blob/986be2f1a1186cbbd1b2dc68fe6d11ba1f32247e/src/internal/operators/map.ts#L45-L61) and takes an [`Operator`](https://github.com/ReactiveX/rxjs/blob/986be2f1a1186cbbd1b2dc68fe6d11ba1f32247e/src/internal/Operator.ts#L4-L6) - which is not what is returned by a operator like `catchError`.

**Comment by cartant** [comment]
For more information on `lift`, have a look at https://github.com/ReactiveX/rxjs/issues/60

**Comment by davidgengenbach** [comment]
Thanks a lot for your reply! I am very new to rxjs, so I suspected that the way I used the pipe/lift function is not right. On the other hand, I tried a lot of different combinations when trying to get the WebSocket to reconnect on failure - none with success.

Could you please give me a hint as how to proceed in getting a reconnecting WebSocket? 

As per your comment:

> Closing this because that is not how `lift` is supposed to be used.
> 
> [`lift`](https://github.com/ReactiveX/rxjs/blob/986be2f1a1186cbbd1b2dc68fe6d11ba1f32247e/src/internal/Observable.ts#L59-L71) is not a method that should be called from user code. It's used in [operator implementations](https://github.com/ReactiveX/rxjs/blob/986be2f1a1186cbbd1b2dc68fe6d11ba1f32247e/src/internal/operators/map.ts#L45-L61) and takes an [`Operator`](https://github.com/ReactiveX/rxjs/blob/986be2f1a1186cbbd1b2dc68fe6d11ba1f32247e/src/internal/Operator.ts#L4-L6) - which is not what is returned by a operator like `catchError`.

`catchError` is in the `operator` folder of rxjs: https://github.com/ReactiveX/rxjs/blob/986be2f1a1186cbbd1b2dc68fe6d11ba1f32247e/src/internal/operators/catchError.ts#L90
It returns an `OperatorFunction`. Also, the type system does not complain when giving the `catchError` "operator" to "`lift`.

On the other hand: when using `pipe`, the returned type is an `Observable` but I need a `Subject` to receive and **send** messages through the WebSocket - so using `pipe` also did not work out.

I would be very thankful if you could give me some hints on that: Is there a possiblity to use rxjs WebSocket implementation with reconnecting without explicity handling all the low-level things like re-assigning Subjects etc.?

**Comment by cartant** [comment]
`WebSocketSubject` is not something with which I am especially familiar, as I've not had the need to use it.

Regarding `pipe` returning `Observable`, that's because the `lift` mechanism isn't (easily) expressed in TypeScript. See [this comment](https://github.com/ReactiveX/rxjs/issues/3861#issuecomment-400126524) for more information.
