### ISSUE TITLE
Monitoring Subscriptions

### ISSUE THREAD

**Issue by vitaly-t** [ReactiveX/rxjs#4792]
I recently started with RXJS, and the first thing I tried, which in my mind was very basic, I got stuck with right away...

Here, I published a question on StackOverflow: [How to monitor RXJS subscriptions?](https://stackoverflow.com/questions/56195932/how-to-monitor-rxjs-subscriptions)

This is the most basic thing when dealing with subscriptions, and I'm surprized not to be able to find an answer to it.

Any help is much appreciated!

**Comment by kwonoj** [comment]
Probably you can follow so's question for other detailed answer, but in short observable doesn't expose those and you may need manage in your code. I.e write wrapper to given subject, manage counter to subscription then do necessary teardown.

Observable by design (though subject is multicast) it is unicast and 1:1 corresponds to subscription, so observable itself doesn't have global state.

**Comment by vitaly-t** [comment]
> observable doesn't expose those

Isn't it a bit of a shortcoming, not to be able to track the number of subscriptions easily?

**Comment by kwonoj** [comment]
This is actually some common questions around, but most cases you don't need to count numbers. Subscription itself is compositable so you can have parent subscription to hold all other subscriptions then trigger teardown and vice versa, which can serve same purpose (which may need in user code's wrapper) and there and some other way to manage things as well. As mentioned above observable is unicast by design and do not expect to expose some global state across each subscriptions.

**Comment by vitaly-t** [comment]
@kwonoj Would you be able to offer an answer to that specific question on StackOverflow, please!

**Comment by vitaly-t** [comment]
@kwonoj Could you, please at least keep this question open, until there is a usable code example either here on against the [question on StackOverflow](https://stackoverflow.com/questions/56195932/how-to-monitor-rxjs-subscriptions)?
