### ISSUE TITLE
Observable types in RxJS v6.5.2 and v6.4.0 are incompatible

### ISSUE THREAD

**Issue by ahasall** [ReactiveX/rxjs#4818]
## Bug Report

**Current Behavior**
If you use RxJS v6.5.2 and a library that depends on RxJS v6.4.0, you may get a TS2322 error.
For example you can get the following error:
Type 'Observable<BuilderOutput>' is not assignable to type 'BuilderOutputLike' while
```typescript
export declare type BuilderOutputLike = Observable<BuilderOutput> | Promise<BuilderOutput> | BuilderOutput;
```

**Reproduction**
- REPL or Repo link:
https://github.com/ahasall/rxjs-v6.4-v6.5-bug
```bash
yarn install
yarn build
```

**Expected behavior**
It should work
**Environment**
- Runtime: Node v10.15.3
- RxJS version: v6.5.2

**Comment by kwonoj** [comment]
> RxJS v6.5.2 and a library that depends on RxJS v6.4.0,

we don't recommend to mixin different versions of single library. You should match versions.

**Comment by ahasall** [comment]
Hello @kwonoj, thank you for your answer.
I totally get it. But what happens when you don't have control over the versions? For instance, you may have a library A that depends on RxJS v6.4.0 and a library B that depends on RxJS v6.5.2

I am forced to have two different versions in my node_modules.

**Comment by kwonoj** [comment]
observable instance between different version is unsupported scenario. Mean, it could work, but also it could not work like problem you're seeing - we don't actively support compatibility of multi-version installation sceanario. Best path is making library to get support same version range and install same version. Unless some libarary have strict version setting in pkg, version range in package.json should allow it. Otherwise, let each library need update to support latest.

**Comment by cartant** [comment]
Really, the library should have a peer dependency on RxJS, giving you control of the actual version of RxJS that's to be used.

**Comment by ahasall** [comment]
Thank you for your answers.

I will raise an issue with the Angular CLI team.
