### ISSUE TITLE
Possible dedundant info in the documentation of 'of' function

### ISSUE THREAD

**Issue by Nocturnal-2** [ReactiveX/rxjs#4825]
### Documentation Related To Component:

https://rxjs.dev/api/index/function/of

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

I learn from the document that 'of' function can accept and emit several different types of values.

I think the following line in the document already illustrates this (with two different types of argument T and T2):
`of(a: T, b: T2, scheduler: SchedulerLike): Observable<T | T2>`

I am wondering what is the necessity to add more types to the argument like **T3, T4, until T9** like in the line below :
`of(a: T, b: T2, c: T3, d: T4, e: T5, f: T6, g: T7, h: T8, i: T9, scheduler: SchedulerLike): Observable<T | T2 | T3 | T4 | T5 | T6 | T7 | T8 | T9>`

**Comment by cartant** [comment]
The docs are generated from the source and the source actually contains the signatures to which you refer:

https://github.com/ReactiveX/rxjs/blob/f07d349da8c2e0dbddca17d33a9b4a1ceaf59354/src/internal/observable/of.ts#L32-L44

The overload signatures are needed so that the types of the argument parameters can be represented in the type of the returned observable.
