### ISSUE TITLE
[docs]: Example for throttleTime broken

### ISSUE THREAD

**Issue by reod** [ReactiveX/rxjs#4886]
### Documentation Related To Component: 
`throttleTime` operator

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

1. Go to [`throttleTime` doc](https://rxjs-dev.firebaseapp.com/api/operators/throttleTime)
2. Scroll to example with *Double Click*
3. Run code sample on stackblitz.com via provided link (or try it on your own)
4. Try to test double click and single click

**expected behaviour**: `console.log` fired only when double clicked (two click in between 400ms)
**actual behaviour**: `console.log` fired on every click

**Comment by Eddie-CooRo** [comment]
Yeah, I can approve that it's broken.
I think that "throttleTime" is not suitable for handling double clicks at all because it emits values "Every" *x* seconds, even if there is only one event occurred.
Probably something like this will work:
```
import { fromEvent, asyncScheduler } from "rxjs";
import { pairwise, filter, debounceTime } from "rxjs/operators";

const click = fromEvent(document, "click");
const doubleClick = click.pipe(
  pairwise(),
  filter(([e1, e2]) => e2.timeStamp - e1.timeStamp < 400),
  debounceTime(400, asyncScheduler)
);

doubleClick.subscribe(() => {
  console.log(`Double-clicked!`);
});
```
[codesandbox link](https://codesandbox.io/s/loving-hooks-32qn9?fontsize=14)
(Note that debounceTime is used to prevent three fast clicks get counted as two double clicks)

So this example should move to the pairwise documents.

**Comment by Armenvardanyan95** [comment]
Should this be addressed? I can try to add a better example

**Comment by jakovljevic-mladen** [comment]
The example is removed with the PR #6625. Closing the issue. @reod, thanks for reporting.
