### ISSUE TITLE
The `complete` callback of `tap` operator is not executed on source Observable completion

### ISSUE THREAD

**Issue by niwinz** [ReactiveX/rxjs#4965]
## Bug Report

**Current Behavior**
The `tap` operator does not executes the `complete` callback when the source Observable is completed (in the following example I also use  the `finalize` operator that works as expected).

**Reproduction**

```js
import * as rx from "rxjs";
import * as op from "rxjs/operators";

const stoper = rx.fromEvent(document, "click").pipe(
  op.tap(
    m => console.log("stoper (on-message)"),
    e => console.log("stoper (on-error"),
    () => console.log("stoper (on-complete)")
  ),
  op.finalize(() => console.log("finalize"))
);

stoper.pipe(op.take(1)).subscribe({
  next(m) {
    console.log("next");
  },
  complete() {
    console.log("complete");
  }
});

// This will trigger the following lines on the console:
// => stoper (on-message)
// => next
// => complete 
// => finalize 
```

**Expected behavior**
I expected the following output:

```
// => stoper (on-message)
// => next
// => stoper (on-complete)
// => complete 
// => finalize 
```

I expect that the `complete` callback passed to `tap` operator to be called after the source Observable is completed (in this case bacause of take operator).

**Environment**
- Runtime: Chrome v75
- RxJS version: 6.5.2

**Comment by martinsik** [comment]
This is expected behavior. The complete notification is created by `take(1)` and passed down the chain. 
If you want to see `"stoper (on-complete)"` as well then you'd have to make `fromEvent` emit the  complete notification. In other words, in your example the source Observable created by `fromEvent` never completes.

`finalize` is called correctly because it's triggered when the chain is being disposed.
