### ISSUE TITLE
share and two concatMap duplicates first concatMap

### ISSUE THREAD

**Issue by DavidTanner** [ReactiveX/rxjs#4981]
## Bug Report

**Current Behavior**
Even after using share, using two concatMap's causes observers to execute twice.  No matter where I put share, the actual array ends up with double the inputs, and doesn't even finish the second source pipe correctly.

**Reproduction**
https://stackblitz.com/edit/rxjs-concat-duplicates

```js
import { interval, concat, merge } from 'rxjs'; 
import { take, share, filter, map, finalize } from 'rxjs/operators';

const source = interval(100).pipe(
  take(10)
)

const actual = [];

const secondSource = concat(
  source.pipe(
    filter(x => x % 2 === 0),
    map(x => x * -1),
    share()
  ),
  source.pipe(
    filter(x => x % 2 === 1),
    share()
  )
).pipe(map(x => actual.push(x)), share());

const finalSource = concat(
  secondSource.pipe(
    filter(x => x % 2 === 0),
    map(x => x * 2)
  ),
  secondSource.pipe(
    filter(x => x % 2 === 1)
  )
);

finalSource.subscribe(x => console.log(actual));

// expected ends last with: [0, -2, -4, -6, -8, 1, 3, 5, 7, 9, 0, -2, -4, -6, -8, 1, 3, 5, 7]
// Should be: [0, -2, -4, -6, -8, 1, 3, 5, 7, 9]
```

**Expected behavior**
Adding share to the original source should prevent observable duplication

**Environment**
- Runtime: [e.g. Node v8.10.0, Chrome v 76.0.3809.100]
- RxJS version: ^6.5.2

**Comment by cartant** [comment]
This does not look like a bug, to me. You are using `concat` which is going to wait for the first observable to complete before subscribing to the second observable. And that means an unsubscription from first observable will occur before the subscription to the second, so the reference count will drop to zero.

Essentially, the `share` is not doing what you expect because the reference count drops to zero between subscriptions to the concatenated observables and that effects a repeated subscription to the source.

**Comment by cartant** [comment]
Closing for the reason given in the comment above.
