### ISSUE TITLE
'tag', 'name' or 'metadata' operator for debugging and tracing (i.e. rxjs-spy)

### ISSUE THREAD

**Issue by stasberkov** [ReactiveX/rxjs#5082]
## Feature Request

We more and more use rxjs. Logic flow becomes very complex and hard to debug.
There is tool that ease debugging: https://www.npmjs.com/package/rxjs-spy
Inconvenience of this tool is that it has its own "tag" operator and you have to reference
that 3rd pary debugging lib even when you build in prod mode (removing all 'tag' operators and then adding them back for debug is not a good solution).
Having alike operator right in rxjs will avoid of having such inconvenience.

**Comment by cartant** [comment]
`rxjs-spy` will be be more or less deprecated when the DevTools for RxJS are done. And the `tag` operator will be a thing of the past. Adding something similar here would be a step backwards, IMO.

**Comment by stasberkov** [comment]
What are DevTools for RxJS? Is there any verion of it?

**Comment by cartant** [comment]
> What are DevTools for RxJS?

A Chrome/Firefox DevTools extension for RxJS.

> Is there any verion of it?

There is no released version. Yet.

**Comment by stasberkov** [comment]
Any way to try? Who is developing them? https://github.com/topics/devtools-extension ? Can you give repo url?

**Comment by cartant** [comment]
> Any way to try?

No

I'm going to close this because regarding the "you have to reference that 3rd par[t]y debugging lib" point, `rxjs-spy` was written so that when `tag` is imported like this:

```ts
import { tag } from "rxjs-spy/operators/tag";
```

there are no references to any other parts of `rxjs-spy` - you get the operator and that's it.

If that is, for some reason, still a problem, you should open an issue in the `rxjs-spy` repo.
