### ISSUE TITLE
tests2png is defeated by TestScheduler#run()

### ISSUE THREAD

**Issue by timdp** [ReactiveX/rxjs#5100]
## Bug Report

**Current Behavior**

As part of #5019, I discovered that the `tests2png` script currently (as of 1b2021f) renders the following PNG images as only the operator and no observables:

- audit
- auditTime
- buffer
- bufferCount
- bufferTime
- bufferToggle
- bufferWhen
- catch
- combineAll
- combineLatest
- delay

**Example**

![audit](https://user-images.githubusercontent.com/201034/67158253-240b1380-f336-11e9-85cd-c8eef6d89d18.png)

**Diagnosis**

I did a `git bisect` and found out that the issue is introduced by multiple commits. For `audit`, the behavior started in c41d00b. For `auditTime`, it's broken as of bc91ba0.

This suggests that the problem is the introduction of `TestScheduler#run()`.

**Environment**

- Runtime: Node v12.11.0
- RxJS version: 1b2021f

**Comment by timdp** [comment]
Still seeing this on master as of d2f68db3.

Pinging @JWO719 for visibility.

**Comment by timdp** [comment]
Still happening with d7f70782.

Additionally, I had to `npm install ts-node tsconfig-paths -D` first.

I guess the diagrams haven't been receiving a lot of love recently?

**Comment by JWO719** [comment]
The diagrams definitely didn't received a lot of love in the recent time, that's true. Sorry for coming back this late to you. To be honest, I kinda lost track on the issues with the marble diagrams in general. Is there anything I can support you with, because I would really love to have the improved marble diagrams you worked on?

**Comment by timdp** [comment]
I won't be able to take a look for another couple of weeks due to medical reasons, but I think it would definitely help to have some form of documentation on how the testing APIs changed. Perhaps the tests' authors could share an explanation?

**Comment by niklas-wortmann** [comment]
This topic kinda poped up again. Sorry I didn't respond in the meantime. I'll take a look and when I am stuck connect to the people that might can help here

**Comment by niklas-wortmann** [comment]
Just to be totally clear, so besides the operator listed at the top, it is working properly in the current state?

**Comment by timdp** [comment]
With 02f458d, in addition to the operators in my original message, the following now also render empty:

* concat
* concatAll
* concatMap
* take

I also still had to `npm install ts-node tsconfig-paths -D` on a clean repo before I was able to run tests2png.

**Comment by niklas-wortmann** [comment]
Ok great I will have a look at this tomorrow and come back to you!

**Comment by cartant** [comment]
FWIW, the `asDiagram` function that's used in the test is declared [here](https://github.com/ReactiveX/rxjs/blob/02f458d26d9a885bbf913c98011e77d251837226/spec/helpers/testScheduler-ui.ts#L222-L227) - in the Mocha context - and it uses the [diagram function](https://github.com/ReactiveX/rxjs/blob/02f458d26d9a885bbf913c98011e77d251837226/spec/helpers/testScheduler-ui.ts#L59) that's only made available when the [`diagram-test-runner`](https://github.com/ReactiveX/rxjs/blob/02f458d26d9a885bbf913c98011e77d251837226/spec/helpers/tests2png/diagram-test-runner.ts#L73-L104) is used.

It doesn't work because it depends upon using the assert function passed to the global - 🤮 - `TestScheduler` instance and that instance is not ignored by tests that use `TestScheduler#run`.

IMO, this `asDiagram` infrastructure should be abandoned in favour of using swirly, some input files and a script. Maybe that's what Ben was referring to in [this tweet](https://twitter.com/BenLesh/status/1258755398284333057). I sure hope so.

**Comment by niklas-wortmann** [comment]
I would be very fine with that. That sounds actually like a pretty good idea

**Comment by cartant** [comment]
Also, Ben has been deleting the `asDiagram` stuff in [his changes to the tests](https://github.com/ReactiveX/rxjs/pull/5326/files), so I doubt anyone will be sorry to see it go.

**Comment by timdp** [comment]
Ping me if you need any help interpreting Swirly's API. You can probably figure it out by inspecting the call to `drawMarbleDiagram` but I'm happy to assist.

**Comment by niklas-wortmann** [comment]
I think this can be closed for now as we will use swirly to manually create the svgs. POC is already in master, we just need to create new marble and update the image refs.

**Comment by timdp** [comment]
Looking forward to it!
