### ISSUE TITLE
Is: "Operators should always return an Observable" valid for rxjs 6?

### ISSUE THREAD

**Issue by ghuser** [ReactiveX/rxjs#5300]
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [X] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

In this section: https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md#guidelines
I read the following:

> Operators should **always return an Observable**. You're performing operations on unknown sets of things to create new sets. It only makes sense to return a new set. If you create a **method that returns something other than an Observable, it's not an operator**, and that's fine.

According to the above, `map()` should not be considered an operator because it does not return an observable. It returns a function.

A contradicting definition(described [here](https://angular.io/guide/rx-library#operators)): 
> "Operators take configuration options, and **they return a function** that takes a source observable. **When executing this returned function**, the operator observes the source observable’s emitted values, transforms them, **and returns a new observable** of those transformed values"

**Comment by jakovljevic-mladen** [comment]
I guess that this is an old definition when pipeable operators weren't around. Before pipeable operators were introduced (I think in version 5.5 of RxJS), operators were returning Observables. An old [`map()`](https://github.com/Reactive-Extensions/RxJS/blob/master/src/modular/observable/map.js#L50) implementation indicates just that.

This outdated problem seems to affect the whole [`/doc`](https://github.com/ReactiveX/rxjs/tree/master/doc) folder. Contents of the many files from this folder are mainly outdated and seems like this documentation is not being updated regularly.

Can I have someone from the core team to explain what should be done with the contents from `/doc` folder since this is clearly outdated documentation that needs some big rewrites or maybe deletion?

**Comment by jakovljevic-mladen** [comment]
I think that this issue can be closed as the old `/docs` is [removed](5338) now. This documentation was obsolete.

**Comment by niklas-wortmann** [comment]
As suggested I will close this issue. If there is anything else needed to do about this, feel free to reopen this issue
