### ISSUE TITLE
Support using type definitions when using the UMD build

### ISSUE THREAD

**Issue by valeriob** [ReactiveX/rxjs#5302]
Hi,
i would like to use this awesome library via the UMD build, leveraging the type definitions.

For instance :
npm i @reactivex/rxjs
Create a index.ts file with some function that use RxJs
Create an index.html file that reference RxJs UMD build and the index.js file created by the typescript compiler from the index.ts one.

here there is a repro : https://github.com/valeriob/Repro_rxjs_typescript Just run "tsc" and see the compiling error.

How do i get type definitions while editing index.ts in this scenario ?

Following those guidelines https://github.com/zspitz/TypeScript-Handbook/blob/release-2.0/pages/Modules.md#umd-modules i was able to make it work by appending "export as namespace rxjs;" to the file node_modules/rxjs/index.d.ts .

Also posted on :
https://stackoverflow.com/questions/58728020/how-do-use-rxjs-with-type-definitions-when-using-the-umd-build

Thanks

**Comment by valeriob** [comment]
adding this line 

> export as namespace rxjs;

at the end of file dist\package\index.d.ts works like a charm, just the typings are not automatically discovered by typscript compiler due to  the typings property in package.json pointing to another file "typings": "./dist/package/Rx.d.ts",

**Comment by kwonoj** [comment]
Since we create umd as single file via bundler after transpilation, we don't create merged type definition for it. 

Quick searching in this repo it seems there are repeated question around this you have filed, as suggested in other issue this is more for stackoverflow-like question to configure manual way to utilize typins for umd bundle and would recommend to avoid filing duplicated issue.
