### ISSUE TITLE
Strange behaviour after a stream is completed when related to another stream by subscription's `.add`. 

### ISSUE THREAD

**Issue by unao** [ReactiveX/rxjs#5355]
## Bug Report

**Current Behavior**

Strange behaviour after a stream is completed when related to another stream by subscription's `.add`. 

**Reproduction**
https://stackblitz.com/edit/rxjs-1yyabm?file=index.ts

```js
import { timer } from 'rxjs'; 
import { take } from 'rxjs/operators';

timer(3000, 1000).subscribe(
  x => console.log('TIMER-1')
)
.add(
  timer(2000, 1000)
  .pipe(take(1))
  .subscribe(
    x => console.log('TIMER-2'), () => null, () => console.warn('DONE-2')
  )
)
.add(
  timer(0, 1000)
  .subscribe(
    x => console.log('TIMER-3'), () => null, () => console.warn('DONE-3')
  )
)
```
`TIMER-3` stops to be logged once timer-2 is completed.

**Expected behavior**

Completion of the second subscription should have no effect on third one.

```js
import { timer } from 'rxjs'; 
import { take } from 'rxjs/operators';

timer(3000, 1000).subscribe(
  x => console.log('TIMER-1')
)
// .add(
//  timer(2000, 1000)
//  .pipe(take(1))
//  .subscribe(
//    x => console.log('TIMER-2'), () => null, () => console.warn('DONE-2')
//  )
// )
.add(
  timer(0, 1000)
  .subscribe(
    x => console.log('TIMER-3'), () => null, () => console.warn('DONE-3')
  )
)
```

*version:* ^6.5.2

**Comment by cartant** [comment]
IIRC, `add` is not a fluent-API-style method. It returns the added subscription; not the subscription it was added to.

**Comment by Andrei0872** [comment]
Hello! I think this is the expected behavior.

When you do `Observable.subscribe(obsever)` and the `observer` is **not** an instance of `Subscriber`, a `Subscriber` instance will be created based on the `observer`.

With that in mind, here's how I'd visualize your snippet:

```ts
timer(3000, 1000).subscribe(
  x => console.log('TIMER-1')
) /* Subscriber#1.add */
.add(
  timer(2000, 1000)
  .pipe(take(1))
  .subscribe(
    x => console.log('TIMER-2'), () => null, () => console.warn('DONE-2')
  )
) /* Subscriber#2.add */
.add(
  timer(0, 1000)
  .subscribe(
    x => console.log('TIMER-3'), () => null, () => console.warn('DONE-3')
  ) /* Subscriber#3 */
)
```

Each `.subscribe()` will return a `Subscriber` instance.

The `Subscriber` class **extends** `Subscription`, which is why you are able to use the `add` method.

In this case, `s1.add(s2)`, among other things, will [return](https://github.com/ReactiveX/rxjs/issues/5355) `s2`, because `s2` is an instance of `Subscriber`. 

So, we can simply your snippet like this:

```
//                       Subscriber2
//                           |
Subscriber1.add(Subscriber2) . add(Subscriber3)
```

Which can also be seen like this:

```
S#n - Subscriber#n

    S#1
     |
    S#2
     |
    S#3

------------------------------------------------

 S#X
   |
 S#Y

* subscriber X - the parent of subscriber Y
* X._subscriptions = [Y]
* Y.parentOrParents = X
```
When `Subscriber2` completes, it will also unsubscribe, which means that [this block of code](https://github.com/ReactiveX/rxjs/blob/master/src/internal/Subscription.ts#L85-L104) will eventually be reached.

Remember that `Subscriber2._subscriptions = [Subscriber3]`, so when `Subscriber2` unsubscribes, it will call `Subscriber3.unsubscribe()`, which should explain why `TIMER-3` stops when `TIMER-2` stops.

**Comment by unao** [comment]
@Andrei0872

Thank you for your explanation - very interesting, but to be honest this behaviour is pretty counter-intuitive to me. I would expect combining subscriptions with `add` to work analogous to combining underlining streams with `merge` with single `subscribe`. The current implementation is order dependent and can easily produce race conditions.

Putting aside my expectations, it still seems current behaviour breaks Observable contract: we end up in a situation where a stream is technically dead (`timer-3`), but whose `complete` / `error` callback was not called.

> IIRC, add is not a fluent-API-style method. It returns the added subscription; not the subscription it was added to.

Oh this is bit unfortunate.

**Comment by cartant** [comment]
> Putting aside my expectations, it still seems current behaviour breaks Observable contract ...

No, it doesn't break the contract. Subscribers can unsubscribe explicitly and that's what happens here. A subscriber's `complete` won't be called in that situation. It's behaving as expected.
