### ISSUE TITLE
Create a lint rule for Subject next

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#5392]
### Problem

Currently, the typings on `Subject` `next` are incorrect. They allow for optional arguments even when the subject itself not a `Subject<void>`. This is a holdover from when RxJS was first developed against TS, during which time is was unergonomic for developers to have to call `subject.next(undefined)` on `Subject<void>`. In particular for Angular developers, who use `EventEmitter` which inherits directly from `Subject`.

We tried to correct the types for v7, however, the change caused way too much breakage, particularly in Angular apps. So we decided to revert the change for v7 and we would instead
create a lint rule during v7 that would help users migrate their code to the appropriate types rather than just breaking their builds.

One problem is that any fix that is done here may cause additional issues.

There's the "tight" fix, where we simply add `void` to the types for the Subject. But the problem there is it may break consuming code that are not expecting `void` (even thought they *should* be). 

There's also the "loose" fix, where we fix identified issues with `any`. The problem there being that we break type safety downstream in the name of preparing to fix the types.

**Odds are that the loose fix is the appropriate thing to do.**. I say this because what will happen is the lint rule will fail for some people, and they will do the appropriate fix, but for other people with larger code bases, they will be able to opt in to the "loose" fix and just move on, circling back to fix their code later.

### Task

- Create a lint rule that will identify TypeScript usage of `Subject` where `next()` is called without an argument, but the Subject type does not include `void`.
- Create a fix for the lint rule that will correct the types of the `Subject` in question.
- Work with important teams, such as the Angular team, to identify the appropriate change for the fix.

**Incorrect:**

```ts
class Foo { foo = 'test';  };

const s = new Subject<Foo>();
s.next(); // Error should be here.
s.next(new Foo());
```

**Fixed (loose):**

```ts
const s = new Subject<any>(); 
s.next(); // No error
s.next(new Foo());
```

**Fixed (tight):**

```ts
const s = new Subject<Foo | void>(); 
s.next(); // No error
s.next(new Foo());
```

**Comment by cartant** [comment]
There is now an `rxjs-no-unsafe-subject-next` rule in [`rxjs-tslint-rules`](https://github.com/cartant/rxjs-tslint-rules) and a `no-unsafe-subject-next` rule in [`eslint-plugin-rxjs`](https://github.com/cartant/eslint-plugin-rxjs).

I've not implemented fixers because not all problems can be fixed within the linting process. Files are linted one by one and they are fixed when they are linted. The problem is that the site that needs the fixin' is not the site of the rule failure. The fixes outlined above 'fix' the subjects declaration and that could be in another file - or even in another package. The subject might not even be called directly - it could be returned from a method or a getter. IMO fixing this is way too hard and not worth the effort. And, generally, I am not in favour of fixers that only work in some situations. They are certainly not something that I would want to support or (continually) explain.

**Comment by benlesh** [comment]
We've decided to just keep Subject with the proper types in 7.
