### ISSUE TITLE
Why is the pluck deprecated?

### ISSUE THREAD

**Issue by jakovljevic-mladen** [ReactiveX/rxjs#5453]
I saw [this commit](https://github.com/ReactiveX/rxjs/commit/e7347b90e73347146074e0dfed5396e208e01d9e) and I'm wondering why `pluck` is deprecated? I couldn't find any issue where this is discussed.
By the logic behind the explanation about using optional chaining, this means that you can easily deprecate lot's of other simple operators like `startWith`, `endWith`, `timestamp` and so on, because it's always possible to use pipe + something in case of these. I just wonder what's the reason behind deprecating this operator.

**Comment by kolodny** [comment]
`pluck('prop')` is a shorthand for `map(x => x.prop)`, the main advantage to using pluck was the path traversal safety, meaning you can do

```ts
pluck('foo', 'bar', 'baz')
```

and this would be fine even if the emitted value didn't have a `foo` property. Contrast this with  
`map(x => x.foo.bar.baz)` which will error if the emitted value doesn't have a `foo` property

With optional chaining this advantage is no longer true since you can now do

```ts
map(x => x?.foo?.bar?.baz)
```

And it will be as safe as the `pluck` usage. Note that having proper TypeScript typing for pluck is quite complex and not as robust as the map usage which is a major reason to prefer the `map` method

**Comment by cartant** [comment]
FWIW, deprecated parts of the API won't necessarily be removed in the very next version of the library. ATM, one of the things on which we are working is improving the deprecation messages to make them easier to understand and to include links to the documentation to explain what is being deprecated and why. IMO, `pluck` won't be **removed** from the API until version 8 or later.

**Comment by jakovljevic-mladen** [comment]
Thanks for the clarifications @kolodny, @cartant. I like this operator and I use it a lot because it's easier (and more clean IMO) to write `pluck` than `map`.

**Comment by rdohms** [comment]
Just dropping my 2 cents here.

As much as the code is equivalent and the usage of optional chaining is preferred, with the transition to `map` you are losing a huge "readability" advantage for the person reading the code.

It's mentally a lot easier to recognize a `pluck` than to identify the `map` call is doing the same. Maybe an alias function that still uses the underlying code but allows quicker recognition?

**Comment by krawaller** [comment]
> And it will be as safe as the pluck usage. Note that having proper TypeScript typing for pluck is quite complex and not as robust as the map usage which is a major reason to prefer the map method

Late to the party, but, I just wanted to echo this part ☝️ of @kolodny's argument for preferring `map`.  We got bit by an unintended action payload shape change, which was hidden from TS via `pluck`. The path was no longer valid, which meant that the output of `pluck` was typed as `unknown`, but with some bad luck in exactly how that was consumed downstream (straight comparisons and string concatenation), there was no TS error. If we'd used `map` instead from the beginning, we would have immediately noticed the erroneous payload shape, instead of shipping broken code..
