### ISSUE TITLE
RequestIdleCallback Scheduler

### ISSUE THREAD

**Issue by richieforeman** [ReactiveX/rxjs#5531]
This was previously discussed @ https://github.com/ReactiveX/rxjs/issues/1870 -- It would be nice to have a scheduler that used `RequestIdleCallback` to process work.  While [most browsers are supported](https://caniuse.com/#feat=requestidlecallback), there's probably a remaining question of what to do if it's not supported by the browser (run immediately? fallback to RequestAnimationFrame? "setTimeout-based" polyfill?)

This would be super useful.

**Comment by joshribakoff** [comment]
The concern on whether to polyfill should be up to the consumer IMO, if the consumer does not use this scheduler, it should be tree shaken out & not polyfilled.

**Comment by cartant** [comment]
I've put my thoughts on this into a blog post: https://ncjamieson.com/how-to-use-requestidlecallback/

Mostly because several other people have asked me about this recently.

**Comment by richieforeman** [comment]
Great article!

I was actually using something similar to an idle observable and had a passing thought a scheduler may have been better (admittedly, the ergonomics of using the RAF scheduler are quite nice).  The article actually explains it quite nicely and at least confirms my current path forward ;D Awesome.

**Comment by joshribakoff** [comment]
@cartant thanks for the article. I use a home made operator to change the execution context today, instead of a scheduler. I still think having an official blurb in the docs would be great, to make sure these great thoughts from your blog get more visibility.

Regarding the "experimental" nature of it, couldn't it just be in a separate package, still living under this namespace, officially maintained, and referenced from the official docs?

Even if we don't provide the official implementation, I think it should be called out. Omitting it makes RxJs seem outdated for new users who may be approaching it. They may falsely conclude from it's omission that RxJs is not able to meet their needs.

**Comment by cartant** [comment]
> Regarding the "experimental" nature of it, couldn't it just be in a separate package, still living under this namespace, officially maintained, and referenced from the official docs?

All of that takes time - which is limited - and doesn't include the time that would be spent explaining the situation in issues that would surely be opened on an ongoing basis. I see no point in 'officially' supporting an experimental API that has been discussed for something like 4 years - IIRC - and is still not in Safari and iOS Safari.

**Comment by joshribakoff** [comment]
Right now the consumers of RxJs are paying the time each time to figure this out for themselves & re-implement it in every project over & over. I was hoping we could at least add a blurb in the docs that explains how to make the operator yourself & explains why it belongs as an operator instead of a scheduler. This blurb could contrast operators with schedulers like you've done in your excellent blog post.

My idea with providing an implementation in addition to docs would just require initial time commitment to create an official "extras"  repo. I'd bet there are volunteers willing to help maintain it & field any issues, including me, and I see you already have an "extras" repo, perhaps it could go there & be linked to from the official docs?

The tradeoff is fragmentation of the ecosystem, where users of RxJs have to write a bunch of third party libraries, which makes it harder to get going as a user. The other tradeoff is people will post issues like these if it is not added, or users will still be confused, they may just wrongly assume RxJs does not allow for using requestIdleCallback, I would personally rather help answer possible issues & clarify the docs vs potentially having a smaller community because of small barriers to entry like lack of support for some newer browser APIs. Ideally IMO if its not added here under this namespace, its added to a popular "extras" library like your awesome rx-etc package, to minimize the number of new packages a user of Rx must deal with to get basic tasks done.

I also quite frankly don't see why Safari matters, if people chose to pull in the optional package that houses this operator, the burden on them to polyfill or not would be on them.  My intent is to lower the barrier to entry so people don't have to independently discover the concepts themselves.

I think having a stand alone package that implements this operator, would be great, too. Ideally it lives under the official namespace, or is linked to from the official docs, so that users do not have to stop their task at hand & go search through a dozen slightly different community implementations.
