### ISSUE TITLE
timestamp operator no longer honors TestScheduler run mode.

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#5553]
In an attempt to make `timestamp` smaller and not depend on schedulers, I broke the ability for `TestScheduler` "run mode" to naturally override the `now()` behavior that `timestamp` uses.

**Comment by cartant** [comment]
Has this been addressed by the changes in #5607? I'm guessing 'yes'.

**Comment by cartant** [comment]
Closing because this was resolved in #5607 with the addition of a `dateTimestampProvider`:

https://github.com/ReactiveX/rxjs/blob/0dff2dcf19d69738c7dd5594cd02db8742133744/src/internal/operators/timestamp.ts#L36

https://github.com/ReactiveX/rxjs/blob/0dff2dcf19d69738c7dd5594cd02db8742133744/src/internal/testing/TestScheduler.ts#L661
