### ISSUE TITLE
Discussion: forkJoin completing early if any source completes without value

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#5561]
The current behavior as described in a marble test:

```ts
    it('should complete early if any of source is empty and completes before than others', () => {
      rxTestScheduler.run(({ hot, expectObservable }) => {
        const e1 = forkJoin({
          foo: hot('      --a--b--c--d--|'),
          bar: hot('      (b|)'),
          baz: hot('      ---------|'),
        });
        const expected = '---------|';

        expectObservable(e1).toBe(expected);
      });
    });
```

### Thoughts:

This seems like it should be an known error type of some sort. Like an `EmptyError` or the like. Instead, the result completes as if everything is "okay" but doesn't provide a value. It's certainly _detectable_... but it's a bit of nuance I'd wager most people don't know. And it seems like an exceptional case.

### Proposal:

Have `forkJoin` emit an error of `EmptyError` if a provided source completes without emitting a value.

**Comment by benlesh** [comment]
Core team agreement: This should be an `EmptyError`. Unfortunately, that is a breaking change, and will have to wait for version 8.

**Comment by supercargo** [comment]
`forkJoin` semantics for the dictionary form make early termination handling a bit less intuitive.  For version 8, is it possible to have alternative behavior in which the dictionary entry for completed-without-emitting sources is `undefined`, with other entries populated?

**Comment by benlesh** [comment]
@supercargo you can accomplish what you're asking right now like so:

```ts
forkJoin(sources.map(defaultIfEmpty(undefined)))
```

[example here](https://stackblitz.com/edit/rxjs-7pqkql?file=index.ts)

**Comment by supercargo** [comment]
@benlesh Good point, and thanks for pointing out some higher order functions that can fill the gap, but `map` isn't available if `sources` is an object rather than an array, but maybe that's a JS/TS language issue and not something for RXJS to solve.

Anyway, my point is that requiring non-empty observables for the array form makes sense since the input and output need to be tuples of the same arity.  However, missing values (or keys) in objects is more natural, which is why I had a read-the-docs moment with forkJoin object form.  Either way, I'm glad to see the `EmptyError` will help highlight these situations.
