### ISSUE TITLE
request `BehaviorSubject.isBehaviorSubject()` test function

### ISSUE THREAD

**Issue by xp44mm** [ReactiveX/rxjs#5570]
## Feature Request

rx has a lot of type for example, Observable, Subscription, ... if we test them using:

```js
if(value instanceof BehaviorSubject){...
```
is this way is safely? some times using webpack after treat code. it will not work. may i get a static test method every class:
```js
Observable.isObservable //have existed.
Subscription.isSubscription
BehaviorSubject.isBehaviorSubject
// and so on
```

**Comment by kwonoj** [comment]
No, core will not include those. It is not frequent all of the custom types exposing validating self. Secondly, more important q is why you need this - for some few edge cases rx indeed does not allow interop across context (i.e different versions, or differently bundled context). It is important to avoid those instead of trying to verify it actually. Lastly if a specific instance include those checks, it'll likely fall back to the limitation of given interop context which'll make redundant. 

I do not even recommend to create user land implementation for these case, I'd more recommend to avoid these check as much.

**Comment by xp44mm** [comment]
a use case :`JSON.stringify(data,replacer)`:

````js
let data = {bs:new BehaviorSubject(1111)}
let outp = JSON.stringify(data, v => v instanceof BehaviorSubject? v.value:v)
```
