### ISSUE TITLE
Feature Request: pluckBy(Function)

### ISSUE THREAD

**Issue by matze1234** [ReactiveX/rxjs#5633]
## Feature Request

Hi,
i recently got familiar with the pluck() operator. Sadly, **type references are lost** after using it. I wonder if an alternative might be a pluckBy() operator that receives the Array.map callback function as a parameter, instead of property names, and thereby can keep up the type references.

Example:

```
const source = from([
  { name: 'Joe', age: 30 },
  { name: 'Sarah', age: 35 }
]);
//grab names
const example = source.pipe(pluckBy((person) => person.name));
//output: "Joe", "Sarah"
const subscribe = example.subscribe(val => console.log(val));

```
**Typescript should automaticly know that const example is of type Observable<string[]>**

**Comment by tonivj5** [comment]
I think you want to use [`map`](https://rxjs.dev/api/operators/map) operator. Using your example:
```ts
const source = from([
  { name: 'Joe', age: 30 },
  { name: 'Sarah', age: 35 }
]);
//grab names
const example = source.pipe(map((person) => person.name));
//output: "Joe", "Sarah"
const subscribe = example.subscribe(val => console.log(val));

```

**Comment by niklas-wortmann** [comment]
As you can see in this stackblitz (https://stackblitz.com/edit/rxjs-eresea) the type is properly inferred when using pluck. 
What you are trying to do with `pluckBy` is already possible by just using the `map` operator. 

2 sidenotes: the inferred type of the Observable when using `pluck`is `Observable<string>` not `Observable<string[]>` and additionally since ts supports safe null navigation it is recommended to use `map`over `pluck` as it is more performant

**Comment by niklas-wortmann** [comment]
As from my point of view this issue is already covered by the `map` operator I will close it for now. If there's anything new popping up, feel free to reopen it.

**Comment by matze1234** [comment]
I actually misunderstood the concept of pluck(), since i mistook from() for an of() in the example of pluck().

**Comment by matze1234** [comment]
By any chance, is there a shorter version for mapping arrays like so: 

```
source.pipe(
  map((persons) => personse.map((person) => person.name))
);

```
