### ISSUE TITLE
Fix operators that fail the synchronous firehose test

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#5658]
The following operators currently fail tests that were introduced in #5652 and those failing tests are currently skipped:

- [x] `catchError` - see #5655
- [x] `exhaust` - see #5743
- [x] `exhaustMap` - see #5743
- [ ] `multicast`
- [x] `raceWith` - see #5743
- [ ] `refCount`
- [x] `repeat` - see #5742
- [x] `repeatWhen` - see #5742
- [x] `retry` - see #5742
- [x] `retryWhen` - see #5743
- [ ] `share`
- [ ] `shareReplay`
- [x] `single` - see #5743
- [x] `skipLast` - see #5749
- [x] `throttle` - see #5749
- [x] `timeout` - see #5748
- [x] `timeoutWith` - see #5748

The tests are marked with `// TODO: fix firehose unsubscription` comments.

Update: [it's not going to be possible to make the `multicast`-based tests pass](https://github.com/ReactiveX/rxjs/pull/5749#pullrequestreview-495185071).

**Comment by josepot** [comment]
:wave: @kobelb 

This is the behavior that I would expect. Because `exhaustMap` will ignore any emissions from its source until the inner-observable hasn't completed. The code of the first example generates an emission into the source, before the inner observable has had a chance to complete. That's why I think that this should be the expected behavior.

> the inner observable isn't marked as completed when the next callback is called

Keep in mind that once an observable has completed, then it can no longer emit any values. So, it's not possible to complete before emitting the value. First it emits and after it completes :slightly_smiling_face:

One way to address that would be to observe the resulting observable of `exhaustMap` through the `asapScheduler`, like this:

```ts
const subject = new BehaviorSubject<number>(0);
const obs$ = subject.pipe(
  tap(() => console.log('before')),
  exhaustMap((val) => {
    return Promise.resolve(val * 100);
  }),
  observeOn(asapScheduler),
  tap(() => console.log('after')),
);

let i = 0;
obs$.subscribe(x => { 
  i++;
  console.log(x)
  if (i === 1) {
    subject.next(i); // the `exhaustMap` causes this to have no effect
  }
});
```

> It feels like these two code-paths should behave the same

I disagree. In the second snipped, the inner observable of `switchMap` creates a micro-task that ensures that when the resulting observable emits the source of `exhaustMap` has completed. The code that should be equivalent (and it is equivalent), if the inner-observable of `switchMap` was synchronous, like this:

```ts
const subject = new BehaviorSubject<number>(0);
const obs$ = subject.pipe(
  tap(() => console.log('before')),
  exhaustMap((val) => {
    return Promise.resolve(val * 100);
  }),
  switchMap((val) => {
    return of(val);
  }),
  tap(() => console.log('after')),
);
```

**Comment by miginmrs** [comment]
I had to make a change in ConnectableObservable by adding an internal method `prepare` to prepare the `connect` subscription before calling `connect`. I didn't understand why "it's not going to be possible to make the multicast-based tests pass".
