### ISSUE TITLE
BLM on homepage

### ISSUE THREAD

**Issue by LittleFox94** [ReactiveX/rxjs#5675]
Just needed some docs and saw the very big message on your homepage and ...

Thank you. Black lives matter!

(founds some negative issues here, wanted to make at least one positive. Sorry for spamming, but think this is important)

**Comment by benlesh** [comment]
Thank you for leaving a positive message, @LittleFox94! There's a couple of 👎 on this, and that's good. It gives a little bit of signal about the people who did that.

I'm going to close this issue, not because I don't like it, I love it... but because I'm trying to go through and clean up issues (which is hard to believe, given we have >300 of them 😬 )

**Comment by LittleFox94** [comment]
Thank you for keeping that open for some days, didn't expect that ^^

**Comment by benlesh** [comment]
FYI... I've blocked @ericmartinezr from the repository. I remember him specifically from when I was on the Angular team and he frequently trolled their repositories. I don't think they did anything about it, back then, but I'm very pleased to block him now. 

I just wanted people to know this wasn't a knee jerk, I've seen this same person do the same thing for over a year now.

Locking this thread to prevent more unnecessary interactions.
