### ISSUE TITLE
Change to dematerialize breaking types in Ngrx (and Google)

### ISSUE THREAD

**Issue by leggechr** [ReactiveX/rxjs#5706]
## Bug Report

**Current Behavior**
While updating Google I got compilation errors in some ngrx files related to dematerialize. The files and their errors are as follows:
https://github.com/ngrx/platform/blob/master/modules/effects/src/act.ts#L157
```
TS2345: Argument of type 'OperatorFunction<ObservableNotification<any>, any>' is not assignable to parameter of type 'OperatorFunction<Notification<OutputAction | ErrorAction | CompleteAction | UnsubscribeAction>, any>'.
  Type 'ObservableNotification<any>' is not assignable to type 'Notification<OutputAction | ErrorAction | CompleteAction | UnsubscribeAction>'.
    Type 'ErrorNotification' is missing the following properties from type 'Notification<OutputAction | ErrorAction | CompleteAction | UnsubscribeAction>': hasValue, observe, do, accept, toObservable

183                   dematerialize(),
                      ~~~~~~~~~~~~~~~
```

https://github.com/ngrx/platform/blob/master/modules/effects/src/effect_sources.ts#L71
```
TS2345: Argument of type 'OperatorFunction<ObservableNotification<any>, any>' is not assignable to parameter of type 'OperatorFunction<Notification<Action>, any>'.
  Type 'ObservableNotification<any>' is not assignable to type 'Notification<Action>'.
    Type 'ErrorNotification' is missing the following properties from type 'Notification<Action>': hasValue, observe, do, accept, toObservable

87           dematerialize()
             ~~~~~~~~~~~~~~~
```

**Comment by benlesh** [comment]
Need to make sure we have a dtslint test for `Observable<Notification<T>>` passing through `dematerialize()`.

**Comment by benlesh** [comment]
Core Team Meeting: Action item, get an ngrx team member to try v7.

**Comment by alex-okrushko** [comment]
I'll take care of it - it's the result of NgRx being a bit behind on syncs (I think)

**Comment by leggechr** [comment]
Is there any update on this @alex-okrushko? Or would anyone be able to help me to come up with a quick local mod workaround? It's blocking the google upgrade.

**Comment by cartant** [comment]
@leggechr Try this:

```ts
                  map((notification):
                    | NextNotification<ResultAction>
                    | undefined => {
                    switch (notification.kind) {
                      case 'E':
                        errored = true;
                        return { kind: 'N', value: error(notification.error, input) });
                      case 'C':
                        completed = true;
                        return complete
                          ? { kind: 'N', value: complete(projectedCount, input) })
                          : undefined;
                      default:
                        ++projectedCount;
                        return notification;
                    }
                  }),
```

**Comment by alex-okrushko** [comment]
### Objective

The goal for me was to refactor the NgRx code to work with both RxJS v6 and RxJS v7 through `materialize`/`dematerialize` operators.

### Problems

#### 1. [RxJS v6 `dematerialize` is expecting](https://github.com/ReactiveX/rxjs/blob/1e1e022ed9fdc4a4bfed63cf151887031ac57398/src/internal/operators/dematerialize.ts#L53) `Notification<type>` object as an input, while [RxJS v7 `dematerialize wants`](https://github.com/ReactiveX/rxjs/blob/c51a6e3265d3f25df0c0c3fc8f666acbe5fc745c/src/internal/operators/dematerialize.ts#L54) `ObservableNotification`.

The new `ObservableNotification` is just a union of `{kind: 'N', value: T} | {kind:'E', error: any} | {kind: 'C'}` and I like this change, because that's what is really needed for `dematerialize` to work, however the previously used `Notification` is the class that has more properties such as `hasValue` and methods such as `observe`, `do` and etc.

##### Why is this the problem?

Let's take a look at the example, where we want to catch the `error` and transform it into the `next` value:
```ts
input$.pipe(
  materialize(),
  map(notification => {
    if(notification.kind === 'E') {
      return createNextNotification(notification);
    }
    return notification;
  }),
  dematerialize(),
);
```

The `createNextNotification(...)` cannot just return the type of `{kind: 'N', value: any}` - it would be fine in v7, but v6 would complain that ([stackblitz example](https://stackblitz.com/edit/rxjs-xymf3x?file=index.ts)):
```sh
Type 'Notification<string> | { kind: "N"; value: any; }' is not assignable to type 'Notification<string>'.
    Type '{ kind: "N"; value: any; }' is missing the following properties from type 'Notification<string>': hasValue, observe, do, accept, toObservable`
```

##### Solution (bad solution - loosing types after `dematerialize`)

The solution is to cast the return type of the function to `Notification<any> & {kind: 'N': value: any}`
[Stackblitz example](https://stackblitz.com/edit/rxjs-jqnkek?file=index.ts)

```ts
declare function createNextNotification(
  input: any
): Notification<any> & { kind: "N"; value: any };
// making it `any` and future-proofing with additional NextNotification interface
```

#### 2. RxJS v6 `dematerialize` does NOT deal with unions well. RxJS v7 `dematerialize` is fine with unions, but changed the generic type.

If we continue with the solution above, we'll end up with `Obsevable<any>` after `dematerialize`.

> But I don't what `Observable<any>` after `dematerialize()`. I want to have the proper types.

If function `createNextNotification` returns the notification that carries the same value type as the incoming notification, then "it just works", but if it carries the value of a different type then **RxJS v6** struggles with it ([Stackblitz example](https://stackblitz.com/edit/rxjs-lz98du))

##### Solution 1 (not working because it would fail for v7)

One of the solutions was to provide the explicit generic type for the `dematerialize` operator:

```ts
  dematerialize<string|number>(),
```

However, the RxJS v7 takes a different generic (which is not so good, I think), so this solutions is **NOT** future-proof. Of course, the typings of v7 `dematerialize` could've been adjusted, but that's a longer shot and requires more syncing.

##### Solutions 2 (the ACTUAL solution)

The final solution without changing RxJS v7 would be do BOTH of the following:
- to provide the explicit return type of the `map` before it gets to `dematerialize`
- cast any untouched notification to the type that adds `ObservableNotification` interfaces
[Stackblitz example](https://stackblitz.com/edit/rxjs-28dvqc) works with v6
and **the same code** ([Stackblitz example](https://stackblitz.com/edit/rxjs-htfl2x)) that works for v7.

```ts
//           👇 source is correctly inferred as Observable<string|number>
const source = of("World").pipe(
  materialize(),
  map(
    (notification): Notification<string | number> &({
            kind: "N";
            value: string | number;
          }
        | { kind: "C" }) => {
      if (notification.kind === "E") {
        return createNextNotification(notification);
      }
      return notification as Notification<string> &({
              kind: "N";
              value: string;
            }
          | { kind: "C" });
    }
  ),
  dematerialize()
);

declare function createNextNotification(
  input: any
): Notification<number> & { kind: "N"; value: number };
```

It's ugly, but it works. I would've preferred to adjust the typing of `dematerialize` in RxJS v7 to allow `dematerialize<string|number>()` instead.

#### Final note

Even in the final solution, in the body of `createNextNotification` function we would need to some casting:
```ts
unction createNextNotification(
  input: any
): Notification<number> & { kind: "N"; value: number } {
  // EITHER of these solutions would work:
  // return new Notification("N", 5) as Notification<number> & { kind: "N"; value: number };
  return { kind: "N", value: 5 } as Notification<number> & {
    kind: "N";
    value: number;
  };
}
```

**Comment by alex-okrushko** [comment]
The adjustments to NgRx were also merged at Google, so its safe to close this one.

The comment above could be used as a reference for anyone who's migrating to v7.

**Comment by leggechr** [comment]
Thanks Alex!
