### ISSUE TITLE
Impose a minimum TS lib for version 7.

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#5708]
Because v7 has interop with `AsyncIterable`, we need to make sure TS users have a minimum `lib` setting of `es2018`.

Issue created for discussion.

Currently, with v7, TypeScript builds targeting ES2017 and under will have issues with typings because `ObservableInput<T>` includes `AyncIterable<T>` which isn't available unless you have a `lib` of ES2018 or greater.

One alternative might be to do some TypeScript type meta-programming to figure out if `AyncIterable` was available or not.

**Comment by benlesh** [comment]
Related, it would be great if our `esm` build was targeting ES2018, however, I don't think we can because the `esm` build is what Angular uses, and they can't move past ES2015 because of Zones. I've filed an issue for that so it can be tracked: https://github.com/angular/angular/issues/38782

**Comment by benlesh** [comment]
Also related: https://github.com/microsoft/TypeScript/issues/40462

**Comment by cartant** [comment]
I've had a quick look at this. Adding the triple-slash reference to `types.ts` - as [suggested here](https://github.com/microsoft/TypeScript/issues/40462#issuecomment-689879308) - does effect the reference in the generated `.d.ts` file, so manual manipulation of the `.d.ts` files is not required.

What we do need to do, though, is figure out just how the `lib` filenames work. I mean, there is no `lib.esnext.asynciterable.d.ts` in the TypeScript `lib` directory, as the type definition for `AsyncIterable` has not changed since the one that's in `lib.es2018.asynciterable.d.ts`. So does the `lib="esnext.asynciterable"` that's in Ryan's comment end up resolving to `lib.es2018.asynciterable.d.ts` ... 🤷‍♂️

**Comment by cartant** [comment]
It seems the value for the `lib` attribute is what would be passed to the [command-line option](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-lib-), so `lib="esnext.asynciterable"` is exactly what we want.
