### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by Chiragasourabh** [ReactiveX/rxjs#5733]
How to pass authentication headers while establishing websocket connection ? I have to pass through a security barrier with Basic auth token inorder to create a websocket connection with microservice. 
I already have a basic auth token generated through login . Now I can pass that token as param and establish websocket connection successfully . But it's not a secure way as token is directly visible in url param . 
What is the best way to achieve this using rxjs websocket . ?
Is there any way I can set request headers ? Like in other languages

**Comment by josepot** [comment]
:wave: @Chiragasourabh !

Unfortunately [the WebSocket API](https://html.spec.whatwg.org/multipage/web-sockets.html#network) doesn't provide a means for setting custom headers on the initial HTTP connection, and since the [RxJS webSocket](https://rxjs-dev.firebaseapp.com/api/webSocket/webSocket) is a:

> Wrapper around the w3c-compatible WebSocket object provided by the browser.

then it's not possible to set those custom headers.

The only hacky way -that I know off- for customizing a websocket header is to set a cookie before the connection, because the browser should set the cookies (that if CORS doesn't get in the way, of course). However, setting an auth token in the cookies is probably a bad idea security-wise (i.e CSRF attacks).

Another option is to use query-strings. However, that has another security drawback: most BE systems usually log urls of incoming requests immediately after SSL termination. So, unless you have the absolute guarantee that the same service that is doing SSL termination (e.g nginx) can convert that query-string into a http-header downstream before anything has the chance to log the original url, then you probably shouldn't do that either.

I'm afraid that auth over websocket connections is a pretty complex topic. Sorry, but I can't help you any further. In summary: it's not possible to set custom headers from the browser for websocket connections, that's why RxJS can't support that behavior for the `webSocket` wrapper.

**Comment by Chiragasourabh** [comment]
Hey @josepot ,
Thank you for the info. 
When you said setting basic auth token as cookie, before establishing connection, is the key name is X-Authorizaton or something else ?

**Comment by josepot** [comment]
> When you said setting basic auth token as cookie

Sorry, I guess that I didn't explain myself very well. I said that the only way -that I know off- for customizing the headers of the initial HTTP connection is to set a cookie. That's because when the browser creates the HTTP request for the handshake, it will set a number of standard headers. One of them being `Cookie`, which will contain the cookies that the browser is supposed to send to the server.

So, just to be clear: **it is not possible (using the Web API) to add custom entries on the headers of the initial handshake HTTP request of a WebSocket connection**. However, it is possible to alter the **value** of -at least- one of the entries that the browser may set: the `Cookie` header.

I hope this helps. Also, since this has nothing to do with RxJS, I think that you should consider closing this issue 🙁.

**Comment by benlesh** [comment]
It seems like this question has been answered. I'll close. Thank you for the question, @Chiragasourabh, and the assist, @josepot!
