### ISSUE TITLE
Potential testscheduler issue?

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#579]
While this snippet works

```
var expected = '----------0---------1---------2---------3---------4---------5---------6-----';
var unsub =    '^                                                                          !';
expectObservable(Observable.interval(100, rxTestScheduler), unsub).toBe(expected, [0,1,2,3,4,5,6]);
```

this doesn't, testScheduler hangs at some point and test does not completes.

```
var expected = '0123456';
var unsub =    '^     !';
expectObservable(Observable.interval(0, rxTestScheduler), unsub).toBe(expected, [0,1,2,3,4,5,6]);
```

Not sure if this is expected behavior of testScheduler or potential issue though.

**Comment by staltz** [comment]
Shouldn't the interval in the second case be `10`? But anyway, the hanging doesn't sound good. I recall having some hanging when the source Observable synchronously emits next values, and the internal timeFrame inside the TestScheduler doesn't progress. Makes some sense, though, because the time scale in the test scheduler is virtual, `10` time units is not `10ms`. It's just an arbitrary time unit, could be for instance `10years`, and in that case it make a lot of sense that it will hang if you are emitting synchronous events constantly, virtual time doesn't progress like you wish.

**Comment by kwonoj** [comment]
> Shouldn't the interval in the second case be 10?  

: I just write snippet in a hurry, so `expected` might not reflect actual expected values. Original intention was testing behavior of `Observable.interval(0)`

**Comment by kwonoj** [comment]
>  it make a lot of sense that it will hang if you are emitting synchronous events constantly, virtual time doesn't progress like you wish.

I agree in general, I also could observe some of cases like value emits synchronously and doesn't complete. Creating issue was for clarification, if this is somewhat acceptable behavior, I can pick traditional way of creating test case per this specific case or either drill down into testscheduler to make this work, currently lean on to use traditional way.

**Comment by staltz** [comment]
Yeah, I'd opt for testing without the testscheduler

**Comment by kwonoj** [comment]
Cool, closing issues :)
