### ISSUE TITLE
filter control flow

### ISSUE THREAD

**Issue by criskrzysiu** [ReactiveX/rxjs#5826]
lets say we 
```ts
    const subject = new Subject<string | null>();

    const stringOrNull$= subject.pipe(filter((str) => str != null));
    const nonNullObservable2 = subject.pipe(switchMap((str) => (str != null ? of(str) : EMPTY)));
```

- Here we would expect type of ```stringOrNull$``` to be ```Observable<string>``` as we are filtering out all null values but we actually get ```Observable<string | null>```. 
- But the type of ```nonNullObservable2```  is  ```Observable<string>```

we have same problems with 
```ts
   interface ValidationSuccess {
      isValid: true;
      reason: null;
    }

    interface ValidationFailure {
      isValid: false;
      reason: string;
    }

    type ValidationResult = ValidationSuccess | ValidationFailure;

    const subject2 = new Subject<ValidationResult>();
    const validationResult$ = subject2.pipe(filter((obj) => obj.isValid));
    const validationSuccess$ = subject2.pipe(switchMap((obj) => (obj.isValid ? of(obj) : EMPTY)));
```

- ```validationResult$``` is ```Observable<ValidationResult >```
- ```validationSuccess$``` is ```Observable<ValidationSuccess>```

same will happen for other control flows checks done by ts like
```ts
type Easing = 'ease-in' | 'ease-out' | 'ease-in-out';

    const subject3 = new Subject<Easing>();
    const withEaseOut$ = subject3.pipe(filter((easing) => easing !== 'ease-out'));
    const withoutEaseOut$ = subject3.pipe(switchMap((easing) => (easing !== 'ease-out' ? of(easing) : EMPTY)));
``` 
- ```withEaseOut$``` is ```Observable<'ease-in' | 'ease-out' | 'ease-in-out'>```
- ```withoutEaseOut$``` is ```Observable<'ease-in' | 'ease-in-out'>```

Wouldn't it be better to change current implementation of filter operator to just combination of switchMap as in example or change typing of filter operator mayby?

**Comment by josepot** [comment]
Hi @criskrzysiu ,

This is a "limitation" of TypeScript. Even if the `filter` operator was internally implemented with `switchMap` TypeScript wouldn't be able to infer what's the type that has to be excluded. For instance, even with this code:

```ts
type Easing = 'ease-in' | 'ease-out' | 'ease-in-out';

const subject = new Subject<Easing>();

const customFilter = <T>(filterFn: (val: T) => boolean) =>
  switchMap((val: T) => filterFn(val) ? of(val) : EMPTY);

const withEaseOut$ = subject.pipe(customFilter((easing) => easing !== 'ease-out'));
```
`withEaseOut$`'s type would be `Observable<'ease-in' | 'ease-out' | 'ease-in-out'>`

Notice that `Array.filter` also suffers from [this exact same issue](https://www.typescriptlang.org/play?#code/C4TwDgpgBAoghgZwJYDsDmUC8UDkFEQC0qOUAPrvgkQPYCuwpFeBxKh9jA3AFA8DGNFAmBRgEEQC4oAQQBOcuCAA88ZOgB8WKAG0W1NjgA0lVqg4Njpg5xwBdAUJFQ5EugBtR2cSIB0AMyRPCDkAClCANzh3OggASiwtKJjoAEJMbH0iEjigA), which is why TS provides the [`is` keyword](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards), so that we can [help TS infer the resulting type of a `filter`](https://www.typescriptlang.org/play?ssl=4&ssc=73&pln=4&pc=35#code/C4TwDgpgBAoghgZwJYDsDmUC8UDkFEQC0qOUAPrvgkQPYCuwpFeBxKh9jA3AFA8DGNFAmBRgEEQC4oAQQBOcuCAA88ZOgB8WKAG0W1NjgA0lVqg4Njpg5xwBdAUJFQ5EugBtR2cSIB0AMyRPCDkAClCANzh3OggASmkomOgkBFgAD34YgBMIVURUNBN9IhItTC0k2KgAQkxsEsM4oA)

So, the way to handle this would be to write your code like this:

```ts
const validationResult$ = subject2.pipe(filter((obj): obj is ValidationSuccess => obj.isValid));
```

Also, maybe you would find this operator that I made useful :wink: :

```ts
type Diff<T, U> = T extends U ? never : T;

export default function filterNonFalsy<T>(): (
  x: Observable<T>
) => Observable<Diff<T, null | undefined | false | 0 | 0n | ''>> {
  return filter(Boolean as any);
}
```

**Comment by cartant** [comment]
As mentioned above, you need to use a [user-defined type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) so that [this signature](https://github.com/ReactiveX/rxjs/blob/adbe65e659bbf17f6ab20a9b30fcca0e4d76af9a/src/internal/operators/filter.ts#L7) is matched and the non-nullable return type is inferred:

```ts
const result = subject.pipe(filter((str): str is string => str != null));
```

Or you can use `Boolean` to match [this signature](https://github.com/ReactiveX/rxjs/blob/adbe65e659bbf17f6ab20a9b30fcca0e4d76af9a/src/internal/operators/filter.ts#L9):

```ts
const result = subject.pipe(filter(Boolean)); // Observable<string>
```

**Comment by josepot** [comment]
> Or you can use Boolean to match this signature

Nice!!!

Although, AFAICT that's not yet available on the stable release... it's only available on the beta version of v7. On v6 the type would be `Observable<unknown>`

I'm very excited about the release of v7!

**Comment by criskrzysiu** [comment]
@josepot  yeah I use similar operator but wanted to make sure it is not possible to infer proper type. I did play with conditional types as with infer and B extends boolean and conditional types and infer but with no luck so far.
