### ISSUE TITLE
Export an operator subscriber for user-land operators and refine Observable ctor

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#5836]
ATM, it's not possible - without subclassing `Subscriber` - for user-land operators to correctly chain the `closed` property of the subscriber received by the `Observable` ctor's callback.

We should export something like the internal `OperatorSubscriber`, to facilitate the more straightforward creation of user-land operators. IMO, we should export something that accepts callbacks using a config object - rather than the positional arguments.

Also, as raised in #2314, we should use a narrower type - e.g. a `SubscriberLike` - that does not expose as many implementation details as `Subscriber`.

**Comment by kwonoj** [comment]
Some months ago core team meeting had discussed similar to this - make `Observable` itself as strongly public interfaced one which can create operators, and all of `rxjs` operator itself try to utilize it to create operators instead of rely on some internals. Discussion concluded we'd like to setup monorepo-ish (yes, again) to make `rxjs/Observable` itself as explicitly seperated import site operators can import.

In my opinion, regardless of publishing `rxjs/observable` or not - it may worth to explore these paths in a long run. I wanted to try this after we get concluded how to organize our repo for separated packages. (then we can make observable as internal packages to all operator enforced to follow its public interfaces)

Not directly related, but I guess this is somewhat related topics.

**Comment by cartant** [comment]
Closed in favour of #5863.
