### ISSUE TITLE
Behavior subject's value is not updated correctly within the tap operator

### ISSUE THREAD

**Issue by markostanimirovic** [ReactiveX/rxjs#5855]
## Bug Report

![rxjs-state-mgmt-bug](https://user-images.githubusercontent.com/17877290/97115717-75dc3b80-16f8-11eb-8b8d-87e315fa7134.gif)

**Current Behavior**

Every time when `selectedPageSize$` emits a new value, state is updated with `loading` set to `true`, then the data is taken from `todosService` and state is updated with new data and `loading` set to `false`:

```typescript
this.selectedPageSize$
  .pipe(
    tap(() => this.patchState({ loading: true })),
    switchMap(pageSize => this.todosService.getTodos(pageSize)),
  )
  .subscribe(todos => this.patchState({ todos, loading: false }));
```

As you can see in the screenshot, it works fine on first emission, but on each subsequent emission, when `loading` is set to `true` within the `tap` operator, it is immediately set to `false`.

**Reproduction**

1. Clone https://github.com/markostanimirovic/rxjs-state-mgmt-bug
2. Run `npm install` and `ng serve --open`
3. Repeat the steps from the screenshot above

**Expected behavior**

`loading` should not be set to `false` immediately after it is set to `true`.

**Environment**
- Node v12.18.2
- RxJS v6.6.0
- Angular v10.2.0

**Possible Solution**

Open `todos.facade.ts` file. Comment out all expressions above the `/** workaround **/` comments, uncomment all expressions bellow the `/** workaround **/` comments.

**Comment by elpddev** [comment]
Hi @markostanimirovic . I am not a maintainer.  It interesting. I would be easier to look at and less time consuming if it was online on codesandbox/stackblits.

**Comment by alexsherekin** [comment]
Hi @markostanimirovic . This case is very curious. I'm not a maintainer either, but I'd say it works as intended. 
You emit values from the subscription handler, which leads to this behavior and this is rather a bad design, that a problem in RxJS.

After some debugging I found out the following behavior:
- you emit value from `updateSelectedPageSize` method
- this causes `selectedPageSize$` observable to emit as well (there are 6 observers listening to the `store` BehaviorSubject and `selectedPageSize$` is the first of them, so it's being called as the first) 
- this causes `patchState` to be called and emit another value (so now we are in the nested handling cycle)
- all 6 observers are being notified about this change
- the nested cycle finishes and other 5 observers of the first change are being notified

That's why you first get `loading: true` and right after it `loading: false`, although the actual value in the `store` is still `true`.

As another workaround you could call the nested `patchState` asyncronously, like this
```typescript
this.selectedPageSize$
      .pipe(
        tap(() => **setTimeout**(() => this.patchState({loading: true}), 0)),
        switchMap(pageSize => this.todosService.getTodos(pageSize)),
      )
      .subscribe(todos => this.patchState({todos, loading: false}));
```

**Comment by kwonoj** [comment]
I'll close as above answered adequately. RxJS currently does not guarantees synchronous reentrant and caller should take care of escaping it explicitly.
