### ISSUE TITLE
finalize documentation doesn't mention it runs on unsubscribe

### ISSUE THREAD

**Issue by basro** [ReactiveX/rxjs#5856]
### Documentation Related To Component:

finalize

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

`finalize` documentation doesn't mention that it will run on unsubscribe.
This was previously reported in issue #4578 but it was closed and the issue remains.

**Comment by cartant** [comment]
FWIW, the referenced issue was closed because the documentation in `master` - i.e. the version 7 codebase - was updated:

https://github.com/ReactiveX/rxjs/blob/79da549d33da2e7a2677e44c2371e88701c40c41/src/internal/operators/finalize.ts#L5-L7

However, as version 7 has not yet been released, the docs site shows the version 6 docs.

**Comment by cartant** [comment]
Closing this 'cause version 7 has been released.
