### ISSUE TITLE
`onErrorContinue` like reactor core in java

### ISSUE THREAD

**Issue by nomi-ramzan** [ReactiveX/rxjs#5891]
## Feature Request

**Is your feature request related to a problem? Please describe.**
catch an error from anywhere from stream same like 'onErrorCountinue`

**Java Example**

```java
Flux.range(1, 5)
  .flatMap(n -> {
    if (n == 3) return Mono.error(new Throwable("StoppedError"));
    return Mono.just(n);
  })
  .map(n -> n + n)
  .flatMap(n -> {
    if (n == 8) return Mono.error(new Throwable("StoppedError"));
    return Mono.just(n);
  })
  .onErrorContinue((throwable, o) -> {
    System.out.println("error with " + o);
  })
```
Error can come from any point, all error will go to one place, and main stream will continue

**Comment by cartant** [comment]
You can do this using `publish` and `catchError`:

```ts
import { of, range } from "rxjs";
import { catchError, flatMap, map, publish } from "rxjs/operators";

range(0, 10).pipe(
  publish(source => source.pipe(
      flatMap(value => of(value)),
      map(value => {
        if (value === 3) {
          throw new Error("Threes are the worst!");
        }
        return value;
      }),
      flatMap(value => of(value)),
      catchError((error: unknown, caught) => {
          console.log(error);
          return caught;
      })
  ))
).subscribe(value => console.log(value));
```

You could use this combination of `publish` and `catchError` in a user-land operator - to which you'd pass a selector, much like the one received by `publish`.

Closing this because we favour new features being implemented in user-land before being considered for inclusion in the code - which we'd like to make smaller, rather than larger.
