### ISSUE TITLE
I love you support BLM but how about putting words into action and help black people/minorities code

### ISSUE THREAD

**Issue by xtianus79** [ReactiveX/rxjs#5947]
You have a great platform and if you support the BLM movement help black and other minorities learn to code. If you're interested I would be interested in helping you with that project. As a minority coder it is hard to break barriers and get into the industry. 

It would be a greatly beneficial project. 

Thanks

**Comment by delafer** [comment]
someone (not me, of course) might think, that "highly likely" or "almost certainly" they are hidden racists, unlike Hollywood where there are some quotas for black actors -> RxJs Team doesn't have any black developers in a core team. looks like a creepy discrimination. 
I don't see any black guys in RxJS core team, but may be I just missed something?

**Comment by tonymet** [comment]
@xtianus79 – have you heard back?

**Comment by damusix** [comment]
Elections are over guys. Can we take politics out of work again?

**Comment by benlesh** [comment]
@xtianus79 this is an open source project, we're always happy to have your contributions, and we'll do our best to foster an environment where you feel comfortable doing so. I imagine it would be helpful to offer mentorship, but unfortunately, since this is an all-volunteer group the time any of us has to work on this project is limited. However, if you find an issue you'd like to work on, and you decide to put in a PR, I'll do my best to provide constructive feedback to help you be successful with your PR.

Thanks.

**Comment by KamilSocha91** [comment]
I am not from United States and country where I was born never been involved into slavery. 

So that's hard for me to understand racism...
However from my perspective USA peoples treat minorities like they would be disabled, isn't it racist approach?

Btw. Supporting disabled peoples would be much more clear and responsible in my opinion.

**Comment by niklas-wortmann** [comment]
In all honesty, it's always interesting for me to see that people say racism is a US only problem. I am not from the USA either and I have put the statement there. There might not be this level of systematic racism in other countries but in most countries there is still a general problem with racism.

@KamilSocha91 I can really recommend checking out the resources mentioned on the homepage.

**Comment by kwonoj** [comment]
I believe @benlesh answered main question in here, this is open source project where we welcome contributions and trying to help as much. I'll close this for now.
