### ISSUE TITLE
RxJS 7 allow to call 'next' without parameters (Typescript checks).

### ISSUE THREAD

**Issue by ievgennaida** [ReactiveX/rxjs#6324]
## Bug Report

**Current Behavior**
I am using update subject only as a signal, without any arguments. 
```
const updateSubject = new Subject();
updateSubject.next();
```
With the latest version this gives typescript check error that argument for the next is mandatory.
But I don't want to pass any. 

This gives typescript error:
```
TypeScript error in react.tsx(500,51): TS2554
Expected 1 arguments, but got 0.
t.updateSubject.next();
```

**Expected behavior**
Code should allow to call next without any arguments.

**Environment**
- Runtime: Chrome
- RxJS version: 7.0.0
- TypeScript checks

**Possible Solution**
Allow to pass no arguments.

**Comment by cartant** [comment]
```ts
const updateSubject = new Subject<void>();
updateSubject.next();
```

**Comment by benlesh** [comment]
@ievgennaida this is expected behavior. `new Subject()`, on it's own is a `Subject<unknown>`, which means next expects to be called with `next(unknown)`. If you don't want to pass an argument, you need to make sure that you have a `new Subject<void>()` or a `new Subject<void | SomeOtherTypeHere>()`, as @cartant recommended above.

**Comment by ievgennaida** [comment]
@benlesh thank you.

**Comment by rosslovas** [comment]
`new Subject()` is incorrectly documented as `Subject<void>` in https://rxjs.dev/guide/subject#void-subject.
