### ISSUE TITLE
Generic Typedef Issues with Operators

### ISSUE THREAD

**Issue by robwormald** [ReactiveX/RxJS#635]
Will investigate this further tomorrow, but:

Imagine I have an Observable of Foos:
```typescript
interface foo {
  bar: string;
}
let o: Observable<foo> = new Observable(obs => {});

```
If I .subscribe, I get (as expected) the generic passed through appropriately:
```typescript
o.subscribe( v => {
  return v.bar //ok - v is appropriately cast to foo
});
```

however, if I use .map() 
```typescript
o.map( v => {
  return v.bar; //error! v is cast to any here.
});
```
I would expect the parameter passed into an operator (in this case, the project function) to maintain the cast type, no? Obviously the return from a map function is different, but looks like there's a bit of a snafu on typedefs here.

**Comment by robwormald** [comment]
Interestingly, the *return* from .map() is cast appropriately:

```typescript
//force cast to foo
o.map((v:foo) => {
  return foo.bar; //bar is string
}).subscribe(v => {
  v //string!
})
```

**Comment by kwonoj** [comment]
> I would expect the parameter passed into an operator (in this case, the project function) to maintain the cast type, no?

I agree, I think this is somewhat unexpected.
This seems happening due to source's type constraint is not being passed to operator declared via prototype. So in this case, `o` is `Observable<foo>` as expected, but `o.map` becomes `o.map<{}, any>`. 

If explicitly specify type constraint per operator like `o.map<foo, string>` then projection function won't complain, but this is obviously something we do want. Question might be how to pass type constraint into prototype - might need to investigate.

**Comment by kwonoj** [comment]
I'm considering this is related with https://github.com/ReactiveX/RxJS/issues/608.

**Comment by robwormald** [comment]
cheers OJ, thanks for checking on it.

**Comment by kwonoj** [comment]
no luck with some immediate tryout, I'll try few more and update further.

**Comment by kwonoj** [comment]
Think I can prepare PR for this issue around today - tomorrow. I came to feel better modularity strategy will resolve this much more clean way, but that's further story. Will work on this scope as immediate issue.
