### ISSUE TITLE
observeOn(asyncScheduler) is leaking memory

### ISSUE THREAD

**Issue by Vikasg7** [ReactiveX/rxjs#6458]
I wanted to use the async version of `Rx.range` so I tried `Rx.range(1, 2 ** 32, Rx.asyncScheduler)` but got to know this syntax is being deprecated so went on to use `observeOn(Rx.asyncScheduler)` syntax. After a  few seconds, my Nodejs process crashed with `couldn't allocate memory` error. I am successful in reproducing the bug in the plnkr below. After you run the code, you will see your tab go unresponsive and memory consumption for google chrome in the task manager will jump to the max until it eats up all the memory.

Here is the [plnker](http://plnkr.co/edit/aRKSublOq7xRKNzG).  

Version info  
Rxjs: 7.1  
Nodejs: 16.2.0
Chrome: 91.0.4472.77

**Comment by kwonoj** [comment]
I may be incorrect, this looks like we are creating asyncaction in synchronous (due to range is synchronus) for the observeon so it fills up memory before fully tear down.

**Comment by backbone87** [comment]
is this solvable at all? seems like it's just not possible without the scheduler directly involved in the origin observable. i would argue however that the deprecated execution path may only work in these cases where the rest of the downstream pipe is sync, so the async emission is consumed and GCed immediately, else the scheduled actions would also pile up. (though this may take a while since it takes a whole while until 2 ** 32 ticks are ran.

**Comment by voliva** [comment]
Yep, from the first looko I don't think it's an issue specific from rxjs....  This code:

```js
Rx.range(1, 2 ** 32).pipe(
  RxOp.observeOn(Rx.asyncScheduler),
).subscribe()
```

What it essentially does is:

```js
for (let i=1; i<= 2**32; i++) {
   setTimeout(() => {
       return i; // do whatever with i - In rxjs this would continue down the pipe
   })
}
```

> I wanted to use the async version of `Rx.range`

What do you mean by "async version of Rx.range"? If you mean that the emissions shouldn't happen synchronously but over time, have you tried `interval(0)`?

**Comment by Vikasg7** [comment]
By async, I meant this `Rx.range(1, 2**32, Rx.asyncScheduler)` which is working perfectly fine without leaking any memory. As this is being deprecated in the near future, I used `observeOn` which is not behaving the same.  
`interval(0)` is not self-explanatory/self declarative in my case like `range(start, end/count)` is and I can't stop the interval without adding an extra step in my observable chain. However, it seems like 'to be deprecated' range and interval are following almost the same logic difference being range has a way to stop itself and interval doesn't.

**Comment by josepot** [comment]
> is this solvable at all? seems like it's just not possible without the scheduler directly involved in the origin observable.

Using `scheduled`, while passing a lazy iterator as the observable-like argument would do the trick, i.e:

```ts
function* makeRangeIterator(start = 1, end = 100, step = 1) {
  let iterationCount = 0;                                    
  for (let i = start; i < end; i += step) {                  
    iterationCount++;                                        
    yield i;                                                 
  }                                                          
  return iterationCount;                                     
}                                                            
                                                             
const foo$ = scheduled(makeRangeIterator(1, 2 ** 32), asyncScheduler); 
```

Although, I agree with @voliva, I would probably use `interval(0)`:

```ts
const foo$ = interval(0).pipe(
  map((_, idx) => idx + 1),
  takeWhile(x => x < 2 ** 32)
)
```

**Comment by Vikasg7** [comment]
@josepot  `scheduled` version looks very declarative and neat. But what stops me to expect the following version to work the same which leaks memory.
```javascript
Rx.scheduled(Rx.range(1, 2 ** 32), Rx.asyncScheduler)
```
Also, the fact that `scheduled` expects `ObversableLike` as the first argument.

**Comment by backbone87** [comment]
Just to reiterate:
- There are no memory leaks in either case. You instruct the observable to produce 2 ** 32 next notifications without pause or backpressure and it does exactly that. The fact that this does not cause OOM errors depends solely on the downstream pipe:
  - If the downstream pipe is sync then you will be in a long "normal" loop
  - If the downstream pipe is async (e.g. via `observeOn`) then the next notifications are queued without backpressure which causes OOM.
- That the deprecated way of passing the scheduler or using `scheduled` + ES iterator works is just a "coincidence", because instead of emitting 2 ** 32 next notifications synchronously, they are emitted one per tick. Again if the downstream pipe is async you may run into OOM errors.
- Infinite iterations work with ES iterators because they are pull streams and not push streams. You can convert observables into pull streams by introducing a control loop that handles backpressure (read: "send next notification only when the current notification reached a certain point in the downstream pipe").

Using an "infinite" observable that does not have some form of backpressure control (like when converting a socket to an observable, or just a timer with `interval`) is most likely an anti-pattern.
