### ISSUE TITLE
Bug: Off-by-one error with retry's count parameter

### ISSUE THREAD

**Issue by staltz** [ReactiveX/RxJS#674]
### This is what should happen (this is RxJS 4 behavior):

```js
var source = Rx.Observable.of('foo')
  .repeat(3);

source.subscribe(
  x => console.log(x), 
  e => console.error(e.message), 
  () => console.log('|'));
```
```
"foo"
"foo"
"foo"
"|"
```

```js
var source = Rx.Observable.of('foo')
  .concat(Rx.Observable.throw(new Error('ERR')))
  .retry(3);

source.subscribe(
  x => console.log(x), 
  e => console.error(e.message), 
  () => console.log('|'));
```

```
"foo"
"foo"
"foo"
"ERR"
```

- - -

### But currently RxJS 5 does this (notice the off-by-one error with retry()):

```js
var source = Rx.Observable.of('foo')
  .repeat(3);

source.subscribe(
  x => console.log(x), 
  e => console.error(e.message), 
  () => console.log('|'));
```
```
"foo"
"foo"
"foo"
"|"
```

```js
var source = Rx.Observable.of('foo')
  .concat(Rx.Observable.throw(new Error('ERR')))
  .retry(3);

source.subscribe(
  x => console.log(x), 
  e => console.error(e.message), 
  () => console.log('|'));
```

```
"foo"
"foo"
"foo"
"foo"
"ERR"
```

**Comment by jinroh** [comment]
[I've been bitten by this](https://github.com/Reactive-Extensions/RxJS/issues/234) too, but with the RxJS4 behaviour :). I feel the RxJS5 signature is more natural, because it counts to number of retries and not the total number of subscriptions.

However, retro-compatibility might be more important on this one... as long as the documentation is clear.

**Comment by staltz** [comment]
I'd either make both `repeat(3)` and `retry(3)` show 'foo' 4 times, or both show 'foo' 3 times, but the disparity would become a gotcha that annoys developers.

**Comment by blesh** [comment]
I'm indifferent about this behavior.

Although this is a weird one for readability, when (in the world outside of Rx) I think "Do X, and retry up to 3 times if it fails" I expect X to be executed up to 4 times, because the *first* one isn't a "retry", right?


However, if I say "Do repeat X three times", I expect X to be executed 4 times, because the first one counts as a repeat.

**Comment by blesh** [comment]
I think as long as the `repeat` semantic matches the RxJS 4 behavior, we're good. That one is important because that's something where people are acting in the affirmative.

The `retry` one I think should work as people would expect, where the first execution does not count as a retry.

**Comment by staltz** [comment]
Anyway, it's yet another breaking change with questionable benefits.

**Comment by blesh** [comment]
You do realize this "breaking change" appeared because the author of that operator (I don't think it was me, actually) thought that was how RxJS 4 behaved because it's really the only way that makes sense?

I really don't care if we change to. But if we're going to change it we need to update the docs to say something like:

"retry(3) actually only retries 2 times, this is to match what RxJS 4 does".

**Comment by trxcllnt** [comment]
I remember something funny with "retry(1)" throwing a stack overflow exception in RxJS v4, but my memory may be foggy. I vote for the, "do this once, and retry it x times" behavior for both repeat and retry.

**Comment by staltz** [comment]
> I vote for the, "do this once, and retry it x times" behavior for both repeat and retry.

I also think this makes more sense.

In order of "makes most sense" to "makes less sense", this is what I think:
- repeat(3) does it once and repeats +3 times, retry(3) does it once and retries +3 times
- repeat(3) does it 3 times in total, retry(3) does 3 times in total
- repeat(3) does it 3 times in total, retry(3) does it once and retries +3 times

**Comment by blesh** [comment]
Retry and Repeat are semantics for two _very_ different completion types. There is no logical reason why their output counts should be related.

- completion happens *after* the side-effect occurs. 
- errors happen *before* the side-effect occurs. 

If we read the operators as "try and if it errors retry 3 times" and "repeat 3 times". The current behavior makes sense.

I just checked... in RxJava retry and repeat work just like it does _right now_ in RxJS 5.

> repeat(3) does it once and repeats +3 times

That doesn't make any sense... because `Observable.of('x').repeat(1)` is you saying "repeat 'x' 1 time", not "repeat 'x' 2 times".

> retry(3) does 3 times in total

Doesn't make any sense... because `myObservable.retry(1)` _doesn't retry anything_ in RxJS 4. How could `retry(1)` not at least "retry once"?

> repeat(3) does it 3 times in total, retry(3) does it once and retries +3 times

That's the one that makes the most sense.

**Comment by staltz** [comment]
IMHO.

**Comment by blesh** [comment]
> I vote for the, "do this once, and retry it x times" behavior for both repeat and retry.

That's fine. However that is a breaking change for _two_ operators vs RxJS 4.

I'm okay with this though, because `retry(1)` not doing anything makes the least sense of all available options. And if that's the compromise that needs to be made to keep that from happening, so be it.

However I'd like to leave this issue open for a while for more input.

**Comment by blesh** [comment]
closing in favor of separate discussion issues.
