### ISSUE TITLE
You can't scroll on documentation website if you click outside the content area

### ISSUE THREAD

**Issue by lukonik** [ReactiveX/rxjs#6831]
### Describe the bug

Whenever you are on documentation website for example on this page https://rxjs.dev/guide/scheduler and you click outside the content area, like here. the mouse wheel scroll is disabled. you need to click in the content area again to be able to scroll again.
![image](https://user-images.githubusercontent.com/81145822/154655970-19638ac7-04bb-407b-9d37-00f1a8638559.png)

### Expected behavior

It should scroll nonmatter where you click

### Version

7.1.1

**Comment by benlesh** [comment]
I looks like this can be resolved by removing `bottom: 12px` on the `.toc-container` class.

cc @jakovljevic-mladen do you think you can take care of this one?

**Comment by jakovljevic-mladen** [comment]
@lukonik, IMO, this is not a bug. The area where you're trying to scroll is the contents area and it isn't/shouldn't be scrollable. @benlesh, removing `bottom: 12px;` from the mentioned class would break pages with a large number of items in this area, such as [this one](https://rxjs.dev/6-to-7-change-summary).

Since the docs originated from the Angular, it's always a good idea to compare behavior in Angular docs. [For example](https://angular.io/guide/routing-overview), scrolling is disabled there as well.

**Comment by benlesh** [comment]
@jakovljevic-mladen I see what you mean. 🤔 

It seems like we could have that area grow to fit the space though, instead of being fixed with `bottom: 12px`. Like with `max-height: 100%`, maybe?

**Comment by benlesh** [comment]
Ugh, it looks like max-height is being set dynamically at the moment. :\ That's not the nicest thing. haha. I'm not sure if this issue is worth the time it would take to resolve it. It's the first complaint we've gotten.

**Comment by lukonik** [comment]
I was reading the docs from start to end during the whole week and sometimes it was irritating :D, and from my point of view, it's a natural behavior to be able to scroll. But definitely doesn't worth much effort. 
Moreover, if I'm the only guy who is complaining, I already finished reading soo nvm :D
