### ISSUE TITLE
docs: https://rxjs.dev/guide/installation#cdn link error

### ISSUE THREAD

**Issue by lecepin** [ReactiveX/rxjs#6897]
### Describe the bug

open https://rxjs.dev/guide/installation#cdn

<img width="906" alt="image" src="https://user-images.githubusercontent.com/11046969/158514705-8887592a-c575-4080-873f-007ee0837054.png">

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/11046969/158514772-1d531757-186d-4563-863d-b06601f8f6a5.png">

### Expected behavior

normal access

### Version

Current online environment

**Comment by jakovljevic-mladen** [comment]
This is exactly what I was talking about [here](https://github.com/ReactiveX/rxjs/issues/6544#issuecomment-982709910). We need to convert such link syntax to another one - having links with `{@link }` syntax makes it possible to get a warning (or even error) about non existing documents when build the docs.

However, this has been fixed in [#6548](https://github.com/ReactiveX/rxjs/pull/6548/files#diff-629e40c820275f0431b1019a131a6f9a46c82bbfa0fc0a4fb676f5ae3d8321f4R6), so I'm gonna close this for now - we're still waiting for the latest docs app to be published publicly. Thanks for reporting.

**Comment by lecepin** [comment]
Hi @jakovljevic-mladen, I would like to join [ReactiveX](https://github.com/ReactiveX) Organization, how can I join? 

thanks.

**Comment by jakovljevic-mladen** [comment]
Hi @lecepin, that's a bit hard to answer. If you want to contribute to RxJS, I could try to help.

**Comment by lecepin** [comment]
Yes, I really like Rx, and I hope I can contribute to it.

thanks @jakovljevic-mladen .
