### ISSUE TITLE
exhaustAll marble diagram references deprecated exhaust function

### ISSUE THREAD

**Issue by mlegenhausen** [ReactiveX/rxjs#6909]
### Describe the bug

The marble diagram in the description references the deprecated "exhaust" function.

### Expected behavior

The text "exhaust" needs be changed to "exhaustAll" in the `exhaust.png` and resulting from that the file should be renamed to `exhaustAll.png`.

### Reproduction URL

https://rxjs.dev/api/operators/exhaustAll

### Version

7.5.5

**Comment by jakovljevic-mladen** [comment]
@timdp, I will need some help from you with this one. The [current](https://github.com/ReactiveX/rxjs/blob/7.5.5/docs_app/src/assets/images/marble-diagrams/exhaust.png) marble diagram for `exhaustAll` operator looks like this:

![image](https://user-images.githubusercontent.com/28087049/171050778-7a04a689-f7d4-415f-a5dd-6624d58f102d.png)

I need to create the second "inner" Observable with opacity applied. Is it possible with Swirly package to apply opacity to a single inner Observable and if it is, can you give me an example how to do it? Of course, if you have time to open a PR instead, feel free to do it.

**Comment by timdp** [comment]
I think you should be able to change the stroke and individual fill colors. Lowering the opacity doesn't seem like the best idea since it might reveal overlapping strokes. HSL color notation should help though.

That said, it's probably going to be tedious to do it by hand. You'll probably want to use the JS API and automate the color computations. I'll also give some thought to making it easier through styling.
