### ISSUE TITLE
Text on marble diagrams have some ugly artifacts

### ISSUE THREAD

**Issue by tyilo** [ReactiveX/rxjs#7089]
### Describe the bug

Text on all marble diagrams on the https://rxjs.dev/ website doesn't look very nice as there are some artifacts below most letters.

Example from https://rxjs.dev/api/index/function/takeUntil:
![](https://i.imgur.com/NFgdL3Q.png)

Zoomed in:
![image](https://user-images.githubusercontent.com/568036/196434962-ccacefc1-8dff-444d-876e-84bd1febeaf4.png)

### Expected behavior

The text should not have these weird artifacts.

### Version

7.5.7

**Comment by jakovljevic-mladen** [comment]
Hey @tyilo, thanks for reporting this. We are aware of this issue and we would like to update every marble diagram we have in the repository, but this is something that requires quite a lot of effort. If you have enough time, feel free to open PRs to update these images. We now have a new and better way of creating marble diagram images. For the reference, I'm gonna post a couple of PRs here to check how to do it: #6636 #6742 #6638 #6983

Also, I'm gonna close this issue since GitHub issues are intended to be used for bugs in the library core. If needed, we can open a new discussion where we could write (and track progress) of all marble diagram images that need to be updated.
