### ISSUE TITLE
Timeout : throw error with Subject, even after data emitted by Subject 

### ISSUE THREAD

**Issue by Rebolon** [ReactiveX/rxjs#7142]
### Describe the bug

Following documentation, i expect that opertor "timeout" emit an Error only if no data has been emitted after a delay.
With an operator like "of" or "interval", it works well. But with a Subject, even after a data is emited, the timeout will throw an Error. 

### Expected behavior

If the Subject emit something in the expected delay, there should not be any Error from the timeout operator

### Reproduction URL

https://stackblitz.com/edit/rxjs-uwysqx?file=index.ts

### Version

7.5

**Comment by Andrei0872** [comment]
Hi @Rebolon,

I think the answer as to why an error occurs can be found with the help of the other 2 examples(`of` and `interval`):

* `of`:  it emits a value and then **immediately completes** within 1s
* `interval`: will keep on emitting values once every 500ms, so it's still acceptable for `timeout`'s 1s

In the Subject example:

```typescript
const subject = new ReplaySubject(1);
subject.pipe(timeout(1000)).subscribe({
  next: (value) => console.info('ReplaySubject next', value),
  complete: () => console.info('ReplaySubject complete'),
  error: (err) => console.info('ReplaySubject error', err),
});
subject.next('new value');
```

Notice that you only emit a value and **that's all**. What's actually happening [under the hood](https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/timeout.ts#L373) is that the `timeout`'s **internal timer will reset** after a value has been received from the source. The relevant lines are these:

```typescript
// When receiving a value from source:

// clear the timer so we can emit and start another one.
timerSubscription?.unsubscribe();
seen++;
// Emit
subscriber.next((lastValue = value));
// null | undefined are both < 0. Thanks, JavaScript.
each! > 0 && startTimer(each!);
```

So, the problem comes from the fact that after receiving the first value from the Subject(i.e. `'new value'`), `timeout` will restart its timer, but the Subject will **no longer emit** values at all, so `timeout` will throw.

**Comment by Rebolon** [comment]
Thank for the answer. So now i understant that the timeout operator is not just to control that there is at least 1 emitted value, but to control that each value are emitted before timeout. 

Now i need to find a solution for my use case :-)
