### ISSUE TITLE
`repeat`ed `scheduled` on `animationFrameScheduler` runs request twice

### ISSUE THREAD

**Issue by gizm0bill** [ReactiveX/rxjs#7226]
### Describe the bug

trying this:
```ts
scheduled([0], animationFrameScheduler).pipe( repeat() )
``` 
runs at 30fps, meaning the `requestAnimationFrame` is called twice (tested)

whilst this:
```ts
interval(0, animationFrameScheduler)
```
runs at 60fps

You can notice this behavior here: https://stackblitz.com/edit/rxjs-aksefi?file=index.ts and the corresponding question that raised this bug, here: https://stackoverflow.com/questions/75781770/rxjs-animationframescheduler-is-triggered-only-every-35ms

Is this a bug or by design?

### Expected behavior

```ts
let last = performance.now();
scheduled([0], animationFrameScheduler).pipe( 
  repeat(), 
  tap(() => {
    const performanceNow = performance.now();
    console.log(performanceNow - last);
    last = performance.now();
  }) )
```
would expect to print values ~= 16

### Reproduction URL

https://stackblitz.com/edit/rxjs-aksefi?file=index.ts

### Version

7.8.0

**Comment by ajafff** [comment]
not sure if this is a bug, but with the current implementation this behavior is expected (or at least it can be explained):
https://github.com/ReactiveX/rxjs/blob/master/src/internal/scheduled/scheduleArray.ts
For each animationFrame is looks at one index of the array. so at the first animationFrame it emits an item and at the second animationFrame it closes the Observable because there are no more items to emit. here `repeat` subscribes again so the emit happens at the third animationFrame

**Comment by gizm0bill** [comment]
Makes sense @ajafff thanks!
Well I guess it can be closed then?

**Comment by jakovljevic-mladen** [comment]
Closing as per OP's [comment](https://github.com/ReactiveX/rxjs/issues/7226#issuecomment-1476381589).
