### ISSUE TITLE
Expose options types publicly

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#7336]
I ran across userland code recently where the developer had to copy the `BasicGroupByOptions` interface into their own code because we don't expose it. If we have an interface for an options/config argument, we should be exposing that type so people can use it.

We'll probably want to make sure their naming convention is consistent prior to exposure.

**Comment by jakovljevic-mladen** [comment]
But [we do](https://github.com/ReactiveX/rxjs/blob/27855c635ca74107352ae3336944433a328c0b41/src/index.ts#L141C19-L141C19) expose this interface since v7 🙈. (Which version does the mentioned repo use?)

We expose a lot of configuration interfaces and one of the reasons we do is because the docs app would required them exposed so it can [show](https://rxjs.dev/api/index/interface/BasicGroupByOptions) them in the app. For more info, please check [this PR](https://github.com/ReactiveX/rxjs/pull/6247).

**Comment by benlesh** [comment]
Mkay
