### ISSUE TITLE
iif subscriptions

### ISSUE THREAD

**Issue by borosbela** [ReactiveX/rxjs#7488]
### Describe the bug

The documentation says, that only `trueResult` of the given observables will be subscribed, but both of the `falseResult` and `trueResult` will be subsrcibed to, and only returns the `trueResult` observable's value. 

### Expected behavior

Only subsrcibe to the `trueResult` observable.

### Reproduction code

```typescript
iif(() => false,
 firstObs(),
 secondObs()
)

function firstObs(): Observable<string> {
 console.log("Why?"); // <--- this got logged
 return of("one way");
}

function secondObs(): Observable<string> {
 console.log("Why not?"); // <--- this got logged
 return of("other way");
}
```

### Version

7.8.1

**Comment by jakovljevic-mladen** [comment]
Hi @borosbela,

If you subscribe to your `iif` Observable, you'll see that it only logs `other way`. `one way` is not logged and will not be logged as long as the function passed as the first parameter to `iif` returns falsy value. Please visit [this link](https://stackblitz.com/edit/rxjs-3aldpq?devtoolsheight=60&file=index.ts) for demo.

The reason why `Why?` gets logged is because you're actually calling `firstObs` function when preparing the second parameter for `iif` which calls `console.log("Why?")` before returning `of("one way")`. This has nothing to do with RxJS, it's just how JavaScript works.

If you need to postpone execution of `firstObs`, you can use this:

```
import { defer, iif } from 'rxjs';

iif(() => false,
 defer(firstObs),
 defer(secondObs)
)
```

I'm gonna close this issue as there's no bug here.
