### ISSUE TITLE
Observable.of and Observable.from need to be async to meet spec

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#752]
According to @zenparsing's spec, `Observable.of` and `Observable.from` result in Observables that emit on a micro task.

This is probably fine, since it results in a more predictable store for newbie developers. Also, we can just default the scheduler parameter on these two methods to `nextTick`, allowing those that want synchronous subscription to schedule `immediate` easily.

**Comment by trxcllnt** [comment]
@blesh ew gross, and hell no. That's why  `Observable.of` and `Observable.from` accept a scheduler argument. Users should opt-in to asynchrony, otherwise all the work we've done to improve performance is wasted. No offense to @zenparsing, but the problems with the always-async Promise spec is a clear example of why concurrency preferences should not be mandated by the specification.

**Comment by zenparsing** [comment]
@trxcllnt Haha - and no offense taken.  : )  I'm sympathetic to your principled stance here, and I'd like to continue the discussion.  I'm traveling at the moment, so it might be tomorrow before I can reply.

**Comment by blesh** [comment]
I guess one of my problems with it, it is means that anywhere someone uses an `Observable.of` or `Observable.from`, it's going to reset the call stack and developers will lose context while debugging. I think this is more of a problem for `Observable.of` than the other, but it *could* be problematic for both.

There is a similar issue in RxJava with `observeOn` and `subscribeOn` ruining stack trace context for developers... which is actually true for RxJS as well, for exactly the same reasons. Once you schedule out of the call you're in, you lose your call stack.

**Comment by blesh** [comment]
Closing this for now. I think RxJS is going to willfully deviate from @zenparsing's spec on this issue. :)

Being able to opt-in to asynchrony is fine for now.

**Comment by zenparsing** [comment]
I'm not understanding why eager (too-early) emission is a better default, when there seems to be agreement that eager emission is a potential footgun.  It's trivial to implement an eager version of `of` and `from` if that's what is wanted.

**Comment by trxcllnt** [comment]
@zenparsing it's not trivial to implement a synchronous `of` and `from` if they're spec'd to be async by default (without rewriting and replacing them on the prototype, but that's dirty). It is trivial to emit asynchronously if scheduling is parameterized: `Observable.of(1, 2, 3, Scheduler.nextTick)`.

What am I missing here? Is this the same as the async subscribe issue?

**Comment by blesh** [comment]
*Technically*, we can opt in to the synchronous behavior just as easily as opting out, because of the Scheduler behavior. The real question is if the spec is around scheduling *subscription* or scheduling *emission*. The latter is pretty gross because of what it does to call stacks. The former still messes with call stacks, but not quite as bad as the latter.

**Comment by trxcllnt** [comment]
@blesh that's only half true. You couldn't opt-in to the synchronous recursive scheduling strategy in an async-spec'd world.

**Comment by blesh** [comment]
> You couldn't opt-in to the synchronous recursive scheduling strategy in an async-spec'd world.

We're not spec'd here, though. We could default the `scheduler` argument to the microtask scheduler (nextTick or whatever), and then if someone passes a `Scheduler.NONE` or `Scheduler.immediate` we can opt-out of scheduling or use the immediate scheduler (respectively).

**Comment by trxcllnt** [comment]
@blesh so we're going to require people pass `undefined` as the last argument to `of` and `from` when they want to opt-in to what is default behavior everywhere else? That doesn't seem very friendly.

Most of the performance wins in real-world scenarios are because we fall-back to the recursive scheduling strategy with loops. It's likely `of` and `from` are most likely used from within the selectors passed to operators like `flatMap`, thus *don't* benefit from asynchronous `next`s.

**Comment by blesh** [comment]
> @blesh so we're going to require people pass undefined as the last argument to of and from when they want to opt-in to what is default behavior everywhere else? That doesn't seem very friendly.

No. You could have them pass `Scheduler.unscheduled` or `Scheduler.none` or the like:  `Observable.of(1, 2, 3, Scheduler.unscheduled)`.

> It's likely of and from are most likely used from within the selectors passed to operators like flatMap, thus don't benefit from asynchronous nexts.

I completely agree with @trxcllnt on this, @zenparsing. The only time someone uses `Observable.of` as the start of an observable chain is for examples and demos. In practice, `Observable.of` is much, much more likely to appear as a value returned by the selector of a `flatMap`, in which case, the async behavior is unnecessary, and more harmful than anything, as ruins the call stack and (mildly) hurts performance.

On the `from` front, I think there are more cases were someone might start an observable chain with `from`. So `from` is more debatable, in my mind. If someone gives you a value, and you're unsure what it is and you're going to use `Observable.from` with it, it could be dangerous to imperative programmers, especially in combination with `forEach`, which has a "wee, I'm an array and I'm synchronous" flavor to it.

**Comment by zenparsing** [comment]
> In practice, Observable.of is much, much more likely to appear as a value returned by the selector of a `flatMap`.

If it's an in-memory sequence, why map to an Observable?  Why not map to an iterator (or iterable) and then flatten over that?

**Comment by blesh** [comment]
> If it's an in-memory sequence, why map to an Observable? Why not map to an iterator (or iterable) and then flatten over that?

Good point... and you can totally do that in RxJS 5. In fact, we've optimized for just that sort of thing.

**Comment by blesh** [comment]
I'm reopening this for now. I'm seeing fewer and fewer compelling reasons for `of` and `from` to default to being completely synchronous.

The hanging issue that would stop me though would be the fact it destroys the call stack and hinders debugging quite a bit. Especially if the asynchrony is `observeOn` and not `subscribeOn`.

**Comment by blesh** [comment]
So @zenparsing clarified via Twitter DM that it would be async _subscription_ not observation. The tricky part about that would be that it's actually weirder/harder to opt-out of async subscription, as most Scheduler arguments are used for scheduling observation.

**Comment by trxcllnt** [comment]
> @blesh: No. You could have them pass Scheduler.unscheduled or Scheduler.none or the like: Observable.of(1, 2, 3, Scheduler.unscheduled).

The Observable creation operators all check their `scheduler` argument against `undefined`. If it's there, they use it, if it's not, they loop locally. Since `Scheduler` doesn't have static `none` or `unscheduled` fields, passing `Scheduler.unscheduled` would evaluate to undefined.

We could (theoretically) introduce a synchronous recursive scheduler that implements the iteration generically (using state to avoid introducing recursion), but I doubt the increased implementation and runtime complexity would be worth the effort.

> So @zenparsing clarified via Twitter DM that it would be async subscription not observation. The tricky part about that would be that it's actually weirder/harder to opt-out of async subscription, as most Scheduler arguments are used for scheduling observation.

So we're back to the async subscription/zalgo debate again. As Promises have proven, this is the wrong behavior to enshrine in a standard, because each level of composition that uses `of` or `from` introduces another "tick" delay into the subscription pipeline, potentially causing race conditions somewhere else (@jlongster alerted me to this a few weeks ago).

I understand you're trying to save people from "Zalgo," but this solution just pushes the complexity somewhere else. External/mutable state is the problem. Async subscription and/or dispatch provides some localized relief, but the only complete solution is to give developers new tools to eliminate external state (`flatMap`, `switchLatest`, `scan`, etc.). From that perspective, async subscription *detracts from* our ability to use those tools efficiently.

**Comment by blesh** [comment]
>  Since Scheduler doesn't have static none or unscheduled fields, passing Scheduler.unscheduled would evaluate to undefined.

I'm proposing adding just that #857. There are other reasons it should exist, frankly. I don't even know if it should be a full-on Scheduler implementation or just a really dumb/simple specialization of the current ImmediateScheduler with `schedule` overridden to just immediately execute anything passed with a delay of `0`.

> I understand you're trying to save people from "Zalgo," but this solution just pushes the complexity somewhere else. External/mutable state is the problem. 

I don't think there is much we can do to prevent bad developers from shooting themselves in the foot with mutable state. Consequently, the TC39 _loves_ scheduling async jobs with all the things. I sincerely doubt that synchronous `Observable.of` or `Observable.from` will pass the committee.

**Comment by zenparsing** [comment]
> So we're back to the async subscription/zalgo debate again.

Yep.

> External/mutable state is the problem.

You can always fall back to this line of argument, and that's totally fine, but the fact is that programmers use mutable state within the lexical environment all the time.

For me, the question boils down to this: do we want Observable to be a power tool for FRP enthusiasts?  Or do we want Observable to be a broadly useful async programming model for all kinds of developers (even the ones that use mutable state)?

If we want broad reach, then I think it's appropriate to spec `Observable.of` and `Observable.from` such that they work well for the general case that allows the possibility of mutable ambient state.  They are entry-level factories, as I see it.  For anyone that wants pure synchronous `of` and `from`, it's easy enough to write their own implementation using same core protocol, perhaps in the form of an Observable subclass.

I don't know.  I'm not 100% convinced that I'm right or that it matters a whole terrible lot, but delayed emission when converting from iterables integrates well with design decisions made elsewhere in the language (and I believe those decisions were made for good reason).

Maybe it's not so bad if Rx deviates from es-observable on this point, particularly if we view Rx Observable as a "subtype" (whether in a strict nominal sense or more loosely).

**Comment by trxcllnt** [comment]
> @blesh dumb/simple specialization of the current ImmediateScheduler with schedule overridden to just immediately execute anything passed with a delay of 0.

That's already in RxJS 4 today (as the `ImmediateScheduler`), but it suffers from stack overflows when it's used to reschedule many times in a row.

> @zenparsing the fact is that programmers use mutable state within the lexical environment all the time.

I concede it happens, but I'm not convinced it should affect Observable's behavior, and I'll illustrate why:

|         | One | Zero-Infinity
| -------|----------|------------
| **Pull** | Function | Iterable 
| **Push** | Future | Observable

- A Function is a lazily evaluated computation that synchronously returns a single value on invocation.
- An Iterable is a lazily evaluated computation that synchronously return zero to ∞ values on iteration.
- A Future is a lazily evaluated computation that can synchronously or asynchronously return a single value from the time it's invoked until some point in the future, and possibly never.
- An Observable is a lazily evaluated computation that can synchronously or asynchronously return zero to ∞ values from the time when it's invoked until some point in the future, and possibly infinitely.

These lazily evaluated computations only differ by their relationship between the producer and consumer (either the consumer pulls values from the producer, or the producer pushes values to the consumer), and how many values they can produce (exactly one, or between zero and infinity).

An Observable can, as defined, accomplish everything that each Functions, Iterables, and Futures can. In fact, I prefer to describe Observables as *async generator functions*, and generally disagree with comparisons to Promises/EventTarget etc.

An Observable that can't synchronously push values upon subscription is inconsistent with mathematical definitions of Functions, Iterables, and Futures. If you're trying to specify this subset of the Observable definition, be my guest, but I doubt JS would be what it is today if it only specified a subset of, for example, the closure definition.

Promise's deviation from the Future definition has introduced entirely new classes of bugs and race conditions which are difficult or impossible to discover and reproduce. **Don't make the same mistake with the Observable specification.**

> For me, the question boils down to this: do we want Observable to be a power tool for FRP enthusiasts?

Observables are as much a power tool for FRP enthusiasts as functions are for FP enthusiasts.

FRP doesn't dictate a definition of time. FRP is solely an application of functional programming principles to reactive programming. Aside from the distinction that they push zero to infinity values to the consumer, Observables should behave as their Function counterparts do, or risk not being true Observables at all.

> If we want broad reach, then I think it's appropriate to spec Observable.of and Observable.from such that they work well for the general case that allows the possibility of mutable ambient state. They are entry-level factories, as I see it. For anyone that wants pure synchronous of and from, it's easy enough to write their own implementation using same core protocol, perhaps in the form of an Observable subclass.

Could you help me understand what you believe should be logged in this example?

```es6
Function.return = function(x) {
  return function() {
    return x;
  };
};

Observable.from = function(arr) {
  return new Observable((o) => {
    arr.forEach((y) => o.next(y));
    o.complete();
  });
};

const arr = [1, 2, 3];
const pullValues = Function.return(arr);
const pushValues = Observable.from(arr);

printValues();

arr[0] = 4;
arr[1] = 5;
arr[2] = 6;

printValues();

function printValues() {
  console.log(pullValues.apply());
  pushValues.subscribe((x) => console.log(x));
}
```

**Comment by zenparsing** [comment]
```
[1, 2, 3]
1
2
3
[4, 5, 6]
4
5
6
```

In this case, you've defined `Observable.from` to emit values at subscription time.  The constructor and subscribe protocol allow for fully sync dispatch if that's what you want.

The `Observable.from` that I want looks more like:

```js
Observable.from = function(arr) {
  return new Observable((o) => {
    enqueueJob(_=> { // <--- Note the job enqueuing
      arr.forEach((y) => o.next(y));
      o.complete();
    });
  });
};
```

(The actual implementation is [here](https://github.com/zenparsing/es-observable/blob/master/src/Observable.js#L339).)

Since I agree that we should allow fully sync subscribe-time dispatch, I think we're good on the "mathematical" point.  Yes?

It's just a question of what these built-in convenience factories should do.  Is it fatal if they work by scheduling a job for dispatch, in order to address the Zalgo concerns (keeping in mind that you can always write another "from" function to get fully sync behavior, if that's what you want)?

**Comment by trxcllnt** [comment]
> It's just a question of what these built-in convenience factories should do. Is it fatal if they work by scheduling a job for dispatch, in order to address the Zalgo concerns (keeping in mind that you can always write another "from" function to get fully sync behavior, if that's what you want)?

No, because even if I want to replace `of` and `from` with their sync implementations, it's bad practice to mutate built-in Objects, and it's asinine to expect anybody to write anything resembling `Observable.fromSync(arr)` because you don't want to separate subscription from concurrency. Just parameterize it already, or at least don't specify something now that you can't un-specify later.

**Comment by zenparsing** [comment]
> it's bad practice to mutate built-in Objects

For sure.  But you can subclass:

```js
class MyBetterObservable extends Observable {
    static from(x) {
        // Same, but don't enqueue a job
    }
}
```

> because you don't want to separate subscription from concurrency

Hmm...  I don't necessarily agree with this way of looking at it.  "Subscription" is always synchronous, it's just that by default, when converting in-memory lists to observable sequences, the first element should not arrive before the "subscribe" call has completed.  It's just, I don't know, rude to do that to your consumer because eventually someone's not going to protect against the case where a value can come in prematurely.

I don't see the problem with either:

1. Using the subclassing approach to override the factories, or
1. Putting the sync conversion behavior into a separate function or method

**Comment by trxcllnt** [comment]
> For sure. But you can subclass:

One could argue the same thing in reverse.

> the first element should not arrive before the "subscribe" call has completed. It's just, I don't know, rude to do that to your consumer because eventually someone's not going to protect against the case where a value can come in prematurely.

Anytime you call any function, it may call other functions (even callbacks), before releasing control back to the call site. Attempting to conditionally dictate to a program when certain functions can run seems to be the ruder of the two choices to me.

> I don't see the problem with either:
> 
> 1. Using the subclassing approach to override the factories, or
> 2. Putting the sync conversion behavior into a separate function or method

3. Compose the async behavior over the sync behavior.

Asynchrony can be composed from synchronous behavior, but the reverse is not true.

By the way, what happened to `forEach`? Wasn't it supposed to do some sort of asynchronous subscription voodoo?

**Comment by zenparsing** [comment]
> One could argue the same thing in reverse.

This is true : )

> By the way, what happened to `forEach`? Wasn't it supposed to do some sort of asynchronous subscription voodoo?

We had that for a while, but it suffers the same problem that any other async subscription mechanism suffers:  you lose "events" that occur before the next turn.

```js
fromEvent(element, "click").forEach(x => { ... });
// You lose this event
element.dispatchEvent(new MouseEvent("click", {}));
```

But...  maybe we should dust that idea back off and reexamine it...

**Comment by trxcllnt** [comment]
@zenparsing Introducing asynchrony necessitates queueing of some sort (whether it's local in the asynchronous operator sink, or global by deferring subscription), and clean-up logic to cancel and dequeue the prematurely if required.

It's not the Observable's primitive definition, and should be strictly opt-in (via composition), since it is more mathematically and computationally complex than the primitive form, and can't be reverted to primitive behavior once specified.

**Comment by trxcllnt** [comment]
@zenparsing and your example output above is what should happen given the *formal* primitive Observable definition. I have a problem with this desire for asynchrony in the primitive methods because it would change how that example works, instead printing:

```
[1, 2, 3]
[4, 5, 6]
4
5
6
4
5
6
```

**Comment by blesh** [comment]
Hmmm... that's a lot of reading to catch up on.

I thought a lot about this last night, and I think (no, I _know_) we should side with the needs and wisdom of the community when it comes to this. Rx/Observables have been around for > 6 years now, and the type has had ample time to mature under the guidance and use of many, many smart people.

During the relatively short time I've been involved with Rx, I _initially_ thought there should be a default async subscription behavior: I talked to @IgorMinar about it, I pushed on @jhusain and @mattpodwysocki about it; But now I _know_ that what I want is default _synchronous_ subscription all the time.

I'm still not 100% on the issue, but I'm at least 90% in favor of keeping `of` and `from` sync by default.

**Comment by blesh** [comment]
also, @trxcllnt, the need for some sort of way other than `undefined` to flag that you don't want to schedule is related to this, but really it's a seperate issue. #857

**Comment by staltz** [comment]
I've also been reading this, but don't have a lot to add.

One small thing though: synchronous subscription is important for the test scheduler. I tried supporting Promises in the test (or virtual time) scheduler, and ... haha.

**Comment by ivan-kleshnin** [comment]
@trxcllnt can you clarify what do you mean by 

> can synchronously or asynchronously return a (...) value

**Comment by blesh** [comment]
Let's just keep `of` and `from` sync for now, and see what happens with the spec in the TC39. There seems to be an extremely high probably it will change month to month until it reaches a later stage at the committee. I think this library has done what could be considered a best effort in meeting the spec within reason as it's changed drastically over the period of time RxJS 5 has been developed.

I suspect in order to meet the spec, once it's finalized, there will be some breaking changes and an RxJS 6 will be born. But perhaps I'll be pleasantly surprised.

**Comment by zenparsing** [comment]
Sounds good.  I think we captured the arguments here very well.

**Comment by blesh** [comment]
`<hug>@zenparsing</hug>`

**Comment by trxcllnt** [comment]
> @ivan-kleshnin 
> can you clarify what do you mean by
> > can synchronously or asynchronously return a (...) value

> concerning the description of PUSH primitives?

"Return" just means the mechanism by which a value is communicated to the consumer. In (pull-based) interactive programming, we have language support with the `return` keyword. In (push-based) reactive programming, we don't have language support (yet), and must build this behavior with closures.

Side note: If we didn't have the `return` keyword, you could emulate its behavior with closures too.

**Comment by genaby** [comment]
As it was said: sync can be turned into async, but async to sync is impossible. Only that fact is enough to keep sync by default in all possible places. Isn't it obvious?

**Comment by ivan-kleshnin** [comment]
@trxcllnt I'm asking because there is no clear terminology yet. 

Matt Podwysocki here http://2014.jsconf.eu/speakers/matthew-podwysocki-async-and-streaming-js-are-we-doing-it-wrong.html presents a very similar division with `single <-> multiple` and `sync <-> async` axis.

So he calls ASYNC what you call PUSH and calls SYNC what you call PULL.
But you say there is such thing as SYNC PUSH. Which means we have at least a terminology conflict.

**Comment by trxcllnt** [comment]
@ivan-kleshnin no conflict. The terms are meant to describe the relationship between the producer and consumer, not anything about events' location in the 4th dimension. Sync and async are more familiar to most people, but aren't the most precise in this instance.
