### ISSUE TITLE
Behaviour getValue functionality missing

### ISSUE THREAD

**Issue by alisd23** [ReactiveX/RxJS#758]
Is the `value` property of **BehaviourSubject** supposed to be public? Or is there supposed to be a public `getValue` function like there is in the previous version?
There is currently no way of reading the value without subscribing.

**Comment by Johnius** [comment]
I think it's breaking supposed way of reactive paradigm. Can you describe your specific case? Maybe there's better way to solve this problem.

**Comment by blesh** [comment]
> Is the value property of BehaviourSubject supposed to be public? 

Yes (and no). FWIW, you could examine that in previous versions as well. *most* of the time you shouldn't be using this though, but there are situations were it can come in handy.

So: 

- Yes, there it is. 
- But try not to use it.

Fair?

**Comment by chrisprice** [comment]
My (potentially edge!) use case involves a source of deltas to a data structure. In order to apply the delta I need a reference to the existing data structure. E.g. -

```js
private _x: BehaviorSubject<IX[]> = new BehaviorSubject([]);

get x() : Observable<IX[]> {
  return this._x;
}

private apply(delta: Delta<IX>): void {
  delta(this._x.value); // invalid access to private member
}
```

The [commit](https://github.com/ReactiveX/RxJS/commit/61e173b5003b6b0d38d6da076e82a8aa31e70f62#diff-18ecd71915593d19863b5afc958987b1) which changes it from public to private doesn't provide any context. 

My options are to -
* maintain a separate reference to the current value (seems a bit unnecessary).
* create a new subscription to retrieve the current value (seems a lot unnecessary).
* cast around the type checks ```((this._x as any).value as X)``` (seems a bit ugly).

Any pointers to alternative approaches would be much appreciated. Also, FWIW I would rather see it be implemented as (happy to make a PR) -

```js
import {Subject} from '../Subject';
import {Subscriber} from '../Subscriber';
import {Subscription} from '../Subscription';

export class BehaviorSubject<T> extends Subject<T> {
  constructor(private _value: T) {
    super();
  }

  _subscribe(subscriber: Subscriber<any>): Subscription<T> {
    const subscription = super._subscribe(subscriber);
    if (!subscription) {
      return;
    } else if (!subscription.isUnsubscribed) {
      subscriber.next(this._value);
    }
    return subscription;
  }

  _next(value: T): void {
    super._next(this._value = value);
  }

  get value(): T {
    return this._value;
  }
}
```

**Comment by blesh** [comment]
BehaviorSubject's `value` property should not have been made private. That's a good catch. `getValue` seems redundant of the `value` property is public, what do you think?

**Comment by chrisprice** [comment]
I don't like a completely public value because it can then be set without
triggering the subscriber's next.

I was thinking that hiding it behind either a ```getValue``` or ```get
value```protects against this. However, in TypeScript you can get a similar
effect by returning a stricter interface and in JavaScript the _value
member would be directly accessible anyway.

I suppose the big advantage in both cases is to be more expressive about
how it should/should not be used. A future minifier might eventually
obfuscate the _value member by virtue of it being private.

Hm, I think I've managed to talk myself around 360 back to the
implementation I suggested above :)

**Comment by blesh** [comment]
All I know is it's available via `value` in RxJS 4. That's generally where I've gotten it from. I'm not opposed to a `getValue()`, per say. But I think keeping `value` public to maintain that bit of compatability is probably a good idea.

**Comment by mattpodwysocki** [comment]
@blesh calling `.value` is an anti-pattern for many reasons.  If you look at `getValue()` as it stands today it does a number of things.

1. Checks if the current `BehaviorSubject` has been disposed.
2. If there was an error in the stream, then you cannot just get the value, instead the error is thrown.
3. If all else is successful, then you may get the value.

Simply exposing `.value` breaks that encapsulation because you need those safeguards.

**Comment by blesh** [comment]
Okay... `getValue()` then.
