### ISSUE TITLE
Rename fromCallback to bindCallback

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#876]
Per the discussion here #787. I think we're in agreement that `fromCallback`'s behavior differs enough from the other `fromX` methods that we can change the name.

**Comment by benjamingr** [comment]
lgtm. 

Although I'd still rather see a generated function avoiding the closure, and all the objects/created and copying around here. I'd also like to see a benchmark with it - preferably https://github.com/petkaantonov/bluebird/tree/master/benchmark since it simulates exactly the sort of use case we're discussing here (which is why bluebird used it in the first place) that measures the overhead. If it's 2x slower than callbacks I can take the penalty but if it's an order of magnitude slower that might be a problem.

**Comment by blesh** [comment]
> Although I'd still rather see a generated function avoiding the closure, and all the objects/created and copying around here.

Can you elaborate here?

**Comment by benjamingr** [comment]
Yes - look at how promisify is implemented in bluebird. A function is generated for the new function and then the JIT gets to optimize it. Meaning bluebird promisifies at almost zero overhead while other libraries typically are a lot slower.

This is important if we expect it to be called per-request in servers.  On the client it's insignificant though.

**Comment by blesh** [comment]
> Although I'd still rather see a generated function avoiding the closure

Ah, I see, Bluebird is actually building function via strings. That's what you meant by "generated function". That's an interesting approach, actually. Totally worth investigating for something like this. Thanks @benjamingr for pointing me to that. Hopefully I'll have time soon to try it with some perf tests.
