### ISSUE TITLE
Implement `observablify` method

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#877]
Per discussion here #787, it would be really good to have an `observablify` method that was similar to Bluebird's `promisify`.

**Comment by benjamingr** [comment]
It would be a terrific idea to make sure this method has as low overhead as possible - it needs to generate a fast method. It's also important that it returns a function for a regular Rx observable (no caching/etc) and the docs convey that behavior (unicast, which is the default anyway) explicitly.

More important than this is that we have an `observablifyAll` that converts an entire API from callbacks to observables.

I'm going to repeat my performance concerns here - bluebird promises are blazing fast and there can be hundreds of thousands in-flight at the same time which makes `promisifyAll` possible - otherwise promises would not be practical. The _most common_ way for Rx to be used is to create observables once at initialization time and then reuse them - with `obserablify` you'd suddenly create multiple observables per request so both consuming observables from observables and creating hundreds of thousands of observables would have to support this.

**Comment by david-driscoll** [comment]
My big concern when you're talking no caching is that you might suddenly introduce unexpected side-effects.  For example, `fs.writeFile`, if every subscription to an observable returned from the observable factory version of `writeFile` caused the file to be re-written that would make for some really interesting behavior.

**Comment by blesh** [comment]
@david-driscoll you can compose-in caching with things like `publishReplay` and `publishLast` (which we still need to implement, actually).

**Comment by david-driscoll** [comment]
I'm just trying to see where the side-effects would be valuable when you compare it to something like `promisify` which by it's very nature caches the results, because everything is just a promise.

I just look at it as, one invocation of a particular method produces one call to the callback.  In this case then every subscription would produce one call to the callback.

As long as it's documented I'm sure it would be okay, but I just can't see where the lack of caching is a true benefit versus caching the result.

**Comment by benjamingr** [comment]
@david-driscoll it's just the model. Unicast means you can treat the returned observable like a function that subscribe invokes. Things like `retry` make sense. It's true that not all observables in all libraries act like this - but once you understand it it's pretty nice.

As for - "is it a useful default" I'm not sure - but no one is stopping you from mixing and matching.

As corobservify- I think it should be able to deal with methods that return node streams too.

**Comment by david-driscoll** [comment]
@benjamingr  fair enough, just trying to understand the use case.  Thanks!

As long it gets well documented in the future, then it probably won't be an issue in the long run.

**Comment by benjamingr** [comment]
Basically, my vision is that `Observable.observablifyAll` takes an API and returns that API converted to observables - with all methods that return streams return observables and all methods that take callbacks return observables.

**Comment by blesh** [comment]
As this issue has gone stale, I'm going to close it for now. But I'd like to reinvestigate it in the future.

**Comment by tycho01** [comment]
fwiw their bit with actual promise-related code there [seems limited](https://github.com/petkaantonov/bluebird/blob/3746b7eca90dd8b11af73db5d30cf46d7dd90f9b/src/promisify.js#L170-L237).
